### ISSUE TITLE
No code found in this project.

### ISSUE THREAD

**Issue by SuperWangKai** [SaschaWillems/Vulkan#1]
Not a single line of code is found in this project.

**Comment by shurcooL** [comment]
The readme says:

> Sources will be available when Vulkan is released to the public. Current ETA is early 2016.

**Comment by SaschaWillems** [comment]
As shurcooL noted, sources for the examples will be available when the Vulkan SDK goes live. See the Vulkan Working Group update for more infos on this : https://www.khronos.org/vulkan.
