### ISSUE TITLE
questions regarding the dependencies in inputattachments example

### ISSUE THREAD

**Issue by jmoguill** [SaschaWillems/Vulkan#1000]
Hi,
I have a question in the input attachments example:

dependencies[2].srcSubpass = 0;
		dependencies[2].dstSubpass = VK_SUBPASS_EXTERNAL;
		dependencies[2].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
		dependencies[2].dstStageMask = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT;
		dependencies[2].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
		dependencies[2].dstAccessMask = VK_ACCESS_MEMORY_READ_BIT;
		dependencies[2].dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT;
		
Should this be depencies[2].srcSubpass = 1?
In other words, we transition the color attachment of subpass 1 from color attachment write to memory read?

If you can provide some more clarification on these dependencies that would be very helpful.

Some additional questions:
		dependencies[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

Do we need write and read bit or can it just be write bit?  Is that in case blending is enabled, we can read from the color attachment?
This dependency is for the intermediate color attachments used in subpass 0 (e.g. the input attachments)?
Also:
dependencies[0].dstSubpass = 0;
Should this be:
		dependencies[0].dstSubpass = 1;
?
the first subpass writes to an intermediate color attachment, not the swapchain image...

**Comment by SaschaWillems** [comment]
> Should this be depencies[2].srcSubpass = 1?
In other words, we transition the color attachment of subpass 1 from color attachment write to memory read?

No, the attachment is written in subpass 0 and read in subpass 1.
