### ISSUE TITLE
compare directX11 and vulkan in UE5 use NVIDIA Nsight

### ISSUE THREAD

**Issue by Judgecut** [SaschaWillems/Vulkan#1001]
ue5 render VolumetricCloud call vkCmdDispatch use 0.88ms in Nsight.
![image](https://user-images.githubusercontent.com/58514140/204686814-e2732558-b0f4-4e39-ae17-8ec5cded8022.png)

but use directX11 call Dispatch use 0.40ms only.
![image](https://user-images.githubusercontent.com/58514140/204686854-68230838-9509-4cea-ab71-a6e4d60768ee.png)

it is a little strange.
figure of vulkan API call:
![image](https://user-images.githubusercontent.com/58514140/204686872-6fefb37d-9ec7-44de-8786-966aa80fe505.png)
figure of dx11 API call:
![image](https://user-images.githubusercontent.com/58514140/204686890-984a3826-2996-4762-b6d9-9d89bb3ad53c.png)

I don‘t know it is normal.
it is seems to be an issue with the driver's implementation of Vulkan?
my graph card is nvidia 2070s.  driver's version: 526.98

**Comment by SaschaWillems** [comment]
Sorry, but this place is for issues regarding my Vulkan samples. This topic doesn't fit in here, and I won't be able to answer. This seems to be something related to a game engine or driver, so please ask either Epic or your driver vendor for help.

**Comment by Judgecut** [comment]
ok thanks
