### ISSUE TITLE
How to install Vulkan on a headless server

### ISSUE THREAD

**Issue by LIUQI-creat** [SaschaWillems/Vulkan#1002]
Hi
@jku @pH5 @baryluk @laanwj @chrisforbes 
I want to install Vulkan on a headless server, what the instructuion should I execute when it  is at **BUILD** stage
![image](https://user-images.githubusercontent.com/75316518/206076038-993cfe16-654c-4e9b-86ff-36028372c81d.png)

Thank you very much!

**Comment by SaschaWillems** [comment]
This is a repository for Vulkan samples, not for Vulkan itself. If you need help installing Vulkan, please refer to the vendor of the GPU in your server.
