### ISSUE TITLE
imgui_draw.cpp error

### ISSUE THREAD

**Issue by CPP-Enjoyer** [SaschaWillems/Vulkan#1011]
Compiled in Visual Studio. I have this error in almost every exe file

Assertion failed!

Program: bloom.exe
File: imgui_draw.cpp
Line: 1573

Expresion: 0

**Comment by SaschaWillems** [comment]
did you download the asset pack?

**Comment by CPP-Enjoyer** [comment]
> did you download the asset pack?

Yes, but now everything is working
