### ISSUE TITLE
raytracingsbtdata example has invalid RayGenShaderBindingTable

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#1017]
In `buildCommandBuffers()` 

```
VkStridedDeviceAddressRegionKHR raygenShaderSbtEntry{};
raygenShaderSbtEntry.deviceAddress = getBufferDeviceAddress(raygenShaderBindingTable.buffer);
raygenShaderSbtEntry.stride = handleSizeAligned;
raygenShaderSbtEntry.size =  vks::tools::alignedSize(handleSizeAligned + 3 * sizeof(float), rayTracingPipelineProperties.shaderGroupBaseAlignment);
```
results in a mismatch of **stride** and **size** values (32 vs. 64 on my machine for example).
This is a violation of the Vulkan specification, which states "_The size member of pRayGenShaderBindingTable must be equal to its stride member._"
https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdTraceRaysKHR-size-04023

**Comment by SaschaWillems** [comment]
Do you get a validation error for this?

**Comment by kyamant** [comment]
It did on my framework which is a bit different than yours.

**Comment by SaschaWillems** [comment]
And what validation message did you get?

**Comment by kyamant** [comment]
> VUID-vkCmdTraceRaysKHR-size-04023(ERROR / SPEC): msgNum: -836035013 - Validation Error: [ VUID-vkCmdTraceRaysKHR-size-04023 ] Object 0: handle = 0x218dc558180, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xce2b1e3b | vkCmdTraceRaysKHR: The size member of pRayGenShaderBindingTable must be equal to its stride member The Vulkan spec states: The size member of pRayGenShaderBindingTable must be equal to its stride member (https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdTraceRaysKHR-size-04023)
>     Objects: 1
>         [0] 0x218dc558180, type: 3, name: NULL
> Validation Layer: Validation Error: [ VUID-vkCmdTraceRaysKHR-size-04023 ] Object 0: handle = 0x218dc558180, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xce2b1e3b | vkCmdTraceRaysKHR: The size member of pRayGenShaderBindingTable must be equal to its stride member The Vulkan spec states: The size member of pRayGenShaderBindingTable must be equal to its stride member (https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdTraceRaysKHR-size-04023)

**Comment by SaschaWillems** [comment]
Thanks. And what GPU are you on?

**Comment by kyamant** [comment]
RTX 3070 ti, Vulkan 1.3.236.0, Nvidia 531.29

**Comment by SaschaWillems** [comment]
I can reproduce this on my setup. Will try to fix it.

**Comment by kyamant** [comment]
Further problems with this example:
In `buildCommandBuffers()`
`raygenShaderSbtEntry.size` is 64 but `raygenShaderBindingTable.buffer` has a size of 44
The same goes for `missShaderSbtEntry` and `hitShaderSbtEntry`.

> The Vulkan spec states: If size is not zero, all addresses between deviceAddress and deviceAddress + size - 1 must be in the buffer device address range of the same buffer (https://vulkan.lunarg.com/doc/view/1.3.250.0/windows/1.3-extensions/vkspec.html#VUID-VkStridedDeviceAddressRegionKHR-size-04631)
