### ISSUE TITLE
handleEvent() is defined but not used

### ISSUE THREAD

**Issue by 1ace** [SaschaWillems/Vulkan#102]
> warning: ‘void handleEvent(const xcb_generic_event_t*)’ defined but not used [-Wunused-function]

Is your event handling working correctly? From what the compiler says and what I've seen by looking at the code, it seems like it would always be ignored.
I don't have Vulkan-capable hardware at home, so I can't test it myself.

**Comment by SaschaWillems** [comment]
LInux event handling is not yet finished, see #56. Common event handling (zoom, rotate, etc.) is working, but specific example keys not.

**Comment by 1ace** [comment]
Right, sorry. I should've checked the existing issues :S
