### ISSUE TITLE
Small bug in descriptorBuffer sample

### ISSUE THREAD

**Issue by jackohound** [SaschaWillems/Vulkan#1024]
https://github.com/SaschaWillems/Vulkan/blob/fa0e3485d00c73b0637b914e6510d142ee2e5fdf/examples/descriptorbuffer/descriptorbuffer.cpp#L194

In the above code, the "binding" parameter to  `vkGetDescriptorSetLayoutBindingOffsetEXT()` shoudl be 0 rather than 1 since  `descriptorSetLayoutImages` only has 1 descriptor.

**Comment by SaschaWillems** [comment]
Thx for noticing. I'm not using the offsets anyway, so I'll just remove them.
