### ISSUE TITLE
Incorrect UV calculation in terrain tessellation sample

### ISSUE THREAD

**Issue by NotAPenguin0** [SaschaWillems/Vulkan#1035]
In the terrain tessellation sample, the following code is used to calculate UVs for each patch vertex:

https://github.com/SaschaWillems/Vulkan/blob/9993d4210215b0793abb49c07f5206823531fde9/examples/terraintessellation/terraintessellation.cpp#LL423C45-L423C45

However, for the final vertex in the outer corner, this results in uvs slightly below `1.0`, while they should both be `1.0`. I believe doing 
```cpp
vertices[index].uv = glm::vec2((float)x / (PATCH_SIZE - 1), (float)y / (PATCH_SIZE - 1)) * UV_SCALE;
```

should fix this.

**Comment by SaschaWillems** [comment]
Thx for bringing this up. Should also fix what's noted in #758.

Will fix it.
