### ISSUE TITLE
Met oom issue when running computecullandlod on a 2G board

### ISSUE THREAD

**Issue by pleasurefish** [SaschaWillems/Vulkan#1039]
Hi,
meet OOM issue when running computecullandlod on a 2G memory board.
could you pls change the OBJECT_COUNT to 32 on either Android or other platform?
```c++
diff --git a/examples/computecullandlod/computecullandlod.cpp b/examples/computecullandlod/computecullandlod.cpp
index 5b5296d5..384944e1 100644
--- a/examples/computecullandlod/computecullandlod.cpp
+++ b/examples/computecullandlod/computecullandlod.cpp
@@ -16,11 +16,7 @@
 #define ENABLE_VALIDATION false

 // Total number of objects (^3) in the scene
-#if defined(__ANDROID__)
 #define OBJECT_COUNT 32
-#else
-#define OBJECT_COUNT 64
-#endif

 #define MAX_LOD_LEVEL 5
```

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. It's the first time that someone reported this issue. Where do you get the OOM error?

**Comment by pleasurefish** [comment]
Hi Sascha,
i met the OOM issue on odroidN2 2G board, which uses a Mali GPU.

**Comment by SaschaWillems** [comment]
What needs to be changed here? The sample already lowers object count on android, see https://github.com/SaschaWillems/Vulkan/blob/master/examples/computecullandlod/computecullandlod.cpp#L19

**Comment by SaschaWillems** [comment]
Or do you want to lower the limit to 32 on all platforms?

**Comment by pleasurefish** [comment]
got it, but i think the 2G non-Android devices can run the linux Wayland at the same time.
