### ISSUE TITLE
SaschaWillems can you describe exactly how do render to texture ?

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#104]
I translate your examples to another language and i need know exactly how do render to texture.
I mean algorithm step by step. 
And how copy render result to SwapChain texture

**Comment by Ronniko** [comment]
Because in your example not simply understand how this done.

**Comment by httpdigest** [comment]
Every example renders to a texture level (i.e. image) provided by the swapchain using an image view.
For a start, see the references to the Vulkan functions and structs `vkGetSwapchainImagesKHR`, `VkImageViewCreateInfo`, `vkCreateImageView` for obtaining the swapchain images and getting image views on them, and then to setup the framebuffer see `VkFramebufferCreateInfo` with `vkCreateFramebuffer`. You then have to reference the framebuffer in `VkRenderPassBeginInfo` when doing `vkCmdBeginRenderPass`.

**Comment by SaschaWillems** [comment]
@Ronniko : Can you please use the Khronos Vulkan forums for asking Vulkan related questions?
