### ISSUE TITLE
Questions regarding the order independent transparency example

### ISSUE THREAD

**Issue by AnnaYouIMG** [SaschaWillems/Vulkan#1043]
Hi,

In OIT (Order Independent Transparency) test, I noticed that the "early_fragment_tests" layout qualifier is being used in the shader "geometry.frag". However, the OIT test disables the depth test and stencil test. As a result, the early fragment tests may not function as intended. 
Are there any other testing purposes associated with enabling the early fragment test?

**Comment by SaschaWillems** [comment]
Sadly can't help on this. The sample was an external contribution. If you think this is an error, a PR is very much appreciated.
