### ISSUE TITLE
Missing Textures from glTF

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#1044]
`VulkanglTFModel` is not presenting _specularGlossiness_ and _diffuse_ textures.

**Comment by SaschaWillems** [comment]
Can you elaborate? Is this something that's missing or is this a bug?

**Comment by kyamant** [comment]
It's missing. `void vkglTF::Model::loadMaterials(tinygltf::Model &gltfModel)` is not populating `material.specularGlossinessTexture` and `material.diffuseTexture` fields.

**Comment by SaschaWillems** [comment]
yeah, that sample isn't supposed to be a full fledged glTF renderer. If you're looking for a more complete glTF sample, please take a look at https://github.com/SaschaWillems/Vulkan-glTF-PBR/.
