### ISSUE TITLE
Possible typo in descriptor buffer example.

### ISSUE THREAD

**Issue by Tonyx97** [SaschaWillems/Vulkan#1045]
I've been following the descriptor buffer example, everything works fine except for image arrays which don't work once you try to access any index bigger than 0. I fixed it by using the actual per-descriptor size instead of the alignment thing. [Here](https://github.com/SaschaWillems/Vulkan/blob/master/examples/descriptorbuffer/descriptorbuffer.cpp#L229C142-L229C142) you can see how imageDescriptorOffset is used as a stride in raw memory, as long as I changed that with descriptorBufferProperties.combinedImageSamplerDescriptorSize, it worked, for fixed and variable-sized arrays. If it's not a typo please let me know why you used imageDescriptorOffset instead of the descriptor size. Thanks!

**Comment by SaschaWillems** [comment]
I used this because alignment is something you need to adhere to. I'm not sure if your solution is correct or if it work by accident. Can you add some details? What did you change exactly? And did you get any validation layer errors? And on what implementation does the sample cause the issue?

**Comment by Tonyx97** [comment]
Sorry for the late reply. I'm going to explain in more detail my case.

The following code is how I update a buffer/image in a descriptor buffer:

**· buffer:** the descriptor buffer.
**· offset:** the binding offset inside the descriptor buffer (obtained through getDescriptorSetLayoutBindingOffsetEXT).
**· index:** the index of the buffer/sampler in a buffer/sampled image array (I only use this for sampled images).

![image](https://github.com/SaschaWillems/Vulkan/assets/12673334/d5657e34-4d50-4db0-9267-863669bd122a)

The stride is what differs from the repo sample, I use **combinedImageSamplerDescriptorSize** from **PhysicalDeviceDescriptorBufferPropertiesEXT** instead of using the calculated alignment, the first time I saw the sample I was like: ok I should implement alignment like in the sample (I try to take care with alignments everywhere), it was hard for me to "fix" this, I also checked [this](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_EXT_descriptor_buffer.adoc) from [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/tree/main) repo and it doesn't use any alignment (for array entries) there. Is it possible the alignment offset is used between descriptors and not elements inside them such as sampled images etc? I don't get any validation errors with alignment nor with my approach. My hardware is GTX 3090 implementation 536.40. I'm currently using a single descriptor buffer per descriptor set abstraction with a few bindings inside. I've invited you to my repo just in case you want to check more deeply into it. The vulkan abstraction is [here](https://github.com/Tonyx97/VTEngine/tree/main/engine/code/vk/vko).

**Comment by SaschaWillems** [comment]
Thanks for the update. I'll check and see if the sample needs fixing. Afaik I added the alignments because the orignal sample (without alignments) crashed on AMD devices.

**Comment by SaschaWillems** [comment]
I have reworked the alignment size calculations. They should work properly now with different implementations.
