### ISSUE TITLE
Maximize window

### ISSUE THREAD

**Issue by andreluizbarbieri** [SaschaWillems/Vulkan#105]
The maximize of window (any example executable) no result in maximize of graphics, why?

**Comment by SaschaWillems** [comment]
Because this is not implemented yet (see #26). Resizing in Vulkan is not as straight forward as it is in e.g. OpenGL. I may add this feature at some point in the future, but other things have higher priority right now.

**Comment by httpdigest** [comment]
If you don't mind reading Java code with LWJGL instead, which does not look that much different from C/C++, then you can have a look at these demos: https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/vulkan

All of them implement resizing properly.

**Comment by SaschaWillems** [comment]
I have added window resizing to the base class, so it works with all examples. Currently only for windows, Linux will be added at a later point.
