### ISSUE TITLE
Headless surface mode crashes

### ISSUE THREAD

**Issue by kimoohuang** [SaschaWillems/Vulkan#1051]
I use vulkan-wsi-layer (https://gitlab.freedesktop.org/mesa/vulkan-wsi-layer) to support the VK_EXT_headless_surface, and use cmake . -DUSE_HEADLESS=ON to builed a headless version triange. However, it failed at acquireNextImage from the swapchain.

Here is the output:
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/xxx/vulkan_examples/Vulkan/examples/triangle/triangle.cpp at line 350
triangle: /home/xxx/vulkan_examples/Vulkan/examples/triangle/triangle.cpp:350: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)

**Comment by kimoohuang** [comment]
Here is all the logs of setting ENABLE_VALIDATION true:

ERROR: [459314243][VUID-VkImportSemaphoreFdInfoKHR-handleType-07307] : Validation Error: [ VUID-VkImportSemaphoreFdInfoKHR-handleType-07307 ] Object 0: handle = 0x95a125000000001a, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x1b609443 | vkImportSemaphoreFdKHR(): handleType is VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT so VK_SEMAPHORE_IMPORT_TEMPORARY_BIT must be set, but flags is 0x0 The Vulkan spec states: If handleType refers to a handle type with copy payload transference semantics, flags must contain VK_SEMAPHORE_IMPORT_TEMPORARY_BIT (https://vulkan.lunarg.com/doc/view/1.3.243.0/linux/1.3-extensions/vkspec.html#VUID-VkImportSemaphoreFdInfoKHR-handleType-07307)
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/xxx/vulkan_examples/new_VulKanSampleGit/Vulkan/examples/triangle/triangle.cpp at line 350
triangle: /home/xxx/vulkan_examples/new_VulKanSampleGit/Vulkan/examples/triangle/triangle.cpp:350: void VulkanExample::draw(): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)

**Comment by SaschaWillems** [comment]
That looks like the layer is faulty. I'm not using external semaphores in my code. Probably best to open an issue at the layer repo.

**Comment by kimoohuang** [comment]
OK, thanks.
