### ISSUE TITLE
Vulkan Samples Fail to Build with Cmake and Mingw Makfiles

### ISSUE THREAD

**Issue by richardebel** [SaschaWillems/Vulkan#1055]
The Base will build with Cmake Mingw Makefiles but the examples fail to build in the linking stage.

I can build and run the base and examples using my own handmade Mingw makefiles with the base as a static lib.  And of course, these examples build perfectly with Visual Studio.  Very well-designed project.  I just prefer to use the Mingw64 GCC compiler.

**Comment by SaschaWillems** [comment]
Please add the error message you get.

**Comment by richardebel** [comment]
My mistake.  When I ran the cmake generator with MinGW makefiles, I failed to select the Vulkan Library built for MinGW and instead used the default which was for MSVC
