### ISSUE TITLE
glTF Model Loading Example Issues

### ISSUE THREAD

**Issue by gregorwoggle** [SaschaWillems/Vulkan#1057]
### Discussed in https://github.com/SaschaWillems/Vulkan/discussions/1056

<div type='discussions-op-text'>

<sup>Originally posted by **gregorwoggle** August 17, 2023</sup>
@SaschaWillems,

Hi Sascha,
First of all, thanks a huge amount for the Vulkan examples. This has proved to be an invaluable resource for me as I am learning Vulkan.

Most recently, I have been writing a glTF model viewer based on your example code. During this process, I have uncovered some minor issues in your original code and wanted to bring them to light.

First Issue, glm::quat
In newer versions of glm, the order of quaternion components has changed, and in particular, code like the following is BROKEN:
if (node.rotation.size() == 4) {
			glm::quat q = glm::make_quat(node.rotation.data());
			newNode->rotation = glm::mat4(q);
}
Instead, do something like this:
if (node.rotation.size() == 4) {
			auto doubles = node.rotation.data();
			newNode->rotation = glm::quat(float(doubles[3]), float(doubles[0]), float(doubles[1]), float(doubles[2]));
}
	
Second Issue:	vkCmdDraw() NOT indexed:
When you're loading non-indexed data, you need to track to vertex offset for each primitive. 
In particular, in renderNode() you have code like this:
if (primitive->hasIndices) {
	vkCmdDrawIndexed(commandBuffers[cbIndex], primitive->indexCount, 1, primitive->firstIndex, 0, 0);
} else {
	vkCmdDraw(commandBuffers[cbIndex], primitive->vertexCount, 1, 0, 0);
}
Notice that you're always passing 0 as the index to the first vertex. Clearly, this will never result in drawing the 2nd, 3rd, or nth mesh in the buffer. So you need to revisit your struct Primitive{} and add a uint32_t firstVertex member (which needs to be set in the model loading code.)

I've uploaded a .gltf file (triangle_and_square.txt) that exhibits the problem.

[triangle_and_square.txt](https://github.com/SaschaWillems/Vulkan/files/12374112/triangle_and_square.txt)
</div>

**Comment by SaschaWillems** [comment]
The glTF samples are not meant to be 100% glTF compliant renderers that work with all kinds of models. If you need a more complete version, please refer to https://github.com/SaschaWillems/Vulkan-glTF-PBR/
