### ISSUE TITLE
Latest validation layers 1.0.5.0 complaining about VkImageMemoryBarrier settings

### ISSUE THREAD

**Issue by httpdigest** [SaschaWillems/Vulkan#106]
Using the latest LunarG SDK 1.0.5.0 on Windows, it now gives me the following validation warning whenever using the vulkantools.cpp::setImageLayout() with source layout VK_IMAGE_LAYOUT_UNDEFINED and destination layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, which is used for the setup of every framebuffer image in all demos.

```
Additional bits in Source accessMask 2048 [VK_ACCESS_TRANSFER_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.
```

It seems that whenever the source layout is VK_IMAGE_LAYOUT_UNDEFINED then source access bits must not be set. The current code sets the srcAccessMask in various occasions, also only depending on the destination layout.

**Comment by SaschaWillems** [comment]
Is this marked as a warning or as an error? It should be the first, and tells that Vulkan has just added the bits in the source access mask it's complaining about. 

I know that the setImageLayout function that sets these is not perfect, and in a real world application one would not do it like that but rather set the barriers explicit.

**Comment by httpdigest** [comment]
Yes, it is VK_DEBUG_REPORT_WARNING_BIT_EXT

**Comment by SaschaWillems** [comment]
Did some changes to the flags set by setImageLayout, so this warning should not longer popup.
