### ISSUE TITLE
how to treat uniform buffer?

### ISSUE THREAD

**Issue by yangfengzzz** [SaschaWillems/Vulkan#1066]
I read code in Vulkan-Sample, There are seperated BufferPool in every frame. When update to uniform, The buffer pool object in current render frame will be obtain, then the data is uploaded. But I found in your example, there is only one uniform buffer. Should I concern about this problem? 
I think directly modifying the buffer data will cause the previous data to be overwritten before being used by the GPU.

**Comment by SaschaWillems** [comment]
My samples do a wait idle after each frame. That's why they work fine with a single buffer.

It's not optimal, and you should use multiple buffer instead.

I'm working on changing that, but that'll take time.
