### ISSUE TITLE
How to investigate VK_IMCOMPLETEs

### ISSUE THREAD

**Issue by timprepscius** [SaschaWillems/Vulkan#1067]
Hey there,

Thank you very much for your amazing examples, etc.  Very helpful..

I'm developing an app for Android, targeting a very old Adreno 510, Sony Experia X blah blah blah.
When I "createGraphicsPipelineUnique," I get an Incomplete back for some, but not all of my shaders.

Is there a way to know what the problem is, besides randomly removing things which look like they could be problems for android?

Like for instance- one shader uses an "in flat uint16_t" - maybe that's not supported, how to know?  

Seems like not, but - am I just going to remove things till it starts working, and put things back until it fails again?
https://stackoverflow.com/questions/49689632/vulkan-compute-shader-with-16-bit-floating-point-operation-on-android-device

Anyhow, even if you don't answer - thank you again for your amazing examples.

**Comment by SaschaWillems** [comment]
There are different things that you could do:

- Enable validation layers
- Check ADB output

Esp. the latter will often give you hints at why something fails on android.

P.S. : Is this related to a specific sample? If not, issues is the wrong place to ask.

**Comment by timprepscius** [comment]
Yeah, I realize off topic.  Sorry for that.

ADB gives no clue.  Validation's fine.

I wonder if anyone has made a repository of "shader examples which will show where VK_INCOMPLETE is coming from."

Anyhow.  Thank you for your time.  Thank you for replying.
