### ISSUE TITLE
redundant CMakeLists.txt files for android

### ISSUE THREAD

**Issue by pemgithub** [SaschaWillems/Vulkan#1072]
I think the android CMakeLists.txt files is a bit redundant with the root dir CMakeLists.txt...

For example, there's `include_directories(external/glm)` in the root dir cmake (which I used to generate vs2022 and build for windows) vs `include_directories(${EXTERNAL_DIR}/glm)` in the android specific CMakeLists.txt.

I noticed this when integrating libwebp (to do VkImage dumps to webp instead of ppm)...  I ended up adding mostly redundant lines to the CMakeLists.txt in the root dir (tested on Windows 10 with vs2022) and the android CMakeLists.txt (built with Android Studio).

As I understood it, the main benefit of cmake is to share build configuration across platforms (eg Windows and Android).

Not sure if this qualifies as an "issue" vs some other way to share feedback.  Feel free to close.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. When I started out with this repo, I haven't had much CMake experience and I'm sure there are better ways to do all of this. But esp. for Android in the early day CMake lagged behind. I may return to this and improve it at some point, but it works fine, is low maintenance and not something often mentioned. So I'll keep it in mind but probably won't do anything about in the foreseeable future.
