### ISSUE TITLE
Mesh shader hlsl SPIR-V compiled against NV extension not EXT

### ISSUE THREAD

**Issue by baldurk** [SaschaWillems/Vulkan#1078]
The current `shaders/hlsl/meshshader/meshshader.mesh.spv` is compiled with references to the NV extension rather than the EXT version, it's mostly the same with overlapping opcodes/parameters etc but the execution model is different.

In dxc for some reason it defaults to NV unless you explicitly opt in with a `-fspv-target-env=vulkan1.2`, similar to what the raytracing compilation step does. I also noticed that the compile.py doesn't seem to handle the `.mesh` extension so currently it's not rebuilding those files when run.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. The python script is outdated because I'm no longer using. I use my own SPIR-V VS extension to compile to HLSL instead. Will look into the extension issue and update the shaders.
