### ISSUE TITLE
Pass index (uint16_t uint32_t) to glsl

### ISSUE THREAD

**Issue by WdsPjm** [SaschaWillems/Vulkan#1080]
Hello! I am very sorry for wasting your valuable time
I have found that sometimes a glb model contains several mesh indexes, but some mesh indexes are represented by uint16_t and others are represented by uint32_t, which is intended to save memory. However, if I do this and I want to pass all the indices of a glb (including uint16_t and unit32_t) to glsl via ssbo, what should I do? Can you give me some advice.

**Comment by SaschaWillems** [comment]
Is this related to one of my samples? If not, and this is a general question, please use other channels to ask this. E.g. the Khronos Vulkan forum, reddit, discord or slack.
