### ISSUE TITLE
C++11 what the actual fuck?

### ISSUE THREAD

**Issue by Acromatic** [SaschaWillems/Vulkan#1087]
How do you build this?

**Comment by SaschaWillems** [comment]
Build instructions are here: https://github.com/SaschaWillems/Vulkan/blob/master/BUILD.md

Also please mind your language, I find the title offendng...

**Comment by Acromatic** [comment]
but I hate Cmake... sigh I think my real question was why C++11?

**Comment by SaschaWillems** [comment]
Using C++ 11 for my samples is fine? There is nothing in the samples code that would require anything newer. Also when I wrote these, platforms like Android didn't support anything newer.
