### ISSUE TITLE
"descriptorbuffer" demo causes GPU hang on RDNA2 with RADV and Mesa 23.3.0

### ISSUE THREAD

**Issue by DiabeticCrab** [SaschaWillems/Vulkan#1091]
I don't know if this is a Mesa bug or an issue with the new offset and size calculations, but reverting e006185 fixes the issue.

System: Kernel 6.6.3
RX 6800 XT (w/ linux-firmware-20231030)
Ryzen 5900X
32 GiB RAM
Mesa 23.3.0 vanilla
libdrm 2.4.118
vulkan-loader 1.3.268

[dmesg.txt](https://github.com/SaschaWillems/Vulkan/files/13551878/dmesg.txt)

**Comment by SaschaWillems** [comment]
Do you get any validation layer errors?

**Comment by DiabeticCrab** [comment]
@SaschaWillems Sorry for the late reply! I tried getting validation layers to work using the Vulkan SDK and vkconfig, but to no avail. They don't yield any constructive output.

When I change descriptorbuffer.cpp to have `#define ENABLE_VALIDATION true` instead of `#define ENABLE_VALIDATION false`, the system softlocks and doesn't recover from the GPU hang anymore.

Here's what I got. I also made an apidump, but I don't know whether it'll be of any use:

[descriptorbuffer_apidump.txt](https://github.com/SaschaWillems/Vulkan/files/13745592/descriptorbuffer_apidump.txt)
[descriptorbuffer_validation_output.txt](https://github.com/SaschaWillems/Vulkan/files/13745594/descriptorbuffer_validation_output.txt)
[descriptorbuffer.txt](https://github.com/SaschaWillems/Vulkan/files/13745595/descriptorbuffer.txt)
