### ISSUE TITLE
Question about Offscreen rendering example

### ISSUE THREAD

**Issue by iexavl** [SaschaWillems/Vulkan#1092]
I am relatively new to vulkan and decided to look through some of the examples to try to get a better grasp on the concept. 
Something that caught my eye when looking at  this example:

https://github.com/SaschaWillems/Vulkan/blob/master/examples/offscreen/offscreen.cpp

is that a single offscreen frame buffer is used. Isn't this problematic for the swap chain? Isn't there a chance the offscreen frame buffer will start getting overwritten while its still being read? And if there is some synchronization between the swap chain images to stop that isn't that potentially worse performance wise?

**Comment by SaschaWillems** [comment]
It's properly synced. And the GPU can't write to more than one attachment at once, unless you do MRT.
