### ISSUE TITLE
Triangle example not advancing currentFrame

### ISSUE THREAD

**Issue by nitingupta910** [SaschaWillems/Vulkan#1093]
I see the triangle example is not advancing the `currentFrame` [defined here](https://github.com/SaschaWillems/Vulkan/blob/1a635f16abf73e076088487f07bc4a289525a709/examples/triangle/triangle.cpp#L114) (looks like an oversight?). Should the sample be doing `currentFrame = (currentFrame + 1) % MAX_CONCURRENT_FRAMES` after ever frame render?

**Comment by likemango** [comment]
@nitingupta910 Just as I thought! But there `currentFrame` and `currentBuffer` both used in `virtual void render()`, it may need a lot of changes in the code.
But it's true that triangle example only use one frame in flight, add another one should improve performence.

**Comment by SaschaWillems** [comment]
Yes, that's an oversight. I've been working on redoing all the sync stuff for some time now, see https://github.com/SaschaWillems/Vulkan/issues/871

**Comment by nitingupta910** [comment]
Thanks. On a related note, do you think the Khronos Vulkan tutorial is doing frame synchronization correctly: https://github.com/KhronosGroup/Vulkan-Tutorial/blob/main/attachments/17_swap_chain_recreation.cpp

It's a bit confusing since the triangle example in the official samples: https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/hello_triangle/hello_triangle.cpp is doing frame sync in a different way (not using per-frame sync objects, and what's the need for recycling semaphores).

**Comment by likemango** [comment]
@nitingupta910 Once a semaphore passed to GPU and do any operation with return result VK_SUCCESS, this semaphore already been reset and can be reused. That is what I think about Vulkan-Samples. Is that right?

**Comment by nitingupta910** [comment]
@likemango That makes sense.

**Comment by likemango** [comment]
> @likemango That makes sense.

In triangle example, it's fine to replace all 'currentBuffer' to 'currentFrame', and add `currentFrame = (currentFrame + 1) % MAX_CONCURRENT_FRAMES;` at the end of function `render()`. That works fine as we expected.

**Comment by SaschaWillems** [comment]
Be cautious: There is a reason `currentBuffer` and `currentFrame` are separated. Using the same for buffers and swapchain images may not work depending on how many swapchain images your implementation offers. I'll try to push some changes from my sync rework branch to properly fix this.
