### ISSUE TITLE
glTF loading from Blender 4.0

### ISSUE THREAD

**Issue by Mikez2015** [SaschaWillems/Vulkan#1094]
Hello.

In my project I use your loading glTF files.
It works correctly with files exported from Blender 2.8:

![gltf_1](https://github.com/SaschaWillems/Vulkan/assets/10583925/6b5f5398-71c6-49bb-bbb2-dec1717bc6ea)

If I export the latest versions from Blender, I get this:

![gltf_2](https://github.com/SaschaWillems/Vulkan/assets/10583925/3f0eae42-c82d-4577-96d4-91723117af2c)

It can be seen, for example, that some of the coordinates flies to 0.
This is definitely not a problem with Blender export, as I checked it with an online viewer - everything is ok there.

Please help.

**Comment by Mikez2015** [comment]
If i use 
#define ENABLE_VALIDATION true

I got:
"This sample only supports linear interpolations"

**Comment by Mikez2015** [comment]
I doing research.
I found out that the "vert.jointIndices" contains incorrect values.

**Comment by SaschaWillems** [comment]
The glTF skimnning sample is a basic sample that shows how to do skinning. It's not a fully fledged, 100% correct loader. Please test in https://github.com/SaschaWillems/Vulkan-glTF-PBR instead. If the model doesn't work there either, I need the model file.
