### ISSUE TITLE
Vulkan device error

### ISSUE THREAD

**Issue by dex36** [SaschaWillems/Vulkan#11]
Hello, when i run those samples i get asseration error in vulkaexamplebase.cpp. What can be wrong here ? I use SDK and 630 GeForce.

> / Vulkan device
> 	std::array<float, 1> queuePriorities = { 0.0f };
> 	VkDeviceQueueCreateInfo queueCreateInfo;
> 	queueCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
> 	queueCreateInfo.queueFamilyIndex = graphicsQueueIndex;
> 	queueCreateInfo.queueCount = 1;
> 	queueCreateInfo.pQueuePriorities = queuePriorities.data();
> 
> 	err = createDevice(queueCreateInfo, enableValidation);
> 	assert(!err); // throwing error
>

**Comment by SaschaWillems** [comment]
What is the value of err? If it's not VK_SUCCESS please enable validation (with installed SDK) and check the validation output for errors.

**Comment by dex36** [comment]
The value of err is (-3) and when i set enable validation ->true i get exeption ntdll.dl access violation gears.exe by "return vkCreateDevice(physicalDevice, &deviceCreateInfo, nullptr, &device);"

**Comment by SaschaWillems** [comment]
Do the samples from the LunarG-SDK work?

**Comment by dex36** [comment]
No ;/ there is the same problem " err = vkCreateDevice(demo->gpu, &device, NULL, &demo->device);"
err	-858993460

**Comment by SaschaWillems** [comment]
This may be a driver related issue. Do you have multiple GPUs? Maybte the wrong ICD is selected? Did you try running vulkaninfo from the SDK?

**Comment by dex36** [comment]
Hmm i think it can be problem with multiGPUs i have nividia and intel integrated card. I 've downloaded drivers for GeForce but i couldn't find for intel ;/

**Comment by MacGamerFR** [comment]
Hello, I have the same problem when creating a pipeline, err = -3.
I have two GPU : one integrated AMD in my APU that is not compatible with vulkan, and one discrete that is compatible with vulkan. I can't disable the integrated one, so, how could you change the GPU on which the vulkan context work ?

**Comment by SaschaWillems** [comment]
I have pushed a fix for the physical device enumeration with 40f13fc770bc714235c0545248d72aab967ba314

The example base will now first get the number of available Vulkan devices and setup a vector with that length. I guess with multiple devices this could have caused a crash/error :

`	// Physical device
	uint32_t gpuCount = 0;
	// Get number of available physical devices
	err = vkEnumeratePhysicalDevices(instance, &gpuCount, nullptr);
	assert(!err);		
	assert(gpuCount > 0);
	// Enumerate devices
	std::vector<VkPhysicalDevice> physicalDevices(gpuCount);
	err = vkEnumeratePhysicalDevices(instance, &gpuCount, physicalDevices.data());
...

	// Note : 
	// This example will always use the first physical device reported, 
	// change the vector index if you have multiple Vulkan devices installed 
	// and want to use another one
	physicalDevice = physicalDevices[0];`

If your systems still report multiple devices (supporting Vulkan) and device 0 doesn't work, please change the last line.

**Comment by dex36** [comment]
still error ;/ i think we must wait for Intel GPU support
