### ISSUE TITLE
Either VulkanExampleBase::semaphores or VulkanExample::semaphores

### ISSUE THREAD

**Issue by GoldSciences** [SaschaWillems/Vulkan#110]
Please choose between VulkanExampleBase::semaphores or VulkanExample::semaphores definitions, or change the names if both are different things. Otherwise it's very confusing.

**Comment by SaschaWillems** [comment]
Fixed with refactoring done in https://github.com/SaschaWillems/Vulkan/commit/fdd9594221e59c4cc600cd0c8de3b3c26ccb9d85. The triangle example no longer has a struct containing the semaphores with the same name as the base class.
