### ISSUE TITLE
Receiving VkImage as data.

### ISSUE THREAD

**Issue by ArtemiusMalakhikus** [SaschaWillems/Vulkan#1102]
Hello! I want to draw the depth buffer as a texture.
I'm using the vkCmdCopyImageToBuffer function to get data.
I have some questions:
1. Valid Usage - srcImage must have a sample count equal to VK_SAMPLE_COUNT_1_BIT.
Is it possible to customize image transitions when using MSAA? If yes, then how?
2. Are there other options for receiving VkImage as data?
3. When is the best time to receive VkImage? During a render pass or outside of it?

**Comment by SaschaWillems** [comment]
Please note that this place is for asking issues related to my samples, not general questions. For those use e.g. the Vulkan reddit.
