### ISSUE TITLE
Why in RTX mode not utilized all GPU power?

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/Vulkan#1111]
I have nvidia 3060 laptop and with default scene I have 85%-95% of GPU usage.
Why speed is variable?
When I try run on nvidia 4090, I have 25% -35% of GPU usage.
How to use 95% - 100% of GPU in RTX mode on ANY GPU?

First screenshot - raytracinggltf
![image](https://github.com/SaschaWillems/Vulkan/assets/3808839/f5ec437d-c764-47d5-9697-52526bb61b12)
as we see, clocks of GPU Core uses only 1492Mhz, not maximal 2010Mhz, 
Load 76%-84%, not always 100%

Second screenshot - rayquery
![image](https://github.com/SaschaWillems/Vulkan/assets/3808839/765daa7f-0d51-4fb8-8ce1-2a7ae20c2a75)
Load 73%-80% and clocks is same

Code compiled with Visual Studio 2019 in Release mode with recommended here [https://developer.nvidia.com/blog/vulkan-dos-donts/](https://developer.nvidia.com/blog/vulkan-dos-donts/)
SET  _NO_DEBUG_HEAP=1

How to get maximal performance with 95%-100% of GPU load all the time?

**Comment by tigrazone** [comment]
One more example
![image](https://github.com/SaschaWillems/Vulkan/assets/3808839/461e7290-c3f0-40d5-a1c1-4d6268bd9a6d)
code taken from your repo [https://github.com/SaschaWillems/VulkanPathTracer](https://github.com/SaschaWillems/VulkanPathTracer) and this is sceneIndex = 1 and scene from "models/CornellBox-Original.gltf"
here Load is 97%-100% all the time but GPU core clock 1200-1210MHz, not maximal 1950MHz.
Compiled with VS 2019 in Realease with same seted environment variable

**Comment by SaschaWillems** [comment]
Those are just samples. None of these is especially complex nor meant to show how to fully utilize a GPU.

**Comment by tigrazone** [comment]
Ok. What to do for fully utilize a GPU?

**Comment by SaschaWillems** [comment]
Fully utilizing a GPU is very hard and not always possible. That's totally out of scope for discussion in the issues of my samples.

**Comment by tigrazone** [comment]
thank you. 
if you have some articles to read about it, send me
