### ISSUE TITLE
_WIN32 in vulkanexamplebase.h

### ISSUE THREAD

**Issue by KaxelDreamhack123** [SaschaWillems/Vulkan#1116]
I have a 64x bit system, but the compiler says I can support _WIN32. The question is, this may somehow affect the performance of the program, because after studying some part of the code, I realized that support for several platforms is taken into account here (this is very cool) and some functions, methods, etc. are replaced accordingly. For example, the Instance creation function: `// Enable surface extensions depending on os
#if defined(_WIN32)
	instanceExtensions.push_back(VK_KHR_WIN32_SURFACE_EXTENSION_NAME);`

I understood that initially the VK_KHR_SURFACE_EXTENSION_NAME extension goes into the vector, which is 64x, and after that if _WIN32, then it goes too. As far as I understand, the fact that _WIN32 on 64x has a value of 1 means in VulkanSwapChain. I am interested in this code from VulkanSwapChain.cpp:`
// Create the os-specific surface
#if defined(VK_USE_PLATFORM_WIN32_KHR)
	VkWin32SurfaceCreateInfoKHR surfaceCreateInfo = {};
	surfaceCreateInfo.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
	surfaceCreateInfo.hinstance = (HINSTANCE)platformHandle;
	surfaceCreateInfo.hwnd = (HWND)platformWindow;
	err = vkCreateWin32SurfaceKHR(instance, &surfaceCreateInfo, nullptr, &surface);
`

`er = vkCreateWin32SurfaceKHR(instance, &surface Create Info, null ptr, &surface);` - not how it will affect system performance, since we define surface with Win32? In addition to _WIN32, there is also _WIN64, for which Vulkan does not have prefixes, they say, vkCreateWin64SurfaceKHR, but there is no vkCreateSurfaceKHR. As I understand it, the creation of swapchain took into account the fact that _WIN32 has a value of 1 at 64x and therefore there is a definition for initsurface only for _WIN32 to reduce the code, but I ask, will this not affect performance in any way? I just started implementing my project using the reverse engineering methodology and immediately fell into it)))
Also, VK_KHR_WIN32_SURFACE_EXTENSION_NAME compiler complains that it is undefined, although I tried to do so:
`#if defined(_WIN32)
		instanceExtensions.push_back(VK_KHR_WIN32_SURFACE_EXTENSION_NAME);
#endif`

**Comment by SaschaWillems** [comment]
`_WIN32` is always defined when compiling a 64-bit binary on Windows. There is no need separate code paths that use `_WIN64`.
