### ISSUE TITLE
Sample Request: VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#1123]
There aren't any samples out there showing the usage of `VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR`.
A detailed example will fill this void; may I suggest a `4:2:2 10 bit YUV` sample?

**Comment by SaschaWillems** [comment]
What would be the actual use case of such a sample?

**Comment by kyamant** [comment]
YUV (or YCbCr) format is predominantly used in video. Thus, the typical use case would be the intermix of video originated content and computed generated imagery, be it raytracing pipeline or graphics pipeline. 

The sample could be a glTF tv set but what is shown on that tv is coming from a video recorded in YUV format.

**Comment by SaschaWillems** [comment]
I don't have plans for any sample regarding Vulkan video. But feel free to open a request at https://github.com/KhronosGroup/Vulkan-Samples. Chances of getting such a sample over there are higher.
