### ISSUE TITLE
Question about computeheadless example

### ISSUE THREAD

**Issue by losanc** [SaschaWillems/Vulkan#1131]
Hi Willems, 

I have a question about computeheadless example. [here](https://github.com/SaschaWillems/Vulkan/blob/master/examples/computeheadless/computeheadless.cpp#L462) it creates a buffer memory barrier for `devicebuffer` from `HOST_WRITE` to `SHADER_READ`

After copy from staging buffer to device buffer, there is a [fence](https://github.com/SaschaWillems/Vulkan/blob/master/examples/computeheadless/computeheadless.cpp#L360) to wait for the finish of copy. So is this barrier still necessary ?

if it's necessary, why  `srcAccessMask` is` VK_ACCESS_HOST_WRITE_BIT`. Isn't `host_write` for the staging buffer, not device buffer? After the copy, shouldn't the srcAccessMask of device buffer be `VK_ACCESS_TRANSFER_WRITE_BIT`?

And thank you for this great tutorial!

**Comment by SaschaWillems** [comment]
Sorry for the late reply. The barrier is probably not necessary due to the fence. And yes, the src access mask doesn't make a lot of sense.
