### ISSUE TITLE
CompileShaders.py doesn't compile mesh and task shaders

### ISSUE THREAD

**Issue by TheSpecter52** [SaschaWillems/Vulkan#1143]
This might not be a big deal but I thought I should point this out - CompileShaders.py is missing .mesh and .task extension check while file parsing so it ignores mesh and task shaders.

**Comment by TheSpecter52** [comment]
This would also require to set specific spirv version while compiling these mesh , task and their respective frag shaders

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. I have updated both the GLSL and HLSL compilation scripts to support mesh and task shaders.
