### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by darbyford** [SaschaWillems/Vulkan#1149]
After carefully reading imGui instructions ( i.e. the comments in imgui.cpp etc. ), for enabling keyboard controls in the samples, fail to capture keyboard key presses in the samples.

**Comment by SaschaWillems** [comment]
Please elaborate. What is the actual question/issue?

**Comment by darbyford** [comment]
I want to detect specific keyboard key presses ( key_down and/or key_pressed ) in VulkanExample::updateUniformBuffers(). This is for the pbrtexture sample. The above imGui setup isn't achieving that goal. What is the proper imGui setup to achieve that goal?

**Comment by darbyford** [comment]
Problem solved. Keyboard, mouse, and controller input are built-in to the sample code. Thank you!
