### ISSUE TITLE
Crash in Multisampling example

### ISSUE THREAD

**Issue by Honeybunch** [SaschaWillems/Vulkan#115]
At line 164 in multisampling.cpp I get a crash in the Nvidia driver

```
vkTools::checkResult(vkCreateImageView(device, &viewInfo, nullptr, &multisampleTarget.color.view));
```
I'm running a GTX 780 on Windows 10 with only the LunarG SDK 1.0.5 and driver version 364.72

**Comment by SaschaWillems** [comment]
Thx, I'll check with my GTX 980 and report back. Worked fine on the Shield TV, though.

Any validation layer errors?

**Comment by Honeybunch** [comment]
I enabled validation and the console reported no errors before the crash

**Comment by SaschaWillems** [comment]
I can reproduce this with the latest drivers on a GTX 980. I'll try to find out why it crashes and report back.

**Comment by SaschaWillems** [comment]
@Honeybunch : This was caused by the use of lazily allocated memory which isn't supported. I've added a fallback for device local memory in cf1532dcc51e3a189dd36b8036c2cec5ca37f7d8.

Works fine on my GTX980 now. Can you check if it also works on the GTX780 now?

**Comment by Honeybunch** [comment]
Yes I can confirm it works!

**Comment by SaschaWillems** [comment]
Thx :+1:
