### ISSUE TITLE
A C only exemplar with a NUKLEAR GUI glfw Vulkan?

### ISSUE THREAD

**Issue by DaemonDave** [SaschaWillems/Vulkan#1154]
Would it possible for me to trouble you to adjust a NUKLEAR-glfw-vulkan C/C++ or explain to me how I need to adjust configuration 

Would you please look at
  [https://github.com/m0ppers/nuklear-glfw-vulkan](https://github.com/m0ppers/nuklear-glfw-vulkan)
And see if it wouldn't take more than 15 minutes to adjust 
To operate a GUI pipeline on top of a .C only exemplar?

I can't get two pipelines to work and I'm not sure if it's swapchains need to be the same and then how does the imageviews from one pipeline gets copied overtop or do the separate pipeline shaders don't need access to 

The problem with learning Vulkan is it has to be exquisitely correct or it doesn't work. I've struggled for weeks because I can't see what needs to go where. Or I get a useless YOU CAN'T USE THAT FLAG WITH THIS FORMAT error and exit that doesn't explain itself. 

If experts don't want to be bugged for SFQ it'll be easier if exemplars are clear and complete and not just obvious to experts. 

That's the opposite of how Linux works, experts can insert without knowledge beyond the interface because the interface is clear. 

But since Vulkan interface is lacking insight ( "the flux capacitor capacitates flux" style documentation) we are forced to try 50 interpretations.

**Comment by SaschaWillems** [comment]
I currently have no plans for such a sample.
