### ISSUE TITLE
Question reagrding shqdowmappingcascade example cascade descriptor sets

### ISSUE THREAD

**Issue by Skibbles0** [SaschaWillems/Vulkan#1157]
I have a question regarding the shadowmappingcascade.cpp example. On lines 501 to 509 where the descriptor sets for each cascade are being build, a image sampler for the depth image is included on line 506. Looking at the depth fragment and vertex shaders, it doesn't seem as if this sampler is ever used. I'm not sure why you would want to read from the specific sampler inside the depthpass shaders anyways.

During the command buffer building, there is a comment on line 380 that reads "The layer that this pass renders to is defined by the cascade's image view (selected via the cascade's descriptor set)" but I don't see this. isn't the image written to the selected framebuffer when it is bound on line 383?

Apologies if there is something I don't understand. I'm fairly new to Vulkan and may have missed what is going on in this example.

And thanks for all your great Vulkan examples!

**Comment by SaschaWillems** [comment]
You're correct. That sample went through so many iterations and pull requests that esp. the descriptor setup no longer made sense. I have completely reworked and simplified that part. I hope it's easier to follow now.
