### ISSUE TITLE
example errors

### ISSUE THREAD

**Issue by sevstels** [SaschaWillems/Vulkan#1158]
Examples are not built in Visual Studio for x64. 
Multiple errors due to _WIN32 definitions in code.

![verr](https://github.com/user-attachments/assets/cf367118-c7d2-49e3-8223-88cd423586d4)

**Comment by SaschaWillems** [comment]
This must be a setup issue on your side. I'm on x64 and CI also builds for that. Please elaborate on how you compile my samples. It also looks like you did some modifications (project name).

**Comment by sevstels** [comment]
In your examples you don't have ready projects for vs. To open *.sln and run it without long agony. So I created a new one according to this description.  https://github.com/Valrog/Vulkan_Visual_Studio_Template And named it myself.   

But it didn't help. Further, plugging in the code below, I got over 400x more errors.  This really demotivated me. As it will probably take about a week to run the simple examples. 
```
#if defined (_WIN32)
#include <vulkan/vulkan_win32.h>
#elif defined(__linux__)
#include <vulkan/vulkan_xcb.h>
#elif defined(__ANDROID__)
#include <vulkan/vulkan_android.h>
#endif
```
However. the compiler for x64 builds uses _WIN64. If you change it to _WIN32 as in your files, compilation errors start in other files

**Comment by sevstels** [comment]
There's a less good example right there. But even there it is done ‘crookedly’ and the project is not assembled.  It is very difficult for a beginner to understand these errors.  And there is not a single, even simple example for VS, which just shows a window.

https://www.codeproject.com/Articles/5291871/Vulkan-Playground-An-Easy-Introduction-to-Vulkan-u?msg=6021031#xx6021031xx

**Comment by SaschaWillems** [comment]
You are supposed to use CMake to generate the build files for your compiler toolchain/platform of choice as noted in the build instructions at : https://github.com/SaschaWillems/Vulkan/blob/master/BUILD.md

This has been working for 8+ years and is also used in the CI/CD
