### ISSUE TITLE
trianglevulkan13 example: invalid value is used in api call

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#1159]
In `trianglevulkan13.cpp`, the function `render()` contains
```
// Draw indexed triangle
vkCmdDrawIndexed(commandBuffer, indexCount, 1, 0, 0, 1);
```

The last argument to that function is `firstInstance` which should have been set to 0.

**Comment by SaschaWillems** [comment]
It actually doesn't matter, as instanceId isn't used anywhere. Will fix next time I change something about that sample.
