### ISSUE TITLE
DestroyDebugReportCallback is never called because of unitialized variable

### ISSUE THREAD

**Issue by floooh** [SaschaWillems/Vulkan#116]
I wanted to verify a crash I'm getting with the Vulkan SDK 1.0.5 when cleaning up the debug-report extension inside vkDestroyDebugReportCallbackEXT, and I noticed that this is never called in the demos:

- CreateDebugReportCallback() here (https://github.com/SaschaWillems/Vulkan/blob/30fc2ae77b0b7531f6dfd92efe74c9c4241d2b75/base/vulkandebug.cpp#L82) initializes the local debugReportCallback
- ...but the if() around DestroyDebugReportCallback function here (https://github.com/SaschaWillems/Vulkan/blob/30fc2ae77b0b7531f6dfd92efe74c9c4241d2b75/base/vulkandebug.cpp#L96) is never entered (at least in debug mode on my machine) because the msgCallback variable hasn't been initialized

If DestroyDebugReportCallback() is called, I'm also getting a crash inside this function (some sort of nullptr access) at least with the Vulkan SDK 1.0.5.

(EDIT: missing variable name)

**Comment by SaschaWillems** [comment]
I guess this is related to #15. I'll check if it still happens with the most recent drivers and report back.

**Comment by floooh** [comment]
Oops, yes, this is the same bug, I'll close mine since it's a dup.
