### ISSUE TITLE
trianglevulkan13: adding overlay (UI) causes validation error

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#1161]
The _dynamicrendering_ example displays the UI without validation errors. 
What should I do to make _trianglevulkan13_ display UI without validation errors?

In `VulkanExample() : VulkanExampleBase()`  set
`settings.overlay = true;`

In `virtual void render() override` add 
`drawUI(commandBuffer);`
just before 
`vkCmdEndRendering(commandBuffer);`

The example display the UI but with **validation errors** due to buffer destroy calls (one for vertex and one for index) in 
`bool UIOverlay::update()`

ERROR: [-464217071][VUID-vkDestroyBuffer-buffer-00922] : Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] | MessageID = 0xe4549c11 | vkDestroyBuffer():  can't be called on VkBuffer 0x59ffe0000000003d[] that is currently in use by VkCommandBuffer 0x25b7adb1db0[]. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)

ERROR: [-464217071][VUID-vkDestroyBuffer-buffer-00922] : Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] | MessageID = 0xe4549c11 | vkDestroyBuffer():  can't be called on VkBuffer 0x808562000000003f[] that is currently in use by VkCommandBuffer 0x25b7adb1db0[]. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)

**Comment by SaschaWillems** [comment]
That's to be expected. The triangle samples are deliberately verbose and try to use as little base class functionality as possible. The UI overlay on the other hand is tied to the base class, and the base class will take care of stuff like resizing and managing the command buffers. There is no easy way to fix that for the triangle sample and I don't have plans to do so.
