### ISSUE TITLE
About VK_KHR_dynamic_rendering_local_read

### ISSUE THREAD

**Issue by bioorg** [SaschaWillems/Vulkan#1163]
Hello, I am a beginner but enthusiastic in graphics and Vulkan

May I ask

Can I find good tutorials for "dynamic rendering" and "dynamic rendering local read" together (with the newest version) ??

Is the tutorial "trianglevulkan13" the one ?

Also, VK_KHR_dynamic_rendering is now inside Vulkan core (1.3), so I can use vkCmdBeginRendering without KHR suffix,
then is VK_KHR_dynamic_rendering_local_read also inside Vulkan core now ?

Thank you

**Comment by SaschaWillems** [comment]
See https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/dynamic_rendering and https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/dynamic_rendering_local_read

Please note that this issue tracker is for issues related to my samples and not for asking general questions.

**Comment by bioorg** [comment]
Thank you and have a great weekend, Sascha
