### ISSUE TITLE
waitFences issue of Triangle, Trianglevulkan13

### ISSUE THREAD

**Issue by bioorg** [SaschaWillems/Vulkan#1164]
Hello,
in the base class VulkanExampleBase,
there is a member
std::vector<VkFence> waitFences;

And in the examples triangle and trianglevulkan13
there is also a member of the same name
std::array<VkFence, MAX_CONCURRENT_FRAMES> waitFences{};

I think, this may cause problems
and at now, I don't know which waitFences is used actually in those programs

Also, there looks to be some kind of memory leak issue (I am not sure exactly, on the Visual Studio debugging)
and in the destroyer ~VulkanExample(),
I don't know which waitFences is destroyed actually

vkDestroyFence(device, waitFences[i], nullptr); <=== See this

.....

So could you please rewrite those two examples triangle and trianglevulkan13 and also VulkanExampleBase
so that no redundant variable exist ?

Also may I ask
Actually, which waitFences is used actually in those programs ?

Thank you

**Comment by bioorg** [comment]
I found out
waitFences in VulkanExampleBase is related to drawCmdBuffers (three items)
and
waitFences in TriangleVulkan13 is related to currentFrame (two frames) in virtual void render()

So this is so confusing

Please help me to check if there is something wrong or not

**Comment by SaschaWillems** [comment]
That's correct. The hello triangle samples deliberately do their own sync to make them as stand-alone as possible. Other samples use different (and simplier) means of syncing. If you want to learn how to properly sync in Vulkan take a look at one of the hello triangle samples.

See https://github.com/SaschaWillems/Vulkan/issues/871 for plans on updating other samples to use that way of sync.

**Comment by bioorg** [comment]
Hello, how are you, Sascha
Because I am a beginner, I don't understand what you just said exactly
but I will study those materials (samples etc) more
Thank you and see you

**Comment by bioorg** [comment]
Hello, Sascha

May I ask one more question about this issue?

May I change the name of the variable waitFences (in Triangle example) to something like waitTriangleFences ?
Is it not better to have different names ?
I wonder why we have the same name for two different variables

Please help me more about this. Thank you
