### ISSUE TITLE
That's correct. The hello triangle samples deliberately do their own sync to make them as stand-alone as possible. Other samples use different (and simplier) means of syncing. If you want to learn how to properly sync in Vulkan take a look at one of the hello triangle samples.

### ISSUE THREAD

**Issue by bioorg** [SaschaWillems/Vulkan#1165]
Hello, Sascha
Thank you for your answer just before
and sorry for this reposting

But I have one question

May I change the name of the variable waitFences (in Triangle example) to something like waitTriangleFences ?
Is it not better to have different names ?
I wonder why we have the same name for two different variables

Please help me more about this. Thank you

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

              That's correct. The hello triangle samples deliberately do their own sync to make them as stand-alone as possible. Other samples use different (and simplier) means of syncing. If you want to learn how to properly sync in Vulkan take a look at one of the hello triangle samples.

See https://github.com/SaschaWillems/Vulkan/issues/871 for plans on updating other samples to use that way of sync.

_Originally posted by @SaschaWillems in https://github.com/SaschaWillems/Vulkan/issues/1164#issuecomment-2466264997_

**Comment by SaschaWillems** [comment]
Please note, this is for reporting issues regarding the samples. I don't answer general Vulkan questions in here. This has some community links where you can ask such questions: https://vulkan.org/learn

**Comment by bioorg** [comment]
OK, I understand. Have a nice weekend, Sascha
