### ISSUE TITLE
"/build/Vulkan/data/shaders/hlsl/renderheadless": not found   

### ISSUE THREAD

**Issue by Quicksymphony** [SaschaWillems/Vulkan#1170]
Hi!
I have a  slight issue with this example.
  54 | >>> COPY --from=builder /build/Vulkan/data/shaders/hlsl/renderheadless/ /build/Vulkan/data/shaders/hlsl/renderheadless/
  
  Error:
  ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref [reference-redacted]: "/build/Vulkan/data/shaders/hlsl/renderheadless": not found
  
  `[ 81%] Building C object base/CMakeFiles/base.dir/__/external/ktx/lib/filestream.c.o
[ 90%] Building C object base/CMakeFiles/base.dir/__/external/ktx/lib/vkloader.c.o
[ 90%] Linking CXX static library libbase.a
[ 90%] Built target base
[100%] Building CXX object examples/CMakeFiles/computeheadless.dir/computeheadless/computeheadless.cpp.o
[100%] Linking CXX executable ../bin/computeheadless
[100%] Built target computeheadless
[ 90%] Built target base
[100%] Building CXX object examples/CMakeFiles/renderheadless.dir/renderheadless/renderheadless.cpp.o
[100%] Linking CXX executable ../bin/renderheadless
[100%] Built target renderheadless
ls: cannot access '/build/Vulkan/data/shaders': No such file or directory
Shader directory not found`

how can this be resolved?

**Comment by SaschaWillems** [comment]
This looks like a setup issue. The end of your error message refers a folder that's not part of my repository. How are you building the samples? On what platform? I need more details to help.

**Comment by Quicksymphony** [comment]
> This looks like a setup issue. The end of your error message refers a folder that's not part of my repository. How are you building the samples? On what platform? I need more details to help.

Thanks for the quick response.
for the samples folder Dockerfile.ubuntu:
WORKDIR /build

# Clone and build Vulkan examples
ARG BUILD_EXAMPLES="computeheadless renderheadless"
ENV BUILD_EXAMPLES="computeheadless renderheadless"

RUN git clone --recursive https://github.com/SaschaWillems/Vulkan.git \
    && cd Vulkan && mkdir -p build && cd build \
    && cmake .. \
    && make ${BUILD_EXAMPLES} \
    && ls -R /build/Vulkan/data/shaders || echo "Shader directory not found"

# Use the base image again for the runtime
FROM vnc_ubuntu_test

COPY --from=builder /build/Vulkan/build/bin/computeheadless /build/Vulkan/build/bin/computeheadless
COPY --from=builder /build/Vulkan/build/bin/renderheadless /build/Vulkan/build/bin/renderheadless
COPY --from=builder /build/Vulkan/data/shaders/glsl/computeheadless/ /build/Vulkan/data/shaders/glsl/computeheadless/
COPY --from=builder /build/Vulkan/data/shaders/glsl/renderheadless/ /build/Vulkan/data/shaders/glsl/renderheadless/
COPY --from=builder /build/Vulkan/data/shaders/hlsl/computeheadless/ /build/Vulkan/data/shaders/hlsl/computeheadless/
COPY --from=builder /build/Vulkan/data/shaders/hlsl/renderheadless/ /build/Vulkan/data/shaders/hlsl/renderheadless/

for the docker/Dockerfile i'm testing with a different FROM:
FROM nvidia/cuda:12.6.2-runtime-ubuntu24.04

The original reference:
https://gitlab.com/nvidia/container-images/vulkan/-/tree/master?ref_type=heads

i'm backtracking to see why the folders are offset. Any help would be greatly appreciated.

**Comment by SaschaWillems** [comment]
Sorry, no clue here. I've never built my samples with a docker file and don't have plans to support that. 

If I were to create a docker file I'd simply clone my repo inside of it and just build all samples. On a mid-range CPU you can compile the whole repo in ~40s. Trying to extract a few samples and make them compile is probably not worth the time you're trying to save.
