### ISSUE TITLE
Same depth/stencil attachment for all framebuffers

### ISSUE THREAD

**Issue by ShabbyX** [SaschaWillems/Vulkan#120]
In [`vulkanexamplebase.cpp:1277`](https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkanexamplebase.cpp#L1277), you say that:

>    // Depth/Stencil attachment is the same for all frame buffers

May I ask why? You rightly create a view for each swapchain image and a frame buffer accordingly. If the depth/stencil attachment is the same for all frame buffers, doesn't that mess things up when multiple threads try to render using different frame buffers at the same time (because they share the depth/stencil buffer)?

**Comment by SaschaWillems** [comment]
The examples don't use multiple threads for writing to depth/stencil attachments, so it's fine the way it is. If you want to render to multiple frame buffers with depth attachments, then you may need multiple depth/stencil attachments.

**Comment by ShabbyX** [comment]
Thanks for the clarification. I'm experimenting with Vulkan without much knowledge on modern opengl (I know, I know), and have yet to figure out what's the best way to render from multiple threads to the screen.

I'll figure it out though. I take a peek at your examples when the standard is not very clear, so thanks for them too!

**Comment by carmaZXZ** [comment]
@SaschaWillems  Although the examples don't use mutiple threads, but did it uses the inflight rendering? In the condition of inflight rendering, the depth/stencil may mess up too~ I don't know if what I said is right ~~
