### ISSUE TITLE
Fire particle example is not like on your screenshot 

### ISSUE THREAD

**Issue by Warezovvv** [SaschaWillems/Vulkan#121]
![Amazing fire](http://imgur.com/tGgIf4el.png)

4.4.5-1-ARCH
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

`WARNING: Haswell Vulkan support is incomplete
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability`

**Comment by SaschaWillems** [comment]
Can you run this with validation activated? The Intel GPU I'm testing with (Gen7) doesn't even load the textures, so I suspect a driver bug.

**Comment by Warezovvv** [comment]
Seems I have some errors :)

`Starting /home/nikita/Documents/Work/Diploma/build-Vulkan-Desktop-Debug/bin/particlefire...
WARNING: Haswell Vulkan support is incomplete
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
ERROR: [Image] Code 13 : CreateImage extents exceed allowable limits for format: Width = 1280 Height = 720 Depth = 1:  Limits for Width = 0 Height = 0 Depth = 0 for format VK_FORMAT_D32_SFLOAT_S8_UINT.
ERROR: [Image] Code 13 : CreateImage resource size exceeds allowable maximum Image resource size = 0x384000, maximum resource size = 0 
ERROR: [Image] Code 13 : CreateImage mipLevels=1 exceeds allowable maximum supported by format of 0
ERROR: [Image] Code 13 : CreateImage arrayLayers=1 exceeds allowable maximum supported by format of 0
ERROR: [Image] Code 13 : CreateImage samples VK_SAMPLE_COUNT_1_BIT is not supported by format 0x00000000
ERROR: [DS] Code 6 : Cannot map an image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL. Only GENERAL or PREINITIALIZED are supported.
ERROR: [DS] Code 6 : Cannot submit cmd buffer using image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when first use is VK_IMAGE_LAYOUT_PREINITIALIZED.
ERROR: [DS] Code 6 : Cannot map an image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL. Only GENERAL or PREINITIALIZED are supported.
ERROR: [DS] Code 6 : Cannot map an image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL. Only GENERAL or PREINITIALIZED are supported.
ERROR: [DS] Code 6 : Cannot submit cmd buffer using image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when first use is VK_IMAGE_LAYOUT_PREINITIALIZED.
ERROR: [DS] Code 6 : Cannot submit cmd buffer using image with layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when first use is VK_IMAGE_LAYOUT_PREINITIALIZED.
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability
WARNING: Unsupported SPIR-V Capability
ERROR: [MEM] Code 11 : Mem Object 14531184 has not been freed. You should clean up this memory by calling vkFreeMemory(14531184) prior to vkDestroyDevice().
ERROR: [OBJTRACK] Code 4 : OBJ ERROR : VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT object 0xddba70 has not been destroyed.
ERROR: [OBJTRACK] Code 4 : OBJ ERROR : VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT object 0xdcc230 has not been destroyed.
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance
ERROR: [DebugReport] Code 1 : Debug Report callbacks not removed before DestroyInstance`

**Comment by SaschaWillems** [comment]
Thx. Looks like some image transitions are missing. Is this from the current source or one of the pre compiled binaries?

**Comment by Warezovvv** [comment]
I cloned repository, opened in Qt Creator and build. What can I try to do?)

**Comment by Warezovvv** [comment]
![image](https://cloud.githubusercontent.com/assets/5683877/15075518/7597c78c-13ad-11e6-9f30-cf4b19c46e56.png)
Today I ran example on Windows 10 AMD FX 8530 && AMD HD 7870 in Visual Studio 2015, result is the same. Output only abou " Symbols loaded."
What can it be ? :)

**Comment by SaschaWillems** [comment]
Are you getting any validation errors or warnings? The screenshot is missing the particle system which is rendered using point sprites, maybe the GPU is lacking a feature. I'll try to test this on my R9 390 and see if it works there.

**Comment by Warezovvv** [comment]
after changing ENABLE_VALIDATION to true, I got 
![image](https://cloud.githubusercontent.com/assets/5683877/15077778/b747746a-13b8-11e6-94b2-8da781fcde87.png)

**Comment by SaschaWillems** [comment]
Do you have the SDK installed? The examples use the VK_LAYER_LUNARG_standard_validation meta layer, the error is raised if this cannot be found.

**Comment by Warezovvv** [comment]
Yeah.. forgot about that on Windows, sorry! 
So output is 
`Validation enabled:
ERROR: [SC] Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderClipDistance but is not enabled on the device
ERROR: [SC] Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderCullDistance but is not enabled on the device
ERROR: [SC] Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderClipDistance but is not enabled on the device
ERROR: [SC] Code 15 : Shader requires VkPhysicalDeviceFeatures::shaderCullDistance but is not enabled on the device`

**Comment by SaschaWillems** [comment]
Thx for your effort :! The validation errors you see are due to a recent addition to the SDK and should not cause the particle system to be missing, so it must be something else. I'll check with my AMD card tomorrow and see if I can reproduce this or if it may be some driver related issue on the HD7870.

**Comment by SaschaWillems** [comment]
I can confirm this on AMD. On current AMD drivers, gl_PointCoord is always zero in the shader (on OpenGL you had to enable point sprites for that to work) and so no texture coordinates are generated for the fire particles. And since the sampler is set to transparent black texels, particles are not visible. 

I'll see if the example code is missing something, and if not will inform AMD about it.

**Comment by SaschaWillems** [comment]
@Warezovvv : Can you please check again with the [AMD Crimson 16.5.2 driver](http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-Software-Crimson-Edition-16.5.2.aspx)? I just tested this and point sprites are now again rendering correct.

**Comment by Warezovvv** [comment]
@SaschaWillems : Yeah, AMD now works fine, don't know about intel on arch, haven't that pc anymore, so I think you can close this thread .
P.S. Why AMD have so bad drivers? They initialized Mantle project and Vulkan have heritage of it.

**Comment by SaschaWillems** [comment]
> P.S. Why AMD have so bad drivers? They initialized Mantle project and Vulkan have heritage of it.
I found their drivers to be actually quite good. The pointSize bug is a thing that can happen, especially with a beta driver. Other than that their drivers work just fine from my experience.
