### ISSUE TITLE
vulkanScene leaking meshes

### ISSUE THREAD

**Issue by GoldSciences** [SaschaWillems/Vulkan#122]
The vulkanScene example seems to forget to delete the mesh instances.

You can add:
```
		delete(demoMeshes.logos);
		delete(demoMeshes.background);
		delete(demoMeshes.models);
		delete(demoMeshes.skybox);
```
In the VulkanExample destructor, after releasing the Vulkan resources assigned to them.

Cheers,

**Comment by 1ace** [comment]
Do you know how to make pull requests? If not, this kind of small changes can be the perfect opportunity to [learn] (https://help.github.com/articles/creating-a-pull-request/) :+1:

Note to Sascha: I haven't read the relevant code, and I won't have time to do so tonight either, so don't consider this a +1 on the change.
(It just so happens I'm heading to the Khronos UK presentation on Vulkan right now actually ^^)

**Comment by GoldSciences** [comment]
I believe I'm supposed to pull, create a branch, make the change, commit and push and create the pull request. That's what I do at the company I work at at least. The problem is that I do that all the time and I have to deal with a bunch of repositories, I have my own forkS of this repo with a variety of changes on each version and sometimes I just don't have the time or I"m too tired to do it, etc. =/ Writing the post was just simpler at that moment. I hope you understand. It was 8am here when I wrote this and I was about to leave to come to the office.

**Comment by 1ace** [comment]
I wasn't complaining (sorry of it came across like that), just taking the opportunity to help you learn something new in case you didn't.
It also makes it easier for you to change the code directly, and gives you credit in the history :+1:

**Comment by GoldSciences** [comment]
You're right, sorry, I should have taken it as the help you were providing, no matter if I knew about branching already.

**Comment by SaschaWillems** [comment]
Thx not noticing :+1:  Going to fix this.
