### ISSUE TITLE
no Target solution

### ISSUE THREAD

**Issue by andreluizbarbieri** [SaschaWillems/Vulkan#126]
Must change the target SDK, in case that VS2015 update 2 with only SDK version 10, just do with Retarget Solution in right click in projects.

**Comment by SaschaWillems** [comment]
Can you elaborate? I'm actually developing with VS2015.

**Comment by andreluizbarbieri** [comment]
Sorry. I updated VS2015 to update 2 in my win10 and it remove SDK 8.1
Then just you must Retarget each project to new Target plataforma 10.586
