### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by mikeindevon** [SaschaWillems/Vulkan#128]
I have beeen trying to build the triangle example.  I am running Win 7 and MSVC2013.  It gets stuck in image.inl line 85 and similar places where max is used.

assert(TexelCoord.x < Dimensions.x && TexelCoord.x < std::numeric_limitsstd::uint32_t::max());

The warnings I get are:
warning C4003: not enough actual parameters for macro 'max'
error C2589: '(' : illegal token on right side of '::'
error C2059: syntax error : '::'

If I comment out this and similar lines it all goes through.  I tried #define NOMINMAX but this made no difference.  Any help appreciated.

**Comment by 1ace** [comment]
The file you're referring to is imported from [gli](https://github.com/g-truc/gli), so you should raise this issue on that repo.
I've had a quick look, and it's possible that file is simply missing an `#include <limits>`. You might want to mention that in your new issue.

**Comment by 1ace** [comment]
Actually, I've now had a look at the version of that file on `gli/master` and it's been heavily modified (especially that function), so I doubt the issue is still the same (or present at all).

So: you shouldn't raise this issue on that other repo, and as far as this repo, the issue should go away when `gli` gets updated, but it's been basically rewritten and Sascha's code would need extensive modifications for that.

**Comment by regnirpsj** [comment]
try defining `WIN32_LEAN_AND_MEAN` or just `undef max` (and `undef min` while you're at it). m$ decided a (perceived) century ago that it would be fun to have max/min as macros around and never got rid of them.

**Comment by 1ace** [comment]
@regnirpsj: very good point, I had forgotten about that whole ordeal with `msvc`… So I was completely wrong :]
*Oh, blissful ignorance :P*

BTW, if you're trying to just get rid of the `min`/`max` macros, you can define `NOMINMAX`.

**Comment by regnirpsj** [comment]
@1ace: you're right it's `NOMINMAX`; see http://stackoverflow.com/questions/5004858 as a refrence for posterity

**Comment by SaschaWillems** [comment]
I recently updated the repo to use recent gli and glm versions. If this issue still persists, please open a new issue.
