### ISSUE TITLE
Do you plan vkCmdUpdateBuffer example ?

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#131]
Interested vkCmdUpdateBuffer.

**Comment by SaschaWillems** [comment]
No, nothing planned. I don't think this justifies a new example as it's similar to a buffer copy. But I may use this in one of the examples for e.g. partial ubo updates.

**Comment by Ronniko** [comment]
vkCmdUpdateBuffer is only allowed outside of a render pass. This command is treated as “transfer” operation, for
the purposes of synchronization barriers. The VK_BUFFER_USAGE_TRANSFER_DST_BIT must be specified in
usage of VkBufferCreateInfo in order for the buffer to be compatible with vkCmdUpdateBuffer.

**Comment by Ronniko** [comment]
vkCmdPushConstants more convenient.

**Comment by SaschaWillems** [comment]
vkCmdPushConstants and vkCmdUpdateBuffer  serve two completley different purposes. vkCmdUpdateBuffer can e.g. be used to do partial updates to ubos, ssbos, etc.

**Comment by SaschaWillems** [comment]
But please use the Khrono's official Vulkan forums to ask questions instead of this project's bug tracker.
