### ISSUE TITLE
Please update the binaries

### ISSUE THREAD

**Issue by z3ntu** [SaschaWillems/Vulkan#133]
For me they only displayed in about 640x480 resolution (or something) and the rest of the screen multiplied the pixels on the edge (see screenshot). Compiling the examples from source worked great.
Binaries: ![vulkan demo scene - 2016 by sascha willems_043](https://cloud.githubusercontent.com/assets/3768500/14575257/e4e6302c-0360-11e6-84db-d1619073c919.png)
Self-compiled: 
![vulkan demo scene - 2016 by sascha willems_045](https://cloud.githubusercontent.com/assets/3768500/14575288/1734c34a-0361-11e6-8d5c-8afa78344beb.png)

**Comment by SaschaWillems** [comment]
The binaries have been compiled before I implemented window resizing, that's why they look different. I'm currently tweaking a few of the examples and will provide new examples for all platforms soon.

**Comment by z3ntu** [comment]
The binaries for Linux are still not updated apparently.

**Comment by SaschaWillems** [comment]
Yes, neither are the windows ones. The only ones I updated recently are the android ones due to a vendor request. 

I'm pretty short on time, but releasing updated binaries is still on my list.

**Comment by SaschaWillems** [comment]
Took much longer than expected, but I finally got around updating the binaries for **all** platforms.

Downloads can be found at http://vulkan.gpuinfo.org/examples

**Comment by z3ntu** [comment]
Thanks anyways 👍
