### ISSUE TITLE
Leaking Command Buffer When Staging Data in Triangle Sample

### ISSUE THREAD

**Issue by Manuzor** [SaschaWillems/Vulkan#135]
In the triangle sample when using staging buffers in the `prepareVertices` method, a `VkCommandBuffer` is allocated (line 374) but never freed. I assume that's not on purpose?

**Comment by SaschaWillems** [comment]
Nope, that's not intentional. Thx for spotting this, I'll fix this later today.

**Comment by SaschaWillems** [comment]
Oddly the validation layers didn't catch this one. Older SDK versions reported command buffers that haven't been freed before destroying the instance, but in 1.0.8 I can't get the validation layers to report that error. That's why I didn't catch that one.
