### ISSUE TITLE
Questions about texture mapping in Chopper

### ISSUE THREAD

**Issue by MichaelWei1990** [SaschaWillems/Vulkan#136]
Hi Sascha, 

I have been looking into the vulkan samples, both samples and Chopper, but I am still pretty confused about how the materials/textures are mapped on the model, especially for model's sub-mesh(es). In the solutions, I did not find codes about the mapping procedure. It would be very kind of you to point me to a correct direction or where the mapping procedure is processed. 

Best regards, 
Michael Wei

**Comment by SaschaWillems** [comment]
What do you mean by "mapping"? If you're referring to how textures are bound to meshes, the answer are descriptor sets. You assing your textures sampler and view to a VkDescriptorImageInfo and add it to the descriptor set you want your mesh to be rendered with at your desired binding point.

If you have multiple meshes with different textures you just create multiple descriptor sets (that can share the same descritpror set layout) and bind the descriptor that contains the sampler binding with the texture you want to use for that mesh like this :+1: 

```
// Pipeline with descriptor set layout that matches the shared descriptor sets
vkCmdBindPipeline(...pipelines.mesh...);
...
// Mesh A
vkCmdBindDescriptorSets(...&meshA.descriptorSet... );
vkCmdDrawIndexed(...);
// Mesh B
vkCmdBindDescriptorSets(...&meshB.descriptorSet... );
vkCmdDrawIndexed(...);

```

This is the most straightforward way of binding textures (samplers) for different (sub)meshes.

P.S. : Can you please use e.g. the official Khronos Vulkan Forums for general questions on Vulkan? I don't want the issue tracker to be used as a place for people to ask general Vulkan questions.
