### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by teamblubee** [SaschaWillems/Vulkan#14]
no issues, just wanted to say thinks!

**Comment by sgorsten** [comment]
I second this. Digging through this repository is making it very easy to learn this very large new API.

**Comment by li3** [comment]
I third this! Thanks for putting this together!

**Comment by SaschaWillems** [comment]
Thanks for the kind words. Very much appreciated :+1:

**Comment by fcvarela** [comment]
+1k, thank you, sir!

**Comment by mtronicsDev** [comment]
I fourth this! It is really hard to find examples covering large parts of the API, you seem to have done it all. :+1:

**Comment by SaschaWillems** [comment]
There are a few examples that didn't make the cut, but with things settled I plan on adding some more demos that cover some of the stuff I'v been missing. E.g. multi threaded command buffer generation, staging buffers (performance) and using some of the layers available.

**Comment by httpdigest** [comment]
+1 for providing the examples! None of the other examples/demos I found, even in the LunarG SDK, are of this quality and show that much!

**Comment by Ronniko** [comment]
Thanks for MSAA example !
I do MSAA example. Vulkan API disappointed me.
With MSAA 4x my FPS = 1200, without MSAA my FPS = 2600 in the same 3d scene !
In Directx 11I lost very little FPS.
Now I understand why in game The Talos Principle low fps on Vulkan API. And high in Directx 11

**Comment by jpbruyere** [comment]
Wonderful job, thank you!!

**Comment by eero-t** [comment]
> None of the other examples/demos I found, even in the LunarG SDK, are of this quality and show that much!

+1
