### ISSUE TITLE
Why are you writing both buffers in a for loop

### ISSUE THREAD

**Issue by mlfarrell** [SaschaWillems/Vulkan#141]
I'm curious as to why you pre-populate both command buffers with the same contents.  Doesn't this use up valuable CPU time?  Wouldn't it be better to only record to the buffer that will be for the next image?

**Comment by SaschaWillems** [comment]
`I'm curious as to why you pre-populate both command buffers with the same contents`

The two buffers are not populated with the same content. The render pass used by the command buffers contains a reference to the framebuffer (see vkCmdBeginRenderPass) which differs. 

`Doesn't this use up valuable CPU time?`

No. Command buffers are generated only on application startup, not during runtime. And generating them is very fast.

You could extract the rendering commands into a secondary command buffer that is only created once and embedded into the two primary command buffers using vkCmdExecuteCommands, but in the end that would be pretty much the same.

**Comment by mlfarrell** [comment]
Ah I see. I keep forgetting you can do this.  It's a very different way of thinking.  I suppose even the most dynamic systems can cache their command buffers instead of resetting them and re-recording them like I've been doing each frame.

**Comment by SaschaWillems** [comment]
Exactly, don't re-record command buffers each frame unless necessary (or you want to demonstrate something special). That's the reasoning behind command buffers and e,g, NV_Command_List for OpenGL but also applies to other parts of Vulkan like semaphores and fences too. While creating most Vulkan objects except for pipelines should be pretty fast try to re-use as much as possible.
