### ISSUE TITLE
Triangle.cpp : vertex attribute description binding defined twice

### ISSUE THREAD

**Issue by themike10452** [SaschaWillems/Vulkan#143]
The _problem_ is between the lines 532 and 542 in triangle.cpp

**binding** member is defined twice, first by a macro and  then by a hardcoded value that overrides the macro ...

// Location 0 : Position
**vertices.attributeDescriptions[0].binding = VERTEX_BUFFER_BIND_ID;**
vertices.attributeDescriptions[0].location = 0;
vertices.attributeDescriptions[0].format = VK_FORMAT_R32G32B32_SFLOAT;
vertices.attributeDescriptions[0].offset = 0;
**vertices.attributeDescriptions[0].binding = 0;**
// Location 1 : Color
**vertices.attributeDescriptions[1].binding = VERTEX_BUFFER_BIND_ID;**
vertices.attributeDescriptions[1].location = 1;
vertices.attributeDescriptions[1].format = VK_FORMAT_R32G32B32_SFLOAT;
vertices.attributeDescriptions[1].offset = sizeof(float) * 3;
**vertices.attributeDescriptions[1].binding = 0;**

**Comment by SaschaWillems** [comment]
Thx :+1:  will clean this up after work.
