### ISSUE TITLE
Unable to pass shader source

### ISSUE THREAD

**Issue by adityaatluri** [SaschaWillems/Vulkan#148]
Hi,
I am trying to pass source inside project rather than loading from a file. I am getting assertion error at `vkCreateComputePipelines`

**Comment by SaschaWillems** [comment]
Please add some detail. 

- Did you change one of the existing examples?
- Are you passing SPIR-V or GLSL (if it's the later, you need a vendor-specific extensions)
- Enable the validation layers and check for error messages

**Comment by adityaatluri** [comment]
1. Yes. I was changing computeparticles.
2. I am passing GLSL as a string. It worked when I tried with GLSL file.
3. Working on it.

**Comment by SaschaWillems** [comment]
If you want to pass GLSL directly to Vulkan you need to enable VK_NV_glsl_shader. Note that this extension is only available on NVIDIA.

**Comment by adityaatluri** [comment]
Gotcha! 
Also, can you please create compute-only project (simple vector add). I was trying to do that and got hung up at descriptors. (Able to do pipeline stages).

**Comment by SaschaWillems** [comment]
Do you mean headless (no render output?)

**Comment by adityaatluri** [comment]
Yes.

**Comment by adityaatluri** [comment]
Hi,
I am stuck here. I know that I am doing lot of things wrong. Please take a look at it.
https://gist.github.com/adityaatluri/7d21d47bc89cfc6b08de43ba46203db7

**Comment by 1ace** [comment]
@adityaatluri This isn't a forum. Please ask your questions on the [Khronos forums] (https://forums.khronos.org/forumdisplay.php/114-Vulkan-High-Efficiency-GPU-Graphics-and-Compute) for instance.

And don't tell someone to help you like that, you won't get a good response.

**Comment by SaschaWillems** [comment]
AS @1ace said, please ask such questions on a forum, this is an issue tracker. I'm also active at the Khronos forum and StackOverlfow so I might take a look at it if I find the time (I only do Vulkan stuff in my spare time though).

Also make sure that you run with the Validation layers enabled first, as they might hint you at potential problems.

**Comment by adityaatluri** [comment]
Hi @1ace ,
Thank you for pointing to Khronos forums. I thought non-rendering Vulkan example would be a great add to this project. It wasn't about getting help. It's about helping @SaschaWillems to grow this project.

Hi @SaschaWillems ,
I'll post it soon on StackOverflow or Khronos group if I couldn't get past the issue. Enabling NVIDIA glsl extension help resolve the issue.
