### ISSUE TITLE
 EarlyFragmentTests

### ISSUE THREAD

**Issue by twanks123** [SaschaWillems/Vulkan#159]
Hello Sascha,
i am working on a rendering engine with vulkan and i have a really silly question :D
So far so good i can render unlimited objects with textures and lighting also works (forward rendering with blending pipelines). 
But i need the Depth-Test to be calculated before the fragment shader executes and i dont know how i can specify this in the shader. I dont understand what the Vulkan Documentation means: 

An explicit control is provided to allow fragment shaders to enable early fragment tests. If the fragment shader specifies the EarlyFragmentTests OpExecutionMode, the per-fragment tests described in Early Fragment Test Mode are performed prior to fragment shader execution. Otherwise, they are performed after fragment shader execution.

So how i specify "EarlyFragmentTests OpExecutionMode"? Thanks in advance :) (and thanks for your awesome code samples!)

**Comment by SaschaWillems** [comment]
I haven't yet used early fragment tests in Vulkan, but they should be enabled the same way as with OpenGL (see [here](https://www.opengl.org/wiki/Layout_Qualifier_(GLSL)#Early_fragment_tests)).

The "OpExecutionMode" refers to SPIR-V. To enable this, put this in your GLSL shader:

`layout(early_fragment_tests) in;`

This will enable the SPIR-V exection mode:

![image](https://cloud.githubusercontent.com/assets/10283127/15599140/5bd08610-23e1-11e6-82cb-0c6d837d0960.png)

**Comment by twanks123** [comment]
okay thanks i didnt know where to ask such questions. :)
