### ISSUE TITLE
Problem presenting swap chain to current buffer

### ISSUE THREAD

**Issue by MacGamerFR** [SaschaWillems/Vulkan#16]
Assertion fail occurs in triancle.cpp, when "Present the current buffer to the swap chain"

> 233 // This will display the image
> 234 err = swapChain.queuePresent(queue, currentBuffer);
> 235 assert(!err); // Fail here

err = VK_ERROR_INITIALIZATION_FAILED (-3)

**Comment by SaschaWillems** [comment]
I need more details. What hardware, driver and OS? Did you run the example with validation enabled (requires the SDK)? If not, can you please do so and check for validation errors?

**Comment by MacGamerFR** [comment]
MSI GX70 3BE Notebook : AMD A10 5750M CPU with Radeon HD 8650G iGPU, and Radeon HD 8970M GPU. Windows 10 installed. 
I'm messing around with drivers : error change after installing/removing vulkan/WHQL drivers...

**Comment by dex36** [comment]
Hey where did you find SDK 1.0.2 ?

**Comment by MacGamerFR** [comment]
It comes with AMD Vulkan drivers.

**Comment by SaschaWillems** [comment]
AMD have just released [updated drivers](http://support.amd.com/en-us/kb-articles/Pages/Radeon-Vulkan-Beta.aspx) with support for SDK version 1.0.3.1.

Can you try with these?

**Comment by MacGamerFR** [comment]
I've tried, and got the same error on your example. I make a note : I get different errors when I've installed the drivers differently. When I install vulkan drivers (upgrading from WHQL drivers), I get no vulkan adapter, and after uninstalling regularly and installing regular, I get vulkaninfo working, but your example stop working on the swapchain (vulkanswapchain.hpp).

**Comment by SaschaWillems** [comment]
That's odd. SwapChain works fine here on AMD (Windows 7), even with the initial beta driver. Though I'm on a more recent GPU, so it may be a problem tied to your GPU.

Does this happen with the samples from the LunarG SDK too?

**Comment by MacGamerFR** [comment]
Yep, the tri or cube samples tells me I do not have a "CLI"

**Comment by MacGamerFR** [comment]
I tried on my desktop build, and the samples actually works good but the pushconstant show only glitchs, I don't know why (I don't have a working VS on this machine).

**Comment by SaschaWillems** [comment]
Push constants are a rather new feature, and since drivers are still beta they may not work on every implementation. Does the shadowmapping example work fine? It uses push constants too, but not arrays.

**Comment by MacGamerFR** [comment]
On the Shadowmapping example, I get glitches too, but only on one wall, with sometimes seeing a circle on this wall. 
![shadowmapping](https://cloud.githubusercontent.com/assets/8853392/13204825/810b580e-d8d9-11e5-8315-8835a9c43236.png)

**Comment by MacGamerFR** [comment]
Swap chain issue resolved with new drivers (feb27) and last version of examples.
All examples works fine exept pushconstant, and have one wall of the Shadowmappingomni example that is just covered with one shadow (like before).

**Comment by SaschaWillems** [comment]
Thx for the info. I'm testing on AMD with that driver too and hope to have the two examples fixed soon.

**Comment by MacGamerFR** [comment]
pushconstant example is now properly working :+1:
