### ISSUE TITLE
Component mappings should use VK_COMPONENT_SWIZZLE_IDENTITY 

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#160]
Many of the examples do this on creating an ImageView

`view.components = { VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A };`

However, setting each component to it's own swizzle is unnecessary.  Instead use `view.components = {}` to rely on the fact that VK_COMPONENT_SWIZZLE_IDENTITY is 0

**Comment by SaschaWillems** [comment]
That's true, the explicit swizzles don't make sense anymore and are a relic from the early SDK tays.
