### ISSUE TITLE
Consider switching to the vk_cpp C++ wrapper

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#163]
It significantly reduces boilerplate code and has a number of nice features for returning or passing in container objects

I've created a branch on my own fork where I've ported over all the examples and tested them on Windows:  https://github.com/SaschaWillems/Vulkan/compare/master...jherico:cpp

**Comment by PistonMiner** [comment]
I don't think this is a good idea, for a couple of reasons. Firstly, these examples are supposed to demonstrate the Vulkan API, not the vkcpp API. The boilerplate code is part of a complete Vulkan setup. Secondly, vkcpp is far from complete. The STL mode also removes some API clarity and introduces C++ exceptions, which are not necessarily a good thing as they also add overhead and require handling.

**Comment by 1ace** [comment]
That's impressive work, thanks, but I agree with @PistonMiner: the point of this codebase is to use plain Vulkan. Using a wrapper takes away from the learning value of this code.
You can always advertise your fork as a `vkcpp` example (make that branch the default one), that's what forks are for :+1:

I would add to anyone thinking about using `vkcpp` that it's being reworked internally and some parts of it might change in incompatible ways (starting with the name), so I'd hold off for the next few weeks.
