### ISSUE TITLE
Anonymous structs with initializers prevent samples from working on Visual Studio 2012.

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#167]
A number of the example classes contain anonymous struct members like this

```
    struct {
        float tessLevel = 3.0f;
    } uboTC;
```

or 

```
    struct {
        VkPipeline postCompute;
        // Compute pipelines are separated from 
        // graphics pipelines in Vulkan
        std::vector<VkPipeline> compute;
        uint32_t computeIndex = 0;
    } pipelines;
```

or 

```
    struct {
        int32_t texWidth = TEX_DIM;
        int32_t texHeight = TEX_DIM;
        float radialBlurScale = 0.25f;
        float radialBlurStrength = 0.75f;
        glm::vec2 radialOrigin = glm::vec2(0.5f, 0.5f);
    } uboQuadFS;

```

In all places where you declare an anonymous struct _and_ specify initializers for the values, they resulting code does not work on Visual Studio 2012.  The initializers are ignored and the values end up uninitialized.  Giving the anonymous struct a name resolves the problem:

```
    struct UboQuadFS {
        int32_t texWidth = TEX_DIM;
        int32_t texHeight = TEX_DIM;
        float radialBlurScale = 0.25f;
        float radialBlurStrength = 0.75f;
        glm::vec2 radialOrigin = glm::vec2(0.5f, 0.5f);
    } uboQuadFS;
```

**Comment by SaschaWillems** [comment]
I know, that's why the readme says to use Visual Studio 2015 or any other modern C++ compiler that supports C++14. I don't have plans to support older versions.

**Comment by jherico** [comment]
The readme doesn't mention C++14.  It just says that VS 2015 is supported out of the box.  As far as I can tell, these anonymous structs with initializers are the *only* thing (in the example code) that blocks all the examples from working just fine in VS 2015.  Many of the examples which don't rely on any anonymous struct initializers work fine as is.

If you're interested I could make a small PR that fixes the issue.

**Comment by cdwfs** [comment]
In fact, the readme specifically says "...using a C++ compiler that supports C++11". But even if that were changed to "a compiler that supports C++14", it _still_ wouldn't be entirely true; I'm currently trying to build with clang 3.4 (which [allegedly supports C++14](http://clang.llvm.org/cxx_status.html)), but these samples still fail due to the use of the unknown `-std=gnu++14` flag.

The dependency on C++14 features like anonymous initializers has prevented me from building your Vulkan samples on any of my available development machines, despite using compilers that (while not bleeding-edge) are definitely still in very widespread use. Are these features _really_ so important that they're worth limiting your audience for?

**Comment by SaschaWillems** [comment]
> The dependency on C++14 features like anonymous initializers has prevented me from building your Vulkan samples on any of my available development machines, despite using compilers that (while not bleeding-edge) are definitely still in very widespread use. Are these features really so important that they're worth limiting your audience for?

Nope. I don't have any problems removing (or replacing or iddeffing them). I'm using different compilers too, but they all seem to support the C++14 features I'm using just fine. Even those from the Android NDK that are usually a bit behind.

So if you could hint me at what is actually missing to get these working (maybe an output from a compiler that doesn't work) I'd take a look at this. Limiting the audience is not what I intended :wink:

**Comment by jherico** [comment]
Just stop using anonymous structs.... i.e. use `struct UboQuadVS { ... } uboQuadVS;` instead of `struct { ... } uboQuadVS;`
