### ISSUE TITLE
Why does multithreading example use per-thread vertex and index buffers?

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#168]
I noticed this when I saw validation errors on the example.  The mesh loader does not apply give the buffer memory the TransferSrc flag, so the copy command in setting up the per-thread buffers generates the errors.  However, I'm not clear on why each thread needs it's own copy of the static mesh data.  Replacing the copy code in `prepareMultiThreadedRenderer` with `thread->mesh = meshes.ufo` seems to work just fine and produce no validation errors.

**Comment by SaschaWillems** [comment]
This dates back to when the buffers weren't device local and may not be necessary anymore. I'll take a look at it this weekend.

As for the validation error from the missing usage flags, see #164.

**Comment by jherico** [comment]
ok, I was just trying to understand if I was breaking something. thanks.

**Comment by dmarian** [comment]
For the record, I adapted this example. I use a single vertex and index buffer for all threads and on each thread I do:

vkBeginCommandBuffer(...);
vkCmdSetViewport(...);
vkCmdSetScissor(...);
vkCmdBindPipeline(...);
vkCmdBindVertexBuffers(...);
vkCmdBindIndexBuffer(...);
for_each (object) {
  vkCmdPushConstants(...);
  vkCmdDrawIndexed(...);
}
vkEndCommandBuffer(...);

**Comment by SaschaWillems** [comment]
Yes, I tested that too some weeks ago and it works fine. Haven't found the time to update this example yet though.
