### ISSUE TITLE
Win32: Window does not resize properly when switching from maximized to non-maximized view.

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#171]
in the WM_SIZE event handler code, the line 

`if ((wParam == SIZE_MAXIMIZED) || (wParam == SIZE_MINIMIZED))`

should be

`if ((wParam == SIZE_MAXIMIZED) || (wParam == SIZE_RESTORED))`

**Comment by SaschaWillems** [comment]
I purposely changed this some time ago with https://github.com/SaschaWillems/Vulkan/commit/5266c25c33d2c6a39f6ad54f96690076018dc705. SIZE_RESTORED was fired constantly during a normal resize, which was something I did not want to happen.

The current solution is not perfect, but I haven't had the time to dig deeper into this.

**Comment by jherico** [comment]
An alternative would add a WM_ENTERSIZEMOVE handler.  If you receive WM_ENTERSIZEMOVE, then you'd ignore WM_SIZE messages until the corresponding WM_EXITSIZEMOVE.  If you haven't seen a WM_ENTERSIZEMOVE, then you process WM_SIZE messages without bothering to check the wParam.

**Comment by jherico** [comment]
I've ported my code to use the new GLFW 3.2 API for window creation, keyboard handling and mouse handling.  In addition to a size callback, it also has a 'framebuffer' size callback, which does what your code is attempting to do, i.e. triggers the callback on maximize, restore, and when you _finish_ any drag resize operation.  It also eliminates the issue of having custom key handlers in the WndProcs on the various individual applications, because you can use the GLFW_KEY_XXX defines.  Doesn't help with Android, but it would likely eliminate 90% of your Linux vs Windows blocks.
