### ISSUE TITLE
When allocating memory for the image in vulkantextoverlay.hpp the wrong memory requirements are used

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#172]
On line 213 of vulkantextoverlay.hpp you get the required memory type for the image:

```
allocInfo.memoryTypeIndex = getMemoryType(
   memReqs.memoryTypeBits,  
   VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
```

However, the memReqs structure still contains the data fetched for the buffer allocated above in this line `vkGetBufferMemoryRequirements(device, buffer, &memReqs);`

There should be a corresponding call to `vkGetImageMemoryRequirements(device, image, &memReqs);` but there is not.

**Comment by SaschaWillems** [comment]
Well spotted, thx :+1:

**Comment by jherico** [comment]
It's just a side effect of essentially re-writing all the code.  I probably wouldn't have noticed it myself, except that I've refactored lines 180 to 193 into

```
		auto createBufferResults = context.createBuffer(vk::BufferUsageFlagBits::eVertexBuffer, bufferSize);
		buffer = createBufferResults.buffer;
		memory = createBufferResults.memory;
```

I haven't yet made a similar refactoring for constructing images, so I noticed that the memReqs was still being used by the image allocation, but not being re-initialized anywhere.
