### ISSUE TITLE
VulkanTextureLoader ignores image usage flags

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#175]
The load texture function takes an image usage parameter like so:

```
void VulkanTextureLoader::loadTexture(
    std::string filename, 
    VkFormat format, 
    VulkanTexture *texture, 
    bool forceLinear, 
    VkImageUsageFlags imageUsageFlags
)
```

However, in both the staging and non-staging paths, the ImageCreateInfo structure is hard coded to use VK_IMAGE_USAGE_SAMPLED_BIT.  The parameter is ignored completely.

**Comment by SaschaWillems** [comment]
Thx for pointing out. This is obviously wrong and there is actually even an overload that always passes the sampled bit, so the base function should not hard code it.

**Comment by jherico** [comment]
You could eliminate the overload by declaring the main function as

```
void VulkanTextureLoader::loadTexture(
    std::string filename, 
    VkFormat format, 
    VulkanTexture *texture, 
    bool forceLinear = false, 
    VkImageUsageFlags imageUsageFlags = VK_IMAGE_USAGE_SAMPLED_BIT
)
```

**Comment by SaschaWillems** [comment]
That's true, and this should apply to several functions in the code base. Maybe I'll do that with the next refactor :wink:
