### ISSUE TITLE
flushCommandBuffer method in triangle.cpp does an invalid evaluation.

### ISSUE THREAD

**Issue by GoldSciences** [SaschaWillems/Vulkan#176]
It seems that you're doing an incorrect `if(free)` in triangle.cpp's `flushCommandBuffer()`. This is likely because you copied the code of the method from the `VulkanExampleBase` class. This doesn't build for me because `free()` is a C function and nothing else for that method's scope. I believe that if this works for you it's because your compiler is doing an implicit conversion of the function pointer to free() instead of the intended input parameter of flushCommandBuffer().

**Comment by SaschaWillems** [comment]
Yes, you're right. The base class flush takes free as an argument, the triangle doesn't, which is obviously wrong. Thx for noticing :+1:

**Comment by GoldSciences** [comment]
Glad to be of help! This work of yours is very helpful.
