### ISSUE TITLE
android-sample can not be compiled

### ISSUE THREAD

**Issue by therains1018** [SaschaWillems/Vulkan#177]
Hi, thanks for sharing the Vulkan Samples. 
The console reminds me that "Buildfile: build.xml does not exist!", after I executed the "build triangle" command. any suggestion?

**Comment by SaschaWillems** [comment]
The build.bat should initialize all required files (by calling _setup), including the build.xml:

`call android.bat update project -p . -t android-19`

If that's not working you may have to install the API19 (4.4.2) SDK platform from the Android SDK manager.

I should mention this somewhere in the readme, or try to check if there is a higher API-Level installed and just use that.

**Comment by therains1018** [comment]
Many thanks for helping, that works.:)
