### ISSUE TITLE
Sample request: Mipmap generation

### ISSUE THREAD

**Issue by bioglaze** [SaschaWillems/Vulkan#178]
A sample demonstrating mipmap chain generation would probably be useful to many people.

**Comment by SaschaWillems** [comment]
The 2D and cuibemap texture examples already load a complete mip map chain, so I guess you're talking about runtime generated mipmaps?

If so, then that's not on my list but should be pretty straight forward (just blit and resize to the mip levels).

Can't promise anything, but if I find the time I may add such a demo.

**Comment by SaschaWillems** [comment]
A bit late, but I have just added an example that generates a complete mip chain, down from the first image to the smallest one: https://github.com/SaschaWillems/Vulkan/tree/master/texturemipmapgen

While it's not completely finished yet, the interesting parts are there, including proper layout transitions and tested to work on three different vendors.

**Comment by bioglaze** [comment]
Thanks! I already did my own implementation but this is a good reference.
