### ISSUE TITLE
comment about possible minimal memory leak

### ISSUE THREAD

**Issue by greatelk** [SaschaWillems/Vulkan#179]
Hello,

at: https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkandebug.cpp#L55

if this path can be reached, you need to add free(message); before the return to avoid the little memory leak

Thanks for your work,

Marc

**Comment by SaschaWillems** [comment]
Thx for pointing this out. And yes, that path could be reached for performance warnings (VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT) if enabled. It actually makes no sense to not output those messages if the performance bit is set, so I'll change that.

**Comment by SaschaWillems** [comment]
I have changed the code for the debug message callback to use std::strings instead and also cleaned up the code and added some comments.
