### ISSUE TITLE
Vulkan GLM Clip space

### ISSUE THREAD

**Issue by Karanlos** [SaschaWillems/Vulkan#18]
Hey,

Noticed you set the viewport depth from 0.0 1.0. This causes some issues because GLMs perspective projection matrix transforms into a -1.0 to 1.0 clip space.

The newest GLM trunk has a new define which enables 0.0 to 1.0 clip space by defining GLM_DEPTH_ZERO_TO_ONE before including matrix_transform.hpp.

**Comment by SaschaWillems** [comment]
See #45
