### ISSUE TITLE
keyboard input not working

### ISSUE THREAD

**Issue by sdack** [SaschaWillems/Vulkan#181]
I am running the examples and noticed that keyboard input doesn't work.

Moving the mouse to rotate the view and using the right mouse button to zoom in and out is working.
The graphics themselves display and appear to be running fine.

The system is Linux Debian stretch/sid with kernel 4.6.2 on an AMD FX 8350 and an Nvidia GTX 960.
Xfce 4.12.13, Xorg 1.18.3, libxcp 1.11.1, libXau 1.0.8, libXdmcp 1.1.2, libvulkan 1.0.8.0, libassimp 3.2

Also, thank you for giving us these examples.

**Comment by SaschaWillems** [comment]
That's true. Right now Keys used by the examples themselves don't work on Linux. I just haven't had the time to add key mappings for Linux yet, but will do so soon.
