### ISSUE TITLE
VkShaderModule_T* vkTools::loadShader(const char*, VkDevice, VkShaderStageFlagBits): Assertion `fp' failed.

### ISSUE THREAD

**Issue by xyproto** [SaschaWillems/Vulkan#185]
Hi. I just compiled the latest commit (37b8eef41c76ff70930da08013a6b35cbbf8ac18). It builds fine. However, when running one of the binary files, for instance `gears`, I get the following output:

```
./gears
gears: ../base/vulkantools.cpp:300: VkShaderModule_T* vkTools::loadShader(const char*, VkDevice, VkShaderStageFlagBits): Assertion `fp' failed.
zsh: abort (core dumped)  ./gears
```

Here's my [vulkaninfo output](http://ix.io/UgY).
I'm on 64-bit Arch Linux, using Nvidia 367.27 with a GTX 750 Ti.
The binaries were built with GCC 6.1.1, CMake 3.5.2 and Ninja 1.7.1.

**Comment by xyproto** [comment]
The weird thing is that when running `stace gears` instead of `./gears`, it works and the animated 3D-gears appears.

**Comment by xyproto** [comment]
When running `bin/gears` from the parent directory, it works. But segfaulting when not finding a file may be an issue still.

**Comment by parkerlreed** [comment]
Same thing for me with amdgpu-pro, except mine doesn't even run with strace.

````
[parker@x3720 bin]$ pacman -Q | grep vulkan
amdgpu-pro-vulkan-driver 16.30.3.315407-1
lib32-amdgpu-pro-vulkan-driver 16.30.3.315407-1
vulkan-headers 1:1.0.23-1
vulkan-icd-loader 1.0.21.0-1
vulkan-validation-layers 1.0.21.0-1
````

````
[parker@x3720 Vulkan]$ bin/gears 
gears: /home/parker/build/Vulkan/base/vulkantools.cpp:313: VkShaderModule_T* vkTools::loadShader(const char*, VkDevice, VkShaderStageFlagBits): Assertion `fp' failed.
Aborted (core dumped)
[parker@x3720 Vulkan]$ cd bin/
[parker@x3720 bin]$ ./gears 
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/parker/build/Vulkan/base/vulkandevice.hpp at line 477
gears: /home/parker/build/Vulkan/base/vulkandevice.hpp:477: void vk::VulkanDevice::flushCommandBuffer(VkCommandBuffer, VkQueue, bool): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)
````

**Comment by SaschaWillems** [comment]
@parkerlreed: If vkTools::loadShader fails, it means that it could not find shaders. Make sure they are in the right directory as described in the readme. If your binaries are in vulkan\bin, the shaders have to be in vulkan\data\shaders.

**Comment by parkerlreed** [comment]
@SaschaWillems I running from git so the data folder is there.

**Comment by DaHoC** [comment]
I had the same issue, I solved it (at least for me) by changing:
base/vulkanexamplebase.cpp:70
from
`	return "./../data/";`
to
`	return "../data/";`
So the shaders (which are at the correct place under data/) are found.
To be honest, I don't understand/know, what ./ should do at this place?

**Comment by xyproto** [comment]
Introducing a `VULKAN_DEMO_DATA_PATH` environment variable might be a good idea, especially if it is meant to be possible to package the executables and install them in locations like `/usr/bin`.

**Comment by arkdae** [comment]
I'm not sure if this is the same issue I'm having, but it is the only one that showed up when I did a search for "ERROR_INITIALIZATION_FAILED." This is what I get when I try to run the triangle demo:

Vulkan-master/bin 110> ./triangle 
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/jlm/downloads/Vulkan-master/triangle/triangle.cpp at line 245
triangle: /home/jlm/downloads/Vulkan-master/triangle/triangle.cpp:245: void VulkanExample::flushCommandBuffer(VkCommandBuffer): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)

Not all of the demos error this way. For example, the texture demo works. I have just installed a Radeon RX 480 8Gb into my computer. I'm running Arch Linux, and I've installed the AMDGPU pro drivers. Everything compiled just fine. I'm running Xorg 1.18, Linux kernel 4.9.

**Comment by SaschaWillems** [comment]
That's pretty odd, as VK_ERROR_INITIALIZATION_FAILED is actually not a valid error code to be returned by vkWaitForFences. Does this happen immediately? If not it's possible that the wait for the fence runs into a timeout. But then it should actually return a different error.

**Comment by arkdae** [comment]
I think it happens pretty quickly:

/bin 8> time ./triangle 
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/jlm/downloads/Vulkan-master/triangle/triangle.cpp at line 245
triangle: /home/jlm/downloads/Vulkan-master/triangle/triangle.cpp:245: void VulkanExample::flushCommandBuffer(VkCommandBuffer): Assertion `res == VK_SUCCESS' failed.
Aborted (core dumped)

real	0m0.330s
user	0m0.293s
sys	0m0.027s

**Comment by SaschaWillems** [comment]
As this sounds like a different issue than the one reported here, can you open up a new issue for this to continue the discussion?

**Comment by SaschaWillems** [comment]
Examples will now check if the asset folder can be found at startup (see https://github.com/SaschaWillems/Vulkan/commit/d9cf65667b6ba2117773c5b51365cb1ca40e10cd).
