### ISSUE TITLE
VK_IMAGE_LAYOUT_PREINITIALIZED used with VK_IMAGE_TILING_OPTIMAL.

### ISSUE THREAD

**Issue by mre4ce** [SaschaWillems/Vulkan#187]
loadTexture in texture/texture.cpp creates an image with VK_IMAGE_TILING_OPTIMAL and VK_IMAGE_LAYOUT_PREINITIALIZED 

The spec says:

"Currently, VK_IMAGE_LAYOUT_PREINITIALIZED is only useful with VK_IMAGE_TILING_LINEAR images because there is not a standard layout defined for VK_IMAGE_TILING_OPTIMAL images."

You probably want to use VK_IMAGE_LAYOUT_UNDEFINED instead.

**Comment by SaschaWillems** [comment]
This is fixed for the texture loader. A few of the examples also use preinitialized as the initial layout for optimal tiled images, and though it's not against the specs undefined is the correct one. I'll fix these too.

**Comment by mre4ce** [comment]
Using pre-initialized may cause a driver to go down the wrong path trying to maintain the texture contents. In this particular case the contents are updated using a vkCopyBufferToImage before changing the layout so using pre-initialized should be harmless, but probably still better to only use well-defined behavior in Vulkan.

Btw, I believe you previously pointed out that copying image content from a staging buffer is simpler than using a staging linear texture. I argued that it's not that big a deal because it is not all that much simpler. However, using a staging buffer is probably the preferred approach anyway, not because it's simpler, but because it only uses required Vulkan behavior. There are devices/drivers out there right now that don't support any linear textures.
