### ISSUE TITLE
How to get this running on Ubuntu 16.04?

### ISSUE THREAD

**Issue by cirosantilli** [SaschaWillems/Vulkan#188]
I already have OpenGL 4 working on an NVIDIA NVS 5400M (~2012) and NVIDIA driver 361.42 on a Thinkpad T430.

If I do `mkdir build; cd build; cmake ..; make` the binary outputs compile fine under `bin`.

But if I try to run them I get:

    ./triangle: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory

Then I've tried:

    sudo apt-get install libvulkan-dev

and now running the binaries gives:

    Could not create Vulkan instance : 
    ERROR_INCOMPATIBLE_DRIVER

Also asked at: http://askubuntu.com/questions/774131/installing-nvidia-vulkan-drivers-for-16-04

**Comment by SaschaWillems** [comment]
Does your GPU actually support Vulkan? It's not listed on [NVIDIA's supported device list](https://developer.nvidia.com/vulkan-driver). I'm not sure, but the NVS 54000M may be based on the FERMI architecture that does not support Vulkan.

**Comment by cirosantilli** [comment]
Oh no, I'm Fermi. I thought anything that ran OpenGL 4 would also run Vulkan. Sad. Buy new GPU.
