### ISSUE TITLE
Today I am install vulkan spec. 1.0.17 and all examples stop run !

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#189]
All get create device error !

Windows 7 AMD Radeon HD 7950.

**Comment by Ronniko** [comment]
All work fine with vulkan spec. 1.0.05

**Comment by SaschaWillems** [comment]
Please add more details? Are you using the latest AMD drivers? Do you compile from source? Does this happen with validation enabled?

**Comment by Clematrics** [comment]
since 1.0.17, device layers and vkEnumerateDeviceLayerProperties are deprecated. Hope it helps ! https://vulkan.lunarg.com/app/doc/1.0.17.0/windows/release_notes-1.0.html

**Comment by SaschaWillems** [comment]
But that should only apply when using validation, though it works fine here on NVIDIA with the latest drivers and SDK.

@Clematrics: But yes, I guess I should update the example base code to reflect these changes.

**Comment by Ronniko** [comment]
I try install Crimson 16.6.1 but setup get me error "Display driver not have digital signature" and setup aborted.
Befor i install many Crimson version (15\16.3) and all install fine.

**Comment by SaschaWillems** [comment]
Do the examples from the LunarG SDK work? If not this is probably driver related.

**Comment by Ronniko** [comment]
> Do the examples from the LunarG SDK work?

No

**Comment by SaschaWillems** [comment]
Well, then it looks more like a driver/system issue. AMD has a [Vulkan forum](https://community.amd.com/community/devgurus/graphics_programming).
