### ISSUE TITLE
I install Vulkan spec. 1.0.17 and vkCreateWin32SurfaceKHR get me surface = NULL !

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#192]
Befor i use Vulkan spec. 1.0.5
And all work fine.
vkCreateWin32SurfaceKHR get me surface = adres.
But after i install Vulkan spec. 1.0.17 and vkCreateWin32SurfaceKHR get me surface = NULL !

Windows 7 64 bit service pack 1
AMD HD 7950
Driver Crimson 16.6.1

**Comment by Ronniko** [comment]
vkCreateWin32SurfaceKHR get me error 0xFFFFFFF9

**Comment by SaschaWillems** [comment]
Does this happen with my examples only? If not, pleas run the vkjson_info.exe and check it's output. If it's related to the driver, please report this at the AMD forums.

**Comment by Ronniko** [comment]
Strange !
When i create instance with extension "VK_KHR_win32_surface"
Then vkCreateWin32SurfaceKHR  create surface, and surface = adr !
But if i create instance with extension "VK_KHR_surface"
vkCreateWin32SurfaceKHR get me error and surface = NULL

**Comment by Ronniko** [comment]
in system vulkaninfo.exe
Get me three extensions:
"VK_KHR_surface"
"VK_KHR_win32_surface"
"VK_EXT_debug_report"

**Comment by SaschaWillems** [comment]
Does this only happen with my examples or do the SDK examples fail too?

**Comment by Ronniko** [comment]
I found error.
Create instance must have 3 extensions.
I create instance with one extension.
