### ISSUE TITLE
Build error (Linux) deferred.cpp:21

### ISSUE THREAD

**Issue by RicardasSim** [SaschaWillems/Vulkan#193]
In file included from deferred.cpp:21:0:
deferred.cpp: In function ‘void handleEvent(const xcb_generic_event_t*)’:
vulkanexamplebase.h:430:1: error: a function-definition is not allowed here before ‘{’ token
 {                         \
 
Fixed by adding  } \  after line 428 to vulkanexamplebase.h

before:
427 vulkanExample->handleEvent(event); \
428 } \
429 int main(const int argc, const char *argv[]) \

after:
427 vulkanExample->handleEvent(event); \
428 } \
429 } \
430 int main(const int argc, const char *argv[]) \

**Comment by SaschaWillems** [comment]
Thx for noticing :+1: 

Will fix when I get home.
