### ISSUE TITLE
push_constants

### ISSUE THREAD

**Issue by ChristophLGDV** [SaschaWillems/Vulkan#195]
The shadow examples, specifically the offscreen shader use a layout qualifier
'push_constant'

Using the generator below i get an error:
'push_constant' : unrecognized layout identifier, or qualifier requires assignment (e.g., binding = 4)

https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Windows/

**Comment by SaschaWillems** [comment]
Push constants are a glsl language addition for Vulkan, so I guess the glslang validator from your link is outdated and does not know what to do with that block and thus expects a binding point (which is not required for a push constant block).

Please use the glslangvalidator from the LunarG SDK or compiled from the [current sources](https://github.com/KhronosGroup/glslang) for generating the SPIR-V shaders.

**Comment by ChristophLGDV** [comment]
Thank you, that did the trick.
