### ISSUE TITLE
Incorrect depth resolve attachment.

### ISSUE THREAD

**Issue by mre4ce** [SaschaWillems/Vulkan#197]
The "multisampling" sample sets up a resolve attachment for the depth buffer. However, the spec says:

"If pResolveAttachments is not NULL, each of its elements corresponds to a color attachment (the element in pColorAttachments at the same index)."

"If colorAttachmentCount is not 0, and pResolveAttachments is not NULL, pResolveAttachments must be a pointer to an array of colorAttachmentCount valid VkAttachmentReference structures"

Afaik you will have to use vkCmdResolveImage if you want to resolve a multi-sampled depth buffer.

**Comment by SaschaWillems** [comment]
Thx for pointing this out. I'll take a look at that.

**Comment by Qjames** [comment]
Checked the spec

> Resolve of depth/stencilimages is not supported.
Is there a way to resolve multisampled depth buffer?
Thanks.

**Comment by Novum** [comment]
The correct way of doing this is to read the samples individually from a shader. Depth multisample resolve can't be done in a meaningful, generic way.
