### ISSUE TITLE
all demos fail to run on linux

### ISSUE THREAD

**Issue by tjaalton** [SaschaWillems/Vulkan#20]
triangle: .../vulkan-demos.git/base/vulkantools.cpp:236: VkShaderModule_T* vkTools::loadShader(const char*, VkDevice, VkShaderStageFlagBits): Assertion `size > 0' failed.
Aborted (core dumped)

running the intel driver on linux

**Comment by SaschaWillems** [comment]
This assertion is raised if the shader files could not be found. Be sure to put the binaries into the bin subfolder (see readme.md for details) and make sure they have access to the shaders in data/shaders.

I tested all examples on Linux and they run fine.

**Comment by tjaalton** [comment]
OK I missed that.. so it's not "meant" to be packaged as an system-wide installable thing? At least I don't know what to change

and my own build makes many binaries segfault, but that could be a driver bug too

**Comment by SaschaWillems** [comment]
No, there is no systemwide install for Linux.
