### ISSUE TITLE
Assimp linking issue on Mageia 6 (looking for -lassimpd)

### ISSUE THREAD

**Issue by akien-mga** [SaschaWillems/Vulkan#200]
Hi there,

I'm trying to build the current master branch on Mageia 6 x64, using system-installed assimp 3.2.
It fails linking with:
```
[  1%] Linking CXX executable bin/vulkanscene
/usr/bin/cmake -E cmake_link_script CMakeFiles/vulkanscene.dir/link.txt --verbose=1
/bin/c++    -DVK_USE_PLATFORM_XCB_KHR -DNOMINMAX -D_USE_MATH_DEFINES -O3 -DNDEBUG   CMakeFiles/vulkanscene.dir/vulkanscene/vulkanscene.cpp.o CMakeFiles/vulkanscene.dir/base/vulkandebug.cpp.o CMakeFiles/vulkanscene.dir/base/vulkanandroid.cpp.o CMakeFiles/vulkanscene.dir/base/vulkantools.cpp.o CMakeFiles/vulkanscene.dir/base/vulkanexamplebase.cpp.o  -o bin/vulkanscene -rdynamic -lxcb libs/vulkan/libvulkan.so libs/vulkan/libvulkan.so -lassimpd -lpthread -Wl,-rpath,/home/akien/tmp/Vulkan/libs/vulkan 
/bin/ld: cannot find -lassimpd
collect2: error: ld returned 1 exit status
CMakeFiles/vulkanscene.dir/build.make:201: recipe for target 'bin/vulkanscene' failed
```

`-lassimpd` would be the debug version of `libassimp.so`, but such debug versions of libraries are rarely packaged by distro maintainers.

I haven't spotted yet in the buildsystem what triggers the linking of `-lassimpd` instead of `-lassimp`, but I'll keep my eyes open..

**Comment by akien-mga** [comment]
I'll investigate on my end as this looks like it could be a packaging issue in Mageia.

**Comment by akien-mga** [comment]
This does seem to be a packaging issue as the `d` suffix comes from:
```
$ grep "ASSIMP_LIBRARIES" /usr/lib64/cmake/assimp-3.2/assimp-config.cmake
set( ASSIMP_LIBRARIES assimp${ASSIMP_LIBRARY_SUFFIX})
set( ASSIMP_LIBRARIES ${ASSIMP_LIBRARIES}d)
```

**Comment by SaschaWillems** [comment]
Thx for hinting me at this. I'm having the exact same problem on my Ubuntu development machine, so I guess it's time to update to the latest ASSIMP version.

**Comment by akien-mga** [comment]
A quick fix to get your current version working would be `sed -i /usr/lib/cmake/assimp-3.2/assimp-config.cmake -e 's/\${ASSIMP_LIBRARIES}d/\${ASSIMP_LIBRARIES}/'` (escape sequence untested, might need two `\`, and the path to the file on Ubuntu might differ too.
