### ISSUE TITLE
Triangle example misses vkFlushMappedMemoryRanges

### ISSUE THREAD

**Issue by Overv** [SaschaWillems/Vulkan#203]
The triangle example uses `vkMapMemory` to copy vertex data to the memory for the vertex buffer, but it does not ensure that this memory is from a coherent heap. Therefore it should have a call to `vkFlushMappedMemoryRanges` to make sure that the host cache is flushed.

**Comment by SaschaWillems** [comment]
That was an oversight, thx for noticing :+1: . For simplicity the staging buffers should also use the coherent bit like the uniform buffer. Will change after work.
