### ISSUE TITLE
deferredshadows.exe Crash

### ISSUE THREAD

**Issue by andreluizbarbieri** [SaschaWillems/Vulkan#204]
deferredshadows.exe don't run.

**Comment by SaschaWillems** [comment]
As mentioned in the commit, that example is not finished yet. I guess it crashes because I haven't uploaded some of the textures for it.

Once it's finished and ready for public use I'll add it to the readme. Until then, consider it unfinished.

**Comment by andreluizbarbieri** [comment]
No crash more! Thanks. But only dark textures...

**Comment by SaschaWillems** [comment]
Please add some details What does "dark textures" mean? Can you add a screenshot? And what GPU are you running on and what OS?

**Comment by SaschaWillems** [comment]
@andreluizbarbieri: Can you please check again? I've pushed a change that sets the number of layers for the framebuffer to the max. number of layers of it's attachments. On AMD this was ignored, NVIDIA needs this information (if not set, all GS invocations write to the first layer of the FB). I've fixed this and it works fine on my GTX 980.

**Comment by andreluizbarbieri** [comment]
it Works perfectly now. Before there is no color or texture visible but now everything Works.
