### ISSUE TITLE
Found bug on AMD and NVIDIA in  vkCmdDrawIndexed

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#208]
On AMD work and rendering if write  vkCmdDrawIndexed,Cmd_buf,NumTriangles,0,0,0,0 !!!
But on NVIDIA we not see render !
Only vkCmdDrawIndexed,Cmd_buf,NumTriangles,1,0,0,0 !!!

**Comment by SaschaWillems** [comment]
How is this related to my examples?

**Comment by Ronniko** [comment]
I just say.
