### ISSUE TITLE
Latest GLI?

### ISSUE THREAD

**Issue by acterhd** [SaschaWillems/Vulkan#21]
Why in examples no latest GLI? I tried to fix your base for 0.8.0.0 working (or as minimum - compiling).

**Comment by SaschaWillems** [comment]
I will update to the latest GLI and GLM releases once things have settled. Since everything is working fine, there is no immediate need to update.

**Comment by acterhd** [comment]
Can I use vkCmdBindDescriptorSets few times? I know that analogic function have in DirectX 12, and can use same heap with different offsets (i.e. handles).
