### ISSUE TITLE
Computeparticles display nothing only black frame, computeshader(image processing) display left half screen.

### ISSUE THREAD

**Issue by Qjames** [SaschaWillems/Vulkan#210]
As description in the title, computeshader cannot display correct on my Snapdragon820 device.
Are there some features you used are special and not supported by my device? 
Very confused.

**Comment by SaschaWillems** [comment]
Not sure what your device supports, but at least the particle one uses large points, so the device must support the largePoints feature. But even if it doesn't, you should at least see something.

Maybe the Vulkan driver on your device is still in beta. Have you tested other compute shader examples?

**Comment by SaschaWillems** [comment]
@Qjames: I have pushed a commit that fixes the descriptor types (and usage flags) for image reads and writes in the compute shader. At least the compute shader image processing example should not work properly.

On my Intel Ultrabook it didn't display the result (as you mentioned in your description), and these changes fix that.

**Comment by Qjames** [comment]
Thanks, the result of compute can be displayed now.
