### ISSUE TITLE
Compute particles example does not use the computeQueue

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#211]
The compute particles example locates a compute queue, but never uses it and does not free it when it exits.

**Comment by SaschaWillems** [comment]
Thx for pointing this out. Can't believe I didn't notice this :+1:

**Comment by SaschaWillems** [comment]
The example now actually uses the compute queue. Also did lots of refactoring to the code to make it more clear. It's not 100% optimal, as the example class currently still does a queue idle on the graphics queue in the submitFrame function, but that's something I'll fix in the future along with adding async compute stuff.
