### ISSUE TITLE
Incorrect window client area size in windowed mode

### ISSUE THREAD

**Issue by ethan-tqa** [SaschaWillems/Vulkan#212]
The code that adjusts window's client area size on Windows is currently incorrect, so if you expect a 1280x720 render area, what you actually get is a window with swapchain extent of 1272x689. This would affect the window if it is not in fullscreen mode. The reason is that AdjustWindowRectEx not only adjust the right and bottom values, it will also adjust top and left values., The recommended way is to just set top and left as 0, right = desired width, bottom = desired height, call AdjustWindowRectEx and then calculate width as right - left, and height as bottom - top. You can then call MoveWindow to move it to the center of the screen. Like this:

    RECT windowRect;
	if (fullscreen)
	{
		windowRect.left = 0L;
		windowRect.right = (long)screenWidth;
		windowRect.top = 0L;
		windowRect.bottom = (long)screenHeight;
	}
	else
	{
		windowRect.left = 0L;
		windowRect.right = (long)width;
		windowRect.top = 0L;
		windowRect.bottom = (long)height;
	}

	DWORD dwExStyle;
	DWORD dwStyle;

	if (fullscreen)
	{
		dwExStyle = WS_EX_APPWINDOW;
		dwStyle = WS_POPUP | WS_CLIPSIBLINGS | WS_CLIPCHILDREN;
	}
	else
	{
		dwExStyle = WS_EX_APPWINDOW | WS_EX_WINDOWEDGE;
		dwStyle = WS_OVERLAPPEDWINDOW | WS_CLIPSIBLINGS | WS_CLIPCHILDREN;
	}

	AdjustWindowRectEx(&windowRect, dwStyle, FALSE, dwExStyle);

	auto window = CreateWindowEx(0,
		TEXT("wat"), TEXT("wat"),
		dwStyle,
		0, 0, windowRect.right - windowRect.left, windowRect.bottom - windowRect.top,
		nullptr, nullptr, hinstance, nullptr);`

**Comment by SaschaWillems** [comment]
Thx :+1:
