### ISSUE TITLE
New OpenGL 2016 ARB extension

### ISSUE THREAD

**Issue by andreluizbarbieri** [SaschaWillems/Vulkan#213]
@SaschaWillems , Did you know about New OpenGL 2016 ARB extension ? The new driver of nvidia already have this extension. https://developer.nvidia.com/opengl-driver

**Comment by vinjn** [comment]
I think it's GL extensions, not Vulkan extensions.

**Comment by SaschaWillems** [comment]
Yes, with those extensions you can use SPIR-V shaders with OpenGL. This is not related to Vulkan.
