### ISSUE TITLE
[bisected] Incorrect rendering due to commit 2e6e9d5e

### ISSUE THREAD

**Issue by nanley** [SaschaWillems/Vulkan#214]
Commit 2e6e9d5eb28aca15561293304eee298003da5765 , was titled as a refactor. It seemed to do more than a refactor however as many rendering problems (incorrect geometry) arose because of it. 

Removing the comments around aiProcess_PreTransformVertices fixes this. I don't know why however.

**Comment by SaschaWillems** [comment]
I'm aware of this. I accidentally commented out the aiProcess_PreTransformVertices flag for loading the meshes. That's causing the wrong rendering.

Was just about to push a fix :wink:
