### ISSUE TITLE
text overlay doesn't allocate enough memory for tiled texture

### ISSUE THREAD

**Issue by airlied** [SaschaWillems/Vulkan#215]
In base/vulkantextoverlay.hpp:196 or so:

the code creates a texture image, gets the memory requirements for it, then allocates memory. It ignores the returned size from the image creation in favour of its own. However on GPUs which use tiled formats the memory required could be larger.

-               allocInfo.allocationSize = STB_FONT_WIDTH * STB_NUM_CHARS;
+               allocInfo.allocationSize = memReqs.size;

but also later it uses allocationSize, so maybe also something like
-                       allocInfo.allocationSize));
+                       STB_FONT_WIDTH * STB_NUM_CHARS));

**Comment by SaschaWillems** [comment]
Fixed with https://github.com/SaschaWillems/Vulkan/commit/81fc1420534b8f500480449499c74331f00f46b9
