### ISSUE TITLE
Device creation procedure: queue count may exceed the driver limitation

### ISSUE THREAD

**Issue by pbialeck** [SaschaWillems/Vulkan#216]
In the ``vulkandevice.hpp`` there is a fragment:

``queueCreateInfos[0].queueCount++;``

which does not take into account the limitation reported by ``vkGetPhysicalDeviceQueueFamilyProperties`` and if the Vulkan implementation supports only ``queueCount == 1``, then device creation fails.

**Comment by SaschaWillems** [comment]
Thx for noticing. Will take a look at this, as it's clearly wrong and may be
