### ISSUE TITLE
Deferred examples depth buffer issue

### ISSUE THREAD

**Issue by Lipt0nas** [SaschaWillems/Vulkan#217]
This is what happens for me when fragments exeed the camera's far plane:  [Image](http://i.imgur.com/duZhjaW.png).

Same thing happens on both the deferred shading and deferred shadows sample. Im running Windows 8.1 and tested on GTX1080 and GTX760 with the latest Nvidia drivers.

**Comment by SaschaWillems** [comment]
Did you change anything about the far plane? It should be large enough to cover the whole scene. Can you also post a screenshot of the MRT output (toggle with F1).

**Comment by Lipt0nas** [comment]
Yeah, I changed the camera's far plane to 10.0f. [MRT](http://i.imgur.com/lYc5drG.png).

**Comment by Lipt0nas** [comment]
Same thing happens on Linux with a GTX760M ([Normal View](http://i.imgur.com/N3PAl35.png)) ([MRT View](http://i.imgur.com/0ETnLsH.png))

**Comment by Lipt0nas** [comment]
I seem to have found the problem. In `vulkantools.cpp` the initializer for `VkPipelineRasterizationStateCreateInfo` has it's `depthClampEnable` field set to true by default and according to the spec: 

> Depth clamping is enabled or disabled via the depthClampEnable enable of the VkPipelineRasterizationStateCreateInfo structure. If depth clamping is enabled, the plane equation
0≤zc≤wc0≤zc≤wc
(see the clip volume definition above) is ignored by view volume clipping **(effectively, there is no near or far plane clipping)**.

Settting the field to false fixes the problem. That also means that plane clipping does not work in any other examples that use the initializer, not just the deferred ones.

**Comment by SaschaWillems** [comment]
You're right, this shouldn't be enabled by default. Thx for hinting me at this, I'll fix it with one of the next updates :+1:
