### ISSUE TITLE
Support for direct image file output

### ISSUE THREAD

**Issue by Voultapher** [SaschaWillems/Vulkan#223]
I plan to add a feature that would allow directly outputting the swapchain image to an easy file format such as .png

What are some things I should consider before and whilst working on said feature?

The motivation for this feature, came from wanting to enable people to easily create snapshots or videos of their projects.

**Comment by MikiraSora** [comment]
Dose this feature support.the WDCM with win7?maybe I wanna take a snapshot and get other windows together.

**Comment by SaschaWillems** [comment]
For screenshots I'd take a look at [LunarG's screenshot layer example](https://github.com/LunarG/VulkanTools/tree/master/layersvt). Afaik it works even on Android.

Capturing a video of a Vulkan application could be done with a layer too, but at leas the big IHVs (NVIDIA and AMD) both have capture tools that should be able to capture Vulkan applications. The one from NVIDIA for example works fine and I have used that to capture the videos of my Vulkan examples over at youtube.

**Comment by Voultapher** [comment]
Thinking about it a bit more, I agree there is no need for such feature.
