### ISSUE TITLE
Segmentation fault (core dumped) (with WARNING: Ivy Bridge Vulkan support is incomplete)

### ISSUE THREAD

**Issue by 51mon** [SaschaWillems/Vulkan#224]
I try to run this on an Ivy bridge CPU and I get that log : 
WARNING: Ivy Bridge Vulkan support is incomplete
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/gen7_pipeline.c:241: FINISHME: VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
../../../../../src/intel/vulkan/anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
Segmentation fault (core dumped)

Is the seg fault because of lacky support from Intel or something else ?

**Comment by SaschaWillems** [comment]
Can you add some details (OS, driver version, are you using a recent MESA build)? Are all examples crashing with the same error or just a specific one? I do test on an Ivy Bridge device myself and most of the examples ones. Obviously not all features are supported on Ivy Bridge, so the tessellation examples e.g. won't work. But at least the basic ones should work.

**Comment by 51mon** [comment]
Linux is ubuntu 16.04
kernel is 4.4.0-34-generic
OpenGL version string: 3.0 Mesa 11.2.0

All the examples are crashing. Maybe there is something wrong with my mesa install ... I tried to build the last version from source but gave up because of gazillion dependencies.

**Comment by SaschaWillems** [comment]
Pleas try with a current MESA version. [This PPA](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa) should work fine with Ubuntu 16.x and Intel.

If this doesn't help, it's possible that the application is not able to find assets like shaders, which seems to be a problem for a few users. #185 may include some possible solutions.

**Comment by 51mon** [comment]
Thank you it works now. I downloaded the source code (I had only the compiled code) & it is ok when I start the examples from the bin folder.

**Comment by SaschaWillems** [comment]
Yes, the binaries are outdated, I'll update them at a later point.
