### ISSUE TITLE
libvulkan.so linking on linux

### ISSUE THREAD

**Issue by baldurk** [SaschaWillems/Vulkan#225]
When I build on linux, the binaries link against and run with the pre-packaged `libs/libvulkan.so.1`. I'm not sure if this is intentional, or if it's only supposed to be used as a fallback, but it takes priority over any `libvulkan.so` in the system. The behaviour is unlike the import library on windows `libs/libvulkan.lib` which doesn't actually contain code, but just stub functions for the linker and will dynamically link at runtime to whichever `vulkan-1.dll` is installed.

The problem is that the `libvulkan.so` included in the repository is the initial 1.0.3 loader from way back in February. Because of an annoying binary incompatibility that was introduced between 1.0.3 and 1.0.8, any layers written against newer loaders will crash when run against 1.0.3, and there's no way to be backwards compatible.

I can understand that maybe you want to have `libvulkan.so` in the repo to ease compilation for people on distributions without a vulkan loader package, but who still have a recent enough ICD to be able to run vulkan programs. Would it be possible to update the library to a more recent loader version, and maybe also let cmake find system `libvulkan.so` files first before falling back to the one in the repo?

**Comment by SaschaWillems** [comment]
This makes perfect sense. The lib from the repo shouldn't have priority over the one installed in the system. 

Will update the one included soon and see what I can do to make cmake priorize the system one.

**Comment by SaschaWillems** [comment]
Just updated the Linux (x64) library to the latest one from the SDK and also changed the CMakeLists.txt to first look into the $VULKAN_SDK/lib directory and only use the lib from the repo if this isn't present. While this may not be the perfect way I hope this is okay?

**Comment by baldurk** [comment]
Will that search system paths? I don't know much about CMake. Not everyone will have the vulkan SDK installed and have $VULKAN_SDK pointing there - e.g. I don't since I only do testing on linux not primary development.

I'd still say that if there's a system lib in /usr/lib or /usr/lib/x86_64-linux-gnu or somewhere else in ld.so's search path, then I think that should still be used in preference of one included with the samples.

**Comment by SaschaWillems** [comment]
No, it just checks in the SDK directory and if not present falls back to the one from the repository. I'm looking into the system paths variant, not that skilled with CMake either ;)

**Comment by Anteru** [comment]
There's a `FindVulkan` in CMake 3.7 now ;)

**Comment by SaschaWillems** [comment]
Just pushed a commit that uses the ```FindVulkan``` module from @Anteru if the used CMake version is 3.7.0 (or greater). If not it will fall back to the prior behaviour.

@baldurk: Can you check if this works for you? Tested on a fresh Ubuntu VM and the ```FindVulkan``` module selected the vulkan lib installed in the system libraries just fine.

**Comment by Anteru** [comment]
Ha, it works for real :) Thanks for testing!

**Comment by baldurk** [comment]
I can't check because my Ubuntu install doesn't have CMake 3.7 (it only came out yesterday I think), but I believe you that it works there :).

**Comment by SaschaWillems** [comment]
@baldurk Same over here. On Ubuntu (which has only 3.5.1) you need to manually install a newer version :/
