### ISSUE TITLE
WARNING: Haswell Vulkan support is incomplete - Error: No DRI3 support

### ISSUE THREAD

**Issue by BestThingsInLiveFree** [SaschaWillems/Vulkan#226]
I'm compile the examples and try to execute one. But when i am run the file from terminal, it is gave one warning and error:

WARNING: Haswell Vulkan support is incomplete 
Error: No DRI3 support

I'm using Ubuntu 16.04 with Intel Core i5 and Intel Haswell GPU. What is the problem?

**Comment by SaschaWillems** [comment]
> Error: No DRI3 support

In order to use Vulkan on Ubuntu you need to enable DRI3, which is disabled by default. This is not specific to my examples, but a Vulkan driver requirement. 

The [LunarG docs](https://github.com/LunarG/VulkanTools/blob/master/dri3.md) include details on how to enable this for different Ubuntu versions.

**Comment by BestThingsInLiveFree** [comment]
Thanks, i hope this solve my problem.

**Comment by BestThingsInLiveFree** [comment]
When i open the file "/etc/X11/xorg.conf", i see this:

Section "Device"
    Identifier "Default Card 0"
    BusID "PCI:0@0:2:0"
EndSection

What i need to do?

**Comment by SaschaWillems** [comment]
See [this](https://github.com/SaschaWillems/Vulkan/wiki/Quick-start-guide#enable-dri3)

**Comment by BestThingsInLiveFree** [comment]
Hi there, i install the examples with:

mkdir build
cd build
cmake ..
make

after that i try to run an example, but when runtime it gave this error:


particlefire: /home/ipek/Downloads/Vulkan-master/base/vulkantools.cpp:313:
VkShaderModule_T* vkTools::loadShader(const char*, VkDevice,
VkShaderStageFlagBits): Assertion `fp' failed.
Aborted (core dumped)

I know fp is for file pointer, is this about location of executable files?
How i can solve it?

**Comment by BestThingsInLiveFree** [comment]
Sure, there was a new folder, "bin". Executables was in "bin" folder.

**Comment by SaschaWillems** [comment]
The assert is triggered if the executable can't find assets like shaders, meshes or textures. If you run from the bin directory and the data directory is present this should not happen. 

But this seem to depend on how you actually run the executable under linux, maybe you'll find an answer in https://github.com/SaschaWillems/Vulkan/issues/185

**Comment by BestThingsInLiveFree** [comment]
I solve the problem but thanks. I move the executables to bin directory.
Almost of them is running. But program named "tesselation" not works.

**Comment by SaschaWillems** [comment]
Tessellation support is not mandatory. If these examples won't work, your GPU probably doesn't support tessellation on Vulkan.

**Comment by mleise** [comment]
This is the last info I know about the state of tessellation for Intel GPUs:
https://www.phoronix.com/scan.php?page=news_item&px=Intel-Lands-ARB-Tessellation
It looks like a minefield of GPU hangs is slowing down the development for Haswell and earlier, but may become enabled in future driver updates.

**Comment by PDirSG** [comment]
It's great. So can Vulkan have full Intel Haswell support in future?

**Comment by mleise** [comment]
I know as much as you I'm afraid. It seems to me that they are working on it, including tessellation. But you'll have to ask the Mesa devs working on Intel graphics if they hit a road block in the mean time.

**Comment by eero-t** [comment]
Tessellation support went recently into Mesa Vulkan side, and on GL side HSW is now at GL 4.5, so I think it should work now.   I think they went in time to be included to soon-to-come Mesa 17.0 release.

**Comment by weizper** [comment]
wine: created the configuration directory '/root/.wine'
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:err:ole:start_rpcss Failed to open RpcSs service
wine: configuration in L"/root/.wine" has been updated.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.
