### ISSUE TITLE
Question about omnidirectional shadow map sample

### ISSUE THREAD

**Issue by greatelk** [SaschaWillems/Vulkan#228]
Hello,

at updateCubeFace the result of the render is copied to the correct layer of the cubic texture, it works fine but:

Can you render directly to the correct layer? because changing the VkImageSubresourceRange -> baseArrayLayer in the command buffer for each render pass (face of the cubic texture) looks like the way but, for sure i've misunderstood it because it doesn't work and all faces are rendered to the same layer of the cubic texture (debugged on renderdoc)

there is another way to avoid coping from one texture to another?

Thanks

Marc

**Comment by SaschaWillems** [comment]
The easiest way would be to use a geometry shader to direct the output to the correct layer using gl_layer.

See e.g. the [shader for the deferred shadow example](https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/deferredshadows/shadow.geom). The example uses a layered depth map for multiple shadows and uses a geometry shader to select the layer to render too.

This can also be used with cubemap rendering. Adding this option to the cube shadow example is on my list, but I haven't had the time to do so.

**Comment by greatelk** [comment]
wow, thanks for the fast answer

okay then the baseArrayLayer from VkImageSubresourceRange only is used on copy commands? 

also, what can be better, use only gl_layer and doesn't emit vertices or do the transformations to the transformation of the light (in this case) and emit 6 vertices to the 6 layers?

Thanks

**Comment by SaschaWillems** [comment]
> okay then the baseArrayLayer from VkImageSubresourceRange only is used on copy commands?

Changing the target layer should work fine. But you need to create a layered attachment for that to work. 

> also, what can be better, use only gl_layer and doesn't emit vertices or do the transformations to the transformation of the light (in this case) and emit 6 vertices to the 6 layers?

Depends on the HW. GS may be slow on some GPUs and fast on others.

**Comment by greatelk** [comment]
Thanks!

**Comment by ChristophLGDV** [comment]
If this thread is still read, I have the same question.

I want to understand the subpass feature as it appearantly allows an alternative solution of rendering the different cube faces. 
But I am stuck setting the subpass dependencies (or somewhere else). 

At this point I feel the need to thank you for the samples, they are very helpful.

Anyway, I have six attachments and 6 subpasses referencing those.
However I appear to miss the dependencies of which I need 30 or 36. Omitting them causes warnings and cmd faild to submit errors.
But i completely lack the knowledge to solve this.


Can you please explain what I am missing?
https://github.com/ChristophLGDV/Vulkan/tree/master/shadowmappingomniSubpass

Best Regards
