### ISSUE TITLE
Shadow mapping samples copy renderpass

### ISSUE THREAD

**Issue by ChristophLGDV** [SaschaWillems/Vulkan#229]
The renderpass for the offscreen rendering in the shadow samples uses the renderpass instead of the offscreen renderpass.

This becomes troublesome when trying to add multi sampling.

**Comment by SaschaWillems** [comment]
Which example are you talking about? Both the projected shadow mapping and the omni directional shadows example use the offscreen renderpass for their offscreen passes (framebuffer, pipeline and primary CBs).

It's possible that I missed a spot though, so what example and where exactly?

**Comment by ChristophLGDV** [comment]
void updateCubeFace(uint32_t faceIndex)
{
    VkClearValue clearValues[1]; 
    clearValues[0].depthStencil = { 1.0f, 0 };

    VkRenderPassBeginInfo renderPassBeginInfo = vkTools::initializers::renderPassBeginInfo();
    // Reuse render pass from example pass
    renderPassBeginInfo.renderPass = offScreenFrameBuf.renderPass;// renderPass; //!!!  NOOO
    renderPassBeginInfo.framebuffer = offScreenFrameBuf.frameBuffer;
    renderPassBeginInfo.renderArea.extent.width = offScreenFrameBuf.width;
    renderPassBeginInfo.renderArea.extent.height = offScreenFrameBuf.height;
    renderPassBeginInfo.clearValueCount = 1;
    renderPassBeginInfo.pClearValues = clearValues;



That was from the omni shadow sample, it might also be in the regular one.
I may have altered a little bit.

**Comment by SaschaWillems** [comment]
The [current source](https://github.com/SaschaWillems/Vulkan/blob/master/shadowmappingomni/shadowmappingomni.cpp#L390) is already using the offscreen render pass. 

Though the comment is still wrong.

**Comment by ChristophLGDV** [comment]
Ah yes.


What do you mean with “comment is wrong”?

**Comment by SaschaWillems** [comment]
> What do you mean with “comment is wrong”?

I was referring to the comment in the source code that still reads "Reuse render pass from example pass" but that's obviously no longer the case. Gonna remove that.

**Comment by ChristophLGDV** [comment]
Ah, OK thanks for clarifying.
