### ISSUE TITLE
Shadow mapping PCF using sampler2DShadow?

### ISSUE THREAD

**Issue by ChristophLGDV** [SaschaWillems/Vulkan#231]
Does Vulkan support a shadow sampler.

I tried replacing your pcf with the inbuilt version:

layout (binding = 1) uniform sampler2DShadow shadowMap;
float shadow = texture( shadowMap, inShadowCoord / inShadowCoord.w).r ;
But no luck.

**Comment by ChristophLGDV** [comment]
I have to enable comparing of 

sampler.compareEnable = VK_TRUE;
sampler.compareOp = VK_COMPARE_OP_LESS;

**Comment by SaschaWillems** [comment]
Yes, that's what you'd have to do with OpenGL and Vulkan applies the same rules.

**Comment by z11027747** [comment]
thanku，i meet same question
