### ISSUE TITLE
Skybox images in cubemap sample flipped

### ISSUE THREAD

**Issue by msc-** [SaschaWillems/Vulkan#232]
The images of Yokohama Minato-Mirai in the skybox of the cubemap sample are flipped (mirror images) from reality.  Landmark Tower, the tall tower which you can see on the left when looking towards the sculpture that looks like a mini roller-coaster, is really on the right.

I have not yet tried to find the source of the problem.

**Comment by msc-** [comment]
Adding the indicated line to skybox.vert to flip the X coordinate fixes this:
```
void main() 
{
	outUVW = inPos;
+	outUVW.x = -outUVW.x;
	gl_Position = ubo.projection * ubo.model * vec4(inPos.xyz, 1.0);
}
```
It makes sense, I guess, since we're looking from inside the cube.

**Comment by msc-** [comment]
The reflections in the ball are still the wrong way round. A similar trick in reflect.vert had no apparent effect.

**Comment by SaschaWillems** [comment]
I'm using the PVRTexTool from the PowerVR SDK for creating the KTX. It works fine with the files from my repo.

Thx for reporting this, will push a fix it.

**Comment by msc-** [comment]
Thanks for the quick fix. PVRTexTool is one of the tools I tried. It correctly showed the structure of the file but did not display any images only a grey background in the image window. Perhaps this is a problem with the OS X version.

**Comment by msc-** [comment]
I was finally able to view the cubemap images using both PVRTexTool, this time on Windows, and PicoPixel after a bug had been fixed. The images are all flipped from reality. I think the fix in the shaders is wrong; the texture itself should be fixed and the shaders reverted.
