### ISSUE TITLE
Blender import/export of shadowscene_fire.dae with strange line loop

### ISSUE THREAD

**Issue by ChristophLGDV** [SaschaWillems/Vulkan#234]
Importing the mesh in blender shows a line below the stone.

Exporting back to .dae causes a crash of the mesh loader.

**Comment by SaschaWillems** [comment]
I don't think this is related to my examples but rather a bug in the blender collada exporter or importer. The shadow scene was made with a different 3D modelling application and worked in different viewers and applications.

**Comment by ChristophLGDV** [comment]
It exports OK, its the import that does something funny.

I can remove the lineloop in blender.
