### ISSUE TITLE
Window becomes black when resize

### ISSUE THREAD

**Issue by Nikolsi** [SaschaWillems/Vulkan#241]
Hello, I have faced with a problem while testing your examples when I resize a window, it becomes black, then starts drawing after resizing. What to do? Any quick fixes? 

Thanks

**Comment by MonkeyD-IchiJou** [comment]
I have the same issues, but after I change the wndClass.hbrBackground = (HBRUSH)GetStockObject(NULL_BRUSH);, the window wont become black when resize. I believe the real solution shld be using multi-thread to separate window input and rendering (just guessing)

**Comment by Nikolsi** [comment]
Yeah. Because resizing actually stops drawing.

**Comment by SaschaWillems** [comment]
That behavior is intentional and is the same as on Linux. Resizing requires several resources to be regenerated (like the swapchain), and this is now only done when the resized operation has finished.
