### ISSUE TITLE
Incorrect usage of pResolveAttachments

### ISSUE THREAD

**Issue by PistonMiner** [SaschaWillems/Vulkan#245]
In the multisampling example right [here](https://github.com/SaschaWillems/Vulkan/blob/master/multisampling/multisampling.cpp#L293), it uses differing a size for pResolveAttachments that differs from colorAttachmentCount (with resolveReferences being an std::array of size 2). This is covered in the Vulkan specification under VkSubpassDescription in the [renderpass section](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#renderpass-creation).

> pResolveAttachments is NULL or an array of colorAttachmentCount VkAttachmentReference structures [...]

**Comment by SaschaWillems** [comment]
This has already been mentioned in #197

**Comment by PistonMiner** [comment]
Closing as pointed out.
