### ISSUE TITLE
Multisampling texture loading issue.

### ISSUE THREAD

**Issue by Qjames** [SaschaWillems/Vulkan#247]
I found that you use VK_FORMAT_BC3_UNORM_BLOCK format when loading textures, and create Image&ImageView, but I think you may need to query the ImageFormatProperties before use it.
On my Qualcomm device with Adreno530 GPU, it doesn't support BC formats. I can only get black images as attached.
Can you check if I am right? Thanks.
![rendered](https://cloud.githubusercontent.com/assets/2987952/20050829/77d24cb2-a506-11e6-9d8c-53edbd9e74e0.png)

**Comment by Qjames** [comment]
Same issue as particlefire & sceneRendering.

**Comment by SaschaWillems** [comment]
Yes, that's correct and I'm aware of this. See https://github.com/SaschaWillems/Vulkan/issues/174

The only solutions would be to either only use uncompressed textures (bad for file size) or duplicate all textures to be available in different formats. Though that would result in having all compressed textures in BC, PVRC and ASTC format.

I'm not yet sure what to exactly do about this.

**Comment by Qjames** [comment]
Hi Willems,

For ParticleFire, what format should I use for particle_fire & particle_smoke, I use RGBA8888, it doesn't work. For this multisampling example, I convert the texture to rgba8888, it can work.
What format should I convert to, so that it can work on my device?
Thanks.

**Comment by SaschaWillems** [comment]
You need to check what format your device actually supports. [This report](http://vulkan.gpuinfo.org/displayreport.php?id=805#formats) e.g. is for an Adreno 530. Pick a format that is supported and convert the textures to it. At least judging from that report the GPU should support ETC and ASTC.

> For ParticleFire, what format should I use for particle_fire & particle_smoke, I use RGBA8888, it doesn't work. 
Can you specify tha "doesn't work" part? Does it crash? Or just won't display the texture?

**Comment by Qjames** [comment]
I cannot saw the fire & smoke. I've changed the code like below.
`	void loadTextures()`
`	{`
`		// Particles`
`		textureLoader->loadTexture(`
`			getAssetPath() + "textures/particle_smoke-rgba8888.ktx",`
`			VK_FORMAT_R8G8B8A8_UNORM,`
		`	&textures.particles.smoke);`
	`	textureLoader->loadTexture(`
			`getAssetPath() + "textures/particle_fire-rgba8888.ktx",`
			`VK_FORMAT_R8G8B8A8_UNORM,`
			`&textures.particles.fire);
`
![screenshot_19700115-021005](https://cloud.githubusercontent.com/assets/2987952/20058299/3869b55e-a52b-11e6-99ed-6a08f0345bb5.png)

**Comment by SaschaWillems** [comment]
Try disabling blending and see if it changes anything. Depending on how you created thos textures the blend mode used by the example may not be working for you.

**Comment by Qjames** [comment]
After disable the blend of particle pipeline, the fire truns out to be small black tiles.
Looks like need change the blend mode?

![screenshot_19700115-025557](https://cloud.githubusercontent.com/assets/2987952/20059549/bdc38e7c-a531-11e6-863a-d721c74cb918.png)

**Comment by SaschaWillems** [comment]
This looks like a driver problem I've encountered on Intel graphics before where the driver did not generate texture coordinates for point sprites. Try changing the shader for the point sprites to display the uv-coordinates and if that's still black, this may be a driver related problem.

**Comment by Qjames** [comment]
I modified the texture coordinates with fixed value, with blend enable. Then the flame can come out.

**Comment by Qjames** [comment]
Thanks, this was vendor's issue, close it now.
