### ISSUE TITLE
SkeletalAnimation not working..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/Vulkan#25]
I know this isn't included in CMakeLists but I compiled and the sample crashes on Nvidia Linux driver..
all other samples work correctly..

**Comment by SaschaWillems** [comment]
It actually should be in the CMakeLists, I just forgot to add it. I'll also check why this crashes on Linux. I actually had it running there once, so maybe I broke something at some point.

Thanks for noticing!

**Comment by wobakj** [comment]
The Segmentation Fault happens at line 466 in skeletalanimation.cpp because "mAnimations" does not contain any animations. It seems like the astroboy.dae file does not include animations. The example works fine when loading a Collada file with animations included.

**Comment by SaschaWillems** [comment]
The example does contain animations, and it's working fine over here. This may be related to the ASSIMP version.

**Comment by SaschaWillems** [comment]
Just tested on Linux and this runs fine, even with the LunarG Intel ICD. Can you try again from current source?

**Comment by wobakj** [comment]
I pulled and built the repository and it still crashes for the same reason. Apparently both "assimp 3.0~dfsg-2" and blender2.76 cannot read animations from this Collada file. (That is why I concluded the the file does not contain any) Maybe

**Comment by RicardasSim** [comment]
The same here, on Debian Jessie

Program received signal SIGSEGV, Segmentation fault.

at skeletalanimation.cpp:466
466 float TicksPerSecond = (float)(mesh.meshLoader->pScene->mAnimations[0]->mTicksPerSecond != 0 ? mesh.meshLoader->pScene->mAnimations[0]->mTicksPerSecond : 25.0f);

becouse mAnimations is zero

Then builded with Assimp-3.2 library, works as expected.
No segfault anymore.

**Comment by SaschaWillems** [comment]
I have added a paragraph about building on Linux that hints at assimp and that version 3.2 is required.
