### ISSUE TITLE
'computeparticles' has non-deterministic results

### ISSUE THREAD

**Issue by kspagnoli-nv** [SaschaWillems/Vulkan#251]
Hi Sascha, 

I found a subtle bug in the 'computeparticles' example. The compute shader is actually doing 16x the work it needs to which results in multiple work items writing to the same memory location. This results in non-deterministic results. 

In the current implementation, you are dispatching with a global size of 16348x1x1 and a local size of 16x16x1. This results in an overall grid of 261568x16x1 where the x-size matches the number of particles (good!) but the work is done 16x for each particles (trouble!).

This can easily be fixed by changing the local_size_y in the compute shader from...

```glsl
layout (local_size_x = 16, local_size_y = 16) in;
```

To...

```glsl
layout (local_size_x = 16, local_size_y = 1) in;
```

Though, I'd recommend changing to...

```glsl
layout (local_size_x = 256, local_size_y = 1) in;
```

And updating the global dispatch size for better performance.

For what it's worth, I noticed this while debugging with NVIDIA Nsight and seeing inconsistent post-dispatch buffer data.

Thanks for the great samples!

**Comment by SaschaWillems** [comment]
You're right, the current work group and dispatch size doesn't make sense. Thx for the detailed explanation, will push a fix for this later 👍
