### ISSUE TITLE
Validation Error: Mismatched format between renderPass and framebuffer attachments

### ISSUE THREAD

**Issue by nanley** [SaschaWillems/Vulkan#254]
When running the any demo with the validation layers, I get the following error for each swapchain image (three in total):
 
> DS(ERROR): object: 0x11 type: 18 location: 9652 msgCode: 50: vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #0 has format of VK_FORMAT_B8G8R8A8_SRGB that does not match the format of VK_FORMAT_B8G8R8A8_UNORM used by the corresponding attachment for renderPass (0x11).

**Comment by SaschaWillems** [comment]
Thx for pointing this out. I'll take a look at it.

**Comment by Ekzuzy** [comment]
Fix for this issue is provided in the #238 pull request.

**Comment by sg-brcm** [comment]
I was about to open an issue with almost the same change for the color formats, until I saw this issue. It really doesn't make sense for the renderpass color attachment format and multisample target format to not match the framebuffer image view format. It would be helpful if at least that part of Ekzuzy's change got committed even if there is still some question over the layout transitions.

**Comment by SaschaWillems** [comment]
I just pushed a fix for this that always uses the swapchain's color format instead of the fixed one specified in the example base. Can you check if this works for you now without validation errors?

**Comment by nanley** [comment]
This error is no longer reported by the validation layers. Thanks!
