### ISSUE TITLE
Computecullandlod: Command buffer submitted to the graphics queue is not synchronized with the compute task which causes GPU lock-ups

### ISSUE THREAD

**Issue by DominikWitczakAMD** [SaschaWillems/Vulkan#257]
The application works by first submitting a command buffer to a queue with graphics capabilities, in which it schedules indirect draw call execution. There's quite a bunch of the draw calls in there (~256k), so they can take a little while to execute.

Then, without any kind of synchronization, it submit another command buffer, this time to a compute queue, where the scheduled dispatch call overrides the indirect draw call arguments, stored in a storage buffer.

This breaks as soon as the compute and graphics queues are physical separate entities, capable of running in parallel, eg. on GCN. What we're seeing on our hardware is random lock-ups of the application in question, due to the fact the application does not make any attempt to synchronize command buffers' execution.

The issue can be fixed by having the vkQueueSubmit() calls use semaphores, or - even simpler, but significantly slower - by making the app wait on a fence, set separately by the first, and then the second vkQueueSubmit() call (with a reset in-between, of course).

**Comment by SaschaWillems** [comment]
Thx for pointing this out. I haven't had time to check this example on GCN hardware yet, but will try to do so this weekend and add proper synchronization.

**Comment by SaschaWillems** [comment]
I was able to reproduce the lock-ups on a R390 and pushed a fix for this using a new semaphore that is signaled by the compute submission and used as an (additional) wait for the graphics submission:

		computeSubmitInfo.signalSemaphoreCount = 1;
		computeSubmitInfo.pSignalSemaphores = &compute.semaphore;

		VK_CHECK_RESULT(vkQueueSubmit(compute.queue, 1, &computeSubmitInfo, VK_NULL_HANDLE));
		
		// Submit graphics command buffer

		std::vector<VkPipelineStageFlags> stageFlags = {
			VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
			VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
		};
		std::vector<VkSemaphore> waitSemaphores = {
			semaphores.presentComplete,						
			compute.semaphore								
		};

		submitInfo.pWaitSemaphores = waitSemaphores.data();
		submitInfo.waitSemaphoreCount = static_cast<uint32_t>(waitSemaphores.size());
		submitInfo.pWaitDstStageMask = stageFlags.data();
		
		...

The example now runs fine here without looking up, so I think this should do the job.
