### ISSUE TITLE
ParticleFire vertex shader issue.

### ISSUE THREAD

**Issue by Qjames** [SaschaWillems/Vulkan#259]
vertex shader: /data/shaders/particlefire/particle.vert
I saw gl_PointSize has been assigned two different values, is it an error or the last gl_PointSize take effects?
`	gl_PointSize = outPointSize;
		
	gl_Position = ubo.projection * ubo.modelview * vec4(inPos.xyz, 1.0);	
	
	float pointDist = (gl_Position.w == 0.0) ? 0.00001 : gl_Position.w;
	float viewportAR = ubo.viewportDim.x / ubo.viewportDim.y;
	
	gl_PointSize = (((inSize * 2048.0 * viewportAR) / pointDist) * viewportAR);	`

**Comment by SaschaWillems** [comment]
Last value set is the one that counts. The other ones are left-overs. I'll update the shaders and remove the unnecessary assignments to the point size.
