### ISSUE TITLE
Namespace cleanup

### ISSUE THREAD

**Issue by Delwin9999** [SaschaWillems/Vulkan#260]
There's name collisions if you're using the c++ bindings.  Is there a strong reason to use namespace vk?

**Comment by SaschaWillems** [comment]
No strong reason. Itt just predates the vkcpp bindings and I don't have plans to change my examples to use vkcpp.

**Comment by Delwin9999** [comment]
Given that the vkcpp bindings are now part of the core Vulkan (as vulkan.hpp) I'd think it would be good practice to get out of the way via a namespace other than 'vk'.  You've already got a few other namespaces in there  (vkTools etc).  I can't do pull requests from where I am but I could try to put together a cleanup from another location that I can do pull requests from.

Would you be interested in a namespace cleanup pass?  I'd also like to put VulkanExampleBase in the namespace since it's currently in the global namespace.

**Comment by SaschaWillems** [comment]
> Would you be interested in a namespace cleanup pass? I'd also like to put VulkanExampleBase in the namespace since it's currently in the global namespace.

Cleaning up the namespaces for my examples is on my todo list and something I'll take a look at soon, so no need for a PR. I'll also account for the vkcpp headers.

**Comment by Delwin9999** [comment]
Thank you!

**Comment by SaschaWillems** [comment]
Finally got around reworking and unifying the whole namespace thing. The main namespace used by the examples is now ```vks``` with nested namespaces where appropriate and will now longer collide with the namespace from the c++ bindings.
