### ISSUE TITLE
the gli  

### ISSUE THREAD

**Issue by git6721** [SaschaWillems/Vulkan#267]
i want to know why the gli in your project is different from (https://github.com/g-truc/gli),

because it would throw some errors and the codes are very very diff to yours

**Comment by SaschaWillems** [comment]
My examples use an old version of gli. Due to changes in recent gli versions the examples won't compile out of the box with newer versions.

Updating to a recent gli version is on my todo list, but no ETA on that yet.

**Comment by git6721** [comment]
thanks!!!
