### ISSUE TITLE
Options for window size

### ISSUE THREAD

**Issue by eero-t** [SaschaWillems/Vulkan#270]
It's nice that the demos support interactive window resizing.

Would be possible also to support specifying the initial window sizes from command line instead of them being hard-coded separately in each of the demos?

PS. Another alternative than command line option for specifying the window size, fullscreen and perf options (that I listed in earlier feature requests), would be configuration file, but I think then demos should take config file name as optional argument.

**Comment by SaschaWillems** [comment]
I don't think I'll go as far as adding configuration support for the examples, but adding command line options do override hard coded window sizes is something that should be easy to implement.

**Comment by eero-t** [comment]
Thanks!  Works great with everything else than triangle (which doesn't parse options yet).

It could be a bit more robust:
$ ./bloom -w
(segmentation fault)

Error message and usage help output when options aren't understood would also be nice.  Should I file separate issue about that?
