### ISSUE TITLE
Surface Format Selection Bug?

### ISSUE THREAD

**Issue by Ziflin** [SaschaWillems/Vulkan#271]
In vulkanswapchain.hpp there's a few lines that do the following:
```c++
// If the surface format list only includes one entry with VK_FORMAT_UNDEFINED,
// there is no preferered format, so we assume VK_FORMAT_B8G8R8A8_UNORM
if ((formatCount == 1) && (surfaceFormats[0].format == VK_FORMAT_UNDEFINED))
{
	colorFormat = VK_FORMAT_B8G8R8A8_UNORM;
}
```
I'm wondering where this logic comes from as I can find no source. I can say that my nVidia 1060 is reporting the following:
```
Avaliable Surface Formats: 2
    0: [Format=Undefined, ColorSpace=SrgbNonlinear]
    1: [Format=Undefined, ColorSpace=SrgbNonlinear]
```
I have no idea why it's reporting two identical surface formats, but because it is, the above if statement fails (there's more than 1 format) and the _colorFormat_ value will be assigned 'Undefined'. I'm not sure if that is 'ok' when it is used later or not.

**Comment by SaschaWillems** [comment]
Can you upload a report for your device (if you haven't done at http://vulkan.gpuinfo.org)? It contains surface format information so I can check this out.

Taking a look at other GTX 1060 devices (e.g. http://vulkan.gpuinfo.org/displayreport.php?id=1019#surfaceformats) they report multiple surface formats too (like most devices), but all have proper formats.

The logic comes from the early days of Vulkan (before it even went public), and it may have to rework it in parts.

**Comment by Ziflin** [comment]
Thanks for the help. Sorry I should have mentioned that this is my own codebase, so I'm pretty sure it's something I'm doing wrong that is generating the 2 Undefined formats. I ran the GPUInfo tool and it's clearly showing 2 valid 'format' values. Here's the report: http://vulkan.gpuinfo.org/displayreport.php?id=1061

So instead of 2 Undefineds I should be getting:
```
0	B8G8R8A8_UNORM	SRGB_NONLINEAR_KHR
1	B8G8R8A8_SRGB	SRGB_NONLINEAR_KHR
```
I can't see what I have wrong yet in my code, but it's odd that I get the color-space correct and not the format, so it must be something silly. 

At any rate, thanks for mentioning the GPUInfo / Vulkan Caps Viewer as they're both very handy.

**Comment by Ziflin** [comment]
And yes, it was something simple. I copy/pasted the first call to vkGetPhysicalDeviceSurfaceFormatsKHR and forgot the pass in the array for it to fill in. I guess it's legal to pass in a non-zero 'count' but a null array?  I didn't see a debug report log for it.

**Comment by SaschaWillems** [comment]
No, you don't have to pass in the pointer to a surface-formats array. If it's null the function will only update the surface format count parameter. So even if you pass in a format count greater zero, passing a nullptr for the array is not a violation of the specs.

**Comment by Ziflin** [comment]
Yup. I just meant that if the spec had required _count=0_ if you pass in a _null_ array then there could have been a warning to catch the copy/paste mistake where the second call would have been _count=2_ and the array was still (accidentally) passed in as _null_.

Thanks for the help though. Should I close this or did you want it open as a reminder to check on that if statement?

**Comment by SaschaWillems** [comment]
The if-statement that selects VK_FORMAT_B8G8R8A8_UNORM if there is only one undefined format is still present in the current SDK demos, so I guess it still has it's uses so I'll leave it in there for now.
