### ISSUE TITLE
Memory flush size incorrect in dynamicuniformbuffer example

### ISSUE THREAD

**Issue by gary-sweet** [SaschaWillems/Vulkan#272]
In `updateDynamicUniformBuffer()` the list of model matrices is updated locally and then memcpy'd into `uniformBuffers.dynamic.mapped` (line 505).

The intention is then to flush that changed memory range, but the size of the range is incorrect. The size used is `sizeof(uboDataDynamic)`, which just contains a pointer, so is either 4 or 8 bytes. The correct size would be `uniformBuffers.dynamic.size`, which is the amount of data that was memcpy'd.

So, line 509 should become:
`memoryRange.size = uniformBuffers.dynamic.size;`

**Comment by SaschaWillems** [comment]
Thx for noticing 👍
