### ISSUE TITLE
Missing coherent memory flags/flushing

### ISSUE THREAD

**Issue by sg-brcm** [SaschaWillems/Vulkan#273]
Although the recent createBuffer changes cleaned up some missing coherent memory flags, it appears not all were caught. The attached patch shows where I think some additional changes are needed, although you may wish to do something different. At least one of the texture uploads resulted in visibly corrupt results on the embedded platform I am working on, where you do not get coherent memory unless you explicitly ask for it.

[Fix-memory-coherency-issues-after-CPU-writes.txt](https://github.com/SaschaWillems/Vulkan/files/727049/Fix-memory-coherency-issues-after-CPU-writes.txt)

**Comment by SaschaWillems** [comment]
Thx for the patch file 👍 Will take a look at it as soon as possible.
