### ISSUE TITLE
Any sample "Has stopped working"

### ISSUE THREAD

**Issue by Mikez2015** [SaschaWillems/Vulkan#274]
Tryed Windows 7 and 10 x64
Visual Studio 14 2015 
Cmake 3.7.2
VulkanSDK-1.0.39.0

Screen error with debug mode attached:
![error](https://cloud.githubusercontent.com/assets/10583925/22317831/d82b26fc-e3a8-11e6-9c26-24233aa99a56.png)

**Comment by SaschaWillems** [comment]
Is this with unmodified current code? Please also add some additional details, especially the call stack. Judging by that line it seems that the example is not able to load the shaders (loadSPIRVShader function in triangle.cpp), and the shaderCode variable is not initialized with nullptr (will do that later). So the problem may be missing assets or the assets being in the wrong path relative to the binaries.

**Comment by Mikez2015** [comment]
Yes, unmodified fresh current code, downloaded today. Call stack:
![error1](https://cloud.githubusercontent.com/assets/10583925/22324359/60e983a8-e3db-11e6-8463-f0a3710914b9.png)

**Comment by SaschaWillems** [comment]
Can you step through the code and check if the examples are able to load the assets?

**Comment by Mikez2015** [comment]
I modify code function loadSPIRVShader:

```
if (is.is_open())
		{
			shaderSize = is.tellg();
			is.seekg(0, std::ios::beg);
			// Copy file contents into a buffer
			shaderCode = new char[shaderSize];
			is.read(shaderCode, shaderSize);
			is.close();
			assert(shaderSize > 0);
			**MessageBox(NULL, "File opened", "Ok", MB_OK);**
		} **else MessageBox(NULL, "File NOT Opened", "Ok", MB_OK);**
```

and got "File NOT Opened".
It's very strange. triangle.vert.spv and triangle.frag.spv placed in "data/shaders/" and "All" have permisions for all folders.

**Comment by SaschaWillems** [comment]
Where are the binaries located and from what's their working directory when running from Visual Studio?

**Comment by Mikez2015** [comment]
I can't run from VS - got error "access denied"
I copy shaders folder to bin folder and modify loadSPIRVShader params:
`loadSPIRVShader("shaders/triangle.frag.spv");`
May be and sample work correct. 
Problem with "getAssetPath()"? Or with my VS (but I tryed original code with two different machines, with Windows 7 and Windows 10).

**Comment by Mikez2015** [comment]
Binary files lacated "bin/release/"

**Comment by SaschaWillems** [comment]
getAssetPath refers to "../data/" and expects the binaries in the "bin" folder. So either output binaries to bin or adjust getAssetPath relative to your binary path.

**Comment by Mikez2015** [comment]
May be checking errors opening assets files need too.
Thx for help.
