### ISSUE TITLE
Offscreen demo appears to have reversed reflection

### ISSUE THREAD

**Issue by gary-sweet** [SaschaWillems/Vulkan#279]
When the lit side of the dragon is visible, the reflection is very dark.
When the dark side of the dragon is visible, the reflection is very bright.

![image](https://cloud.githubusercontent.com/assets/20819159/22587511/d64753fe-e9f9-11e6-81bf-cbf0244ee83c.png)

![image](https://cloud.githubusercontent.com/assets/20819159/22587537/f1983a38-e9f9-11e6-881a-77d982e6993d.png)

**Comment by SaschaWillems** [comment]
Thx for pointing this out. Looks like I forgot (or accidentally removed) the line to switch cull mode (only a comment is there, but no code).
