### ISSUE TITLE
Compute Shader Example Hotkeys

### ISSUE THREAD

**Issue by eduardobraun** [SaschaWillems/Vulkan#280]
Not a real issue, but the hotkeys selected for the Compute Shader example (num+ and num-) are not multi-layout friendly. There are a lot of people out there using tenkeyless or 60% keyboards that don't have easy access to numpad keys.

So, given there are various multi-layout compatible keys, I suggest changing the hotkeys to common keys like:

- j,k
- [,]

or, adding extra support for the non-numpad + and -.

**Comment by SaschaWillems** [comment]
That's a good point. I actually test on a Linux notebook that has no numpad too. Though I'd also like to add some graphical UI at some point in the future where values like these would be mapped to a slider that can be used with touch/mouse. But until then I guess it's best to just add hotkeys you mentioned as an alternative to the numpad keys.

**Comment by FireBurn** [comment]
Alternatively if you could make it work with regular "+" and "-" that'd be great

**Comment by SaschaWillems** [comment]
As I'm currently adding touch support for mobile devices (thanks to one IHV lending me two mobile devices that support Vulkan 😄) I'm currently thinking about a different approach for options that doesn't rely on keyboard input and would use a more UI like approach that is easier to control with mouse and touch and would also support gamepads.

**Comment by sjfricke** [comment]
@FireBurn 

I have the 80% Keyboard problem as well and I just went and mass replaced the `KEY_KPADD` and `KEY_KPSUB` to values not used in the [keycodes.hpp](https://github.com/SaschaWillems/Vulkan/blob/master/base/keycodes.hpp)

If you are running Linux and have Perl built in (`sed` command ) you can run this quick in the head repo folder

* `grep -rl "case KEY_KPSUB" ./ | xargs sed -i 's/case KEY_KPSUB/case 0x34/g'`
* `grep -rl "case KEY_KPADD" ./ | xargs sed -i 's/case KEY_KPSUB/case 0x35/g'`
* `make`

and it will turn
`-` -> `Z` -> (0x34 Linux) -> (0x58 Windows)
`+` -> `X` -> (0x35 Linux) -> (0x5A Windows)

for all the demos that uses `+/-`
(**Note**: I used X and Z as they are not used in the demos currently)
(**Note 2**: if you are using Windows then swap `0x34` -> `0x58` and `0x35` -> `0x5A` from the two commands as window uses ASCII for key shortcuts)

**Comment by SaschaWillems** [comment]
Just changing the keys is tricky due to different keyboard layouts. Just compare a german layout with an US one ;)

So instead of trying to fix this isolated issue by replacing keycodes I'll replace the text overlay (and manual key handling) with a proper UI using ImGui. This will fix all keyboard layout issues and also allows setting changes on mobile devices with touch screens ;)

**Comment by SaschaWillems** [comment]
I have just merged the new ImGui based UI overlay into master, so no more keycodes and full support for touch devices (windows and android). 

For e.g. the compute example you get a combo box instead:
![image](https://user-images.githubusercontent.com/10283127/32407154-233db744-c185-11e7-9ae7-3feae11ca66c.png)

Using a proper UI also allows me to expose other options and functionality that would not fit due do limited number of available keys and different language layouts :)
