### ISSUE TITLE
Crash in sparse resources example

### ISSUE THREAD

**Issue by phoerious** [SaschaWillems/Vulkan#281]
I wanted to try out the sparse resources example (texturesparseresidency), but it keeps crashing for me in line 868 where the pipeline is created (vkCreateGraphicsPipelines()).
I tried linking against a newer libvulkan.so and also enabled validations layers, but it still crashes without giving a clue why.

This is how far it gets:
```
Sparse image format properties: 1
	 Image granularity: w = 128 h = 128 d = 1
	 Aspect mask: 1
	 Flags: 0
Image memory requirements:
	 Size: 357,957,632
	 Alignment: 65,536
Sparse image memory requirements: 1
	 Image granularity: w = 128 h = 128 d = 1
	 Mip tail first LOD: 7
	 Mip tail size: 65,536
	 Mip tail offset: 357,892,096
	 Mip tail stride: 357,915,648
Texture info:
	Dim: 8,192 x 8,192
	Virtual pages: 5,461
Image blits took 20.147 ms
Signal: SIGSEGV (Segmentation fault)
```
The generated stack trace is completely useless.

Graphics card: Nvidia GTX 960
Graphics card driver: 375.26
Operating system: Arch Linux

**Comment by SaschaWillems** [comment]
Is this on a public driver? I've had crashes at pipeline creation time using sparse function in the shaders but with non-publich drivers. Can you test if it still crashes with the lastes Vulkan drivers from https://developer.nvidia.com/vulkan-driver?

As a sidenote that demo is still considered a work-in-progress, esp. aas NVIDIA is the only IHV to currently support sparse on Vulkan.

**Comment by phoerious** [comment]
It's the official binary Nvidia driver, version 375.26. 375.27.10 is the very latest, but it looks like they only added some new Vulkan extensions between those two versions.

**Comment by phoerious** [comment]
It appears that the sample works again with the 378.x series of the Nvidia driver.

**Comment by SaschaWillems** [comment]
Thx for the feedback. The sparse example is still considered as work-in-progress and it may still crash if you fill the mip layers and reach the max. memory allocation limit of a device.
