### ISSUE TITLE
Update glm to fix Build error:  error: wrong number of template arguments

### ISSUE THREAD

**Issue by slacka** [SaschaWillems/Vulkan#283]
With gcc 6.3.1, I'm getting:

`func_common.inl:193:51: error: wrong number of template arguments (5, should be 6) struct compute_sign<T, P, vecType, false, Aligned>`

Seems to be fixed by https://github.com/g-truc/glm/issues/605 when I overwrite `external/glm` with the upstream master.

**Comment by SaschaWillems** [comment]
What compiler are you using? I'm using CI to test on multiple compilers (MSVC, gcc, clang) and all compile fine. 

I recently updated to the most recent version of glm, but I'll check if the mentioned fix was applied later and update again if necessary.

**Comment by slacka** [comment]
I needed to update glm for both Arch i686 and Ubuntu 16.04 i686, but it looks like you only support AMD64.

AMD64 does not require this, so I'll close this for now. Please reopen if I am mistaken.
