### ISSUE TITLE
Memory leakage for this Vulkan App.

### ISSUE THREAD

**Issue by Qjames** [SaschaWillems/Vulkan#286]
Hi Willems,

I found there could be memory leak in android device.
When the app lose focus, like hidden or closed, it only clean up the swapchain resources. If the app is get focused again, I saw it will do init again. After several times, the memory will be exhausted.
```
`	case APP_CMD_INIT_WINDOW:
		LOGD("APP_CMD_INIT_WINDOW");
		if (androidApp->window != NULL)
		{
			vulkanExample->initVulkan();
			vulkanExample->initSwapchain();
			vulkanExample->prepare();
			assert(vulkanExample->prepared);
		}`
```

**Comment by SaschaWillems** [comment]
Thx for the info. I'll be doing some additional work on the Android part of the examples soon and will then also take a look at this.
