### ISSUE TITLE
Screenshot sample doesn't work

### ISSUE THREAD

**Issue by EddieGong** [SaschaWillems/Vulkan#288]
Hello Willems,

I tested your sample of the screenshot and found the result is not correct. (I use GIMP)

**Comment by SaschaWillems** [comment]
Please add some details:
- GPU/Driver/Platform
- Validation layer errors (if you get some)
- The image generated by the example

The example blits from optimal to linear, so it requires some image feature flags (see https://github.com/SaschaWillems/Vulkan/blob/master/screenshot/screenshot.cpp#L349) that may not be available on all platforms.

**Comment by EddieGong** [comment]
Hello Willem,


GPU: Nvidia GTX 960.

Driver: 378.66

Platform: Window 10 Pro

VulkanSDK: 1.0.39.1


The properties are supported, but there are some warning like you said.

"

WARNING: [DS] Code 10 : Source AccessMask 2048 [VK_ACCESS_TRANSFER_READ_BIT] must have required access bit 32768 [VK_ACCESS_MEMORY_READ_BIT]  when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, unless the app has previously added a barrier for this transition.
WARNING: [DS] Code 10 : Dest AccessMask 0 [None] must have required access bit 32768 [VK_ACCESS_MEMORY_READ_BIT]  when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, unless the app has previously added a barrier for this transition.

"


If I try to add "VK_ACCESS_MEMORY_READ_BIT", it will get some new warning.

"

WARNING: [DS] Code 10 : Additional bits in Source accessMask 0x8800 [VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_MEMORY_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.

"

In both cases, the results are same, but sometimes it's totally black instead of random pixels.

Please take a look. Thanks.

Sincerely,
Eddie.


________________________________

**Comment by Delwin9999** [comment]
I've got the same problem.
GPU: NVidia GTX 980 Ti
Driver: 375.27.08
OS: CentOS 6 (Linux)
Vulkan SDK: 1.0.39
echo $VK_INSTANCE_LAYERS 
VK_LAYER_GOOGLE_threading:VK_LAYER_LUNARG_parameter_validation:VK_LAYER_LUNARG_object_tracker:VK_LAYER_LUNARG_image:VK_LAYER_LUNARG_core_validation:VK_LAYER_LUNARG_swapchain:VK_LAYER_GOOGLE_unique_objects

The feature is supported.

No warnings or errors reported by layers.

The resulting image is blank (all black).

**Comment by Delwin9999** [comment]
Just tried it on a seperate CentOS6 box with twin 1070's and driver 375.39

Same issue: no layer warnings or errors and a blank screenshot.

**Comment by Delwin9999** [comment]
I think I found it.  

        // Check if the device supports blitting to linear images
        if (!(formatProps.linearTilingFeatures & VK_FORMAT_FEATURE_BLIT_SRC_BIT)) {
            std::cerr << "Error: Device does not support blitting to linear tiled images!" << std::endl;
            return;
        }

Shouldn't this be VK_FORMAT_FEATURE_BLIT_DST_BIT?  Likewise the optimal check is checking for destination instead of source.  If I swap those I get the error that the device does not support blitting to linear tiled images, which seems to be the case.

That said how do we get data out of the framebuffer then?  Can we do a vkCopyImage?

**Comment by eero-t** [comment]
You could VulkanTools screenshot layer.  It works also with vktrace.

**Comment by SaschaWillems** [comment]
Yes, looks like I made a mistake there. Will fix this.

> That said how do we get data out of the framebuffer then? Can we do a vkCopyImage?

Yes, either that or vkCmdCopyImageToBuffer.

I may change the example to use vkCmdCopyImageToBuffer at some point if I can manage to get a bit more time.

**Comment by Delwin9999** [comment]
Got it working.  Unfortunately I can't do pull requests from here but if you replace between the two setImageLayout calls with this it works for me:

       // Define the region to copy (we will copy the whole swapchain image)
        VkImageCopy imageCopyRegion{};
        imageCopyRegion.srcSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        imageCopyRegion.srcSubresource.layerCount = 1;
        imageCopyRegion.dstSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        imageCopyRegion.dstSubresource.layerCount = 1;
        imageCopyRegion.extent.width = width;
        imageCopyRegion.extent.height = height;
        imageCopyRegion.extent.depth = 1;

        // Issue the blit command
        vkCmdCopyImage(
            copyCmd,
            srcImage, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            dstImage, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            1,
            &imageCopyRegion
            );

**Comment by SaschaWillems** [comment]
Thx, will check before changing. I've tested on three different platforms (and four GPUs) and it worked fine on all. I preferred the blit method because it allows for resize. If the basic copy runs on more platforms I may switch over to that and also scrap the blit feature checks.

**Comment by SaschaWillems** [comment]
I have a setup where I can reproduce this. I'll add a fallback path to a plain copy (with manual swap if necessary) if blit isn't supported for either src or dst.

**Comment by SaschaWillems** [comment]
Just pushed changes with alternative copy-only path and manual component swizzle and also reworked the image memory barriers (no more validation warnings). Please test again and let me know if it works now.

**Comment by BennD** [comment]
i dont know if this is the right thread to post in, but there were 2 errors for me in screenshot.cpp:
there are two lines of code where boolean is used instead of bool, which results in a compiler error.

**Comment by SaschaWillems** [comment]
Please check again. I'm working with a different programming language at work (that only has boolean) so I often tend to mix these up, and with VS boolean works just fine.

**Comment by BennD** [comment]
still is in in your latest push, doesnt work for me

**Comment by BennD** [comment]
using g++

**Comment by SaschaWillems** [comment]
See https://github.com/SaschaWillems/Vulkan/commit/cdf8c68d9e3116aa3b39d81ff61591e08d0af0d8

**Comment by BennD** [comment]
thanks. I really appreciate your work. The fact alone that your examples work out of the box is really nice.

**Comment by Delwin9999** [comment]
Works out of the box on master for me.  Wonderful!  Thank you!

**Comment by eero-t** [comment]
I.e. this can be closed... (I cannot)
