### ISSUE TITLE
Missing file? "./../data/textures/cubemap_uffizi_env.dds"

### ISSUE THREAD

**Issue by GoldSciences** [SaschaWillems/Vulkan#290]
Hi Sascha,

I just pulled the latest sources and tried running the pbr example where this file seems to be required but the file isn't in data/textures.

**Comment by SaschaWillems** [comment]
Yes, that's right. The PBR example is still work-in-progress and I'm not yet decided on what cubemaps to use, that's why they're currently missing. I'll upload all assets used by the example as soon as it's finished.

**Comment by GoldSciences** [comment]
I didn't know it was still WIP, sorry. 

Thanks for the hard work you put into this.

**Comment by SaschaWillems** [comment]
I have updated the PBR example and it no longer requires any textures and should work out of the box. I also added a PBR example with IBL that uses two different cube maps included in the repository.
