### ISSUE TITLE
Multisample Sample is incorrect

### ISSUE THREAD

**Issue by danielmaciel** [SaschaWillems/Vulkan#293]
You should not add a non-multisample ZBuffer to the pResolveAttachments array.
pResolveAttachments refer to color attachments only. 
In fact, you should not use a non-multisample ZBuffer at all as it is completely unused.

Refer to:
https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSubpassDescription.html

**Comment by SaschaWillems** [comment]
Yes, I'm aware of this, see #197. I'll fix that at some point.
