### ISSUE TITLE
How do you want to implement the Android build system for Linux? bash, python, cmake, etc.

### ISSUE THREAD

**Issue by cirosantilli** [SaschaWillems/Vulkan#297]
I'm considering porting the android build to work from Linux.

If I do, will you consider merging it?

Looks trivial, just porting those `.bat` under `android`, which basically just call `mkdir`, `cp` and `android`?

If yes, then how do you want it to be done?

I see a few possibilities:

- bash: would be easy to do, but would duplicate the Windows .bat thing
- python: also easy, and would work both on Windows and Linux. Only possible concern is availability in Windows
- cmake: not sure if possible, a bit less easy, but would be good since already used in repo

**Comment by SaschaWillems** [comment]
The newer examples already use python to build with the NDK on linux, so no need for a PR. I'll move all examples from the windows batch files to pyhton scripts in the future.

**Comment by cirosantilli** [comment]
Ah true, they actually work! :-)

```
cd android/pbrbasic
android update project -p . -t android-23
python build.py
```

**Comment by SaschaWillems** [comment]
I'm currently going through all examples adding support for ASTC and ETC2 texture compression format and will also replace the batch files with python build files along the way.

**Comment by SaschaWillems** [comment]
@cirosantilli: I have so far updated all build files to python, including the ones in the base folder for building all examples. The samples use android-23 by default, if you want to change you need to adjust the ```SDK_VERSION``` variable in the main build.py (in the android folder). I'll update the documentation later on.

Note that I have only tested this on windows, so I'll leave this issue open until I get positive feedback on this from a linux user.

**Comment by cirosantilli** [comment]
Has `python build-all.py` run for you without exceptions? :-)

For it to work in Python 2 (I'd recommend writing a Python 2 / 3 subset), off the bat you need:

```
diff --git a/android/build-all.py b/android/build-all.py
index 56b46dc..9d9849a 100644
--- a/android/build-all.py
+++ b/android/build-all.py
@@ -70,7 +70,7 @@ print("Building all examples...")
 
 for example in EXAMPLES:
     print(COLOR_GREEN + "Building %s (%d/%d)" % (example, CURR_INDEX, len(EXAMPLES)) + COLOR_END)
-    if subprocess.call("python build.py %s %s" % (example, BUILD_ARGUMENTS)) != 0:
+    if subprocess.call(["python", "build.py", example, BUILD_ARGUMENTS]) != 0:
         print("Error during build process for %s" % example)
         sys.exit(-1)
     CURR_INDEX += 1
diff --git a/android/build.py b/android/build.py
index 1097d78..f1b1fd9 100644
--- a/android/build.py
+++ b/android/build.py
@@ -20,7 +20,7 @@ if not os.path.exists(PROJECT_FOLDER):
 # Check if a build file is present, if not create one using the android SDK version specified
 if not os.path.isfile(os.path.join(PROJECT_FOLDER, "build.xml")):
     print("Build.xml not present, generating with %s " % SDK_VERSION)
-    if subprocess.call("android.bat update project -p ./%s -t %s" % (PROJECT_FOLDER, SDK_VERSION)) != 0:
+    if subprocess.call(["android", "update", "project", "-p",  PROJECT_FOLDER, "-t", SDK_VERSION]) != 0:
         print("Error: Project update failed!")
         sys.exit(-1)
 
@@ -29,7 +29,7 @@ if not os.path.isfile(os.path.join(PROJECT_FOLDER, "build.py")):
     print("Error: No build script present!")
     sys.exit(-1)
 
-BUILD_ARGUMENTS = ""
+BUILD_ARGUMENTS = []
 for arg in sys.argv[1:]:
     if arg == "-deploy":
         BUILD_ARGUMENTS += "-deploy"
@@ -37,12 +37,14 @@ for arg in sys.argv[1:]:
         BUILD_ARGUMENTS += "-validation"
 
 os.chdir(PROJECT_FOLDER)
-if subprocess.call("python build.py %s" % BUILD_ARGUMENTS) != 0:
+if subprocess.call(["python", "build.py"] + BUILD_ARGUMENTS) != 0:
     print("Error during build process!")
     sys.exit(-1)
 
 # Move apk to bin folder
-os.makedirs("../bin", exist_ok=True)
+bin = "../bin"
+if not os.path.exists(bin):
+    os.makedirs(bin)
 for file in glob.glob("vulkan*.apk"):
     print(file)
     shutil.move(file, "../bin/%s" % file)
```

But then we get `TypeError: makedirs() got an unexpected keyword argument 'exist_ok'` on Python 2.

And because of code duplication that has to be fixed in all directories if we want to support Python 2 :-(

I might do a full patch later if you are interested in reviewing it.

**Comment by SaschaWillems** [comment]
Is Python 2 still widely used? I moved to version 3.x for all private and work projects so I went for Python 3 compatibility. Any reason you can't upgrade?

I plan on having only one build script template in the future that is auto-generated for each example upon build time, which would make changes a lot easier.

**Comment by cirosantilli** [comment]
Python 2 is the default on the latest Ubuntu 16.10, and so I expect it to be the case for most distros.

> Is Python 2 still widely used? I moved to version 3.x for all private and work projects so I went for Python 3 compatibility. Any reason you can't upgrade?

Most distros also come with Python 3, but here it doesn't work to simply do `python3 build-all` because of the subshell calls to `python`.

And using setting python 3 as you default `python` is asking for trouble since many components use Python.

Not to mention corporate environments, which will be running Ubuntu 16.04 until 2020 :-)

Writing Python 2 / 3 subset for such simple scripts is simple however,  `exist_ok` should be the last obstacle. I can patch if you will review it.

> I plan on having only one build script template in the future that is auto-generated for each example upon build time, which would make changes a lot easier.

Awesome. I also recommend that instead of auto-generating python code, that we just use standard python imports or the like.

**Comment by eero-t** [comment]
> Is Python 2 still widely used? I moved to version 3.x for all private and work projects so I went for Python 3 compatibility. Any reason you can't upgrade?

Because there's still a lot of Python v2 specific code around, all the distros still provide Python v2.  Except for older enterprise distros, all the still supported distros versions support also Python v3.

> Python 2 is the default on the latest Ubuntu 16.10, and so I expect it to be the case for most distros.

I assume you mean that /usr/bin/python symlink points to Python v2.  That's for backwards compatibility, and won't change.  At some point it will just go away:
https://www.python.org/dev/peps/pep-0394/

Ubuntu has supported Python v3 at least since 12.04.  Python v3 scripts just need to use correct hashbang: /usr/bin/python3

**Comment by cirosantilli** [comment]
@eero-t yes, updating shebangs and the subprocess calls to `['python3'` would be fine too.

**Comment by SaschaWillems** [comment]
Finally found some time to rework the android build scripts. As of now there is only one global python build script (android/build.py) and the examples are defined using .json files (e.g. android/pbrtexture/example.json). The build script will use these json definition files to gather assets and build the example. It should now also run fine on Linux but still require python3.

**Comment by cirosantilli** [comment]
Android build works fine now.

**Comment by cirosantilli** [comment]
All I'd need to close this issue is: https://github.com/SaschaWillems/Vulkan/pull/391 :-)
