### ISSUE TITLE
Examples don't work in linux.

### ISSUE THREAD

**Issue by DmitryHetman** [SaschaWillems/Vulkan#300]
Error: Could not find asset path in ./../data/

**Comment by eero-t** [comment]
Works fine for me with git version from 1/2 hour ago:
- mkdir -p build; cd build
- cmake ..
- make -j4
- cd ../bin
- run all demos: for i in *; do ./$i; done

**Comment by mrcmunir** [comment]
Working fine here I can't reproduce this (Using Arch distro).

**Comment by SaschaWillems** [comment]
Just checked on my linux dev machine and it works fine there too. Just make sure that the examples binaries are run from the correct directory relative to the asset folder.
