### ISSUE TITLE
precompiled version error

### ISSUE THREAD

**Issue by DmitryHetman** [SaschaWillems/Vulkan#301]
deferred: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory

While it should use on my machine:
/usr/lib64/libvulkan_intel.so

**Comment by SaschaWillems** [comment]
Precompiled versions are pretty dated and rely on the old SDK, so please build them yourself if you want to test with a current SDK / Vulkan driver. I'll update the prebuilt binaries when (if) I'll get some to spare.

**Comment by notaz** [comment]
Yeah please update the binaries, they trigger asserts in open source drivers:
https://bugs.freedesktop.org/show_bug.cgi?id=100161

**Comment by SaschaWillems** [comment]
I have updated the binaries for all platforms at http://vulkan.gpuinfo.org/examples

@DmitryHetman, @notaz: Please try these. If they work I'll close this issue.

**Comment by notaz** [comment]
All working fine for me, thanks.
