### ISSUE TITLE
Ask a question about graphics API

### ISSUE THREAD

**Issue by leihonh** [SaschaWillems/Vulkan#302]
Hi,Williems,
    I want to ask a question, how do you think using  graphics API to do numerical calculation of convolution? Thx.

**Comment by SaschaWillems** [comment]
If you have general questions related to Vulkan or graphics API please ask them at a forum like the one from [Khronos](https://forums.khronos.org/forumdisplay.php/114-Vulkan-High-Efficiency-GPU-Graphics-and-Compute), [reddit ](https://www.reddit.com/r/vulkan/)or [stackoverflow](http://stackoverflow.com/search?tab=newest&q=vulkan). This place is for posting issues related to my examples.

**Comment by leihonh** [comment]
ok,Thx
