### ISSUE TITLE
viewportarray and texturesparseresidency don't work

### ISSUE THREAD

**Issue by andreluizgit** [SaschaWillems/Vulkan#307]
Only this two examples doesn't work. Windows 10 14393.953 + nvidia driver 378,92

**Comment by SaschaWillems** [comment]
Please add some details, do they crash? Both examples require specific hardware features. What validation layer messages do you get?

**Comment by andreluizgit** [comment]
![image](https://cloud.githubusercontent.com/assets/22436084/24148095/0c05433e-0e1c-11e7-898b-4aa43cba9892.png)
![image](https://cloud.githubusercontent.com/assets/22436084/24148104/13cd9b34-0e1c-11e7-8019-ad9097086402.png)

**Comment by SaschaWillems** [comment]
The second error is to be expected if your device does not support sparse residency. For the second example please post at least a stack trace or (better) validation layer output. While the viewport array example is still wip it's running fine for me on a GTX 980 on Windows and an Intel IGP on Linux.

**Comment by andreluizgit** [comment]
Vulkan in totallity can not run in GTX 700 series then why run vulkan?

**Comment by SaschaWillems** [comment]
Can you elaborate? Sparse residency e.g. is an optional feature, so it's not required to be supported for a vulkan implementation.

**Comment by SaschaWillems** [comment]
For the viewport array example please post a call stack and validation layer output, so I can see why it crashes on your setup.

**Comment by andreluizgit** [comment]
![image](https://cloud.githubusercontent.com/assets/22436084/24215031/34e1fafe-0f16-11e7-83ce-c2f21db3a8b6.png)

**Comment by SaschaWillems** [comment]
Please also add validation layer output. If it crashes at vkCmdEndRenderPass it's possible that the example uses features not supported by the GPU and that should be reported in the validation layer output.

**Comment by andreluizgit** [comment]
Should I change the code to get the output? http://gpuopen.com/using-the-vulkan-validation-layers/

**Comment by andreluizgit** [comment]
Should I change the code to get the output?

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Sascha Willems<mailto:notifications@github.com>
Enviado:Wednesday, March 22, 2017 15:45
Para: SaschaWillems/Vulkan<mailto:Vulkan@noreply.github.com>
Cc:andreluizgit<mailto:andreluizbarbieri@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [SaschaWillems/Vulkan] viewportarray and texturesparseresidency don't work (#307)


Please also add validation layer output. If it crashes at vkCmdEndRenderPass it's possible that the example uses features not supported by the GPU and that should be reported in the validation layer output.

**Comment by SaschaWillems** [comment]
No code change required. Just make sure that the validation layers are installed (and can be found by the loader) and run the example with the "-validation" command line argument.

**Comment by andreluizgit** [comment]
![image](https://cloud.githubusercontent.com/assets/22436084/24217459/a1b9557a-0f1e-11e7-892c-cdae27f9ebc0.png)

**Comment by SaschaWillems** [comment]
Can you please check again? I have updated the SPIR-V shader for that example.
