### ISSUE TITLE
build on Android has error 

### ISSUE THREAD

**Issue by leihonh** [SaschaWillems/Vulkan#309]
![33v_9bua clzzltq](https://cloud.githubusercontent.com/assets/15853042/24343423/f6b14f3c-12f8-11e7-8ee8-c90517996207.png)

Hi,Willems,
     I want to run those demos on Android, but I meet with this problem at the first, which step I was wrong?

**Comment by SaschaWillems** [comment]
I haven't fully converted the build process to Linux yet, and as you can see from the error message it tries to call "android.bat" which is obviosuly not available on linux. So either replace this with the android ndk shell script for Linux, wait until I updated everything to work on Linux, or build each sample separate as described in #297.

**Comment by leihonh** [comment]
![Uploading 微信图片_20170327192959.jpg…]()
This is I run on Windows 7 with using cmd

**Comment by leihonh** [comment]
![Uploading cc.jpg…]()
This result is I run on Windows 7 with cmd

**Comment by leihonh** [comment]
![cc](https://cloud.githubusercontent.com/assets/15853042/24354761/bab9f83a-1325-11e7-8e4a-a494bef515b4.png)

This result is run on Windows 7 with cmd

**Comment by SaschaWillems** [comment]
Google changed the way NDK builds are done with the latest NDK, but I haven't had the time to check this out. So you have to wait until I have updated myself or revert to an older version of the NDK.

**Comment by leihonh** [comment]
ok ，thank you for your answer

**Comment by sjfricke** [comment]
I have searched and found no replacement for the `android update project` command.
If you still need to build I suggest reverting to SDK Tools 25.2.5 or earlier as they removed the command in [Build Tool 25.3.0](https://developer.android.com/studio/releases/sdk-tools.html)

You can download them from here and replace the `tools` folder in your ANDROID_SDK_HOME directory
https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip
https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
