### ISSUE TITLE
Vulkan Texture problen

### ISSUE THREAD

**Issue by Steven201314** [SaschaWillems/Vulkan#310]
just look the image,Should I realize or Vulkan has had Solution?
![qq 20170329104449](https://cloud.githubusercontent.com/assets/8087730/24436363/ca145d4a-146d-11e7-94f2-a20cb951b000.jpg)

![vulkan_problem](https://cloud.githubusercontent.com/assets/8087730/24436366/ca75edd0-146d-11e7-8fa1-de9b2f402078.png)

**Comment by SaschaWillems** [comment]
So what's the actual problem? Can you be a bit more specific? Is my texturing example rendering wrong?

**Comment by Steven201314** [comment]
If it's a rectangle, the texture effect is correct, but if you use a non-rectangle，like this code:
std::vector<Vertex> vertices =
		{
			{ {  1.0f,  1.0f, 0.0f }, { 1.0f, 1.0f },{ 0.0f, 0.0f, 1.0f } },
			{ { -1.0f,  1.0f, 0.0f }, { 0.0f, 1.0f },{ 0.0f, 0.0f, 1.0f } },
			{ { **-0.5f** -1.0f, 0.0f }, { 0.0f, 0.0f },{ 0.0f, 0.0f, 1.0f } },
			{ {  **0.5f,** -1.0f, 0.0f }, { 1.0f, 0.0f },{ 0.0f, 0.0f, 1.0f } }
		};

If Carefully observe the rendering results , we'll find the effect is error.  
Someone tell me it is  because of "Affine Texture Mapping", NOT "Perspective Texture Mapping",
Or the vk default is "Affine Texture Mapping"?
 I'm being confused！In my project,the result is like this 

![1 1stdi1ivj3j0co h42m](https://cloud.githubusercontent.com/assets/8087730/24465589/2a4154da-14e0-11e7-84f7-0c1449c29c7d.jpg)

**Comment by SaschaWillems** [comment]
That's correct behavior because the quad is made up of two triangles. So either also adjust the UV-Coordinates (and not just the vertex positions) or use projection, e.g. like in [this fine article by Nathan Reed](http://www.reedbeta.com/blog/quadrilateral-interpolation-part-1/).

**Comment by Steven201314** [comment]
Oh,I see .I'll alter the code tomorrow morning.Thank you every much.

**Comment by McNopper** [comment]
![grafik](https://cloud.githubusercontent.com/assets/3677213/24504427/95add218-1556-11e7-8e79-ad5ca98a3305.png)
`	static const float vertices[4 * (4 + 2)] = { 
-1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f,
1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f,
-1.0f, -2.0f, 0.0f, 2.0f, 0.0f, 1.0f,
1.0f, -2.0f, 0.0f, 2.0f, 1.0f, 1.0f 
};
`

**Comment by McNopper** [comment]
I still do not know what you want to achieve but probaly u need to read this:
http://www.geeks3d.com/20130514/opengl-interpolation-qualifiers-glsl-tutorial/
