### ISSUE TITLE
imgui sample is crashing 

### ISSUE THREAD

**Issue by pandurangkatkar** [SaschaWillems/Vulkan#311]
imgui sample is crashing  over Nvidia and AMD GPU

could you please look in to this issue I am using late Vulkan RT 1.0.42.2

**Comment by SaschaWillems** [comment]
Note that the imgui example is stil work-in-progress and not yet finished.

Also please add at least a call stack and the validation layer output so I can see why it crashes.

Works fine over here on an NV desktop GPU and multiple mobile devices.

**Comment by SaschaWillems** [comment]
@pandurangkatkar : Any update on this?

**Comment by Zouch** [comment]
To update on this, it also crashes for me with an nvidia GTX 660.

`memory` is `0xcdcdcdcdcdcdcdcd`.

```
 	vulkan-1.dll!00007ffc30414510()	Unknown
>	imgui.exe!vks::Buffer::destroy() Line 154	C++
 	imgui.exe!ImGUI::updateBuffers() Line 399	C++
 	imgui.exe!VulkanExample::buildCommandBuffers() Line 558	C++
 	imgui.exe!VulkanExample::prepare() Line 768	C++
 	imgui.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * pCmdLine, int nCmdShow) Line 802	C++
 	[External Code]	
```

I have no output from the validation layers.

**Comment by SaschaWillems** [comment]
Could you test again? I pushed a commit that initializes the buffer and memory members of the buffer wrapper class with VK_NULL_HANDLE which may be the cause for the crash in this example.

**Comment by Zouch** [comment]
It's working for me after the update.

**Comment by SaschaWillems** [comment]
Thx for the feedback 👍

**Comment by pandurangkatkar** [comment]
For me also it"s working fine after Update :+1: 

Sorry For Late response :)

**Comment by pandurangkatkar** [comment]
Thanks For Fix !
