### ISSUE TITLE
Does any Vulkan driver supports my graphics card?

### ISSUE THREAD

**Issue by 2gud4u** [SaschaWillems/Vulkan#312]
I have a Nvidia GeForce 9500 GT, im not shure if a driver is correct for it, and i dont want to end with a black screen, can somebody help me please?

**Comment by SaschaWillems** [comment]
A list of Vulkan conformant products can be found [here](https://www.khronos.org/conformance/adopters/conformant-products).

A 9500 GT is pretty dated and won't be supported.
