### ISSUE TITLE
Dynamic Uniform Buffer host-visible memory synchronisation

### ISSUE THREAD

**Issue by nidefawl** [SaschaWillems/Vulkan#313]
How does the synchronization in the dynamic-uniform demo work?

The host writes to persistent mapped host-visible device memory.
Then it calls flush to make it device-visible. 
But there are command buffers in flight that reference the now overwritten memory.

From how I understood dynamic uniform buffers the data has to be written to separate locations per frame to avoid overwriting in-flight command buffers data.

**Comment by SaschaWillems** [comment]
The examples issue an idle wait on the queue at each frame submit which takes care of possible synchronization issues. So depending on your setup yes you may want to use one separate buffer for each of your command buffers.
