### ISSUE TITLE
Image-base lighting sample missing files

### ISSUE THREAD

**Issue by Zouch** [SaschaWillems/Vulkan#321]
When trying to start the pbribl example, it complains about the fact that it cannot find "./../data/textures/hdr/pisa_cube.ktx", which indeed does not seem to be there.

**Comment by SaschaWillems** [comment]
That's correct. The header of the example states that it's work-in-progress and not guaranteed to work (until it's finished). Once I'm done with it I'll upload the resources (textures, shaders, etc.) required to run the example.

**Comment by mrcmunir** [comment]
Ah I see Sorry i had not seen this report :)
