### ISSUE TITLE
pbrbasic and pbribl not found textures files 

### ISSUE THREAD

**Issue by mrcmunir** [SaschaWillems/Vulkan#324]
[mrc@Mrc-munir bin]$ ./pbribl 
Could not load texture from ./../data/textures/hdr/pisa_cube.ktx
[mrc@Mrc-munir bin]$ ./pbribl 
Could not load texture from ./../data/textures/hdr/pisa_cube.ktx

It's a regresion the folder /hdr/ in textures not found in the github .

**Comment by SaschaWillems** [comment]
Duplicate of #321, please see the example's header comment.
