### ISSUE TITLE
pbrbasic push constants usage look strange

### ISSUE THREAD

**Issue by airlied** [SaschaWillems/Vulkan#328]
pbrbasic.cpp uses a Material struct, with sizeof(Material) to send the push constants, however that contains a std::string in it, which is definitely not something you want to send to the GPU.

maybe replace sizeof(Material) with a define.

**Comment by SaschaWillems** [comment]
That's true. The std::string doesn't belong in the push constant block. I'll change that in all PBR samples that use named materials.
