### ISSUE TITLE
data/textures/hdr directory not in repo

### ISSUE THREAD

**Issue by ParticlePeter** [SaschaWillems/Vulkan#330]
Thanks for your great work, helps a lot !
`pbribl` and `hdr` examples both don't run, they are missing `ktx` textures in the `data/textures/hdr` directory.

**Comment by SaschaWillems** [comment]
Those files are part of the external asset pack introduced to keep rep size down. Please refer to https://github.com/SaschaWillems/Vulkan/blob/master/data/README.md

**Comment by ParticlePeter** [comment]
O.k. and sorry, I see that I wasn't the first one :-)
