### ISSUE TITLE
Pure offscreen rendering with readback

### ISSUE THREAD

**Issue by dkrikun** [SaschaWillems/Vulkan#331]
Great tutorial!

Could you please add an example of pure offscreen rendering (i.e. without swapchain, surface and window) with readback buffer?

**Comment by SaschaWillems** [comment]
Will put it on my to-do list. What do you want to readback? An image? Data computed by a compute shader?

**Comment by dkrikun** [comment]
An image.
Actually I got a working code by myself, but I suspect it might be over-synchronized.
Thanks

**Comment by SaschaWillems** [comment]
The [screenshot example](https://github.com/SaschaWillems/Vulkan/blob/master/screenshot/screenshot.cpp) does read back an image. It' an image of the swap chain though and not headless.

**Comment by dkrikun** [comment]
Yeah, the problem with headless one is how to sync against the readback..

**Comment by sturfee-petrl** [comment]
@dkrikun Could you please share your code?
I need do rendering on server.

**Comment by SaschaWillems** [comment]
I just added two headless examples. One for doing headless compute and one for headless rendering with readback. The later one might be what you're looking for and works across multiple platforms (windows, linux, android).

**Comment by maddanio** [comment]
can you add cached readback for the rendering example, or another example like that? un-cached readback seems to be quite slow (slower than I achieved before in OpenGL at least).

**Comment by WilliamXiao** [comment]
@SaschaWillems 
Thanks for your examples.  Concerning the example called "renderheadless", Is there a way to render a transparent background?  I get a try by setting clear color, but it does not work.
`			VkClearValue clearValues[2];
			clearValues[0].color = { { 0.0f, 0.0f, 0.2f, 0.0f } };
			clearValues[1].depthStencil = { 1.0f, 0 };`
Any ideas? thanks again.
