### ISSUE TITLE
Rendering bug in viewport arrays example

### ISSUE THREAD

**Issue by programmerjake** [SaschaWillems/Vulkan#332]
I'm not sure if this is a driver bug or not.
Vulkan samples commit: 90a95b495aad7ea5067847f52ed5c36b5d34da84
Ubuntu 16.04 x86_64
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
assimp 3.2.0
kernel 4.4.0-77-generic
amdgpu-pro 17.10-414273
xorg-server 2:1.18.4-0ubuntu0.2
Radeon RX 550

![screenshot from 2017-05-16 14-36-56](https://cloud.githubusercontent.com/assets/4584340/26129610/cc48ea60-3a45-11e7-8274-ec7d74844502.png)

**Comment by SaschaWillems** [comment]
Validation for that example is clean, and all the platforms and devices I have tested this on ran it without the glitch visible in the screenshot, so right now I'd say this is a driver bug.

**Comment by programmerjake** [comment]
I reported this to AMD.

**Comment by SaschaWillems** [comment]
Don't worry. I'll leave this issue open until you've got Feedback from AMD.

**Comment by voidstorm** [comment]
FYI, I'm having exactly the same glitch but on Win10...

Win 10 Pro 64bit, Creators Update,
AMD Radeon R9 380X
Driver Version 17.5.1
Vulkan Driver 1.5.0
API version 1.0.39

**Comment by voidstorm** [comment]
Hi again @SaschaWillems !

I found the problem with the geomtry shader. See: [https://www.khronos.org/opengl/wiki/Geometry_Shader](https://www.khronos.org/opengl/wiki/Geometry_Shader)

"The primitive ID will be passed to the fragment shader. The primitive ID for a particular line/triangle will be taken from the provoking vertex of that line/triangle, so make sure that you are writing the correct value for the right provoking vertex.

The meaning for this value is whatever you want it to be. However, if you want to match the standard OpenGL meaning (ie: what the Fragment Shader would get if no GS were used), you must do this for each vertex before emitting it:
gl_PrimitiveID = gl_PrimitiveIDIn;"

When adding this line before emitting a vertex, it works with amd cards as well. It seems nvidia is, as always a bit more relaxed with that.,..

**Comment by SaschaWillems** [comment]
Thx for the PR, works fine on NV too and makes sense. 👍
