### ISSUE TITLE
create sampler had error when enable validation layer with sdk is updated to 46.0(I 'm not use 49)

### ISSUE THREAD

**Issue by leihonh** [SaschaWillems/Vulkan#336]
![_20170524102458](https://cloud.githubusercontent.com/assets/15853042/26384458/ec7f6ed6-406b-11e7-8482-a56c51183e60.png)
Hi,
 Willems, I found some error as shown above, while the sdk updated 46.0, but when use the earlier version(like 39), they were right.

**Comment by SaschaWillems** [comment]
Those validation checks have been introduced a few months ago and I'm aware of them. I already fixed a few of them and will updated the other examples too once I get the time to do so.
