### ISSUE TITLE
HDR example texture is missing 

### ISSUE THREAD

**Issue by Nikolsi** [SaschaWillems/Vulkan#341]
Example compiles, but gives an error about missing file. I could not find file: "uffizi_cube.ktx" in my folder.
:)

**Comment by SaschaWillems** [comment]
Those files are part of the external asset pack introduced to keep rep size down. 
For details see https://github.com/SaschaWillems/Vulkan/blob/master/data/README.md
This is also noted in the comment header of all samples that require the external asset pack.
