### ISSUE TITLE
Compute demos should not hardcode a 256 item workgroup size

### ISSUE THREAD

**Issue by ghost** [SaschaWillems/Vulkan#348]
Three of the compute demos (and raytracing) have compute shaders with hardcoded workgroup sizes that total 256 workgroup items. However the spec allows for hardware with a maximum supported workgroup invocations of 128 and I am using hardware that only has support for that limit.

From the perspective of teaching people how to write Vulkan, that has a chance of working on a range of hardware platforms, it would be useful if the effected compute demos (at least) queried the physical device limits and then used specialization constants (I think?) to customize the shaders with an appropriate workgroup configuration for the hardware.

**Comment by SaschaWillems** [comment]
Yes, you're right. Any hardcoded limit shouldn't exceed the lower limits of what the API specifies. I'll change the compute shader samplers to check against actual hardware limits.
