### ISSUE TITLE
Viewport seems to not update properly

### ISSUE THREAD

**Issue by httpdigest** [SaschaWillems/Vulkan#35]
Hi, 

I just tried your demos and they are fantastic! I am actually already porting them to Java with LWJGL 3, which recently got Vulkan support.

One issue I am seeing however is that when enlarging the window from its initial size, then the viewport does not seem to update. This seems to happen so far for every demo.

This is an example of the "triangle" demo: http://i.imgur.com/aDkcGKr.png
This is an example of the "shadowmap" demo: http://i.imgur.com/CjCKkSh.png

Somehow everything that overlaps the viewport from the initial window size gets repeated down to the window border, and clipped to the right.

OS/arch: Windows 7 x64
Compiler: MSVC 2015 x64
Driver: Nvidia 356.39
Card: Nvidia Quadro K2000M

**Comment by pendingchaos** [comment]
I had a similar problem with my Vulkan code. I fixed it by recreating the VkSwapchainKHR with the current width and height of the window when it was resized.

**Comment by SaschaWillems** [comment]
Fixed with #105 some time ago.
