### ISSUE TITLE
lose assets?

### ISSUE THREAD

**Issue by Steven201314** [SaschaWillems/Vulkan#350]
Hi, friend , HDR project   misses the resource file.
![qq 20170703151743](https://user-images.githubusercontent.com/8087730/27782023-4bd667f2-6003-11e7-9002-8c8f739dcb4e.png)

**Comment by SaschaWillems** [comment]
Those files are part of the external asset pack introduced to keep rep size down.
For details see https://github.com/SaschaWillems/Vulkan/blob/master/data/README.md
This is also noted in the comment header of all samples that require the external asset pack.
