### ISSUE TITLE
Unclear building instructions for Linux

### ISSUE THREAD

**Issue by wbeyda** [SaschaWillems/Vulkan#351]
The instructions for building the examples is very unclear. Adding something like this would be nice. 

git clone https://github.com/SaschaWillems/Vulkan

cd Vulkan

make build

cd build/Triangle

./triangle
#runs triangle example. 

And then an example at extending the projects would be nice. I'm new to g++ and cmake and don't understand how to build the examples. So my Vulkan learning is pretty stagnant right now.

**Comment by SaschaWillems** [comment]
> The instructions for building the examples is very unclear. Adding something like this would be nice.

Did you take a look at the [quick start guide from the wiki](https://github.com/SaschaWillems/Vulkan/wiki/Quick-start-guide)? 

As cmake is very common (esp. on Linux with C/C++ projects) I assumed this as basic knowledge, and up until now I had no requests in a detailed explanation.

But if you feel that something is missing from the above quick start guide just drop me a line and I'll add it.

> And then an example at extending the projects would be nice. 

Could you detail this? What exactly do you mean with "extending the projects"?

**Comment by wbeyda** [comment]
Ah I didn't see the quick start guide in the wiki. This is exactly what I was looking for.
