### ISSUE TITLE
Could not load texture from ./../data/textures/hdr/uffizi_cube.ktx

### ISSUE THREAD

**Issue by andreluizgit** [SaschaWillems/Vulkan#353]
For the 'hdr.exe' app

Maybe I must download the folder that not exist in my computer...

Congratulations for Great Project! Now with Windows 10 16232.1000 we can see GPU usage for process in 'task manager', what is goood.

**Comment by SaschaWillems** [comment]
Those files are part of the external asset pack introduced to keep rep size down.
For details see https://github.com/SaschaWillems/Vulkan/blob/master/data/README.md
This is also noted in the comment header of all samples that require the external asset pack.
