### ISSUE TITLE
texturemipmapgen demo is crashing at vkQueueSubmit "ERROR_DEVICE_LOST"

### ISSUE THREAD

**Issue by cdgiessen** [SaschaWillems/Vulkan#354]
Error Popup:
Assertion failed!
Program : ...lkan-master\Vulkan-master\bin\texturemipmapgen.exe
File: texturemipmapgen.cpp
Line: 425
Expression: res == VK_SUCCESS

Validation output:
WARNING: [ParameterValidation] Code 9 : vkQueueSubmit: returned VK_ERROR_DEVICE_LOST, indicating that the logical device has been lost
Fatal : VkResult is "ERROR_DEVICE_LOST" in texturemipmapgen.cpp at line 425

Platform is windows 10 and using latest vulkan sdk version (1.0.51.0) and built with visual studio 2017
Gpu is AMD r9 280, with driver version 17.1.1

**Comment by SaschaWillems** [comment]
Working fine for me with an AMD R9 390X using the latest driver and the same SDK version. Is this also happening with the pre-built binaries or only when running from the IDE?

**Comment by cdgiessen** [comment]
It crashes with both the binary and the IDE

**Comment by iFreet1** [comment]
+1
Win 10, vulkan sdk 1.0.68.0, visual studio 2015.
GPU AMD Radeon HD7800, driver 17.50.17.03

**Comment by cdgiessen** [comment]
Running the demo again on the same hardware works for some reason with Vulkan SDK version 1.1.70 and AMD drivers 18.3.4.
