### ISSUE TITLE
glm fails to build on x86

### ISSUE THREAD

**Issue by jku** [SaschaWillems/Vulkan#356]
This is the same issue as in #283:
`func_common.inl:193:51: error: wrong number of template arguments (5, should be 6) struct compute_sign<T, P, vecType, false, Aligned>`

That one was close with "it looks like you only support AMD64" -- if this is really true please close.

The issue comes up when building for x86. I've tested the upstream copy of that template and it works. I can provide a patch if you don't plan to update the copy of glm from upstream.

**Comment by SaschaWillems** [comment]
> That one was close with "it looks like you only support AMD64" -- if this is really true please close.

No, that's not intentional. I want to support as many platforms as possible, so thx for bringing this up. 
I'll check with a recent version of glm and update my repo to fix this.

**Comment by SaschaWillems** [comment]
I have replaced the local glm copy with a proper submodule (master). Can you check again? Works fine for me on x86, but only tested with Visual Studio on Win.

**Comment by jku** [comment]
Looks good to me, builds fine on Yocto for qemux86. Thanks!
