### ISSUE TITLE
Most examples fail on Ubuntu 16.04 Nvidia GTX680 Geforce 375.66 driver 

### ISSUE THREAD

**Issue by wbeyda** [SaschaWillems/Vulkan#357]
# Most examples fail on Ubuntu 16.04 Nvidia GTX680 Geforce 375.66 driver 
After setting:
`#define ENABLE_VALIDATION true`
on all examples I get the error:

> Could not create Vulkan instance : 
> ERROR_LAYER_NOT_PRESENT

for the following examples:  
* computenbody
* computerparticles
* computershader
* debugmarker
* deferred
* deferredmultisampling
* deferredshadows
* displacement
* distancefieldfonts
* dynamicuniformbuffer
* geometryshader
* instancing
* mesh
* multisampling
* multithreading:
    numThreads = 4
* raytracing
* scenerendering
* shadowmapping
* skeletalanimation
* specializationconstants
* sphericalenvmapping
* ssao
* terraintessellation
* tessellation
* texture
* texture3d
* texturearray
* texturemipmapgen
* texturesparseresidency
* vulkanscene

vulankinfo attached. 
[info.txt](https://github.com/SaschaWillems/Vulkan/files/1137360/info.txt)

**Comment by SaschaWillems** [comment]
Are you sure that the validation layers are actually installed? Looking at your info.txt the only layers listed are those from steam, and not one single validation layer:

	Layers: count = 2
	=======
	VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.0.3, layer version 1
		Layer Extensions	count = 0
		Devices 	count = 1
			GPU id       : 0 (GTX 680)
			Layer-Device Extensions	count = 0

	VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.0.3, layer version 1
		Layer Extensions	count = 0
		Devices 	count = 1
			GPU id       : 0 (GTX 680)
			Layer-Device Extensions	count = 0

**Comment by wbeyda** [comment]
How do I install the Validation Layers?

**Comment by SaschaWillems** [comment]
Either build and install from source (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) or install a current version of the LunarG SDK for linux and follow the instructions at https://vulkan.lunarg.com/doc/view/latest/linux/getting_started.html.
