### ISSUE TITLE
Helpful to note `git clone --recursive` needed

### ISSUE THREAD

**Issue by alanmimms** [SaschaWillems/Vulkan#359]
I just spent a while installing my Linux distribution's libglm only to discover that this repo has its _own_ version that I could have used if only I had realized the repo had submodules.

I suggest you put a little note at the start of your `README.md` to let people know this repository should be cloned with `git clone --recursive` for best (or any, really) experience.

**Comment by SaschaWillems** [comment]
I only recently updated to a submodule for glm and haven't had the time to update the readme. Will add the recursive note in one of the next updates.
