### ISSUE TITLE
tesselation example fails to compile

### ISSUE THREAD

**Issue by mmmovania** [SaschaWillems/Vulkan#36]
On my windows 8.1 x64 machine, VS2015, the tessellation demo fails to compile with the following error
`Severity	Code	Description	Project	File	Line
Error	C2797	'VulkanExampleBase::defaultClearColor': list initialization inside member initializer list or non-static data member initializer is not implemented	tessellation	C:\[some_path]\Vulkan-master\base\vulkanexamplebase.h	96`
The solution is to replace line 96 from 
`VkClearColorValue defaultClearColor = {{ 0.025f, 0.025f, 0.025f, 1.0f }};` to
`VkClearColorValue defaultClearColor = VkClearColorValue({ 0.025f, 0.025f, 0.025f, 1.0f });`

**Comment by SaschaWillems** [comment]
That's odd. This compiles fine for me with VS2015 (x64), and is actually used by all the examples. Does this only happen with the tessellation example?

**Comment by mmmovania** [comment]
Yes this is only for tesselaton example. By the way thanks for sharing your examples.  Awesome work.  

For me vulkan is a new territory and the examples seem daunting as a beginner.   What is your suggestion on what is the best source to learn about all those functions.

**Comment by SaschaWillems** [comment]
What VS2015 version is this? The example compiles fine for me with VS2015 (update2) and MINGW on Windows and different gcc versions on Linux.

**Comment by mmmovania** [comment]
Its MS VisualStudio Professional 2015. I am not sure if there is an update for it ?

**Comment by SaschaWillems** [comment]
A bit late, but can you please try again with the current code? I have overhauled the tessellation example, maybe it works now.
