### ISSUE TITLE
shadowmapping improvements

### ISSUE THREAD

**Issue by SteveHill-BRCM** [SaschaWillems/Vulkan#363]
Hi,

The shadowmapping example uses linear filtering on a D16 texture which is not required to be supported by the spec.  However, I think the example could be improved by using shadow samplers rather than regular textures and then that issue goes away.  It also simplifies the shader and is a more efficient way to implement shadow mapping.

I have attached a patch file with some suggested changes to implement this scheme.

[shadowmapping.txt](https://github.com/SaschaWillems/Vulkan/files/1179488/shadowmapping.txt)

Many thanks.

**Comment by SaschaWillems** [comment]
Thx for your contribution! Getting rid of an optional requirement (filtering D16) along with a smaller shader is a great thing. Will test this on a few devices and GPU and apply the patch.

**Comment by SaschaWillems** [comment]
Just had a chance to test this on multiple implementations, and while this looks pretty much the same on desktop GPUs, on mobile GPUs there's no filtering. Will take a look at why (I guess it's just not supported on e.g. Mali) and see if I'll ad a fallback for moblile.

**Comment by SteveHill-BRCM** [comment]
Hi Sascha,

Thanks for looking at this.  I think that shadow map filtering is fairly loosely defined due to vendors having a range of different implementations.  I guess you could use linear filtering as before if it is supported and the hardware doesn't do a good job (not sure how to determine the latter).  It would be a shame to not use the shadow mapping functionality when shadow mapping though :-)

Very much appreciate your hard work on these examples.
