### ISSUE TITLE
Android text overlay height is only half in landscape

### ISSUE THREAD

**Issue by sjfricke** [SaschaWillems/Vulkan#371]
I was running the Pipeline app on my Galaxy S6 (Mali-T760) and noticed the text was getting cut off. After playing around I realized that in the [textOverlay->addText](https://github.com/SaschaWillems/Vulkan/blob/master/pipelines/pipelines.cpp#L428-L436) call had `width == 2560` and `height == 1440` as expected.

I made a bunch of different text and found that the bottom of my screen is half the height. After looking more I still can't figure out why since the viewport and renderpass extent were both 1440 for height as well. 

[Image of screen](https://drive.google.com/open?id=0B46b_H3-cALrb3pJQUJnd1FHN2s)

**Comment by SaschaWillems** [comment]
This is probably due to the scaling based on the device's DPI (see [here](https://github.com/SaschaWillems/Vulkan/blob/master/base/VulkanTextOverlay.hpp#L123)).

I do have several mobile devices with high resolution screens, so I'll take a look at this.

**Comment by sjfricke** [comment]
Ok this makes total sense now!
So my device does have `XXHIGH` and it is [doubling](https://github.com/SaschaWillems/Vulkan/blob/master/base/VulkanTextOverlay.hpp#L581) the `y` value which is why adding text at `height / 2.0f` is the bottom of the screen.

I guess I am not sure the best solution for an all encompassing relative fit text overlay solution is

**Comment by sjfricke** [comment]
@SaschaWillems I think this is safe to close due to the new UI system inplace
