### ISSUE TITLE
VulkanScene, DistanceFieldFonts: Wrong image layout in descriptor set

### ISSUE THREAD

**Issue by iostrowsINTEL** [SaschaWillems/Vulkan#372]
Skybox (VulkanScene) and font (DistanceFieldFonts) are in `VK_IMAGE_LAYOUT_GENERAL` layout in descriptor set while should be in `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL`

**Comment by SaschaWillems** [comment]
Thx for this PR 👍
