### ISSUE TITLE
Question about the memory barrier in compute body.

### ISSUE THREAD

**Issue by weidaru** [SaschaWillems/Vulkan#374]
https://github.com/SaschaWillems/Vulkan/blob/ff4e6e2877fd5aa69e8341edacc2cfdaa3da79e1/data/shaders/computenbody/particle_calculate.comp#L59

Is this missing a "barrier" which synchronize read after write? My understanding is that sharedData should be filled by all invocation before calculating acceleration.

**Comment by SaschaWillems** [comment]
Can you elaborate on your question? You're linking to a memory barrier but I guess you're talking about a different part of the shader?

**Comment by weidaru** [comment]
The question is whether the memory barrier should be memory barrier + execution barrier, something like 
```glsl
memoryBarrierShared(); 
barrier();   //Execution barrier
```
Correct me if I misunderstood. The code before memory barrier is populating sharedData from each invocation. The code after barrier is adding up the acceleration.  This seems to require a exeuction barrier.

**Comment by SaschaWillems** [comment]
Yes, you're right, the execution barrier is missing. Oddly this seems to work fine on every single implementation I've tested. I'll add the barrier in one of the next updates. Thx for bringing up this issue.

**Comment by weidaru** [comment]
No problem. It is really nice to have those examples while learning vulkan.

**Comment by SaschaWillems** [comment]
Added the barrier to the shader. Just in case someone is wondering about both barrier types: 
In GLSL 4.5 the barrier() would also implicitly add a memory barrier, but it looks like this is currently not (correctly as per GLSL 4.5 spec) translated to SPIR-V (see this [issue](https://github.com/KhronosGroup/glslang/issues/502)).

**Comment by jeremyong** [comment]
I randomly found this issue while trying to understand if Spir-V implemented the barrier semantics correctly. Were you operating with a thread group size smaller than or equal to the GPU's subgroup size? If you stay within the warp, the barrier (which synchronizes across subgroups of a work group invocation) is not actually necessary and may explain why you didn't see artifacts.
