### ISSUE TITLE
displacement.cpp(19): fatal error C1083: gli/gli.hpp: No such file or directory

### ISSUE THREAD

**Issue by Mikez2015** [SaschaWillems/Vulkan#376]
GLI - OpenGL Image?

**Comment by Mikez2015** [comment]
I try include CLI, but got many many many errors like this:
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(42): error C2061: syntax error: identifier 'qualifier'
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(43): error C2988: unrecognizable template declaration/definition
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(43): error C2143: syntax error: missing ';' before '<'
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(43): error C2433: 'vec': 'inline' not permitted on data declarations
3>  triangle.cpp
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(43): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(43): error C2059: syntax error: '<'
2>c:\program files (x86)\microsoft visual studio 14.0\vc\include\gli\type.hpp(50): error C2143: syntax error: missing ';' before '{'

Project does not work with Visual Studio 2015

**Comment by SaschaWillems** [comment]
gli is a submodule, so you probably did not initialize the submodeles. See the [readme](https://github.com/SaschaWillems/Vulkan#cloning) for details.

I'm working with VS2015 too (the travis CI build is also using VS2015) and it works fine over here.

**Comment by Mikez2015** [comment]
Now working, thx.
