### ISSUE TITLE
`dynamicAlignment` is accidentally correct.

### ISSUE THREAD

**Issue by NicolBolas** [SaschaWillems/Vulkan#381]
Consider `VulkanExample::prepareUniformBuffers` in `dynamicuniformbuffer.cpp`. It computes `dynamicAlignment` as follows:

````
size_t uboAlignment = vulkanDevice->properties.limits.minUniformBufferOffsetAlignment;
dynamicAlignment = (sizeof(glm::mat4) / uboAlignment) * uboAlignment + ((sizeof(glm::mat4) % uboAlignment) > 0 ? uboAlignment : 0);
````

This code is wrong. `sizeof(glm::mat4)` is an integer, as is `uboAlignment`. Therefore, dividing them will result *in an integer*. Since `uboAlignment` is required to be at least 256, this division will result in the integer 0. And `0 * uboAlignment` is still zero.

So the only term that matters is `((sizeof(glm::mat4) % uboAlignment) > 0 ? uboAlignment : 0);` This will result in `uboAlignment` being the value of `dynamicAlignment`.

So this code is a _very_ obfuscated way of setting `dynamicAlignment` to `minUniformBufferOffsetAlignment`.

**Comment by SaschaWillems** [comment]
Yes, that code actually doesn't make any sense. Thx for noticing.
