### ISSUE TITLE
Terrain tessellation: wrong vertices buffer size

### ISSUE THREAD

**Issue by Rominitch** [SaschaWillems/Vulkan#386]
In the terrain tesselation demo, you allocate a huge vertices buffer (on CPU + GPU).
Hopefully, IBO is correctly made so we never call none-initialized vertices.

I made a patch on my fork : see branch fix_terraintesselation

Regards

**Comment by SaschaWillems** [comment]
Thx for pointing this out. The vertex buffer was in fact too large, just fixed this.
