### ISSUE TITLE
VkQueueFamilyProperties array not freed in vulkanswapchain

### ISSUE THREAD

**Issue by Semmy13** [SaschaWillems/Vulkan#39]
Thanks for the tutorials! Just a minor bug I found.

In VulkanSwapChain::initSwapChain you are allocating memory for queueProps and supportsPresent.
The latter is freed, but queueProps is never freed and leaks memory.

**Comment by SaschaWillems** [comment]
Thx for pointing me at this. This wasn't the only pointer not freed in the swapchain. I have replaced all the mallocs with std::vectors to fix these and bring the source more in line with the rest of the samples.
