### ISSUE TITLE
triangle: vkCmdBindPipeline must be called before setting viewport/scissor

### ISSUE THREAD

**Issue by polarina** [SaschaWillems/Vulkan#395]
https://github.com/SaschaWillems/Vulkan/blob/9fd56e489ce64e141f369cadf01fe9b04011cbfa/triangle/triangle.cpp#L309

Calls to `vkCmdSetViewport` and `vkCmdSetScissor` ***must*** happen after a call to `vkCmdBindPipeline`. To do otherwise is undefined behaviour.

Valid usage for `vkCmdSetScissor` states: _"The currently bound graphics pipeline **must** have been created with the `VK_DYNAMIC_STATE_SCISSOR` dynamic state enabled"_ implying that a pipeline must've previously been bound. Same goes for `vkCmdSetViewport`.

**Comment by SaschaWillems** [comment]
Reading (again) through the current spec version I'm still not sure if a bound pipeline is an actual requirement. The spec only says that a currently bound pipeline needs to have the dynamic states enabled, but not that a pipeline has to be bound when calling these commands. 

I'm still under the impression that vkCmdSetViewport/scissor are both actually command buffer statesm esp. as there is no validation that pops up in these cases. 

I'll take a look at that this weekend and if the spec isn't clear enough on that I'll raise an issue at the Vulkan repo.

**Comment by kennyalive** [comment]
Are there any updates here?

**Comment by kennyalive** [comment]
There are some arguments why it should be a command buffer state here, and it is still open.
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/52

**Comment by SaschaWillems** [comment]
Closing this, see the discussion in the validation layers issue.
