### ISSUE TITLE
Possible incorrect  setting in MSAA sample

### ISSUE THREAD

**Issue by UffiziTerrace** [SaschaWillems/Vulkan#399]
line 257 in multisampling sample:
		attachments[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;

in the vast majority of example is have looked at, this setting is set as:
		attachments[0].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;

the following is taken from the ARM vulkan samples:
	// DONT_CARE is critical here, since it allows tile based renderers to completely avoid
	// writing out the multisampled framebuffer to memory. This is a huge performance and bandwidth
	// improvement.
	attachments[0].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;

When tested on hardware, if found the VK_ATTACHMENT_STORE_OP_DONT_CARE setting gave a better results.

**Comment by SaschaWillems** [comment]
Yes, DONT_CARE gives better results on TBRs, but STORE is not incorrect. The goal of these examples is to run on a wide variety of devices, and as such the samples are not optimized to fit ever performance requirement of all the different GPUs out there.

**Comment by UffiziTerrace** [comment]
many thanks for getting back to me.
Did not realise that DONT_CARE might give unwanted results dependent on the gpu, assumed it was same for all devices. (Apple metal and Dx developer, will take a while to change the mind-set across to multi-hardware/platform).
Great set of examples by the way. Keep up the good work.
