### ISSUE TITLE
Sharing mode parameter of VkSwapchainCreateInfoKHR

### ISSUE THREAD

**Issue by httpdigest** [SaschaWillems/Vulkan#40]
I think [this line](https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkanswapchain.hpp#L312) should rather read as:
```Java
swapchainCI.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
```

**Comment by SaschaWillems** [comment]
Yes, this is obivously wrong. Thanks for noticing!
