### ISSUE TITLE
Dragon's other eye missing in the shadowmapping demo

### ISSUE THREAD

**Issue by eero-t** [SaschaWillems/Vulkan#405]
In the shadowmapping demo, the other eye for the dragon is positioned to the teakettle instead of the dragon.  It's visible also in the screenshots:
https://github.com/SaschaWillems/Vulkan/blob/master/screenshots/shadowmapping.png

But from screenshot one doesn't notice that dragon is missing the other eye, only that teakettle has one.

While this may be on purpose(?), I think it would be best to render a scene that looks correct.

**Comment by jherico** [comment]
This is not a bug.  Look at the [vulkan logo](https://www.khronos.org/assets/uploads/events/2015-siggraph-vulkan-tshirt-clean.jpg)

**Comment by eero-t** [comment]
Teapot having eye(s) is fine.  This bug is about the dragon missing one.

**Comment by SaschaWillems** [comment]
It's possible that the eye got lost while optimizing (lowering poly-count) of the meshes. I may update the model at some point in the future when I move all the assets out of the repository into the asset pack.
