### ISSUE TITLE
Possible incorrect pipeline barrier

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#406]
https://github.com/SaschaWillems/Vulkan/blob/603fdb8a161d0b94cffc5e3e59a1c6301d2c1ebb/examples/computeparticles/computeparticles.cpp#L188

In my fork I'm getting a validation failure on the pipeline barrier that's being created here.  

https://github.com/SaschaWillems/Vulkan/blob/603fdb8a161d0b94cffc5e3e59a1c6301d2c1ebb/examples/computeparticles/computeparticles.cpp#L197

The error is 

    vkCmdPipelineBarrier(): pBufferMemBarriers[0].srcAccessMask (0x4) is not supported by srcStageMask (0x8). 

If I change the source stage mask from `VK_PIPELINE_STAGE_VERTEX_SHADER_BIT` to `VK_PIPELINE_STAGE_VERTEX_INPUT_BIT` the validation error goes away.  I had to do a similar conversion to the destination stage mask in the second pipeline barrier in that function.

**Comment by SaschaWillems** [comment]
Thx for noticing. Saw them in a few examples too with latest layers, esp. for the ones that sync between graphics and compute. Will try to fix these.

**Comment by jherico** [comment]
yeah, I'm unclear on sync between compute and graphics.  It seems like even though the source queue family is set to graphics, the compute queue won't accept barriers with graphics pipeline source stages.  I feel like I'm missing something basic.

**Comment by SaschaWillems** [comment]
The (more-or-less) official synchronization examples [over here](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#compute-to-graphics-dependencies) also access graphics stages.

I'll take a closer a look at what the validation layer is actually referring to in my examples and see if this is an application fault or just a wrong validation layer message.

**Comment by jherico** [comment]
Right, but none of those graphics / compute sync examples mention cross queueFramily synchronization.  That doesn't seem to come up until they start talking about transfer barriers.  The validation errors I've seen seem to be saying "You can't put graphics pipeline stages in a barrier going into a compute only queue.  I don't care what your source queue family index is."

**Comment by jherico** [comment]
So I came up with a solution that seems to work and doesn't trigger validation errors.  Instead of making the pipeline barriers part of the compute command buffer, make them part of the graphics command buffer(s).  Although I still needed to switch the VK_PIPELINE_STAGE_VERTEX_SHADER_BIT  to VK_PIPELINE_STAGE_VERTEX_INPUT_BIT for both barriers.

**Comment by cforfang** [comment]
Hi, I haven't looked at the code very closely, but I'm not seeing any semaphores here, which I believe is required to make cross-queue synchronization work correctly. (Pipeline barriers in different queues only is not sufficient.)

If you read the 'Queue Family Ownership Transfer' section of the spec it seems to say that you, in addition to the semaphore, also need one pipeline barriers in each queue; one in the source queue to release ownership of the resource (make it available for the other queue), and one in the destination queue (to make the now-available resource visible in this queue) -- and that for these barriers you do _not_ need to set any destination and source access masks respectively.

Additionally, I believe the above assumes a VK_SHARING_MODE_EXCLUSIVE resource. If VK_SHARING_MODE_CONCURRENT is used instead it seems like no ownership transfer is necessary so a semaphore would be sufficient (this would automatically make all memory available and visible). 

Which sharing mode is used in this case?

**Comment by jherico** [comment]
The existing code in this case actually uses a fence and a CPU side wait, which is not ideal, but should serve the same purpose.  I'm going to see if I can convert my fork to use a semaphore instead.  I'm interested to see what that will do to the performance.

**Comment by cforfang** [comment]
There doesn't seem to be any synchronization between the compute dispatch and the data then being consumed in the graphics queue, though? Seem like unless you have at least two fences here (one following each submit waiting for it to complete) I'm not sure the needed compute -> graphics execution dependency is actually satisfied (since barriers in different queues do not synchronize with each other).

In any case, semaphores is definitely what you want in this case if you care at all about performance.

**Comment by SaschaWillems** [comment]
No second fence, but there's a vkQueueWaitIdle on the graphics pipeline before compute is dispatched. I want to get rid of that one in a future update due to obvious reasons though.

Semaphores make sense, esp. as I'm already using them in some other samples for e.g. syncing offscreen rendering.

I don't have much time to work on the samples currently (far less than I'd like to), but I'll definitely look into synchronization in general.

**Comment by jherico** [comment]
Wouldn't the idle wait only prevent a problem in one direction?  By the time the next frame rolls around there's no guarantee that the compute operations have completed because there's no waitIdle on the compute queue.
