### ISSUE TITLE
Windows 10 Visual Studio 2017 fails to build

### ISSUE THREAD

**Issue by Warezovvv** [SaschaWillems/Vulkan#411]
My steps was simple
1) Downloaded via bash with --recursive
2) Launced download_assets
3) via cmake-gui I have configured and generated .sln
4) via cmake-gui opened solution
After build I have ========== Build: 16 succeeded, 46 failed, 0 up-to-date, 1 skipped ==========
Log is attached.
[log.txt](https://github.com/SaschaWillems/Vulkan/files/1628298/log.txt)

**Comment by SaschaWillems** [comment]
That's exactly my configuration too and it works fine.

Took a quick look at your log:

> 4>D:\Godlike\Vulkan\libs\assimp\assimp.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'

So it looks like you're building for 32 bit. If that's the case you also need to link to a 32 bit version of assimp.

**Comment by Warezovvv** [comment]
Wow wow, why did you closed it?)
If I will compile just one project, I will have this output.
[log.txt](https://github.com/SaschaWillems/Vulkan/files/1629450/log.txt)

**Comment by SaschaWillems** [comment]
Same problem. You're targeting 32 bits while using a 64-bit build of the
assimp library. That's where the missing externals are coming from.


Am 14.01.2018 um 16:11 schrieb Nikita Krupitskas:

**Comment by Warezovvv** [comment]
Yeah. I rechecked README.md and removed prev messages, you have wrote there about Win64. But cmake-gui by default generating 32 bit. I think its better to make assimp as submodule and add library as static one. You will not need even copy paste .dll 
But its IMHO :)
Anyway after compiling with x64 and copy paste .dll, everything works.

**Comment by Warezovvv** [comment]
Also I can do this and open pull request, but everyone will need to recompile it first time. What you think?
