### ISSUE TITLE
Wrong AttributeDescription offsets used

### ISSUE THREAD

**Issue by mtesseracttech** [SaschaWillems/Vulkan#412]
Hello while going through some of the examples, I noticed that on multiple occasions the wrong attributedescription offsets were used.

https://github.com/SaschaWillems/Vulkan/blob/f1f96cfd62f8779026863ba91fa73cf3c5bbb2ac/examples/pbrbasic/pbrbasic.cpp#L335
https://github.com/SaschaWillems/Vulkan/blob/f1f96cfd62f8779026863ba91fa73cf3c5bbb2ac/examples/texturecubemap/texturecubemap.cpp#L431

It took until I went to the examples where you actually used all of the attributes you specify that I understood the ones above were wrong.

My advice is to wrap them in a comfort class that takes in a VertexLayout and generates the VertexInputBinding and the VertexInputAttribute from that. So there is less doubt about how to approach filling in the values.

**Comment by SaschaWillems** [comment]
Thx for noticing. I probably didn't notice as these attributes are never used in a shader. The pbr basic one e.g. points to the UVs and those aren't used anywhere.

**Comment by mtesseracttech** [comment]
Yeah, I noticed. That's why I'd recommend wrapping them in a class to generate the offsets and such info, so it's not really up to the reader to guess where the numbers come from.
