### ISSUE TITLE
clear background is not working in renderheadless example 

### ISSUE THREAD

**Issue by Rezangyal** [SaschaWillems/Vulkan#415]
![headless](https://user-images.githubusercontent.com/15930993/35467383-d185aa90-030d-11e8-9271-446b2cafcdaa.png)

ps.: I change the clearcolor to {1,1,1,1}

platform: 
AMD Radeon HD 7790
windows 8.1, 32 bit, 
vulkan api 1.0.37, 
sdk 1.0.65.1,

**Comment by SaschaWillems** [comment]
Working fine for me, even with white as clear color. 

Any validation layer messages?

**Comment by Rezangyal** [comment]
no messages
but I found some new problem:

- no vkDestroyDevice in destructor
- no vkDestroyInstance in destructor
- vkDestroyDebugReportCallback called from constructor instead of destructor

after I fix this things
I got some message:

[VALIDATION]: ObjectTracker - OBJ ERROR : For device 0x41ac1c0, ShaderModule object 0x17 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
[VALIDATION]: ObjectTracker - OBJ ERROR : For device 0x41ac1c0, ShaderModule object 0x18 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
[VALIDATION]: ObjectTracker - OBJ ERROR : For device 0x41ac1c0, PipelineCache object 0x16 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)

so vkDestroyShaderModule and vkDestroyPipelineCache also missing.
but no other problem reported

**Comment by Rezangyal** [comment]
now I update my code.
this is the original picture:

![headless](https://user-images.githubusercontent.com/15930993/35474914-6c6eb92a-0395-11e8-872a-415fd8eb4b58.png)

this picture also bad, but hard to spot the small triangles at edge of big one, because dark blue is too dark (tip: zoom is your friend) but the color is not an important factor.

maybe it's same problem as this:
https://stackoverflow.com/questions/35995198/vulkan-failing-to-clear-depth

**Comment by Rezangyal** [comment]
I found some other minor problem:
- "commandBuffer" declared as member variable but not used, because local "commandBuffer" is used
- line 241: the comment is bad, expected "Get a **graphics** queue"
- line 585: same problem
- line 686, comment: in this example no "swapchain"

**Comment by Rezangyal** [comment]
I found a "bugfix": if I add VK_IMAGE_USAGE_STORAGE_BIT to colorAttachment.image in line 355 the clearcolor will be working.
but I think this is not the real solution :-(

**Comment by Rezangyal** [comment]
... or if change the tiling of colorAttachment from VK_IMAGE_TILING_OPTIMAL to VK_IMAGE_TILING_LINEAR also fix the problem. 
I don't know why, VK_IMAGE_TILING_OPTIMAL and VK_IMAGE_TILING_LINEAR has same feature list if format == VK_FORMAT_R8G8B8A8_UNORM

(but tiling of depthAttachment must be VK_IMAGE_TILING_OPTIMAL in my hardware)

**Comment by SaschaWillems** [comment]
Those changes don't actually make sense. The example works fine on all platforms I tested (NV and AMD on desktop, NV, ARM and Mali on android and Intel on Linus) so this may be a driver bug.

**Comment by SaschaWillems** [comment]
Ont thing you could test is to set the storeOp of the depthAttachment to ```VK_ATTACHMENT_STORE_OP_STORE``` instead of DONT_CARE.

**Comment by cforfang** [comment]
I noticed this code:

```
			// Transition color attachment to transfer source
			vks::tools::insertImageMemoryBarrier(
				copyCmd,
				colorAttachment.image,
				0,
				VK_ACCESS_TRANSFER_READ_BIT,
				VK_IMAGE_LAYOUT_UNDEFINED,
				VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
				VK_PIPELINE_STAGE_TRANSFER_BIT,
				VK_PIPELINE_STAGE_TRANSFER_BIT,
				VkImageSubresourceRange{ VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 });
```

Am I reading this wrong, or is this doing transition from `VK_IMAGE_LAYOUT_UNDEFINED` to `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL`, which could be a potentially content-destroying operation?

Does changing `VK_IMAGE_LAYOUT_UNDEFINED` to `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` (`colorAttachment.image`'s actual layout) fix the issue?

**Comment by Rezangyal** [comment]
VK_ATTACHMENT_STORE_OP_STORE has no effect

**Comment by Rezangyal** [comment]
I think VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is something different, its not work in this case:

[VALIDATION]: DS - vkCmdPipelineBarrier(): Image barrier 0x00A2D78C newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is not compatible with image 0x1b usage flags 0x2. The spec valid usage text states 'If either oldLayout or newLayout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL then image must have been created with VK_IMAGE_USAGE_SAMPLED_BIT or VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT set' (https://
www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01211
)

**Comment by cforfang** [comment]
Well, the image is transferred to `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` at the end of the renderpass: ```attchmentDescriptions[0].finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;``` -- so that's the layout it's in.

I guess the easy solution is to change `finalLayout` to `VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL` or `VK_IMAGE_LAYOUT_GENERAL` and remove the transition.

An UNDEFINED -> TRANSFER_SRC transition will definitely make the image contents undefined here, so I'm not necessarily surprising you get artifacts.

**Comment by SaschaWillems** [comment]
> An UNDEFINED -> TRANSFER_SRC transition will definitely make the image contents undefined here, so I'm not necessarily surprised you get artifacts.

That may be cause of the problem. Transitioning from undefined to anything else there is no guarantee that image contents are preserved. So as @cforfang noted you may try another layout there.

This is probably a copy and paste error from the first barrier and working fine on all devices I tested I didn't notice. Will take a look at that.

**Comment by cforfang** [comment]
> [VALIDATION]: DS - vkCmdPipelineBarrier(): Image barrier 0x00A2D78C newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is not compatible with image 0x1b usage flags 0x2

This says `newLayout` is `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL`, but the idea was to change `oldLayout`. Did you modify the correct line (i.e. change UNDEFINED to SHADER_READ_ONLY)?

**Comment by cforfang** [comment]
I get tons of artifacts with the original code on my Intel laptop. I'll see if the above works there.

**Comment by Rezangyal** [comment]
cforfang:

oldImageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is working!
but in this case i must create the image with VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT or i got a wrning:

[VALIDATION]: DS - vkCmdPipelineBarrier(): Image barrier 0x00BCDDB4 oldLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL is not compatible with image 0xc usage flags 0x11. The spec valid usage text states 'If either oldLayout or newLayout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL then image must have been created with VK_IMAGE_USAGE_SAMPLED_BIT or VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT set' (https://
www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01211
)

**Comment by Rezangyal** [comment]
finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL + imageBarrier(VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL -> VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL) is also a working solution.

but think the 
finalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL; 
and no imageBarrier is the best solution. 
its working and in this case extra usage flag is not neccessary.

**Comment by SaschaWillems** [comment]
Please check again. I've merged the PR from @cforfang after testing on different platforms.

**Comment by Rezangyal** [comment]
fixed, thx
