### ISSUE TITLE
Multisample example: GUI should be rendered after MS resolve, not before

### ISSUE THREAD

**Issue by tksuoran** [SaschaWillems/Vulkan#421]
The simple GUI in top left corner is broken in multisample example. It looks like the GUI is also resolved down. Mouseover highlights happen in wrong place.

GUI should be rendered after multisample resolve, not before.

**Comment by SaschaWillems** [comment]
Thx for letting me know. This may be caused by a recent change from a PR that fixed a MSAA crash on certain devices. Will take a look at this.

**Comment by SaschaWillems** [comment]
With the changes from PR #410 the UI should no longer be resolved down, and I can't reproduce the described behavior (mouse overs work fine).

If the problem still persists, can you please add on what hardware, os and driver?
