### ISSUE TITLE
Request for samples using new conservative raster and sample locations exts..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/Vulkan#422]
Hi,
maybe you are working under NDA on some Vulkan Next (2.0?) samples that should launch by GDC18..
if thats not the case, anyway would be good to have simples samples using the "new" conservative raster and sample locations Vulkan exts..
for example would be good to test conser. raster sample with VulkanOnD3D12 which recently added support for it:
https://github.com/Chabloom/VulkanOnD3D12/commit/0381b7c820c54efd8a50794a89e661bf97929c3d

**Comment by SaschaWillems** [comment]
Already played around with conservative rasterization and a sample for it is on my to-do list. No ETA though.

**Comment by SaschaWillems** [comment]
I have added a new example using conservative rasterization. It's pretty basic but should be fine as a starting point. I may add a few more options to it in a future update, e.g. depending on what's supported by a device in terms of conservative rasterization.

**Comment by oscarbg** [comment]
Hi,
thanks.. for me the sample is nice enough..
IMHO in future I would prefer more samples showing new extensions usage (now that Vulkan # extensions shipping on drivers have exploded recently from a few to 30+ or more even on Qualcomm devices for ex.)
of course not all but a few key "select ones".. the selection is of course up to you and also in case you are really interested.. of course your samples pack is very good as it is already.. only if you have interest and time to do it..
let me also also ask about for features that I hope come this month at least with NV GDC driver..
for example:
1)I expect D3D12 ROV (aka fragment shader ordering, PixelSync,etc..) comes finally to Vulkan world.
2) HDR on PCs (at least on Windows): extension seems already on Shield TV from your reports site..
perhaps you can avoid the trouble if NV releases some Vulkan sample ..
3)Seems new KHR_subgroups cross vendor with new "wave ops" is coming hopefully providing at least the same wave ops  exposed by SM6.x and that as of now were only available as VK AMD exts..

and finally let me say about some motivation for it:
do you know https://github.com/msiglreith/rostkatze already?
provides a Vulkan on D3D12 wrapper, and guy seems is using your samples to test correctly of his wrapper..
many already pass..
in fact by using it you conservative raster sample running on it it failed of course, but for reasons not related to conser. raster. per see so I modifiged triangle basic demo which works correctly with rostkatze and added mininal conser. raster. support to this sample (removed code to checking conser. raster. caps which requires extension also not present on this wrapper)..  and with original triangle playing well I made improvements to rostkatze and now locally have it with conservate raster support (i.e. passing overestimate attribute as D3D12 rasterizer option..
hope this motivates to write new simple samples exposing new extensions to work around improving rostkatze in case D3D12 allows it..
in fact plan to test adding HDR and ROV support kostkatze..

**Comment by oscarbg** [comment]
I just posted patches for rostkatze conserv. raster support here:
https://github.com/msiglreith/rostkatze/issues/5

**Comment by SaschaWillems** [comment]
> IMHO in future I would prefer more samples showing new extensions usage (now that Vulkan # extensions shipping on drivers have exploded recently from a few to 30+ or more even on Qualcomm devices for ex.)
of course not all but a few key "select ones".. the selection is of course up to you and also in case you are really interested.. of course your samples pack is very good as it is already.. only if you have interest and time to do it..

Doing more samples to demonstrate extensions is something I'd love to do, though my spare time is limited giving me only a few weeks for coding on Vulkan related stuff a week. So yes, there will be more examples targeting certain extensions in the future (right now I'm playing around with 16-bit storage, which may be the next sample), though I don't have an actual list of extensions that I'll do samples for now. Maybe I should start thinking about doing Vulkan full-time ;)

**Comment by oscarbg** [comment]
understandable you have limited time..
please don't take this request too seriously.. after all I'm mosty interested in maybe up to 5 o 6 new samples showing new key features.. really Vulkan doesn't evolve so fast.. past GDC and possible new GPUs from Nvidia with new graphical features in a few months time I don't expect many more from this year big enough in Vulkan world..
also rostkatze started interested to see samples of new features to play with when trying to add support to this wrapper too..

**Comment by oscarbg** [comment]
Hi,
just reviving old thread..
just pointing Vulkan 1.1.110 got released with VK_EXT_fragment_shader_interlock support and associated SPIR-V ext.: SPV_EXT_fragment_shader_interlock..
I expected ROV functionality to come earlier but anyway here it is and we have 0-day support from NV dev drivers and even Mesa Anvil patches for Intel: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/989
no hurry but are you interested in doing a simple sample (maybe some OIT example? don't know.. maybe too complex for a sample)..
thanks..

**Comment by SaschaWillems** [comment]
Closing this for now. If you still need a specific example, feel free to open an issue at the [Khronos Vulkan Samples Repository](https://github.com/KhronosGroup/Vulkan-Samples/issues).
