### ISSUE TITLE
xcode build fails with llvm error

### ISSUE THREAD

**Issue by kulicuu** [SaschaWillems/Vulkan#423]
MacOS/xcode
High Sierra 
Xcode 9.2

First it failed with a complaint about not finding a Prefix.pch file.  I followed a Stackoverflow answer to make a boilerplate one, then it fails saying can't find `<...>/gears/vulkangear.cpp`.

**Comment by kulicuu** [comment]
Nevermind, I see I'm missing a step in the instructions.

**Comment by SaschaWillems** [comment]
I don't have a MacOS device, so I can't check to see what causes this error. The MacOS/iOS additions were made by @billhollings (See [this PR](https://github.com/SaschaWillems/Vulkan/pull/342)). It's possible that changes I made since then broke the MacOS build.

**Comment by kulicuu** [comment]
I see, thank you for the update.  I'll take a look at that PR, and if I find a fix will contribute it.  I'm very new to MacOS, Xcode development, etc.  Next,  I'll be starting from scratch and adding components one at a time next, trying to reproduce the project structure piece by piece.  Hopefully, I can contribute a fix soon.

**Comment by yanchith** [comment]
@kulicuu Did you find anything? I have the exact same problem. Going to look into it as well.

**Comment by SaschaWillems** [comment]
I can imagine that this was caused by moving all examples into the examples sub folder some time go. The ```examples.h``` header contains relative paths that no longer exist due to this move.

So can you try replacing these in that header and check if it works?

E.g. replace 

    #ifdef MVK_pipelines
    #	include "../pipelines/pipelines.cpp"
    #endif

with 

    #ifdef MVK_pipelines
    #	include "../examples/pipelines/pipelines.cpp"
    #endif

**Comment by yanchith** [comment]
Yay! That worked! I am getting more linking errors though:

```
Undefined symbols for architecture x86_64:
  "vks::UIOverlay::resize(unsigned int, unsigned int, std::__1::vector<VkFramebuffer_T*, std::__1::allocator<VkFramebuffer_T*> >)", referenced from:
      VulkanExampleBase::windowResize() in vulkanexamplebase.o
  "vks::UIOverlay::update()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "vks::UIOverlay::UIOverlay(vks::UIOverlayCreateInfo)", referenced from:
      VulkanExampleBase::prepare() in vulkanexamplebase.o
  "vks::UIOverlay::~UIOverlay()", referenced from:
      VulkanExampleBase::~VulkanExampleBase() in vulkanexamplebase.o
  "ImGui::PopStyleVar(int)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::PopItemWidth()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::PushStyleVar(int, float)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::PushItemWidth(float)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::TextUnformatted(char const*, char const*)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::SetNextWindowPos(ImVec2 const&, int)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::SetNextWindowSize(ImVec2 const&, int)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::End()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::Text(char const*, ...)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::Begin(char const*, bool*, int)", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::GetIO()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
      VulkanExampleBase::handleMouseMove(int, int) in vulkanexamplebase.o
  "ImGui::Render()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
  "ImGui::NewFrame()", referenced from:
      VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am kind of new to both c++ and xcode, so help would be appreciated. Otherwise, I will try to investigate on my own. Keep you updated.

**Comment by yanchith** [comment]
Ok, I managed to run the basic example!

Unfortunately, I had to comment out the overlay functionality from `vulkanexamplebase.cpp`. I will get back to it and try to make it work.

**Comment by yanchith** [comment]
I got it to work properly!

Basically, it was all about referencing newly added files properly from xcode. Would you like me to contribute the fix?

Also: since it's a pain to keep the macos version up to date, maybe we should consider tagging it and linking to the tag in readme, so newcomers can easily find it. Then, once in a while we can update it.

**Comment by kulicuu** [comment]
Wow thank you both !

**Comment by JavinYang** [comment]
> 好极了！那很有效！我遇到了更多的链接错误：
> 
> ```
> Undefined symbols for architecture x86_64:
>   "vks::UIOverlay::resize(unsigned int, unsigned int, std::__1::vector<VkFramebuffer_T*, std::__1::allocator<VkFramebuffer_T*> >)", referenced from:
>       VulkanExampleBase::windowResize() in vulkanexamplebase.o
>   "vks::UIOverlay::update()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "vks::UIOverlay::UIOverlay(vks::UIOverlayCreateInfo)", referenced from:
>       VulkanExampleBase::prepare() in vulkanexamplebase.o
>   "vks::UIOverlay::~UIOverlay()", referenced from:
>       VulkanExampleBase::~VulkanExampleBase() in vulkanexamplebase.o
>   "ImGui::PopStyleVar(int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PopItemWidth()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushStyleVar(int, float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushItemWidth(float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::TextUnformatted(char const*, char const*)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowPos(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowSize(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::End()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Text(char const*, ...)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Begin(char const*, bool*, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::GetIO()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>       VulkanExampleBase::handleMouseMove(int, int) in vulkanexamplebase.o
>   "ImGui::Render()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::NewFrame()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> 我对c ++和xcode都不熟悉，所以请帮助。否则，我会尝试自己调查。让你更新。



> Yay! That worked! I am getting more linking errors though:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "vks::UIOverlay::resize(unsigned int, unsigned int, std::__1::vector<VkFramebuffer_T*, std::__1::allocator<VkFramebuffer_T*> >)", referenced from:
>       VulkanExampleBase::windowResize() in vulkanexamplebase.o
>   "vks::UIOverlay::update()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "vks::UIOverlay::UIOverlay(vks::UIOverlayCreateInfo)", referenced from:
>       VulkanExampleBase::prepare() in vulkanexamplebase.o
>   "vks::UIOverlay::~UIOverlay()", referenced from:
>       VulkanExampleBase::~VulkanExampleBase() in vulkanexamplebase.o
>   "ImGui::PopStyleVar(int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PopItemWidth()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushStyleVar(int, float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushItemWidth(float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::TextUnformatted(char const*, char const*)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowPos(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowSize(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::End()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Text(char const*, ...)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Begin(char const*, bool*, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::GetIO()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>       VulkanExampleBase::handleMouseMove(int, int) in vulkanexamplebase.o
>   "ImGui::Render()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::NewFrame()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> I am kind of new to both c++ and xcode, so help would be appreciated. Otherwise, I will try to investigate on my own. Keep you updated.

How to solve this error?

**Comment by JavinYang** [comment]
> Yay! That worked! I am getting more linking errors though:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "vks::UIOverlay::resize(unsigned int, unsigned int, std::__1::vector<VkFramebuffer_T*, std::__1::allocator<VkFramebuffer_T*> >)", referenced from:
>       VulkanExampleBase::windowResize() in vulkanexamplebase.o
>   "vks::UIOverlay::update()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "vks::UIOverlay::UIOverlay(vks::UIOverlayCreateInfo)", referenced from:
>       VulkanExampleBase::prepare() in vulkanexamplebase.o
>   "vks::UIOverlay::~UIOverlay()", referenced from:
>       VulkanExampleBase::~VulkanExampleBase() in vulkanexamplebase.o
>   "ImGui::PopStyleVar(int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PopItemWidth()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushStyleVar(int, float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::PushItemWidth(float)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::TextUnformatted(char const*, char const*)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowPos(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::SetNextWindowSize(ImVec2 const&, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::End()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Text(char const*, ...)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::Begin(char const*, bool*, int)", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::GetIO()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>       VulkanExampleBase::handleMouseMove(int, int) in vulkanexamplebase.o
>   "ImGui::Render()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
>   "ImGui::NewFrame()", referenced from:
>       VulkanExampleBase::updateOverlay() in vulkanexamplebase.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> I am kind of new to both c++ and xcode, so help would be appreciated. Otherwise, I will try to investigate on my own. Keep you updated.

How to solve this error?
