### ISSUE TITLE
parallax: non-uniform texture fetches

### ISSUE THREAD

**Issue by msiglreith** [SaschaWillems/Vulkan#425]
The parallax shader uses samples the normal map in a non-uniform branch (https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/parallax/parallax.frag#L73), which procudes invalid SPIR-V up to my understanding: SPIR-V Spec, 2.20 Code Motion:

> Texturing instructions in the Fragment Execution Model that rely on an implicit derivative cannot be moved into control flow that is not known to be uniform control flow within each derivative group.

**Comment by cforfang** [comment]
Assuming the texture doesn't have mipmaps, which I believe is the case here, can the texturing instruction be said to "rely on an implicit derivative"? If not, it _seems_ OK, but I don't actually know how SPIR-V works here...

I suppose a fix, if needed, would be to use ``textureLOD()`` with lod=0 instead?

**Comment by cforfang** [comment]
Also, taking a second look, is that actually a non-uniform branch? All the control flow seems to be based on values in UBOs, so should be draw-call uniform right?

**Comment by msiglreith** [comment]
@cforfang The break condition depends on the read texture at non-uniform texture coordinates. Therefore it appears to me that the control flow is non-uniform for the executed primitive group.

**Comment by cforfang** [comment]
Ah, right, yes -- I completely missed that :) I still don't quite get the wording in the SPIR-V spec when it says "cannot be moved". Who's moving anything? I assumed the spec is meant to describe what must be true in valid SPIR-V, but this almost sounds like a directive to compilers.

By contrast, if it said something like "Texturing instructions in the Fragment Execution Model that rely on an implicit derivative **cannot be placed in** control flow that is not known to be uniform control flow within each derivative group." that seems pretty clear, but as-written it almost sounds more like it's meant to tell compilers it should not move texturing-instructions around without considering uniform control flow during compilation.

In any case, to be 100% sure this is legal I guess {{textureLod()}} is the way to go.

**Comment by msiglreith** [comment]
Agree, opened an issue on the official repository: https://github.com/KhronosGroup/SPIRV-Headers/issues/58

**Comment by cforfang** [comment]
Ah, sorry -- didn't see your edit that you were going to do it :) I agree, please check if #431 looks OK.

**Comment by msiglreith** [comment]
Fixed in https://github.com/SaschaWillems/Vulkan/pull/431
