### ISSUE TITLE
Problem compiling with VS2017 (type.hpp, format.hpp, format.inl)

### ISSUE THREAD

**Issue by CBGonzalez** [SaschaWillems/Vulkan#429]
Hi,

Just downladed your vulkan examples and tried to build using VS2017 (x64, tried both debug and release). I get a ton of errors which I cannot seem to explain (below a short example) regarding type.hpp,  format.hpp and format.inl.

I´m assuming some quirk on my part, any clue of what could be wrong?

Thanks for any help.

Cristian.

A tiny part of the log:
'1>------ Build started: Project: computenbody, Configuration: Release x64 ------
2>------ Build started: Project: bloom, Configuration: Release x64 ------
3>------ Build started: Project: computecloth, Configuration: Release x64 ------
4>------ Build started: Project: deferredshadows, Configuration: Release x64 ------
3>computecloth.cpp
2>bloom.cpp
3>c:\users\cristian\documents\visual studio 2017\projects\vulkan-examples-master\external\gli\gli\type.hpp(42): error C2061: syntax error: identifier 'qualifier'
4>deferredshadows.cpp
2>c:\users\cristian\documents\visual studio 2017\projects\vulkan-examples-master\external\gli\gli\type.hpp(42): error C2061: syntax error: identifier 'qualifier'
2>c:\users\cristian\documents\visual studio 2017\projects\vulkan-examples-master\external\gli\gli\type.hpp(43): error C2988: unrecognizable template declaration/definition
2>c:\users\cristian\documents\visual studio 2017\projects\vulkan-examples-master\external\gli\gli\type.hpp(43): error C2143: syntax error: missing ';' before '<''

**Comment by SaschaWillems** [comment]
VS 2017 works fine for me, these are all errors related to the gli imaging library used. Did you generate fresh build files?

**Comment by CBGonzalez** [comment]
Yes, used cmake  -G "Visual Studio 15 2017 Win64"  (changed to vs 2017 as I don´t have 2015). WIll keep trying to understand this....

By the way, cmake runs without a hitch

Thanks for the interest.

Cristian

**Comment by SaschaWillems** [comment]
Did you init the submodules as described in the readme? If not, this may be a duplicate of #376.

**Comment by CBGonzalez** [comment]
I´m shamefaced, had missed that completely and went to download as zip instead of using git to clone...

Thank you very much, it´s compiling perfectly now!

Cristian
