### ISSUE TITLE
Copy buffer region size

### ISSUE THREAD

**Issue by msiglreith** [SaschaWillems/Vulkan#430]
https://github.com/SaschaWillems/Vulkan/blob/master/base/VulkanDevice.hpp#L445
The size must be smaller than or equal to both src and dst buffer. The current implementation sets it to the src buffer, resulting in possible violations of the specification.

**Comment by SaschaWillems** [comment]
Can you elaborate? When would this violate the specs? Is this something special to your D3D12 wrapper? I haven't stumbled upon a situation where the dest buffer created by my examples was smaller than the source buffer.

**Comment by msiglreith** [comment]
Yes, it's specific to my wrapper due to the implementations of buffer <-> image copies. As far as I can see due to D3D12 restrictions I need to align the size of buffers with TRANSFER usage. Currently, only did it for SRC buffers but probably will also need if for DST usage (haven't investigated the image -> buffer route very much..)
I agree that I probably will inluckly be hit for 'native' Vulkan drivers, therefore I can work around this.
The specific issue is that there is no guarentee of the returned buffer sizes by Vulkan afaik. Therefore the sizes don't need to match. The generated region therefore could be out-of-range for one buffer.

**Comment by msiglreith** [comment]
Probably not required for the samples and I made it symmetric (SRC and DST alignment) therefore no demand from my side.
I'm closing it, thanks again!
