### ISSUE TITLE
Debug build in Visual Studio 2017 generates 65,822 warnings

### ISSUE THREAD

**Issue by DiligentGraphics** [SaschaWillems/Vulkan#436]
If you follow the steps to clone the repo, but use Visual Studio 2017 Win64 generator, the build produces lots of warnings.

**Comment by SaschaWillems** [comment]
The majority of warnings is caused by external dependencies likt glm, gli so that's nothing I could fix. If you don't want to see all warnings, switch to a release build or disable the all warning level in [CMakeLists.txt](https://github.com/SaschaWillems/Vulkan/blob/master/CMakeLists.txt#L78).
