### ISSUE TITLE
Should be VK_FRONT_FACE_CLOCKWISE

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#443]
https://github.com/SaschaWillems/Vulkan/blob/8dcaca2ad583404d2007cd97138fa96d201e7d4a/examples/dynamicuniformbuffer/dynamicuniformbuffer.cpp#L344

The cubes look weird because they're rendering the backfaces

**Comment by SaschaWillems** [comment]
The example does not make use of culling, so the front facing orientation shouldn't matter. Can you provide a screenshot that demonstrates the problem? Looks fine for me on my GTX 980 no matter what front facing orientation is set.

**Comment by jherico** [comment]
Sorry, when I ported to my pipeline builder I missed that it was setting the cull mode to none.  My pipeline builder defaults to culling back faces, so I saw the cubes inverted.
