### ISSUE TITLE
vkWaitForFences() returns VK_ERROR_DEVICE_LOST on Mali G-71/G-72

### ISSUE THREAD

**Issue by zombiedeveloper** [SaschaWillems/Vulkan#445]
While running compute shaders on Mali G-71/G-72, it returns VK_ERROR_DEVICE_LOST for vkWaitForFences()

**Comment by SaschaWillems** [comment]
What example? Do you get any validation messages? What device is this?  

I noticed that a few taxing examples crash on my low-spec Adreno 505 too, but that's a driver bug I can't do anyhting about.

**Comment by zombiedeveloper** [comment]
I took a minimal compute vulkan example. 
https://github.com/Erkaman/vulkan_minimal_compute
No validation messages seen as VK_LAYER_LUNARG_standard_validation is not supported. 
The device I am testing on is Samsung S8 and Samsung S9. The same compute vulkan example is running on Pixel devices containing Adreno 530/540.

**Comment by zombiedeveloper** [comment]
Also, I get these message logs
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (1/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (2/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (3/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (4/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (5/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (6/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (7/7) :  0.0.0/0

**Comment by zombiedeveloper** [comment]
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (1/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (2/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (3/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (4/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (5/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (6/7) :  0.0.0/0
03-28 14:48:53.285 22546-22625/com.example.native_activity D/vulkan: vulkan instance layer version (7/7) :  0.0.0/0

**Comment by zombiedeveloper** [comment]
I get these messages also
vulkan instance layer version (1/7) :  0.0.0/0
vulkan instance layer version (2/7) :  0.0.0/0
vulkan instance layer version (3/7) :  0.0.0/0
vulkan instance layer version (4/7) :  0.0.0/0
vulkan instance layer version (5/7) :  0.0.0/0
vulkan instance layer version (6/7) :  0.0.0/0
vulkan instance layer version (7/7) :  0.0.0/0

**Comment by SaschaWillems** [comment]
> I took a minimal compute vulkan example.
https://github.com/Erkaman/vulkan_minimal_compute

That's not my example, or is this happening with my examples too? If so, what example? I do have S7s and S8s from Samsung and my compute stuff works just fine on them.

**Comment by cforfang** [comment]
If it only happens with that example, have you tried lowering the resolution? 3200x2400 might be a bit too much to handle for a mobile GPU, and there's usually a watchdog timer that will kill GPU-jobs -- likely causing a `DEVICE_LOST` -- if something takes too long. (When changing the resolution remember to change both main.cpp and shader.comp and also recompile the shader.)

**Comment by SaschaWillems** [comment]
Closing as this is not related to my samples.
