### ISSUE TITLE
Using glm::perspective with z range [-1..+1] when Vulkan uses [0..+1]

### ISSUE THREAD

**Issue by httpdigest** [SaschaWillems/Vulkan#45]
I am just curious how glm's perspective method can work with Vulkan in your examples.

I mean, as long as your model stays within 0..1 of the transformed NDC depth range, everything should be okay, but as soon as NDC z transforms to anything within [-1..0] it will not be visible anymore in Vulkan, where it still would with OpenGL.

Currently I don't see any option in glm to switch to using Direct3D's/Vulkan's compatible clip space/NDC space.

See the section [23.2. Primitive Clipping](https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vertexpostproc-clipping)

**Comment by SaschaWillems** [comment]
There is a new define in GLM for this called [GLM_DEPTH_ZERO_TO_ONE](https://github.com/g-truc/glm/blob/78f686b4be6c623df829db58b974bf8d79461987/glm/gtc/matrix_transform.inl#L276).

I'll be updating GLM and add this to my examples.

**Comment by SaschaWillems** [comment]
fyi : as of glm 0.9.8 this define is called GLM_FORCE_DEPTH_ZERO_TO_ONE

**Comment by httpdigest** [comment]
Thanks for the info! Closing this now.
