### ISSUE TITLE
Possible synchronization issues in deferred multisampling example

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#451]
https://github.com/SaschaWillems/Vulkan/blob/7b28549bef9e2a65dd59fcc7286c2667fe43e093/examples/deferredmultisampling/deferredmultisampling.cpp#L459

This may be specific to the code in my fork, but I'm not certain.  There are two synchronization issues I'm encountering related to the offscreen command buffer.  First, unless I add VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT to the offscreen command buffer, I get validation errors due to the buffer being concurrently queued multiple times as frames are queued up.  

Second, when triggering the rebuild of the offscreen command buffer by clicking the sample rate shading checkbox in the UI, I get a warning that I'm writing a command buffer that's currently in use.  

The latter issue I've solved by using my context `trash` functionality, which places resources that are no longer needed but might still be in use into a container in the context object... these items are then migrated to another container each frame, protected by the frame fence, and then the `recycle` function actually reclaims the items for each fence that's signaled.  Alternatively, you could just add a queue/device waitIdle function to the `buildDeferredCommandBuffer` function.

**Comment by SaschaWillems** [comment]
> This may be specific to the code in my fork

I think that's the reason. I still use a ```vkQueueWaitIdle``` after submitting a frame in the example base class that avoids those synchronization issues.

Been wanting to get rid of that ```vkQueueWaitIdle``` for some time now, but it's not a small task and in the local branch I've been working on this I do get the exact same behavior as you get.
