### ISSUE TITLE
Uniform way to navigate in Android

### ISSUE THREAD

**Issue by sjfricke** [SaschaWillems/Vulkan#459]
Currently, there is no consistent way of moving around a scene in Android.

The issue stems from that every example has a different `viewChanged()` call and only the ones that use the [Camera class](https://github.com/SaschaWillems/Vulkan/blob/master/base/camera.hpp) work from the current Android movement.

I am willing to help uniform this, but not sure on the approach since it seems the overall control for the camera in the examples in pretty fragmented.

**Comment by SaschaWillems** [comment]
Yes, I'm aware of this and I'm not happy with it either. I'll be updating all examples to use the camera class, but I don't have any time frame for this.
