### ISSUE TITLE
It possible use Vulkan without swap chain? 

### ISSUE THREAD

**Issue by acterhd** [SaschaWillems/Vulkan#46]
Hello. I have question. It possible use Vulkan without swap chain? Or swap chain are required? 
I see that swapchain is extension of Vulkan.

**Comment by SaschaWillems** [comment]
If you do headless (for compute only), then yes. If you want to display something, then now.

**Comment by acterhd** [comment]
Where I can found simple example of swap chain?

**Comment by SaschaWillems** [comment]
The tri.c in the demos folder of the LunarG example is a single file example that also shows the usage of the swap chain. Afaik it's the simplest example available.

**Comment by acterhd** [comment]
How to in C++ make struct?

const VkSwapchainCreateInfoKHR swapchain = {
			.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,
			.pNext = NULL,
			.surface = demo->surface,
			.minImageCount = desiredNumberOfSwapchainImages,
			.imageFormat = demo->format,
			.imageColorSpace = demo->color_space,
			.imageExtent =
		{
			.width = swapchainExtent.width,.height = swapchainExtent.height,
		},
			.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
			.preTransform = preTransform,
			.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR,
			.imageArrayLayers = 1,
			.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE,
			.queueFamilyIndexCount = 0,
			.pQueueFamilyIndices = NULL,
			.presentMode = swapchainPresentMode,
			.oldSwapchain = oldSwapchain,
			.clipped = true,
		};

**Comment by acterhd** [comment]
I want samples with GLFW and C++ wrapper. Sad that in this world does not know both libs, except me.
