### ISSUE TITLE
Crashing option parsing, no options help

### ISSUE THREAD

**Issue by eero-t** [SaschaWillems/Vulkan#468]
Try to get options help:
```
/bloom --help
```
(no output)

Maybe help is with short option?
```
$ ./bloom -h
Segmentation fault (core dumped)
```

What about other options?
```
$ ./bloom -w
Segmentation fault (core dumped)
$ ./bloom -width
Segmentation fault (core dumped)
$ ./bloom -height
Segmentation fault (core dumped)
$ ./bloom -gpu
Segmentation fault (core dumped)
```

Some of the options do have argument validation:
```
$ ./bloom --benchfilename --benchwarmup --benchruntime foo
Filename for benchmark results must not start with a hyphen!
Warmup time for benchmark mode must be specified as a number!
Benchmark run duration must be specified as a number!
```

But those fail to complain about missing argument:
```
$ ./bloom --benchfilename
$ ./bloom --benchwarmup
$ ./bloom --benchruntime
```

And there's no checking for invalid options:
```
$ ./bloom -argh --hmph
```

(Should output the help instead.)

**Comment by eero-t** [comment]
You could e.g. have something like this at start of arg parsing loop in VulkanExampleBase::VulkanExampleBase():
`bool havearg = (i+1 < args.size());`

And  use that to check whether extra arg is present.  If it's not present, or doesn't match expected format (e.g. number), output help.

**Comment by SaschaWillems** [comment]
I have reworked command line argument handling, which is now handled by a separate class with more error checking and help message output. While it does not implement everything noted in this issue, it's better than before and sufficient for the sample use case.
