### ISSUE TITLE
Incorrect/broken asset path handling

### ISSUE THREAD

**Issue by eero-t** [SaschaWillems/Vulkan#470]
This is split from #277

This is what's in ./base/vulkanexamplebase.cpp:
```
const std::string VulkanExampleBase::getAssetPath()
{
#if defined(VK_USE_PLATFORM_ANDROID_KHR)
        return "";
#elif defined(VK_EXAMPLE_DATA_DIR)
        return VK_EXAMPLE_DATA_DIR;
#else
        return "./../data/";
#endif
}
```
Where VK_EXAMPLE_DATA_DIR is a absolute path.

The demos themselves, use a mix of:
```
load...(getAssetPath() + "string"...
load...(ASSET_PATH "string"...
```

Where ASSET_PATH is relative path.

I.e. depending on demo and OS, some demos load their assets with relative paths and some load them with absolute paths.  Which is broken.

A consistent (and IMHO correct) way to do it would be:
* Use always relative path
* Install data file where binaries expect them to be

That way the binaries are "portable": https://en.wikipedia.org/wiki/Portable_application

I.e. in ./base/vulkanexamplebase.cpp:
```
const std::string VulkanExampleBase::getAssetPath()
{
        return "./../data/";
}
```

And either replace getAssetPath() calls with ASSET_PATH, or the other way round.

In build target, there could be just a symlink from build directory to the source data directory so that the built binaries can directly be run from where they are.  Install target would need to copy/hardlink the data files to same place where binaries are installed.

**Comment by SaschaWillems** [comment]
I have slightly reworked this and centralized the code for asset path handling, so it's more consistent now.
