### ISSUE TITLE
03 - Descriptor sets renders nothing

### ISSUE THREAD

**Issue by elect86** [SaschaWillems/Vulkan#473]
As titled.

Tried to turn on validation, I get nothing on console

Amd 18.4.1
Win 10 x64

**Comment by SaschaWillems** [comment]
Works fine for me on my desktop (NVIDIA) and mobile (Mali, Adreno). Can you try changing the clear color to see if objects are rendered at all?

**Comment by elect86** [comment]
Also 3D textures appears to be broken

This one tested on Nvidia, win 7 x64

**Comment by elect86** [comment]
Sascha, one other thing. I'm working on a porting of your tutorials to Kotlin, may I add a link at the bottom of your `readme.md`?
