### ISSUE TITLE
benchmark results are not saved 

### ISSUE THREAD

**Issue by MuraliSridhar** [SaschaWillems/Vulkan#475]
Benchmark results are not saved

**Comment by SaschaWillems** [comment]
Please be more specific and add at least a minimal amount of details on what you tired to do (e.g. arguments) and what did not work.

**Comment by MuraliSridhar** [comment]
Ok, when i run benchmark-all.py, csv files are not saved in bin/benchmark/ dir ?

**Comment by SaschaWillems** [comment]
The benchmar-all.py script needs to be updated to reflect recent parameter handling change. So if you want to bench, run the samples manually with the correct parameters.
