### ISSUE TITLE
Consistent Android AAsset management 

### ISSUE THREAD

**Issue by sjfricke** [SaschaWillems/Vulkan#477]
I am proposing to make all the `AAssetManager` code for Android consistent in all the base src files and examples. I am happy to do it and make the PR, I was thinking of just setting them all to

```
AAsset* asset = AAssetManager_open(assetManager, fileName, AASSET_MODE_STREAMING);
assert(asset);
size_t size = AAsset_getLength(asset);
assert(size > 0);

char *fileData = new char[size];
AAsset_read(asset, fileData, size);
AAsset_close(asset);

// copy fileData to some vulkan handle
// base src file dependent

delete[] fileData;
```

every file is differenet and it leads to things like [texturemipmapgen.cpp#L123](https://github.com/SaschaWillems/Vulkan/blob/master/examples/texturemipmapgen/texturemipmapgen.cpp#L123) having a memory leak because there is not a consistent style to use the Android asset manager.

**Comment by SaschaWillems** [comment]
Yeah, this definitely isn't right and should be consistent. I'm working on a big change on how Android builds are working (moving to gradle, as ndkbuild has been deprecated and removed) so I'll take a look at this once I'm finished with that.
