### ISSUE TITLE
Advanced analysis and visualisation for source code

### ISSUE THREAD

**Issue by elfring** [SaschaWillems/Vulkan#48]
* How do you think about to transform source files for various languages into pictures which can be analysed also by the Vulkan application programming interface?
* Would it make sense to visualise any source code evolution by additional tools?

**Comment by httpdigest** [comment]
What does that have to do with Vulkan? And what do you mean by "transform source files *for various languages*"? What languages? And how does that relate to Vulkan? What would it showcase of the Vulkan API?
And what should the Vulkan API analyze in those "*pictures which can be analysed*"?
You mean some programmer would use a shader/kernel written in some language compiling to SPIR-V and use Vulkan to invoke such kernel to do some image analysis/processing of some image produced by some code metric tool, the latter of which probably has nothing to do with Vulkan?
Do you suggest making a demo to visualize source code metrics somehow? For what purpose and what metric exactly? What is the usecase?

**Comment by elfring** [comment]
Another example:
There are some source files (that were written in a programming language) which contain data that are not directly taken for graphical processing.
* How do you think about to submit special computations by Vulkan interfaces?
* Would you like to display corresponding results in dedicated scenes?

**Comment by httpdigest** [comment]
Source files containing data which is not directly taken/used for graphical processing?
That seems not like an example of what you want to do, but rather seems like another way of abstractly describing it.
What do you mean by *data" exactly and what by "graphical processing"? I assume the latter means 'Rendering' (I. e. rasterizing some primitives / triangles)?
Generally you can submit any kind of computation to the GPU.
And I guess you can/want to present the computation result on your surface/screen/image using some color encoding, yes.
But could you probably be more specific with an actual example?

**Comment by elfring** [comment]
>What do you mean by *data" exactly and what by "graphical processing"?

I imagine that it might be interesting to convert ordinary text into "pretty" images.


>Generally you can submit any kind of computation to the GPU.

* Are these devices optimised for floating-point computations?
* How challenging would it be to perform analysis on source code there?
* Is there any impedance mismatch between input file formats and the usual application domains?

**Comment by SaschaWillems** [comment]
If you just want to crunch data on the GPU you should take a look at [OpenCL](https://www.khronos.org/opencl/)

While it's possible to do computations on general data with Vulkan, OpenCL is much better suited for something like that.

**Comment by elfring** [comment]
I am curious if the software evolution around SPIR-V will bring further possibilities in comparison to OpenCL.
Did any software developers experiment with advanced source code analysis by current GPU capabilities already?

**Comment by httpdigest** [comment]
I'd imagine that you can also compile OpenCL to SPIR-V. If not now than surely in some months.
My gut tells me that "*advanced source code analysis*" (whatever you imagine hiding behind that term) would not be a good fit for the SIMD nature and coalesced memory accesses on GPUs.
It's mainly only because of coalesced memory accesses that the GPU is actually faster in some domains than the CPU. If you jump around AST nodes of some programming language to do stuff, you are very very likely better off with doing that on the CPU with its much much larger CPU caches.

**Comment by elfring** [comment]
Can any algorithms for static source code analysis benefit also from "graphical" data processing techniques?
How would you prefer to distribute the corresponding work load between the available devices?

**Comment by httpdigest** [comment]
Talking abstractly about these things will not lead to a solution.
You have to be very very specific about what that workload would actually be and what you concretely want to do.
Only then can you develop efficient data structures and corresponding algorithms and evaluate whether they would be a good fit for a SIMD architecture, or not.

**Comment by elfring** [comment]
I imagine that the corresponding data structure fine-tuning will result in further software development challenges.
I am talking about an idea abstractly because of the current software evolution and unclear mapping of higher level approaches to concrete application programming interfaces.

**Comment by SaschaWillems** [comment]
@elfring : Can you move this discussion to the [Vulkan forums](https://forums.khronos.org/forumdisplay.php/114-Vulkan-High-Efficiency-GPU-Graphics-and-Compute)?

That's a better place for discussing such things than in an issue on this repo.
