### ISSUE TITLE
texturesparseresidency issues

### ISSUE THREAD

**Issue by yavn** [SaschaWillems/Vulkan#481]
I noticed a few problems in this demo app:

- Some fields of `VirtualTexturePage` are not initialized, in particular `imageMemoryBind.flags`. All unused fields should be initialized to zero in `VirtualTexture::addPage()`, otherwise we risk passing in garbage which may have unexpected effects.
- There's a problem with how allocations for image pages are handled. Each page is a separate memory allocation. Given that there's well over 5000 pages, allocating all of them individually will go over the limit of  `VkPhysicalDeviceLimits::maxMemoryAllocationCount`, which is often 4096.
I would suggest to make an allocation per mip level and suballocate pages from it.

**Comment by SaschaWillems** [comment]
That's correct. I still consider this example as an unfinished work-in-progress  and as along as there's no widespread support for sparse residency in Vulkan I'm not going to put much more work into this. If that changes I'll may completely redo that sample ;)

**Comment by yavn** [comment]
Sure, no problem. Just wanted to record it in the tracker as it was something that caused issues in my testing. Thanks!

**Comment by Trass3r** [comment]
> as along as there's no widespread support for sparse residency in Vulkan I'm not going to put much more work into this. If that changes I'll may completely redo that sample ;)

Seems to have changed?
http://asawicki.info/news_1698_vulkan_sparse_binding_-_a_quick_overview.html

**Comment by SaschaWillems** [comment]
I'll close this for now. I have started the re-write the sparse image residency sample from scratch.
