### ISSUE TITLE
Several examples segfault

### ISSUE THREAD

**Issue by h1z1** [SaschaWillems/Vulkan#487]
Not sure these should all be individual reports or if they are all related(?) but the following currently crash.  Latest from git. Appears similar to #398  .  Isn't clear from that ticket though if the build was in or out of tree.  I had problems with paths on some of the other demos though.  GetAssetPath ultimately resolves to "./../data" which doesn't work for out of tree.

$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  387.34  Tue Nov 21 03:09:00 PST 2017
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 

bloom.lg:bloom: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261:
 void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

computecloth.lg:computecloth: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

deferred.lg:deferred: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

displacement.lg:displacement: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261:
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

hdr.lg:hdr: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

instancing.lg:instancing: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

multithreading.lg:multithreading: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

offscreen.lg:offscreen: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: 
void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

parallaxmapping.lg:parallaxmapping: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

pbrbasic.lg:pbrbasic: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

pbribl.lg:pbribl: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

pbrtexture.lg:pbrtexture: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

pipelinestatistics.lg:pipelinestatistics: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

shadowmappingomni.lg:shadowmappingomni: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

skeletalanimation.lg:skeletalanimation: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

terraintessellation.lg:terraintessellation: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

texturecubemap.lg:texturecubemap: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

vulkanscene.lg:vulkanscene: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

**Comment by SaschaWillems** [comment]
Those are all related to model loading and I'm sure this is because the examples aren't able to locate the proper directories or files. Make sure that getAssetPath points to the correct data directory and that you also have a current version of the asset pack.

**Comment by h1z1** [comment]
Should have a problem there,  the other examples work too.

**Comment by SaschaWillems** [comment]
Looks like this only happens on .obj model files. Are you using the assimp version provided with the repository? Can you debug and check what function of assimp triggers the error?

**Comment by h1z1** [comment]
Using whatever cmake piked up :)   Guessing it's the system version which is indeed older.
```
$ pwd
/dev/shm/Vulkan
$ ldd build/bin/skeletalanimation |grep assim
	libassimp.so.3 => /lib64/libassimp.so.3 (0x00007f7f63162000)
$  build/bin/skeletalanimation > /dev/null 2>&1 || echo fail
Aborted (core dumped)
fail
$ LD_LIBRARY_PATH=/dev/shm/Vulkan/build/libs/lib build/bin/skeletalanimation
skeletalanimation: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.
Aborted (core dumped)
$ # dafaq...
$  LD_PRELOAD=build/libs/lib/libassimp.so.4.1.0 build/bin/skeletalanimation > /dev/null 2>&1 || echo fail
$ #Worked..
$ rpm -qf /lib64/libassimp.so.3
assimp-3.1.1-2.el7.x86_64
$ objdump --all skeletalanimation | egrep '(libassimp|RPATH)'
  NEEDED               libassimp.so.3
  RPATH                /dev/shm/Vulkan/libs/vulkan
$ # Missing lib path


```

**Comment by SaschaWillems** [comment]
So I guess this is nothing I can fix in my repo? Anything I can add to the build instructions to help linux users on this?

**Comment by h1z1** [comment]
Depends. I'll have to look more later.   I'm guessing the API changed somewhat from 3.1 to whatever version your including in external/assimp.  I didn't find any version dependencies set within cmake though which is why I pulled 4.1 hoping it would work.   The extremely hackish work around is fixing rpath.  
Correct way would probably be adding them as a module and setting a minimum version for libassim with cmake.  Trust in your  build system, you must :)

**Comment by SaschaWillems** [comment]
So is there anyhting I can/should do to fix this in my repo?

**Comment by SaschaWillems** [comment]
Closed due to inactivity.
