### ISSUE TITLE
"indexBase" may be incorrectly set in some cases

### ISSUE THREAD

**Issue by zoltan243** [SaschaWillems/Vulkan#490]
In your example the `aMesh->mNumFaces * 3` is equal with `aMesh->mNumVertices`, but it is not true in every case, so I think the line `indexBase += aMesh->mNumFaces * 3;` should be `indexBase += aMesh->mNumVertices;`.
`indexBase += aMesh->mNumFaces * 3;` will give you an incorrect vertex offset.

I've just came across with this issue when I've tried to load an .obj model in my application, which had a lot more indices than vertices (because of vertex reuse) and this solved my problem.
Maybe I'm wrong, I need confirmation.

**Comment by SaschaWillems** [comment]
Thx for bringing this up. I'll check and fix this.

**Comment by SaschaWillems** [comment]
I have reworked the scene rendering sample to use glTF, so closing this for now.
