### ISSUE TITLE
Lots of warnings when using Visual Studio

### ISSUE THREAD

**Issue by SuperflyJon** [SaschaWillems/Vulkan#491]
The CMakeLists.txt sets -Wall, but visual studio generally doesn't build cleanly with this option.

More normal is to set the maximum warning level, e.g. -W4.  There are still a fair few warnings in the projects with this option and -W3 is probably better.

**Comment by SaschaWillems** [comment]
This was added in a PR some time ago, and yes, I also don't use -Wall locally as it displays lots of warnings that are not from my source code but the external dependencies. I'll dial this down.
