### ISSUE TITLE
VulkanExampleBase::setupDepthStencil() VK_IMAGE_USAGE_TRANSFER_SRC_BIT

### ISSUE THREAD

**Issue by tksuoran** [SaschaWillems/Vulkan#492]
Why is VK_IMAGE_USAGE_TRANSFER_SRC_BIT included in image.usage in setupDepthStencil()?

https://github.com/SaschaWillems/Vulkan/blob/0eb306ec9e1e90e0071a957dfd495391b0c7eae8/base/vulkanexamplebase.cpp#L1994

**Comment by SaschaWillems** [comment]
This is a left-over. There were samples in the early days that would read from the depth buffer.
