### ISSUE TITLE
Validation error in texture example when calling vkCmdPipelineBarrier

### ISSUE THREAD

**Issue by Hossein-Noroozpour** [SaschaWillems/Vulkan#494]
(Maybe I'm wrong, I'm steal a newbie in Vulkan!)

In [here](https://github.com/SaschaWillems/Vulkan/blob/0eb306ec9e1e90e0071a957dfd495391b0c7eae8/examples/texture/texture.cpp#L165) you have set **srcStageFlags** and **destStageFlags** values to VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT while you have to set them according to the the value of the old layout and new layout.

In [here](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#synchronization-access-types-supported) spec has specified their values.

And in the other hand (it is a question for me), in [here](https://github.com/SaschaWillems/Vulkan/blob/0eb306ec9e1e90e0071a957dfd495391b0c7eae8/base/VulkanTools.cpp#L96) why do you get their values by arguments instead of inferring them by old and new layout and what the spec is saying?

**Comment by SaschaWillems** [comment]
What's the actual validation message you are getting, and at what line of code. Validation is clean for me, and while the barrier stages may not be the most optimal ones they're not wrong either.

**Comment by Hossein-Noroozpour** [comment]
I had errors in another project at first and then I came to this repository for finding the correct usage of API and try to match my project to the texture example and then I got these errors, and after you said you do not get any error, I tried to run you texture example with validation enabled, 
I'm using VulkanSDK 1.1.73.0
My OS is Ubuntu 18.04
My GPU Ivy Bridge
It is texture log (+ driver complaint)
```
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
ERROR: [DS] Code 461375810 : Object: 0x562bb2df3000 | vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x1000) is not supported by dstStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
ERROR: [DS] Code 461375808 : Object: 0x562bb2df3000 | vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x1000) is not supported by srcStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
ERROR: [DS] Code 461375810 : Object: 0x562bb2df3000 | vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x20) is not supported by dstStageMask (0x1). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
```

**Comment by Hossein-Noroozpour** [comment]
I can fix the errors in the texture example.
But the main problem in here is, that you have exactly same function in `base/VulkanTexture.hpp` and I'm afraid of changing it may break something somewhere else.

**Comment by SaschaWillems** [comment]
I have fixed (and cleaned up) the texture sample. The function used for the texture loader via the vks namespace is fine and does not cause any validation layer errors. Unlike the texture sample it uses ```VK_PIPELINE_STAGE_ALL_COMMANDS_BIT``` which may not be optimal, but does the job fine. Esp. as the textures are loaded up-front and not during run-time.

I may change the pipeline stages in the utility function at some point, but there's no need to fix them.
