### ISSUE TITLE
dimensions not scaled or translated

### ISSUE THREAD

**Issue by jherico** [SaschaWillems/Vulkan#498]
https://github.com/SaschaWillems/Vulkan/blob/1f42dbda61202e32d257b0c10d44800e6b2f933e/base/VulkanModel.hpp#L283

The code here calculates the bounding dimensions of the model, but doesn't apply any of the transformations done [here](https://github.com/SaschaWillems/Vulkan/blob/master/base/VulkanModel.hpp#L242), i.e. the inversion of the Y axis and the scale and translation of the position.  

Also, if you construct a `glm::vec3 scaledPos`, to do these transformations you can replace the component-wise lines with `dim.max = glm::max(scaledPos, dim.max);` etc.

**Comment by SaschaWillems** [comment]
I have replaced the ASSIMP-based load with a glTF loader that should properly account for scaling and translations provided by teh glTF node hierarchy.
