### ISSUE TITLE
Transparent Subpass Rendering will Disable Early-Z ?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [SaschaWillems/Vulkan#504]
I get the idea of:
https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/subpasses/transparent.frag

But I believe that emulating the depth test in the pixel shader instead of using the original depth attachment will disable Early-Z which hurts performance on Non-Tiled Architectures and could be of debatable improvement (until profiled) even on Tiled Ones.

Am I wrong?

**Comment by SaschaWillems** [comment]
Yes, `discard` is bad in terms of performance for pretty much any GPU architecture, including TB(D)Rs. But that sample is not a best-performance practices sample, so it's fine.
