### ISSUE TITLE
Multiple samples use mismatched gl_PerVertex declaration

### ISSUE THREAD

**Issue by jackohound** [SaschaWillems/Vulkan#509]
We have enabled support for geometry/tessellation for Adreno, and encountered the application issue below.  

The following samples (and possibly others) exhibit this common issue:
 geometryshader
terraintessellation
pipelinestatistics

In the samples, the gl_PerVertex is redeclared in the GLSL vertex shader, but is not redeclared in the subsequent stages (TCS/TES/GEOM) where the gl_position built-in is used.  Since the GLSL shaders use "#version 450", the shaders syntax should to conform to the [GLSL 4.50](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf) spec which states:

```
The  gl_PerVertex block can be redeclared in a shader to explicitly indicate what 
subset of the fixed pipeline interface will be used. 
...
If multiple shaders using members of a built-in block belonging to the same interface
 are linked together in the same program, they must all redeclare the built-in block in
 the same way, as described in section 4.3.9 “Interface Blocks” for interface-block 
matching, or a link-time error will result.  It will also be a link-time error if some 
shaders in a program redeclare a specific built-in interface block while another shader 
in that program does not redeclare that interface block yet still uses a member of 
that interface block.

```
Although the shaders are converted to SPIR-V, they still must follow the GLSL 4.50 syntax rules.  The easiest fix is to simply remove the redeclaration in the GLSL vertex shader.  Alternatively you could redeclare the gl_PerVertex in all the stages.

**Comment by SaschaWillems** [comment]
I initially added the gl_PerVertex declaration to the VS because early validation layers complained about it.

Thx. I'll fix try to fix these when I'm back from my business trip.
