### ISSUE TITLE
List of Portings

### ISSUE THREAD

**Issue by elect86** [SaschaWillems/Vulkan#511]
As agreed with Sasha, I'm opening this issue to take track of all the ports:

- [jvm](https://github.com/java-opengl-labs/Vulkan), written in Kotlin

If you have a porting you'd like to add, don't hesitate to reply and I'll update the list :)

**Comment by SaschaWillems** [comment]
I have added a [wiki page to this repository](https://github.com/SaschaWillems/Vulkan/wiki/List-of-Ports) for this and also added your port.

**Comment by elect86** [comment]
Cool, thanks!

Shall we close this issue then or leave it open?
