### ISSUE TITLE
Multiview example does not work correctly on AMD under Windows. (Just black output) 

### ISSUE THREAD

**Issue by BeRo1985** [SaschaWillems/Vulkan#514]
Multiview example does not work correctly on AMD under Windows with a just black output. The AMD graphics card is a Raedon RX580 with 8GB, the AMD GPU driver version is 18.10.2 and the Windows 10 Build is 17763.55 

However it works fine on my other computers with NVIDIA GPUs (GTX970 4GB, GTX1060 6GB, MX150 2GB) and Intel iGPUs (UHD Graphics 620).

See:

![image](https://user-images.githubusercontent.com/428863/47892345-71595100-de57-11e8-964b-8f69fb4dc8aa.png)

**Comment by BeRo1985** [comment]
The Multiview example in renderdoc: https://youtu.be/g2l29xycIYo

So, as far as I can see it with RenderDoc, only the final screen output is broken on AMD.

**Comment by SaschaWillems** [comment]
This could be a driver bug. Works fine for me too on NVIDIA, Intel, Adreno and Mali.

**Comment by BeRo1985** [comment]
Yes, I tried it now, but it didn't help. 

At least the problem seems to have been around for quite some time, because I already had it with the previous AMD driver versions.

**Comment by BeRo1985** [comment]
I've now got the multi-view stuff working myself with PasVulkan, which to my surprise also works fine with my AMD Radeon RX580 as opposed to your multi-view example.  See this [YouTube video](https://youtu.be/NTqEJH46Ek4)

And now it is necessary to find out what your code does differently in your example than my code does in PasVulkan, why your example does not work correctly on AMD but my implementation does work also correctly on AMD (and on NVIDIA & Intel also). 

Do you want access to the source code of the project, which uses Multiview with PasVulkan? And since it's a proprietary project, I can't publish the source code generally for everyone, therefore this question as well.  At least I don't have much or no time to compare both implementations step by step in the moment, because I want to finish the one project as soon as possible.

**Comment by SaschaWillems** [comment]
Thx for the offering, but I do have access to an AMD GPU. Will try to test and fix it on that.

**Comment by SaschaWillems** [comment]
This was actually an oversight on my side. The view display graphics pipeline was created with the wrong renderpass. This is fixed now and the sample works fine on AMD too.
