### ISSUE TITLE
Using Descriptor Sets Project - animate does not work

### ISSUE THREAD

**Issue by RisaStenr** [SaschaWillems/Vulkan#515]
GPU: GeForce GTX 680
Driver: 416.34
Platform: Windows 10 17135.345, Visual Studio Community 2017

In the descriptor sets project, the animate checkbox doesn't do anything.  I am not sure what it is supposed to do, but checking it and unchecking it there is no difference.  Although the FPS does go up a bit when the box is not checked.  There were no validation messages.

**Comment by SaschaWillems** [comment]
The cubes should slowly rotate if that option is checked. Together with the other problem you reported I can imagine that the latest game ready driver has broken something in the Vulkan implementation. I'll have to check that.

**Comment by RisaStenr** [comment]
Tested this on a radeon and in debug mode the boxes still do not animate, but in release mode they do.

**Comment by RisaStenr** [comment]
This bug is fixed now, not sure what fixed it but it was probably a windows update.

**Comment by RisaStenr** [comment]
OK this is fixed on nvidia as well.
