### ISSUE TITLE
Potential issue with descriptor set allocation in descriptorset.cpp

### ISSUE THREAD

**Issue by spanzeri** [SaschaWillems/Vulkan#518]
In the descriptorsets.cpp example, VkDescriptorPoolCreateInfo::maxSets is initialized with descriptorPoolSizes.size(). It should be cubes.size().
According to the vulkan documentation and your comment in code maxSets is the number of vkDescriptorSet that can be allocated from the pool.
In your example it works because descriptorPoolSizes and cubes are both vectors of 2 elements.
If someone tries to draw more cubes, vkAllocateDescriptorSets fails after 2 allocations with VK_ERROR_OUT_OF_POOL_MEMORY.

Cheers :)
Sam

**Comment by SaschaWillems** [comment]
Yes, that's obviously a mistake. Thx for letting me know.
