### ISSUE TITLE
How do I create a ktx compressed texture? 

### ISSUE THREAD

**Issue by liuhongyi0101** [SaschaWillems/Vulkan#519]
What tools are available? thank you

**Comment by liuhongyi0101** [comment]
type  ['astc', 'etc', 'pvr', 's3tc']

**Comment by liuhongyi0101** [comment]
type =>['astc', 'etc', 'pvr', 's3tc'] . which one?

**Comment by SaschaWillems** [comment]
Use a tool like PowerVR TexTool.
