### ISSUE TITLE
Nvidia nvs5100m -- no gpus found

### ISSUE THREAD

**Issue by filipwasil** [SaschaWillems/Vulkan#52]
Hi,

I suspect a bug in my gpu drivers (255.0.28):
 
void VulkanExampleBase::initVulkan(bool): Assertion `gpuCount > 0' failed

**Comment by 1ace** [comment]
Can you run the [`cube` demo](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/tree/master/demos)?

And if you think it's an NVIDIA driver bug, you should probably [tell NVIDIA](https://developer.nvidia.com/content/nvidia-dev-support-submission-form) :)

**Comment by filipwasil** [comment]
Hi,
I link to this lib:

https://github.com/SaschaWillems/Vulkan/blob/master/libs/vulkan/libvulkan.so

because i do not have such although i installed the driver. (?!) Looks like a driver issue,

Damn. I guess i will have to boot windows ...

**Comment by 1ace** [comment]
ICDs such as NVIDIA's driver don't come with `libvulkan.so` (or at least they shouldn't).
That library acts like a sort of dispatch table, letting any application see all the drivers available (and therefore the hardware those drivers support).
You should search for a package called `vulkan-icd-loader` (or something similar) in your distribution's package manager. If all else fails, you can always install the [Vulkan SDK](https://vulkan.lunarg.com/) manually :)

You need 3 things to run a Vulkan app:
- Vulkan-capable hardware
- An ICD which supports that hardware (eg. NVIDIA's driver)
- The loader (`libvulkan.so`)

**Comment by filipwasil** [comment]
Thanks :+1:
