### ISSUE TITLE
conditionalrender.exe fails to load asset

### ISSUE THREAD

**Issue by iostrowsINTEL** [SaschaWillems/Vulkan#521]
Hi,
it seems that the model "models/gltf/glTF-Embedded/Buggy.gltf" does not load.

There's error reported inside the loader:
[json.exception.parse_error.101] parse error at 10711911: syntax error - unexpected '}'; expected end of input

Can you take a look?

Thanks,
Igor

**Comment by SaschaWillems** [comment]
Just checked again, and this is working fine for me with the current version of that loader from my repo.

Can you try again with same model from the glTF sample repo: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy?

**Comment by iostrowsINTEL** [comment]
Both files behaves the same.

I just found that model loads correctly if I build binaries using VS2015. Issue is visible only for VS2017.

In tiny_gltf.h:
*std::ifstream f(filename.c_str())
...
f.seekg(0, f.end);
size_t sz = static_cast<size_t>(f.tellg());
...
f.read(&buf.at(0), static_cast<std::streamsize>(sz));
...*

Size of the file (sz) is computed for \r\n line endings.
Reading from the file in text mode removes \r from the \r\n.
This means that the last character from the file is not placed just before 'sz' byte but much earlier. All remaining bytes (to match sz) should be nulled.

**VS2015:**
Correct behaviour

**VS2017:**
Instead of nulled bytes there is garbage at the end (actually it's doubled part of the file) that fails parsing of the file.

It may be my environment issue or a problem in the VS2017.

Opening files in binary mode:
*std::ifstream f(filename.c_str(), std::ios::binary)*
forks fine for me on both configurations.

Actually on the master of the tinygltf files are being opened in binary mode, so maybe it is possible to update the loader?

Igor

**Comment by iostrowsINTEL** [comment]
I played with this a little bit more and I see the issue.

Loader's LoadASCIIFromFile() opens file in a text mode and due to \r\n -> \n transformation on Windows it reads sz - count_of(\r) bytes. Then it sets fail bit.
The rest count_of(\r) bytes in the buf is **uninitialized**. The loader should append null byte at the end in this case.

tinygltf on the master in LoadASCIIFromFile() internally use binary mode, so the bug is no more there.

I think that in present version of the loader changing LoadASCIIFromFile to LoadBinaryFromFile should also work. I will test it.

**Comment by Cazadorro** [comment]
> I played with this a little bit more and I see the issue.
> 
> Loader's LoadASCIIFromFile() opens file in a text mode and due to \r\n -> \n transformation on Windows it reads sz - count_of(\r) bytes. Then it sets fail bit.
> The rest count_of(\r) bytes in the buf is **uninitialized**. The loader should append null byte at the end in this case.
> 
> tinygltf on the master in LoadASCIIFromFile() internally use binary mode, so the bug is no more there.
> 
> I think that in present version of the loader changing LoadASCIIFromFile to LoadBinaryFromFile should also work. I will test it.
> 
> EDIT: But std::vector buf(sz); is actually zero initializing it and it should be totally fine. Well, I'm still looking for a rootcause... : )

Have you tried the edit anyway?

**Comment by SaschaWillems** [comment]
It's working fine for me with VS 2017, but there's nothing that stops me from updating the loader. Will try to get that done during this weekend.

**Comment by iostrowsINTEL** [comment]
That would be great, thanks!
I will still try to debug the issue on my machine.

**Comment by SaschaWillems** [comment]
Updated the loader to the latest version from the master branch. Had to also change a few bits for the Vulkan glTF loading class due to some breaking changes.

Can you please check again?

**Comment by SaschaWillems** [comment]
I'm currently on 19.14.26431. Oddly my current VS2017 setup doesn't offer me any updates. Will check how to update the compiler.

**Comment by iostrowsINTEL** [comment]
Filled bug: https://developercommunity.visualstudio.com/content/problem/391566/stdbasic-istreamread-used-on-file-stream-in-text-m.html

New loader works fine for me, so the issue can be closed.
If you would have a chance to check the repro on newer MSVC toolset please let me know what are the results :)

**Comment by iostrowsINTEL** [comment]
Will be fixed in future VS release (details in the above link). Closing.
