### ISSUE TITLE
the prefix.pch cannot be found

### ISSUE THREAD

**Issue by LWSSS** [SaschaWillems/Vulkan#522]

**Comment by LWSSS** [comment]
Hi 👍
   I have followed steps by README_MoltenVK_Examples.md, then when built with  scheme: examples-ios. The Xcode shows :error: Build input file cannot be found: '/Users/.../Vulkan-master/xcode/iOS/Prefix.pch'
  Will you kindly give me some suggestions? Thankyou

**Comment by LWSSS** [comment]
@SaschaWillems
 Hi:
    When I ordered :./build.sh --stdlib=libc++ --archs="arm64" --no-fat
   The terminal showed  many warning like this :
          /Users/liuwei/Downloads/assimp-3.3.1-ios/include/assimp/types.h:213:19: warning: 
      taking address of packed member 'r' of class or structure 'aiColor3D' may
      result in an unaligned pointer value [-Waddress-of-packed-member]
        return *(&r + i);
                  ^
      and the progress stoped  at 91%,then showed error  with this :
         make[2]: *** [code/CMakeFiles/assimp.dir/all] Error 2
         make[1]: *** [code/CMakeFiles/assimp.dir/rule] Error 2
         make: *** [assimp] Error 2
         [!] Moving built library into: ./lib/iOS/arm64/
         mv: rename ./lib/libassimp.a to ./lib/iOS/arm64/libassimp.a: No such file or directory

    Can you kindly  give me some suggestions?
    Thanks.

**Comment by LWSSS** [comment]
@SaschaWillems  @billhollings  
I have figure out the Problem above . It because there has a extra character '>' in   D3MFImporter.cpp. ,line  230.
By delete the character '>',now I can order success.
But the problem still exist:
The Xcode shows :error: Build input file cannot be found: '/Users/.../Vulkan-master/xcode/iOS/Prefix.pch'

Could you please tell me how to resolve with that?

**Comment by didito** [comment]
To fix the Prefix.pch problem you must fixup your xcode project:
- delete the file entries in the project referencing Prefix.pch
- change `GCC_PRECOMPILE_PREFIX_HEADER` from YES to NO in build settings
- delete `GCC_PREFIX_HEADER = "$(SRCROOT)/macOS/Prefix.pch"`in build settings

**Comment by SaschaWillems** [comment]
See https://github.com/KhronosGroup/MoltenVK/issues/357

**Comment by felipenmoura** [comment]
Oh, after a lot of search, @didito 's answer helped me out!
I had renamed the project and for some reason it was still looking for the old name's root directory.
The problem was in `GCC_PREFIX_HEADER`.

Thanks.
