### ISSUE TITLE
Computeheadless - search path for assets is wrong

### ISSUE THREAD

**Issue by raffam** [SaschaWillems/Vulkan#527]
on my system the example `computeheadless` does not search the path correctly. After cloning, I made a build subdirectory inside the repository and I ran `cmake ..` from there. The executables files are then in `[REPOSITORY]/build/bin`. All other executables run correctly, except `computeheadless` +

> ./computeheadless
> Running headless compute example
> GPU: GeForce GTX 1050
> Error: Could not open shader file "./../data/shaders/computeheadless/headless.comp.spv"
> computeheadless: /media/raffaele/DATA/data/programmi/Vulkan/examples/computeheadless/computeheadless.cpp:376: VulkanExample::VulkanExample(): Assertion `shaderStage.module != VK_NULL_HANDLE' failed.
> Aborted (core dumped)

I noticed this example use `ASSET_PATH`, while the others use `getAssetPath()`

**Comment by raffam** [comment]
So that would be the definition of `ASSET_PATH` in `VulkanTools.h`:

```
#if defined(__ANDROID__)
#define ASSET_PATH ""
#else
#define ASSET_PATH "./../data/"
#endif

```

and this the one of `getAssetPath()` in `vulkanexmplebase.cpp`

```
#if !(defined(VK_USE_PLATFORM_IOS_MVK) || defined(VK_USE_PLATFORM_MACOS_MVK))
// iOS & macOS: VulkanExampleBase::getAssetPath() implemented externally to allow access to Objective-C components
const std::string VulkanExampleBase::getAssetPath()
{
#if defined(VK_USE_PLATFORM_ANDROID_KHR)
	return "";
#elif defined(VK_EXAMPLE_DATA_DIR)
	return VK_EXAMPLE_DATA_DIR;
#else
	return "./../data/";
#endif
}
#endif
```

So apparently the correct path is in VK_EXAMPLE_DATA_DIR for me?

**Comment by SaschaWillems** [comment]
Yes, for that example (and a few others) the path is taken from VK_EXAMPLE_DATA_DIR.
I'm not happy with how asset paths are handled, as this had be changed several times to support all kinds of builds, so this is something I want to rework at some point.
