### ISSUE TITLE
shadowmapping.cpp build error

### ISSUE THREAD

**Issue by RicardasSim** [SaschaWillems/Vulkan#53]
When building under Linux:
Vulkan/shadowmapping/shadowmapping.cpp:1176:18: error: ‘class VulkanExample’ has no member named ‘handle_event’

line 1176:  vulkanExample->handle_event(event);
works well with vulkanExample->handleEvent(event);

**Comment by ChristophHaag** [comment]
Oops, I made https://github.com/SaschaWillems/Vulkan/pull/55 before seeing this issue.

**Comment by SaschaWillems** [comment]
Thx! Fixed with 6af10ce76432ff0ba3762e69ff7392d040512383
