### ISSUE TITLE
Missing Prefix.pch

### ISSUE THREAD

**Issue by SuperSimon81** [SaschaWillems/Vulkan#531]
When I try to build the examples in xcode i get the following error: 

Error: 'Build input file cannot be found: '/Users/simonthalen/Desktop/Vulkan-master/xcode/macOS/Prefix.pch'

I cant find Prefix.pch anywhere. Please advise

**Comment by SaschaWillems** [comment]
See #522

**Comment by LWSSS** [comment]
@SuperSimon81 
 Hey  ,the issue #522,is not a real resolution fo this problem. Billholling group provided another fork of MoltenVK,which may can help you .https://github.com/KhronosGroup/MoltenVK/issues/357
