### ISSUE TITLE
Assimp linker error

### ISSUE THREAD

**Issue by Rhumage** [SaschaWillems/Vulkan#532]
Trying to run geometryshader project I get: 

geometryshader.obj : error LNK2019: unresolved external symbol "public: __thiscall Assimp::Importer::Importer(void)" (??0Importer@Assimp@@QAE@XZ) referenced in function "public: bool __thiscall vks::Model::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct vks::VertexLayout,struct vks::ModelCreateInfo *,struct vks::VulkanDevice *,struct VkQueue_T *,int)" (?loadFromFile@Model@vks@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UVertexLayout@2@PAUModelCreateInfo@2@PAUVulkanDevice@2@PAUVkQueue_T@@H@Z)
1>geometryshader.obj : error LNK2019: unresolved external symbol "public: __thiscall Assimp::Importer::~Importer(void)" (??1Importer@Assimp@@QAE@XZ) referenced in function "public: bool __thiscall vks::Model::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct vks::VertexLayout,struct vks::ModelCreateInfo *,struct vks::VulkanDevice *,struct VkQueue_T *,int)" (?loadFromFile@Model@vks@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UVertexLayout@2@PAUModelCreateInfo@2@PAUVulkanDevice@2@PAUVkQueue_T@@H@Z)
1>geometryshader.obj : error LNK2019: unresolved external symbol "public: struct aiScene const * __thiscall Assimp::Importer::ReadFile(char const *,unsigned int)" (?ReadFile@Importer@Assimp@@QAEPBUaiScene@@PBDI@Z) referenced in function "public: bool __thiscall vks::Model::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct vks::VertexLayout,struct vks::ModelCreateInfo *,struct vks::VulkanDevice *,struct VkQueue_T *,int)" (?loadFromFile@Model@vks@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UVertexLayout@2@PAUModelCreateInfo@2@PAUVulkanDevice@2@PAUVkQueue_T@@H@Z)
1>geometryshader.obj : error LNK2019: unresolved external symbol "public: char const * __thiscall Assimp::Importer::GetErrorString(void)const " (?GetErrorString@Importer@Assimp@@QBEPBDXZ) referenced in function "public: bool __thiscall vks::Model::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct vks::VertexLayout,struct vks::ModelCreateInfo *,struct vks::VulkanDevice *,struct VkQueue_T *,int)" (?loadFromFile@Model@vks@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UVertexLayout@2@PAUModelCreateInfo@2@PAUVulkanDevice@2@PAUVkQueue_T@@H@Z)
1>geometryshader.obj : error LNK2019: unresolved external symbol _aiGetMaterialColor referenced in function "public: enum aiReturn __thiscall aiMaterial::Get(char const *,unsigned int,unsigned int,struct aiColor3D &)const " (?Get@aiMaterial@@QBE?AW4aiReturn@@PBDIIAAUaiColor3D@@@Z)

**Comment by SaschaWillems** [comment]
Please add more details. What compiler? What OS? What assimp version? etc.

**Comment by Rhumage** [comment]
I've got 2 PCs. Works on PC #1, does not work on PC #2. 

OS is the same, windows 10 x64.
#1 has visual studio 2017 Professional
#2 has visual studio 2017 Enterprise

There are no other relevant differences between them that I can think of. 

Do I need to somehow set up assimp? I have version 4.1 installed and it's in PATH.

**Comment by Rhumage** [comment]
Solved it, I had to set Win64 when building with cmake.
