### ISSUE TITLE
radialblur.cpp should not use a semaphore to sync between passes

### ISSUE THREAD

**Issue by hrydgard** [SaschaWillems/Vulkan#536]
There's absolutely no need for a semaphore sync between the offscreen rendering and the backbuffer rendering. This confused someone in a discussion recently who was looking at the sample.

Why not just use a pipelinebarrier, or a subpass external barrier built into the render passes?

**Comment by SaschaWillems** [comment]
This was added upon request of an IHV in the early stages of Vulkan, and yes, a barrier may be a better option to sync than a semaphore. I'll take a look into this.

**Comment by SaschaWillems** [comment]
I have reworked that example. Synchronization is now properly done using sub pass dependencies from and to external, so I got rid of the semaphores and separate command buffer.

Will also rework this for all other offscreen rendering examples, esp. as I'm preparing for proper per-frame resources.

**Comment by hrydgard** [comment]
Awesome!
