### ISSUE TITLE
Frame rate performance in Android or iOS is different from phone capabilities

### ISSUE THREAD

**Issue by shuaibingChen** [SaschaWillems/Vulkan#538]
Hi, I did a test that executed the Gears example on Samsung Note9 and iPhoneX respectively. The result is that Samsung Note9 has a much higher frame rate than iPhoneX, but it is somewhat different from expectations.
So, is it possible that lose the iPhoneX graphics capabilities when MoltenVK do interface conversion？

**Comment by SaschaWillems** [comment]
I don't have access to Apple devices and can't say much about performance. This question may be better suited for the [MoltenVK repository](https://github.com/KhronosGroup/MoltenVK).

But yes, in general performance is probably not maxed out on iOS as MoltenVK is sitting on top of Metal.

**Comment by SaschaWillems** [comment]
No, I don't have access to any Apple device and have never done anything with the Metal API.
