### ISSUE TITLE
Tessellation shader binaries need to be recompiled using SDK glslangValidator

### ISSUE THREAD

**Issue by jaakkowork** [SaschaWillems/Vulkan#54]
Hi Sascha

The SPIRV binaries in the git repo are missing Location decorations between the tesc and tese pipeline stages.  If you recompile the GLSL shaders using 1.0.3.1 glslangValidator (or hypothetically newer) then it will include the following SPIRV instructions in data/shaders/tessellation/pntriangles.tese.spv:

               OpMemberDecorate %20 0 Location 6
               OpMemberDecorate %20 1 Location 7
               OpMemberDecorate %20 2 Location 8
               OpMemberDecorate %20 3 Location 9
               OpMemberDecorate %20 4 Location 10
               OpMemberDecorate %20 5 Location 11
               OpMemberDecorate %20 6 Location 12
               OpMemberDecorate %20 7 Location 13
               OpMemberDecorate %20 8 Location 14
               OpMemberDecorate %20 9 Location 15

After fixing the shaders, this should resolve startup issues for the tessellation sample.

Please note that if you test this on AMD cards, you may see backfacing triangles.  There is a bug in the beta drivers where tessellator winding mode is inverted.  This has been fixed internally.

Thanks,

Jaakko

**Comment by SaschaWillems** [comment]
Hi Jakko,

thanks a lot!

I'm currently fixing the examples to also work on AMD hardware, so your timing is perfect ;)

**Comment by jaakkowork** [comment]
Sure

I also have a pull request for one of the other samples here: https://github.com/SaschaWillems/Vulkan/pull/38

We've worked around this internally but it's likely to be an issue on other cards as well that implement this instruction similarly.
