### ISSUE TITLE
DLLs should be removed

### ISSUE THREAD

**Issue by onitake** [SaschaWillems/Vulkan#541]
A source code repository should not contain precompiled binaries or external DLLs.

There are multiple issues with this, such as licensing, ABI conflicts with system libraries, the wrong DLL being loaded at runtime, etc.

Please remove the following files from the repository:
```
 bin/assimp-vc140-mt.dll
 libs/assimp/armeabi-v7a/libassimp.a
 libs/assimp/assimp-vc140-mt.lib
 libs/assimp/assimp.lib
 libs/vulkan/libvulkan.so
 libs/vulkan/libvulkan.so.1
 libs/vulkan/libvulkan.so.1.1.73
 libs/vulkan/vulkan-1.lib
```

**Comment by onitake** [comment]
Agreed, the added convenience may be worth it on some platforms (Windows, macOS?), where installing dependencies is usually a painful task.
But I really don't see any benefit on Linux, as most current distributions (I checked Debian, Ubuntu, Fedora and Arch) ship Vulkan libraries and headers in sufficiently new versions.

For what it's worth, getting all examples to run requires downloading the data pack anyway.
Why not put the DLLs into a separate download too?

**Comment by Cazadorro** [comment]
@SaschaWillems Well it looks like there is one liscense violation, though it would merely require putting this file with ASSIMP binary https://github.com/assimp/assimp/blob/master/LICENSE:

> Open Asset Import Library (assimp)
> 
> Copyright (c) 2006-2016, assimp team
> All rights reserved.
> 
> Redistribution and use of this software in source and binary forms,
> with or without modification, are permitted provided that the
> following conditions are met:
> 
> * Redistributions of source code must retain the above
>   copyright notice, this list of conditions and the
>   following disclaimer.
> 
> * **Redistributions in binary form** must reproduce the above
>   copyright notice, this list of conditions and the
>   following disclaimer in the documentation and/or other
>   materials provided with the distribution.
> 
> * Neither the name of the assimp team, nor the names of its
>   contributors may be used to endorse or promote products
>   derived from this software without specific prior
>   written permission of the assimp team.

**Comment by SaschaWillems** [comment]
That's correct, the ASSIMP license is missing. I'll add them.

**Comment by SaschaWillems** [comment]
I'm no longer using ASSIMP (moved to glTF), and as such I have removed it's binaries. Closing this for now.
