### ISSUE TITLE
opengl support?

### ISSUE THREAD

**Issue by marcel-klomsbeck** [SaschaWillems/Vulkan#548]
hello do you plan to add opengl support to vulkan?

it would greatly help with my DXVK opengl implementation
and save me **A LOT** of work

many thanks
 - marcel

thank you for making such a good graphics api

**Comment by marcel-klomsbeck** [comment]
i need to support older hardware

**Comment by SaschaWillems** [comment]
Can you elaborate? I'm not sure what you're actually asking for.

These are just examples for the Vulkan API, and not the Vulkan API itself.

**Comment by marcel-klomsbeck** [comment]
hello there

ah I see this is just example for vulkan
you do not make vulkan api yourself I infer?

if so whom should I make my request of????

**Comment by SaschaWillems** [comment]
Nope, I'm just a member of the Vulkan Advisory Panel. The API itself is maintained by Khronos, the official repository can be found at https://github.com/KhronosGroup/Vulkan-Docs/
