### ISSUE TITLE
Unable to run the files in bin after building in linux

### ISSUE THREAD

**Issue by roniktinnu** [SaschaWillems/Vulkan#551]
i have cloned the repository and created a build directory. gave cmake .. and make all after that.
the above steps are succesfully executed. but still i am unable to run the files in the build/bin directory, i'm getting an error for all the files except for **./traingle**

**

> radialblur: /home/tcs/prasanth/1.1.97.0/Samples/Vulkan/external/imgui/imgui_draw.cpp:1573: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.
> Aborted (core dumped)

**

I'm new to Vulkan and i don't know where i'm doing it wrong , please help me.

**Comment by SaschaWillems** [comment]
This looks like the demos are not able to locate the assets. That error is from the line trying to load the font for the UI (see [here](https://github.com/SaschaWillems/Vulkan/blob/cf83c1b49983a7689e744fe5027d0bb4adaffaf3/base/VulkanUIOverlay.cpp#L75)).

Comment out that line and try again, if it works then I need to fix this on my side.

**Comment by roniktinnu** [comment]
After commenting the line the demos are running succesfully , thanks for the help.

**Comment by sypher7** [comment]
I know this is closed, but I ran into this as well. For anyone else finding this, I was also able to work around it by running the files from within `bin/`:
```
cd bin
./radialblur
```

**Comment by DaSuperFunk** [comment]
I'm seeing the same behavior and error as the OP mentioned, but commenting out the line mentioned by Sascha Willems didn't resolve my issue.

**Comment by SaschaWillems** [comment]
What's the error message? Did you download the asset pack?

**Comment by DaSuperFunk** [comment]
I do have the asset pack. The error identical to OP's: 

/home/[user]/Vulkan/external/imgui/imgui_draw.cpp:1573: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.

**Comment by stellama0208** [comment]
Actually I also ran into this problem as well today. The whole error trace is just 
```
stellama@mahjongkun:~/work/sandbox/vulkan_demo/Vulkan/build-dir/bin[master]$ ./pipelines
pipelines: /usr/local/google/home/stellama/work/sandbox/vulkan_demo/Vulkan/external/imgui/imgui_draw.cpp:1573: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.
Aborted
```
I have downloaded asset before. Executing from within bin/ doesn't work for me, but commenting this line out and rebuild works. Maybe you could look into this. ^_^

**Comment by greyltc** [comment]
Why is this closed? Today it still stops me from running the bins I just compiled.

**Comment by greyltc** [comment]
The line @SaschaWillems pointed out above:https://github.com/SaschaWillems/Vulkan/blob/cf83c1b49983a7689e744fe5027d0bb4adaffaf3/base/VulkanUIOverlay.cpp#L75
uses a hard coded relative import path for a font.

The Linux build instructions have almost no details on how to make this besides "use cmake."

Those two things taken together are why this bug is here.

Anyway, the solution I use here is to make sure I execute the compiled binaries from any place where
```bash
file ./../data/Roboto-Medium.ttf
```
will run without error.

**Comment by foley2k2** [comment]
In case anyone finds this in the future - run download_assets.py in the project root. Fixed it for me. It pulls down 536MB of dependencies.

**Comment by largeword** [comment]
> In case anyone finds this in the future - run download_assets.py in the project root. Fixed it for me. It pulls down 536MB of dependencies.

Thanks, downloading assets according to [https://github.com/SaschaWillems/Vulkan#assets](url) did help!
