### ISSUE TITLE
computenbody uses the compute.ubo before putting data in it

### ISSUE THREAD

**Issue by gary-sweet** [SaschaWillems/Vulkan#552]
prepareUniformBuffers() creates the compute and graphics ubos but only puts data in the graphics ubo.

render() calls draw() before calling updateUniformBuffers(), so the data in the compute ubo is uninitialized on first use.

This has caused GPU lockups, or more often just the demo fading out to black within a few frames. The behaviour is dependent on the content of the undefined memory.

The simplest fix is to call updateUniformBuffers() at the end of prepareUniformBuffers().

**Comment by Cazadorro** [comment]
please link to the relevant code in the repository

**Comment by SaschaWillems** [comment]
Thanks for noticing this. Will fix this asap.
