### ISSUE TITLE
voyager_astc_8x8_unorm.ktx is missing from the asset pack

### ISSUE THREAD

**Issue by gary-sweet** [SaschaWillems/Vulkan#553]
When I try to run 'multisampling' with the latest code, I get an error about a missing asset:

> Could not load texture from data/models/voyager/voyager_astc_8x8_unorm.ktx

**Comment by SaschaWillems** [comment]
I recently reworked the mesh sample and forgot about this one. Will fix this.

**Comment by gary-sweet** [comment]
Thanks. Looks good now.
