### ISSUE TITLE
Windows calling convention error in base

### ISSUE THREAD

**Issue by adv-sw** [SaschaWillems/Vulkan#556]
In:  base\vulkanexamplebase.cpp

Corrected code below.

void VulkanExampleBase::setupDPIAwareness()
{
   //using SetProcessDpiAwarenessFunc = HRESULT * (PROCESS_DPI_AWARENESS);
   
   // ADV_SW_PATCH: Need to specify calling convention for Win32 to prevent stack errors.
   typedef HRESULT *(__stdcall *SetProcessDpiAwarenessFunc)(PROCESS_DPI_AWARENESS);

Crashes vstudio 2017 debug build without the above fix.

Thanks for your awesome work, all.

**Comment by SaschaWillems** [comment]
What VS 2017 version are you using? This works fine for me.

**Comment by adv-sw** [comment]
Its not a VS2017 issue, its Win32 platform issue. Shows up Win32 Debug. Much of your code won't compile Win32. You have missing libraries there. Its still a relevant platform. Not everything needs 64 bit pointers.

**Comment by adv-sw** [comment]
Its not a VS2017 issue, its Win32 platform issue. Shows up Win32 Debug. Much of your code won't compile Win32. You have missing libraries there. Its still a relevant platform. Not everything needs 64 bit pointers.

**Comment by SaschaWillems** [comment]
Okay, didn't realize this was about Win32. Will fix.

**Comment by SaschaWillems** [comment]
I have pushed a fix for this. Can you check again?

**Comment by ryios** [comment]
Nvidia and Amd are dropping 32 bit driver support, so not sure why anyone would make 32 bit vulkan apps these days.

**Comment by gary-sweet** [comment]
32-bit embedded Linux systems won't be dying any time soon, so I'm not sure you can generalize that all 32-bit support is unnecessary. If you're just talking about Windows, that's a different matter.

**Comment by ryios** [comment]
If Nvidia and AMD drop 32 bit support, how is driver availability on 32 bit linux distros?  Are they stable?  Do they fully support Vulkan?

**Comment by gary-sweet** [comment]
I was specifically talking about _embedded_ Linux systems (like ours at Broadcom), or others that might use Arm, Qualcomm or IMG GPUs for example. All of those fully support Vulkan today.

**Comment by ryios** [comment]
Ah.... I completely forgot about arm , mobile, etc etc....  Totally different driver architecture and support system...

My mistake, carry on good sir.
