### ISSUE TITLE
buildCommandBuffers (all samples) fills each multi-buffered command buffer each frame instead of just the current one.

### ISSUE THREAD

**Issue by adv-sw** [SaschaWillems/Vulkan#558]
You're multi-buffering command buffers but not using them in a multi-buffered way.

You have code like this in all your samples : 

void buildCommandBuffers()
{
	for (int32_t i = 0; i < drawCmdBuffers.size(); ++i)
             .....  drawCmdBuffers[i] ....

Should be :

void buildCommandBuffers()
{
     int32_t i = currentBuffer;

    .....  drawCmdBuffers[i] ....

in other words, just fill the current buffer, not all of them.

that you're filling all of them & it still works implies its not multi-buffering at all, so there's some sync code that needs work too.

**Comment by SaschaWillems** [comment]
I'm aware of this but haven't had the time to properly redo this. Right now every frame is synced, so no multi-buffering is in place. My gltf PBR example e.g. implements this properly.

Changing this will take a lot of time that I currently don't have, but it's on my todo list.
