### ISSUE TITLE
EXT Maintenance 1: don't revert Y mesh anymore ?

### ISSUE THREAD

**Issue by Rominitch** [SaschaWillems/Vulkan#563]
Hi,

Since VK_KHR_MAINTENANCE1_EXTENSION_NAME exists, we can use another technic to by-pass Y negative way of viewport.
This is less intrusive (don't use -Y about mesh loader, inside shader, CW vs CCW, ... ).

About this:
https://www.reddit.com/r/vulkan/comments/9fombk/is_this_still_the_best_way_to_handle_invertedy/
https://stackoverflow.com/questions/45570326/flipping-the-viewport-in-vulkan
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html#VK_KHR_maintenance1

Do you think you will provide a demo about it ?

Thanks !
(And really good job ^^)

**Comment by SaschaWillems** [comment]
Sure, why not. I'll either incorporate this into an existing sample or will do a new one esp. for that extension.

**Comment by Rominitch** [comment]
Cool !
I will try to help you using your deferred demo. Currently it's my problematic case (3 viewports: mrt / offscreen / debug).
Moreover, I don't know if this solution is now a "standard" (=good practice): it allows to use same meshes(VBO)/shaders into single renderer engine using OpenGL and Vulkan technology.

Regards

**Comment by Rominitch** [comment]
Hi,
I try to do it here:
https://github.com/Rominitch/Vulkan/tree/563-Maintenance1/examples/deferredmultisampling_EXT_M1

But currently, my demo shows me an empty screen when viewport height is negative (I add interactive tools to change y offset).
Maybe someone find issue(s) ...

**Comment by SaschaWillems** [comment]
I already have a demo up an running and will release it soon. Note that you also need to move your origin, flipping y may not be sufficient.

**Comment by SaschaWillems** [comment]
I have added a [new example](https://github.com/SaschaWillems/Vulkan/tree/master/examples/negativeviewportheight) and also [wrote](https://www.saschawillems.de/blog/2019/03/29/flipping-the-vulkan-viewport/) about it.

If you need further help just drop me a line.

**Comment by Rominitch** [comment]
Great job !
I fix my issue too (just forget to invert CULLING).
