### ISSUE TITLE
Please write a book to support your examples!!!

### ISSUE THREAD

**Issue by amadlover** [SaschaWillems/Vulkan#564]

**Comment by SaschaWillems** [comment]
I have been approached multiple times to do that, but writing a book when having a taxing day-job is something I'm currently pretty unsure about. But that may change at some point in the future.

**Comment by KaelMa** [comment]
> I have been approached multiple times to do that, but writing a book when having a taxing day-job is something I'm currently pretty unsure about. But that may change at some point in the future.

How about 《Vulkan-Cookbook》 to know some basic concepts?

**Comment by giordi91** [comment]
I perfectly understand! @SaschaWillems although there might be few options for both if you intend to sell it or keep it free. one might be start by getting user to vote on most requested/useful to sort your priorities (maybe) then release it with time when they come. Possibly even having a Patreon for unlocking each chapter, like for next chapter roughly need X, once your reach it it gets released and you go on the next. 
Just few options if they can help.
