### ISSUE TITLE
Having trouble getting custom models from Blender showing

### ISSUE THREAD

**Issue by RisaStenr** [SaschaWillems/Vulkan#565]
Several months ago, I was messing around with the Scene loading example and pretty easily got it to load a different model I had been working on.  I made a mental note and moved on.

Now, when I try to get my own models loading in any of the mesh loading, scene loading, or skeletal animation examples, the model will load fine (as in no crashes or anything during loading) but nothing will draw.  These models are all made in Blender.

I looked into it a little bit, and it turns out blender's default collada exporter doesn't really work well with game engines, and I tested it by importing the goblin model into blender and then exporting it (having made no changes) to collada again, and the model when loaded into the skeletal animation example was bugged.  So then I tried the better collada exporter and using that the model just wouldn't show up in the engine.  So then I tried importing the goblin mesh and exporting it to .fbx and, it worked!  So then I tried exporting and loading my models as .fbx but they still didn't work.

And that's where I am.  If anyone has any tips I'd really appreciate it.  If I can't figure out something else I am going to try using a free trial of 3ds max and see if I can get models loaded from it.  I guess what I am gonna end up doing is diving into how assimp loads models and how blender exports models and see where the problem is.  I was just hoping I was doing something dumb.

**Comment by SaschaWillems** [comment]
Did you run the sample with your exported mesh through RenderDoc? The mesh view will show you the mesh before it goes through the vertex shader, so you can check if the input data is okay. Maybe the scale is wrong.

Also collada is pretty dead, so I'd go with something newer like gltf. You can check my Vulkan glTF PBR repository if you need some sample code.

**Comment by RisaStenr** [comment]
Well your PBR example is pretty neat.  Really good graphics.  I will experiment with it and see if I can get models from blender showing in it.  

Would you recommend the Khronos gITF importer/exporter or the one that ships with blender 2.8?

**Comment by RisaStenr** [comment]
Although I never solved the original problem, I will close this issue because I no longer need help with it.
