### ISSUE TITLE
Wayland Cmake generate fails when using Wayland_WSI

### ISSUE THREAD

**Issue by SiebenCorgie** [SaschaWillems/Vulkan#567]
Hi,

I tried to build the examples with `USE_WAYLAND_WSI` since I struggle to get it working on my own Rust+ash(vulkan bindings) application.

I use the Cmake Gui, download the resources via the pyhton script and then just check the box next to `USE_WAYLAND_WSI`. However when pressing "Generate" I get the following output:

```
... (the following 4 lines for each example)
Generating project file for example in /home/siebencorgie/Code/CPP/git/Vulkan/examples/texturesparseresidency
Generating project file for example in /home/siebencorgie/Code/CPP/git/Vulkan/examples/triangle
Generating project file for example in /home/siebencorgie/Code/CPP/git/Vulkan/examples/viewportarray
Generating project file for example in /home/siebencorgie/Code/CPP/git/Vulkan/examples/vulkanscene
Configuring done
CMake Error at examples/CMakeLists.txt:28 (add_executable):
  Cannot find source file:

    /home/siebencorgie/Code/CPP/git/Vulkan/build/xdg-shell-client-protocol.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  examples/CMakeLists.txt:42 (buildExample)
  examples/CMakeLists.txt:116 (buildExamples)


CMake Error at examples/CMakeLists.txt:28 (add_executable):
  No SOURCES given to target: viewportarray
Call Stack (most recent call first):
  examples/CMakeLists.txt:42 (buildExample)
  examples/CMakeLists.txt:116 (buildExamples)


CMake Error at examples/CMakeLists.txt:28 (add_executable):
  No SOURCES given to target: triangle
Call Stack (most recent call first):
  examples/CMakeLists.txt:42 (buildExample)
  examples/CMakeLists.txt:116 (buildExamples)

... (the last CMake Error at example/* lines for each example)
```

I also tried to download `xdg-shell-client-protocol.h` (and the also needed `xdg-shell-protocol.c`) from the web and place it there, but then I only get compiler errors about xdg functions not being in scope.

Any idea how to fix that. May I be missing packages on my system or something else?

Greetings

**Comment by SaschaWillems** [comment]
Can you check again? I have just tested this on a clean install and noticed the same problem. I have never compiled my samples with wayland (was contributed by someone else), and it seems those xdg header files were put into a wrong directory.  I changed the cmake files to put them into the actual build directory, and with that change it's working for me.

**Comment by SiebenCorgie** [comment]
Hi, now it compiles, but when I try to run any of the executables it fails like this:
```
./computecloth 
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/user/Code/CPP/git/Vulkan/base/VulkanSwapChain.hpp at line 287
computecloth: /home/user/Code/CPP/git/Vulkan/base/VulkanSwapChain.hpp:287: void VulkanSwapChain::create(uint32_t*, uint32_t*, bool): Assertion `res == VK_SUCCESS' failed.
[1]    30882 abort (core dumped)  ./computecloth

```

Did you try to run those as well? If that it the case, then this might be a problem on my end. 
I currently try to create a wayland surface but do not check for null after the creation. However, when I try to obtain surface properties it reports that the initialization of the surface object has failed.

I'll try to build the examples on my laptop in an hour or two and check if it's the same problem there.

**Comment by SaschaWillems** [comment]
Sry, I don't have a setup that can run wayland binaries, so I only did compile them.

If surface creation fails you may want to check validation layer messages, maybe they'll help track down the issue.

**Comment by SiebenCorgie** [comment]
I tested it on my intel-graphics laptop now and it actually works. So this seems to be some setup specific thing on my AMD-graphics desktop.

I'll invest some hours to find out if it is some driver specific thing on AMD (I currently use the pro driver and not the open-source one).

However, since the original issue seems to be resolved I'll close this one. If I find something I'll open a new, AMD specific issue :).

**Comment by SiebenCorgie** [comment]
@SaschaWillems I found it out, It seems to be a problem with amd's Pro driver on Linux since it works with the opensource driver. So I won't open an issue here.

**Comment by cppcloud** [comment]
**I have solved this problem by following the steps below.**

wayland-scanner private-code \
  < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
  > build/xdg-shell-protocol.c

wayland-scanner client-header \
  < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
  > build/xdg-shell-client-protocol.h
