### ISSUE TITLE
Is xcode/examples.h up to date to current MoltenVK supported features?

### ISSUE THREAD

**Issue by cesss** [SaschaWillems/Vulkan#572]
Reading xcode/examples.h it says some samples cannot run on MoltenVK because of unsupported features... but... is it up to date with the current MoltenVK bundled with the latest Vulkan SDK? For example, xcode/examples.h says that Compute is not supported on MoltenVK, but taking a look to the MoltenVK repository and searching for "Compute" I get several closed issues related to Compute, so it seems it's supported...

Other samples are excluded in xcode/examples.h as well...

**Comment by SaschaWillems** [comment]
Probably not. I don't own any apple device I could test this on, and the MacOS port was contributed by the makers or MoltenVK. If you want to update the MacOS port feel free to do so.

**Comment by billhollings** [comment]
The [fork here](https://github.com/brenwill/Vulkan) is more up to date wrt MoltenVK for now. It's on my to-do list to push that back here....and then maintain it here. Hopefully soon.

> xcode/examples.h says that Compute is not supported on MoltenVK, but taking a look to the MoltenVK repository and searching for "Compute" I get several closed issues related to Compute

You're right about that. The fork above does include compute samples, but does not yet include tessellation samples. I'll add those when I get a chance.

**Comment by cesss** [comment]
Thanks a lot for the clarifications!! I'm closing this issue, because if you already have it in your to-do list to push back into this repo, it will get be eventually updated.
