### ISSUE TITLE
ShellScalingAPI.h missing

### ISSUE THREAD

**Issue by JackalopeGit** [SaschaWillems/Vulkan#574]
```
In file included from \base\vulkanexamplebase.cpp:9:0:

\base\vulkanexamplebase.h:16: error: ShellScalingAPI.h: No such file or directory
 #include <ShellScalingAPI.h>
          ^~~~~~~~~~~~~~~~~~~
```
With `MingGW 7.3.0 64bit`

**Comment by SaschaWillems** [comment]
That's only used for high-DPI scaling. If your compiler does not find this Windows header, just comment it out along with the part where high-DPI scaling is set.

**Comment by JackalopeGit** [comment]
#https://github.com/SaschaWillems/Vulkan/issues/575
Can't check if it compile, because of different issue.

**Comment by richardebel** [comment]
I commented out high-DPI scaling.  I built several of the examples with gcc9.1 and mingw-64 and they all worked
