### ISSUE TITLE
SPIR-V validation VulkanTools.cpp loadShaderGLSL

### ISSUE THREAD

**Issue by Eths33** [SaschaWillems/Vulkan#576]
New to Vulkan not exactly sure on this. (My shader is simple and runs, so thinking it is ok)
Is the id bound the pCode or "Magic number"?

File: VulkanTools.cpp
Function: VkShaderModule loadShaderGLSL(const char *fileName, VkDevice device, VkShaderStageFlagBits stage)
Line: 388

With VK_LAYER_LUNARG_core_validation enabled I see this error. 
ERROR: [Validation] :  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Invalid SPIR-V.  The id bound is larger than the max id bound 4194303.

Shader code being compiled, probably not relevant. 
`#version 450

layout (std140, binding = 0) uniform bufferVals {
    mat4 mvp;
    vec4 cLoc;
} myBufferVals;

layout (location = 0) in vec4 pos;
layout (location = 1) in vec4 inColor;
layout (location = 2) in vec3 instPos;
layout (location = 3) in vec3 instColor;

layout (location = 0) out vec4 outColor;

void main() {
   outColor = inColor;
   gl_Position = vec4(pos.x + instPos.x, pos.y + instPos.y, pos.z + instPos.z, 1.0);
}`

**Comment by SaschaWillems** [comment]
Don't use that function. Feeding GLSL directly into Vulkan was possible with early NVidia drivers but has since been deprecated. WIth all current implementations you're only allowed to load SPIR-V.

**Comment by Eths33** [comment]
Okay thank you.
