### ISSUE TITLE
Error loading mesh

### ISSUE THREAD

**Issue by cwabbott0** [SaschaWillems/Vulkan#58]
Half of the examples crash with an error like:

bloom: /builddir/build/BUILD/assimp-3.1.1/code/ObjFileParser.cpp:261: void Assimp::ObjFileParser::getVector(std::vector<aiVector3t<float> >&): Assertion `!"Invalid number of components"' failed.

I'm using my distro's (Fedora 23) version of assimp which is 3.1.1, since I'm not sure which version the Windows binary is and there isn't a Linux binary.

**Comment by eloj** [comment]
Earlier issues suggests you need 3.2

**Comment by SaschaWillems** [comment]
Yes, you need at least ASSIMP 3.2. Older version can't load animations from the COLLADA file. The animation is not perfectly repeatable anyway, so I'm looking for a different mesh to use for the example.

I'll also address the linux ASSIMP issue in the future.

**Comment by SaschaWillems** [comment]
I have added a paragraph about building on Linux that hints at assimp and that version 3.2 is required.
