### ISSUE TITLE
Multi / Linked GPU Example?

### ISSUE THREAD

**Issue by zezba9000** [SaschaWillems/Vulkan#581]
Was wondering if there was a multi gpu example that demos "alternate frame rendering" AFR?

No one has anything like this for Vulkan but D3D12 examples do.

**Comment by SaschaWillems** [comment]
Nothing I'm aware of. I'd do one myself, but I'm not on a multi-gpu setup.

**Comment by zezba9000** [comment]
I have 4 different multi-gpu systems. Crossfire x2 RX 580, Crossfire x2 R9 280x, SLI x2 GTX 960, and SLI x2 GTX 250.

I don't have time atm to make a demo myself as I'm focused on a different project but maybe I can help contribute here later.  If anyone ever has a multi-gpu test they would like me to run I can validate it for them. Just clearing the backbuffer in AFR mode would be good enough.

**Comment by engineer1109** [comment]
The idea is good.

**Comment by SaschaWillems** [comment]
Can you open up a sample request at the https://github.com/KhronosGroup/Vulkan-Samples?

**Comment by zezba9000** [comment]
K made one: https://github.com/KhronosGroup/Vulkan-Samples/issues/85

Also I'm working on a framework that will have m-gpu support in Vulkan and D3D12: https://github.com/reignstudios/Orbital-Framework

When I get it working there I can share what API features are needed to make an example here.

**Comment by nanokatze** [comment]
@zezba9000 in case it's still of interest to you, https://github.com/NVIDIA/Q2RTX/ is an example of using device groups, which is one of the ways to do multi gpu.

**Comment by zezba9000** [comment]
@nanokatze Ya device groups is the correct way for SLI/CrossFire like parody.
