### ISSUE TITLE
[Feature Request] VK_EXT_descriptor_indexing example?

### ISSUE THREAD

**Issue by GavinNL** [SaschaWillems/Vulkan#583]
Hello,

I wanted to first thank you for all the hard work you have put into this repo. It has been instrumental in my Vulkan learning experience!

I was hoping I could request an example using the VK_EXT_descriptor_indexing extension. I've been looking all over the web for anyone that had example code of using it, but couldn't seem to find any.

This extension is probably the most useful one I've seen since it allows you to bind all your textures at once as a unsized array, then simply index into whatever texture you need. Maybe you could convert ArrayTextures example to use descriptor indexing?

Thanks again!

**Comment by SaschaWillems** [comment]
Sure, been thinking about doing a sample for that but haven't had the time do so. I'll try to whip up something.

**Comment by SaschaWillems** [comment]
Closing this for now. If you still want an example for this, feel free to open up an issue at the Khronos Vulkan Samples Repository.
