### ISSUE TITLE
Application Crashed when use storage buffer array in shader

### ISSUE THREAD

**Issue by 13431904801** [SaschaWillems/Vulkan#584]
Hi~ when i test the code in compute shader like this:
struct textureFormat
{
	float r;
	float g;
	float b;
	float a;
};
layout(binding = 0) buffer BufferStruct {
   textureFormat values[];
};BufferStruct [2];

It works fine in PC, but when i try to run the demo in android. It Crashed without any information  . I have already enable the validation layer.  the difference is BufferStruct array size.

When i change BufferStruct [2] to BufferStruct [1] it works. It seems that the grammer is not support in andriod platform but i could not find any relative articles mentioned that. Is there anyone met this before?

**Comment by SaschaWillems** [comment]
This may be the wrong place to ask such questions. Android driver quality varies wildly, so you may encounter an actual driver bug that's causing the crash. So best would be asking the IHV of your device on a fix.
