### ISSUE TITLE
Help making a minimal application

### ISSUE THREAD

**Issue by PatrikTegelberg** [SaschaWillems/Vulkan#586]
HI, I am trying to make a minimal RTX application. I made a new project in Visual studio and copied in the dependencies for nv_ray_tracing_shadows.cpp. It does compile but it does not link. I am hoping you have a better guess than I regarding what I missed.

Your cloned repo does run by Visual studio's built in CMake after I copied an assimp dll to a system folder. I don't know how CMake works and I am new to Github.

This is the linker command line found in the project properties, Linker/Command line:
/OUT:"C:\Users\ptegelberg\Documents\Visual Studio 2017\MyProjects\VulkanRTXengine\x64\Debug\VulkanRTXengine.exe" /MANIFEST /NXCOMPAT /PDB:"C:\Users\ptegelberg\Documents\Visual Studio 2017\MyProjects\VulkanRTXengine\x64\Debug\VulkanRTXengine.pdb" /DYNAMICBASE "assimp.lib" "assimp-vc140-mt.lib" "vulkan-1.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG /MACHINE:X64 /INCREMENTAL /PGD:"C:\Users\ptegelberg\Documents\Visual Studio 2017\MyProjects\VulkanRTXengine\x64\Debug\VulkanRTXengine.pgd" /SUBSYSTEM:WINDOWS /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Debug\VulkanRTXengine.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"../external/vulkan" /LIBPATH:"../external/assimp" /LIBPATH:"C:\VulkanSDK\1.1.106.0\Lib" /TLBID:1

This is the C/C++ command line:
/JMC /permissive- /GS /W3 /Zc:wchar_t /I"C:\VulkanSDK\1.1.106.0\Include" /I"../external" /ZI /Gm- /Od /Fd"x64\Debug\vc141.pdb" /Zc:inline /fp:precise /D "NOMINMAX" /D "_USE_MATH_DEFINES" /D "VK_USE_PLATFORM_WIN32_KHR" /D "_DEBUG" /D "_WINDOWS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /FC /Fa"x64\Debug\" /EHsc /nologo /Fo"x64\Debug\" /Fp"x64\Debug\VulkanRTXengine.pch" /diagnostics:classic 

A clue to what might be wrong is that I need to define VK_USE_PLATFORM_WIN32_KHR manually. I have Vulkan SDK 1.1.106 installed.

I have 46 link errors. This is the first one: Error	LNK2001	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vks::tools::errorString(enum VkResult)" (?errorString@tools@vks@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4VkResult@@@Z)		

I followed the other Vulkan tutorial that uses GLFW and that works fine.

This is not an issue but I would be happy for your help.

Best regards, Patrik.

**Comment by SaschaWillems** [comment]
The linker error hints at a missing base library. Easiest way is to have CMake generate the project for your Visual Studio version, e.g. by running:

```cmake -G "Visual Studio 15 2017 Win64"``` 

Which will generate a complete solution you can simply open and build. That solution will also build the base library required by all examples:

![image](https://user-images.githubusercontent.com/10283127/60295210-6cd03400-9923-11e9-843a-891d62ca035d.png)

If you don't want to go this way, you have to manually add the base library to your CMake setup by adding 
```add_subdirectory(base)``` 
to your CMakeLists.txt.

And then you also need to tell your linker to use the base.lib that's generated.

**Comment by PatrikTegelberg** [comment]
Thanks for your reply, all sorted now :)
