### ISSUE TITLE
What is the enter project in visual studio

### ISSUE THREAD

**Issue by zoozooll** [SaschaWillems/Vulkan#589]
I built the source code with cmake-gui like follow picture:
![cmake](https://user-images.githubusercontent.com/1833571/60643404-88789480-9e65-11e9-8cc5-8c8483943750.JPG)
And than I opened the solution generated by cmake, and built it. It showed all projects but no one can be run as Win32 application.
![visual studio](https://user-images.githubusercontent.com/1833571/60643651-5ca9de80-9e66-11e9-9bff-2a2961095597.JPG)
How can I run this solution as an Win32 application?

**Comment by SaschaWillems** [comment]
Can you elaborate? It's unlcear what your question is about.

**Comment by zoozooll** [comment]
I updated my request. Thanks

**Comment by SaschaWillems** [comment]
All examples can be used as starting projects. Judging from your screenshot, you have set the "base" library as your startup project, which will obviously do nothing because that's a library. So just select one of the actual samples below as your startup project to run.
