### ISSUE TITLE
Latest Andriod studio fails to build samples

### ISSUE THREAD

**Issue by charles-lunarg** [SaschaWillems/Vulkan#597]
Android Studio 3.4 and Gradle 5.0+ fails to build due to a change in the include path for gradle projects. I tried different path seperators ( colon and dot) but nothing seemed to take. 
I have since gotten the project built under Android Studio 3.3.2 & Gradle 4.10.1.

> The project name 'examples/' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.1.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

**Comment by SaschaWillems** [comment]
Thanks for letting me know. I have updated too and again they introduced breaking changes. I'm currently trying to fix it.

**Comment by SaschaWillems** [comment]
I have reworked and updated the gradle build files, so building with Gradle 5.x should work now.
