### ISSUE TITLE
[Linux] libassimp.dll.a: error adding symbols: File format not recognized

### ISSUE THREAD

**Issue by bonsairobo** [SaschaWillems/Vulkan#6]
Usually Linux libraries don't use the 'dll' extension, so I assume this is a Windows binary.

**Comment by kainino0x** [comment]
Can confirm.

**Comment by kainino0x** [comment]
Just kidding - it went away on its own after a `git clean -dXf`. Must be some transient bug in the CMake setup.

**Comment by Marqin** [comment]
I also have this problem.

**Comment by Marqin** [comment]
Installing assimp ( so it will use system-one ) fixed it. It seems that `libassimp.dll.a` is broken.

**Comment by kainino0x** [comment]
Ah. I had also done installed system assimp, but I didn't realize that was the fix (I forgot to clean before rebuilding).

**Comment by SaschaWillems** [comment]
libassimp.dll.a is actually a linux library, but yes, it may be broken and it seems I have assimp installed on my linux machine too, so I didn't notice. Thanks for noticing, I'll take a look at at as soon as things have settled a bit.

**Comment by HumanZero** [comment]
The same with Windows. After building one of sample programs in VS, when running: assimp-vc140-mt.dll is missing. I haven't got time though to build attached assimp on my own. Looks like it's not attached to Solution.

**Comment by SaschaWillems** [comment]
Looks like I forgot to add this to the repository :/ Will upload it asap

**Comment by SaschaWillems** [comment]
Added with commit 7194db8dad2d8d0ca24d3bc036d19a8325e330a3

Forgot to force it, as the bin folder is ignored via .gitignore by default

**Comment by MacGamerFR** [comment]
Just a question, because I see you revolved the assimp-vc140-mt.dll (that i was getting myself), I build assimp myself, but I get a assimp-vc140-mtd.dll, did i made something wrong ?

**Comment by rasteron** [comment]
Does this work with MinGW (5.1)? I'm also getting the same error `file format not recognized` even with `git clean -dXf` as @kainino0x suggested.

**Comment by kainino0x** [comment]
My `git clean -dXf` only worked because I had installed assimp globally - and rebuilding from scratch caused it to redo the search.

**Comment by Spencer-H** [comment]
I am still getting this issue. I do NOT have assimp installed globally.

**Comment by Marqin** [comment]
@SaschaWillems I've examined that `libassimp.dll.a` and **it's not linux static library**. It looks like a Windows library, build with `cygwin`, but still **Windows library**.

Could you please provide proper linux library or at least delete this file, so CMake could complain that `assimp` is not installed in our OS ( so we have to install it by ourselves )?

**Comment by SaschaWillems** [comment]
@Marqin : Will do after work, I guess this was a leftover :/

**Comment by bertogs** [comment]
Confirmed as well, had to install assimp to fix it.

**Comment by dnery** [comment]
Also confirming the workaround on Arch... Installing `assimp` from `community` repos and re-runnning `cmake`/`make` solved the error... Listing assimp as a dependency on the **README** is probably the easiest solution for this.

**Comment by testuser147** [comment]
First of all, thanks for sharing these great examples with us.

I got them running on ARM (Nvidia Jetson TX1 Development Board with L4T 24.1 Beta) by building them with Cmake/make. I agree with @dnery: For convenience, it would be helpful to mention in README.md the assimp library must be installed to be able to build the examples on Linux. You might want to refer to this one: http://installion.co.uk/ubuntu/vivid/main/a/assimp-utils/install/index.html.

**Comment by SaschaWillems** [comment]
@testuser147 : Thx for that fix. I'll check if this works for all platforms. I usually test CMake on windows and linux, so if this works fine on both I'll push the fix.

**Comment by SaschaWillems** [comment]
I have removed the libassimp.dll.a which was a static library for windows that I used to test with MinGW and added a note about the assimp requirements for linux to the readme.
