### ISSUE TITLE
Add ScrollEvent to ExampleBase？

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#602]
Can you add ScrollEvent to examplebase API?
I try to achieve it by myself, but I found it is very buggy on X11.
I changed it to this struct.

### changed Struct
struct {
		bool left = false;
		bool right = false;
		bool middle = false;
        bool scrollUp = false;
        bool scrollDown = false;
	} mouseButtons;

### added         
       bool scrollUp = false;
       bool scrollDown = false;

and change the cpp code 

### changed cpp code
       case XCB_BUTTON_PRESS:
	{
		xcb_button_press_event_t *press = (xcb_button_press_event_t *)event;
		if (press->detail == XCB_BUTTON_INDEX_1)
			mouseButtons.left = true;
		if (press->detail == XCB_BUTTON_INDEX_2)
			mouseButtons.middle = true;
		if (press->detail == XCB_BUTTON_INDEX_3)
			mouseButtons.right = true;
        if (press->detail == XCB_BUTTON_INDEX_4)
            mouseButtons.scrollUp = true;
        if (press->detail == XCB_BUTTON_INDEX_5)
            mouseButtons.scrollDown = true;
	}
	break;
	case XCB_BUTTON_RELEASE:
	{
		xcb_button_press_event_t *press = (xcb_button_press_event_t *)event;
		if (press->detail == XCB_BUTTON_INDEX_1)
			mouseButtons.left = false;
		if (press->detail == XCB_BUTTON_INDEX_2)
			mouseButtons.middle = false;
		if (press->detail == XCB_BUTTON_INDEX_3)
			mouseButtons.right = false;
        if (press->detail == XCB_BUTTON_INDEX_4)
            mouseButtons.scrollUp = false;
        if (press->detail == XCB_BUTTON_INDEX_5)
            mouseButtons.scrollDown = false;

The scroll responce is very slow, and hard to use.
Does everybody know the right way to achieve detecting ScrollUp and ScrollDown

**Comment by SaschaWillems** [comment]
This is better asked at some forum like the Khronos Community, Slack or Reddit. I'm not doing much X11 myself and have no need for such an event.
