### ISSUE TITLE
Is there any way to copy a memory or buffer on one logical device to another logical device?

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#603]
Is there any way to copy a memory or buffer on one logical device to another logical device?
All logical devices are in one instance and one physical device.
I don't want to use CPU to achieve it. How to copy directly through GPU?

**Comment by SaschaWillems** [comment]
Yes, that's possible with ```VK_KHR_device_group```. If that's not available or devices are not part of the same group, then no, you'd have to manually copy via CPU.
