### ISSUE TITLE
`shadowmappingcascade` demo can choose unsupported format

### ISSUE THREAD

**Issue by chrisforbes** [SaschaWillems/Vulkan#607]
`vks::tools::getSupportedDepthFormat()` only checks if the format supports the depth stencil attachment usage.  However, depth+stencil formats are not required to be sampleable, so this can choose an unworkable format.

Manifests with swiftshader as asserts in debug (sampling from D32_SFLOAT_S8_UINT, which we don't support), or missing shadows / other more subtle misbehavior in release.

Since this demo doesn't actually use the stencil aspect for anything, perhaps it would be better to prefer a depth-only format, which *is* guaranteed to be sampleable if it's supported as a depth stencil attachment.

**Comment by SaschaWillems** [comment]
I have added a new function to the device class that also allows for checking if a depth format actually supports sampling.

I can't check this, as it works fine for me with swiftshader even without checking is sampling is supported.

**Comment by chrisforbes** [comment]
We added the missing feature in SwiftShader in the mean time for another reason :)
