### ISSUE TITLE
runing ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by wusidn** [SaschaWillems/Vulkan#61]
for ubuntu 14.04  and Compiler success

**Comment by Amadiro** [comment]
Do you have a driver installed that supports vulkan?

**Comment by SaschaWillems** [comment]
The examples require driver with API-Level 1.0.1. What does the vulkaninfo tool from the SDK display?

**Comment by wusidn** [comment]
Oh I am a rookie
