### ISSUE TITLE
strange glitches all over render

### ISSUE THREAD

**Issue by greyltc** [SaschaWillems/Vulkan#613]
Has anyone ever seen artifacts like this?
![Screenshot from 2019-09-14 11-03-18](https://user-images.githubusercontent.com/16778174/64909946-c3226700-d709-11e9-9ecc-31d1a53b8d89.png)
This is under Linux and they seem to be somehow related to Wayland, [but we can't figure it out!](https://github.com/felixdoerre/primus_vk/issues/32)
I have two GPUs in my laptop (Intel's in my CPU and a discrete Nvidia one). I only see them with my Nvidia one.

**Comment by SaschaWillems** [comment]
Is this only related to my samples? I don't test with wayland so I don't know that's causing this.

**Comment by greyltc** [comment]
This is solved. It wasn't an issue with this repo.
