### ISSUE TITLE
fail to run it on ubuntu

### ISSUE THREAD

**Issue by rlvc** [SaschaWillems/Vulkan#614]
it runs smoothly on WIN10 with a VERY old GPU GT730, but when i wanna run it on ubuntu,  i encounter a lot of problems. here is a breaf of my system:
    Operating System | Ubuntu 16.04.5 LTS
    Graphics Card | GeForce GTX 1080
    Driver | 430.50
    SDK Version | 1.1.121.0
but when i run Vulkan, it will return ERROR_INITIALIZATION_FAILED.

so i follow the guide of ["Getting Started with the Vulkan SDK"](https://vulkan.lunarg.com/doc/sdk/1.1.121.0/linux/getting_started_ubuntu.html) on the lunarg website, i install the vulkan-sdk first:

          1. wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          2. sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
          3. sudo apt update
          4. sudo apt install vulkan-sdk
then i tun vkvia as told, the return error shows "Vulkan failed to find a compatible driver", so i follow the doc and then find ["Vulkan Graphics Driver Problems"](https://vulkan.lunarg.com/doc/view/1.1.121.0/linux/via.html#user-content-vulkan-graphics-driver-problems). the doc tells that there are possiblely 4 kind of reasons:

         1. hardware not support Vulkan. but i found on nvidia website GEDORCE GTX 1080 is OK for vulkan1.1
         2. driver not support Vulkan. but i found on nvidia website driver 430.50 is OK for vulkan1.1
         3. no Vulkan driver with support for the OS. i am running on ubuntu 16.04.5 LTS, 
         4. driver failed to install properly. But i can use nvidia-smi to show the card, and i can run my other code on this GPU without VULKAN
if i run vulkaninfo, the error info is vulkaninfo.c:6155: failed with VK_ERROR_INITIALIZATION_FAILED

hope someone can help me! thanks!

**Comment by engineer1109** [comment]
apt install nvidia-driver-435
I run well on Ubuntu18.04

**Comment by SaschaWillems** [comment]
I'm also testing on Ubuntu with NVidia, and every thing works as expected. I don't think this problem is related to my samples, but rather a driver installation problem.
