### ISSUE TITLE
Small issue with ray direction in vk_nv_ray_tracing examples

### ISSUE THREAD

**Issue by n8vm** [SaschaWillems/Vulkan#616]
I think I've found a bug in the VK_NV_RAY_TRACING examples. I noticed that this line was giving me trouble when used in my renderer with a different projection matrix. All my ray directions were coming out the same.

https://github.com/SaschaWillems/Vulkan/blob/ca17e359649c4f25ae9aa07352cfe5f532a8ca13/data/shaders/nv_ray_tracing_basic/raygen.rgen#L22

It seems that for me, "target" can have a w which doesn't equal 1 after being transformed by cam.projinv. I was able to correct my "target" by substituting line 22 with `vec4 direction = cam.viewInverse*vec4(normalize(target.xyz / target.w), 0) ;`

I'm fairly certain target needs to be divided by the w component before being transformed by viewInverse.

**Comment by SaschaWillems** [comment]
Yes, dividing by ```w``` makes sense. I've fixed it in all shaders.

**Comment by JarrettSJohnson** [comment]
Fix seems to be missing from the current ray generation shaders after reorganization. Is this intentional?
