### ISSUE TITLE
loadShaderGLSL is out of date

### ISSUE THREAD

**Issue by baldurk** [SaschaWillems/Vulkan#62]
The loadShaderGLSL function here: [loadShaderGLSL](https://github.com/SaschaWillems/Vulkan/blob/7e8365630e94a2929e0b3ca383b9f201a0e74f03/base/vulkantools.cpp#L289-L317) is out of date with the released Vulkan (the NV_glsl extension just passes the glsl directly). But it should probably be removed as everyone basing things on the samples should do things right, not the horrible nasty glsl extension way :).

**Comment by SaschaWillems** [comment]
That's right, the current GLSL loading code deosn't make any sense with the NV_glsl extension available. So I'll remove it from the existing samples (new ones not public don't use it anymore) and may add a new example showing the use of the NV extension.
