### ISSUE TITLE
Is alignedAlloc actually necessary in the dynamic uniform buffer example?

### ISSUE THREAD

**Issue by jamiebk** [SaschaWillems/Vulkan#620]
I understand the need to use offsets at a multiple of the minUniformBufferOffsetAlignment *within* the host allocation (uboDataDynamic.model) - that is, relative to the start.

Is it necessary to align the *start* of the allocation to the same offset given that we are just copying from this memory to the mapped buffer? 

Could we just use:
`uboDataDynamic.model = (glm::mat4*)malloc(bufferSize);`
rather than:
`uboDataDynamic.model = (glm::mat4*)alignedAlloc(bufferSize, dynamicAlignment);`?

**Comment by Andreyogld3d** [comment]
> Could we just use:

No, because an unaligned access to uniform/storage buffers can decrease a performance. 
[We will receive error message from Validation layers:](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/41e6b844837919e3dec1e119da89f01b2f81ce46/layers/parameter_validation_utils.cpp#L2352)

**Comment by cforfang** [comment]
One could maybe argue about the benefit of aligning the memory for CPU performance reasons when operating on it. But in terms of Vulkan you're right that as long as the initial offset into the buffer is aligned, and the internal stride is a multiple of `minUniformBufferOffsetAlignment`, `malloc` vs `alignedAlloc` for the original CPU side allocation doesn't matter here. Vulkan only cares about what goes into the buffer -- the result of the `memcpy`. Put another way, Vulkan never sees the source data for the `memcpy` and does not care about its alignment.

**Comment by Andreyogld3d** [comment]
@cforfang , yes. You are right,  we can copy from unaligned memory from CPU side to aligned mapped pointer from vkMapMemory, but we need additional C/C++ code like as:
```
ubyte* ptr = vkMapMemory(...)
for (....) {
	memcpy(ptr, ptruboDataDynamic, sizeofglm::mat4());
	ptr += dynamicAlignment;
	ptruboDataDynamic+= sizeofglm::mat4();
}
```
In this case memcpy + alignedAlloc wiil be best solution, even if we have additional memory overhead for dynamicAlignment. Also, aligned memory access on CPU side can be faster than unaligned  ?

**Comment by cforfang** [comment]
Sure, there are no strong arguments for _not_ using `alignedAlloc` here I don't think, but just to point out you _could_ replace it with `malloc` (with no other changes) and that would be totally fine. :)

**Comment by jamiebk** [comment]
Thanks for your comments. 

@Andreyogld3d I realize there are significant advantages to allocating the memory in the same layout on the CPU side as the GPU needs it to be, and copying it with one memcpy, and that the memory overhead is probably negligible. My point was that you could use the exact same memory layout with `malloc`, so, the dynamic alignment is still used for the *offset* of objects in the source memory it's just that that same dynamic alignment doesn't *need* to be used for the *start* of the source memory, which is what `alignedAlloc` gives you. 

So you could use:
```
size_t bufferSize = OBJECT_INSTANCES * dynamicAlignment;
uboDataDynamic.model = (glm::mat4*)malloc(bufferSize);
```
rather than:
```
size_t bufferSize = OBJECT_INSTANCES * dynamicAlignment;
uboDataDynamic.model = (glm::mat4*)alignedAlloc(bufferSize, dynamicAlignment);
```
And the rest of the code can be *completely identical*.

As @cforfang said there is no reason to *not* use `alignedAlloc`, and it might give some performance improvements, but its just not *necessary*. You don't get any message from the validation layers you mention because these check the offset into the buffer, not the offset of the start of the data that was memcpyed into the buffer. In my opinion, using `alignedAlloc` in the context of this sample seems like an example of good practice but it obscures what is essential to using dynamic uniform buffers.

**Comment by jamiebk** [comment]
I'm happy to close this now, but just to be clear about what I take the conclusion to be: 
The use of alignedAlloc rather than just plain malloc in this example is at best an optimization but is probably does nothing except add confusion and as such **should be removed from the example**.
