### ISSUE TITLE
It seems comment needs update

### ISSUE THREAD

**Issue by archimedus** [SaschaWillems/Vulkan#622]
https://github.com/SaschaWillems/Vulkan/blob/ca17e359649c4f25ae9aa07352cfe5f532a8ca13/examples/nv_ray_tracing_basic/nv_ray_tracing_basic.cpp#L247

**Comment by archimedus** [comment]
It looks like here is a scratch size should be requested:
https://github.com/SaschaWillems/Vulkan/blob/e1e348ac7a5b468aadc958bfd998497d6570cb49/examples/nv_ray_tracing_basic/nv_ray_tracing_basic.cpp#L336-L339

I suppose `type` should be changed to:
```
memoryRequirementsInfo.type = VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV;
```

I suppose the initialization of `VkAccelerationStructureMemoryRequirementsInfoNV` for bottom level
https://github.com/SaschaWillems/Vulkan/blob/e1e348ac7a5b468aadc958bfd998497d6570cb49/examples/nv_ray_tracing_basic/nv_ray_tracing_basic.cpp#L179-L181
should be extended with
```
memoryRequirementsInfo.type = VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NV;
```
now it works due to lucky coincidence that  `VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NV = 0`

Same for `VkAccelerationStructureMemoryRequirementsInfoNV` for top level
https://github.com/SaschaWillems/Vulkan/blob/e1e348ac7a5b468aadc958bfd998497d6570cb49/examples/nv_ray_tracing_basic/nv_ray_tracing_basic.cpp#L216-L218

**Comment by SaschaWillems** [comment]
Thanks for adding those details. I'll update my samples accordingly. When I wrote them there wasn't any validation layer support for the rt extension, so those things slipped through.
