### ISSUE TITLE
Add examples of water reflect and refract

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#623]
Enchancement suggestion. Add examples of water reflect and refract

**Comment by SaschaWillems** [comment]
If you're talking about "old-school" reflections and refraction, which are done via rtt, then you can easily modify the offscreen sample.

I'm doing some toying with Vulkan and C++ lately and made exactly that recently:

![image](https://user-images.githubusercontent.com/10283127/68543483-f571dd00-03b7-11ea-84a4-e430c6e1676d.png)

**Comment by engineer1109** [comment]
Cool. You look so welcome.

**Comment by SaschaWillems** [comment]
Closing this. If you still need a proper example, feel free to open up an issue at the [Khronos Vulkan Samples Repository](https://github.com/KhronosGroup/Vulkan-Samples/issues).
