### ISSUE TITLE
A small bug for gcc compiling

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#628]
Link Problems:
[ 11%] Linking CXX executable ../bin/subpasses
CMakeFiles/subpasses.dir/subpasses/subpasses.cpp.o: In function `VulkanExample::buildCommandBuffers()':
subpasses.cpp:(.text._ZN13VulkanExample19buildCommandBuffersEv[_ZN13VulkanExample19buildCommandBuffersEv]+0x4a7): undefined reference to `vks::debugmarker::beginRegion(VkCommandBuffer_T*, char const*, glm::vec<4, float, (glm::precision)0>)'
subpasses.cpp:(.text._ZN13VulkanExample19buildCommandBuffersEv[_ZN13VulkanExample19buildCommandBuffersEv]+0x6d7): undefined reference to `vks::debugmarker::beginRegion(VkCommandBuffer_T*, char const*, glm::vec<4, float, (glm::precision)0>)'
subpasses.cpp:(.text._ZN13VulkanExample19buildCommandBuffersEv[_ZN13VulkanExample19buildCommandBuffersEv]+0x890): undefined reference to `vks::debugmarker::beginRegion(VkCommandBuffer_T*, char const*, glm::vec<4, float, (glm::precision)0>)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/subpasses.dir/build.make:89: recipe for target 'bin/subpasses' failed
make[2]: *** [bin/subpasses] Error 1
CMakeFiles/Makefile2:387: recipe for target 'examples/CMakeFiles/subpasses.dir/all' failed

It is because of the static lib libbase.a.
You can "
`
     add_definitions("-fPIC")   
     set(CMAKE_EXE_LINKER_FLAGS "-fno-pie -no-pie")  
`
"to solve it.
Static library address problems.

**Comment by SaschaWillems** [comment]
It compiles fine for me on gcc. Travis CI is setup to build with clang and gcc, and both work: https://travis-ci.org/SaschaWillems/Vulkan

**Comment by engineer1109** [comment]
It is my old objects bug. Timestamp doesn't update
