### ISSUE TITLE
Any Object picking Example?

### ISSUE THREAD

**Issue by julmich** [SaschaWillems/Vulkan#629]
Those Vulkan examples are the most useful ones currently, Thanks. 
Do you plan to add any Object picking example ? – and if not … what would be the best the approach  – 1. Color coded object on framebuffer or 2. Ray casing or …?  Thanks.

**Comment by giordi91** [comment]
@julmich I personally implemented color coding in the past, it gives you pixel accurate selection without no extra effort on the "engine" side. Doing ray-casting requires you to start hitting bounding boxes and possibly have accell structures (if you have a lot of objects). Would love to know if there are better ways to do it

**Comment by julmich** [comment]
@giordi91 - Yes , I know. I even did “non graphical” raycasting based on Bullet too. I know is more cumbersome, but in Vulkan we have compute and graphics pipelines and they share resources.So my point for ray casting / as ray tracing /was- if it is done in parallel on draw pipeline – it is look like a lot of gain – because we can get not only ID – but position, color etc.  From other side NVidia – already make Vulkan extensions for real time raytracing. I’ve made color coded object picking too- OpenGL – draw in a framebuffer and position the mouse pointer on this picture – but that is whole picture for one pixel and if I want to handle mouse hover – it is look like a lot of drawing for so small trivial thing. I am new in Vulkan and I see how I can do color coding in a sub pass- but again I just wanted to hear what would be the best approach. I think that depth buffer can be used also, for example – to be extended whit pixel alpha value as a color ID.

**Comment by julmich** [comment]
@giordi91 - Yes , I know. I even did “non graphical” raycasting based on Bullet too. I know is more cumbersome, but in Vulkan we have compute and graphics pipelines and they share resources.So my point for ray casting / as ray tracing /was- if it is done in parallel on draw pipeline – it is look like a lot of gain – because we can get not only ID – but position, color etc.  From other side NVidia – already make Vulkan extensions for real time raytracing. I’ve made color coded object picking too- OpenGL – draw in a framebuffer and position the mouse pointer on this picture – but that is whole picture for one pixel ...and if I want to handle mouse hover – it is look like a lot of drawing for so small trivial thing. I am new in Vulkan and I see how I can do color coding in a sub pass- but again I just wanted to hear what would be the best approach. I think that depth buffer can be used also, for example – to be extended whit pixel's alpha value as a color ID.

**Comment by SaschaWillems** [comment]
I don't have such a demo planned right now. But I'd go for the color picking route. 

This can be heavily optimized, by e.g. only rendering a very small viewport around the mouse cursor and doing the rendering while the fragment processing part of the pipeline is free while other heavy tasks use e.g. the vertex processing part of the pipeline.

Or you could go with layered attachments and render the color picking attachment in a single pass.

**Comment by julmich** [comment]
Thanks @SaschaWillems , I appreciate your help.

**Comment by giordi91** [comment]
@SaschaWillems  sorry for asking but how would you synchronize the color picking shader with a vertex heavy  shader (shadow mapping /depth prepass come to mind)? Simply submit shadow and right after the color picking shader and the driver should overlap those computation giving the fact shadow/depth prepass don't use a pixel shader?

**Comment by ShrivastavaKartik** [comment]
Hi @SaschaWillems , I'm implementing something similar to glReadPixels in Vulkan and I'm unable to come up with an approach to get a pixel color value of a given 2d pixel coordinates. Any help would be greatly appreciated.
