### ISSUE TITLE
computeshader

### ISSUE THREAD

**Issue by JavinYang** [SaschaWillems/Vulkan#630]
computeshader.cpp
```
void draw()
{
	VulkanExampleBase::prepareFrame();

	submitInfo.commandBufferCount = 1;
	submitInfo.pCommandBuffers = &drawCmdBuffers[currentBuffer];
	VK_CHECK_RESULT(vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE));

	VulkanExampleBase::submitFrame();
     
	// Submit compute commands
	// Use a fence to ensure that compute command buffer has finished executin before using it again
	vkWaitForFences(device, 1, &compute.fence, VK_TRUE, UINT64_MAX);
	vkResetFences(device, 1, &compute.fence);

	VkSubmitInfo computeSubmitInfo = vks::initializers::submitInfo();
	computeSubmitInfo.commandBufferCount = 1;
	computeSubmitInfo.pCommandBuffers = &compute.commandBuffer;

	VK_CHECK_RESULT(vkQueueSubmit(compute.queue, 1, &computeSubmitInfo, compute.fence));
}
```
I don't quite understand here.
drawCmdBuffers[currentBuffer] runs before compute.commandBuffer, but the consumer drawCmdBuffers[currentBuffer] requires the textureComputeTarget produced by the producer compute.commandBuffer.
_1. I don't understand why drawCmdBuffers[currentBuffer] is called before compute.commandBuffer._
In the following code, only the first frame is rendered, while the right picture does not get the textureComputeTarget, so it is rendered with a blue background.
```
void draw()

{
	VulkanExampleBase::prepareFrame();

	submitInfo.commandBufferCount = 1;
	submitInfo.pCommandBuffers = &drawCmdBuffers[currentBuffer];
	VK_CHECK_RESULT(vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE));

	VulkanExampleBase::submitFrame();
     
	// Submit compute commands
	// Use a fence to ensure that compute command buffer has finished executin before using it again
	vkWaitForFences(device, 1, &compute.fence, VK_TRUE, UINT64_MAX);
	vkResetFences(device, 1, &compute.fence);

	VkSubmitInfo computeSubmitInfo = vks::initializers::submitInfo();
	computeSubmitInfo.commandBufferCount = 1;
	computeSubmitInfo.pCommandBuffers = &compute.commandBuffer;

	VK_CHECK_RESULT(vkQueueSubmit(compute.queue, 1, &computeSubmitInfo, compute.fence));

       sleep(1000) // <-------- Wait
}
```
Executed when calling ``vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE)``:
```
VkImageMemoryBarrier imageMemoryBarrier = {};
imageMemoryBarrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
// We won't be changing the layout of the image
imageMemoryBarrier.oldLayout = VK_IMAGE_LAYOUT_GENERAL;
imageMemoryBarrier.newLayout = VK_IMAGE_LAYOUT_GENERAL;
imageMemoryBarrier.image = textureComputeTarget.image;
imageMemoryBarrier.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 };
imageMemoryBarrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
imageMemoryBarrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
vkCmdPipelineBarrier(
    drawCmdBuffers[i],
    VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
    VK_FLAGS_NONE,
    0, nullptr,
    0, nullptr,
    1, &imageMemoryBarrier);
vkCmdBeginRenderPass(drawCmdBuffers[i], &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);
```
_2. Wait for VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, but this phase has not been executed before, why is the pipeline not stuck? Is it because there is no pipeline before, so there is no need to wait?_

In section 6.6 Pipeline Barriers
vkCmdPipelineBarrier is a synchronization command that inserts a dependency between commands submitted to the **same queue**, or between commands in the **same subpass**.
```
void draw()
{
    printf("%p, %p\n", queue, compute.queue);
        
    VulkanExampleBase::prepareFrame();

    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &drawCmdBuffers[currentBuffer];
    VK_CHECK_RESULT(vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE));

    VulkanExampleBase::submitFrame();
         
    // Submit compute commands
    // Use a fence to ensure that compute command buffer has finished executin before using it again
    vkWaitForFences(device, 1, &compute.fence, VK_TRUE, UINT64_MAX);
    vkResetFences(device, 1, &compute.fence);

    VkSubmitInfo computeSubmitInfo = vks::initializers::submitInfo();
    computeSubmitInfo.commandBufferCount = 1;
    computeSubmitInfo.pCommandBuffers = &compute.commandBuffer;

    VK_CHECK_RESULT(vkQueueSubmit(compute.queue, 1, &computeSubmitInfo, compute.fence));
    sleep(1000);
}
```
Print results:
0x6000039c4a20, 0x6000039c4a20
The current queue and compute.queue are the same queue.But it is possible that the above code may generate different queue. 
_3. Can VkImageMemoryBarrier be synchronized in multiple queues?_

_4. vkCmdPipelineBarrier is a synchronization command that inserts a dependency between commands submitted to the same queue, **or** between commands in the same subpass. why use **"or"**, why not use **"and"**?_

**Comment by SaschaWillems** [comment]
> 1. I don't understand why drawCmdBuffers[currentBuffer] is called before compute.commandBuffer.
In the following code, only the first frame is rendered, while the right picture does not get the textureComputeTarget, so it is rendered with a blue background.

It doesn't matter. Producer is not quite the right term here anyway. The compute shader just writes to a texture, and that texture is present and valid even before the compute shader has run.

But yes, you may switch ordering.

> 2. Wait for VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, but this phase has not been executed before, why is the pipeline not stuck? Is it because there is no pipeline before, so there is no need to wait?

The barrier is fine. That dependency just makes sure that all commands up to that stage have finished execution.

> The current queue and compute.queue are the same queue.But it is possible that the above code may generate different queue.

If you want to use different queue families for compute and graphics you need to insert ownership transfer barriers on both queues.

> 3. Can VkImageMemoryBarrier be synchronized in multiple queues?

Yes, via semaphores.

> 4. vkCmdPipelineBarrier is a synchronization command that inserts a dependency between commands submitted to the same queue, or between commands in the same subpass. why use "or", why not use "and"?

Because it makes a difference. A barrier outside of a subpass sets up a dependency for commands recorded before and after, a barrier inside a subpass is only limited to commands in that subpass.

**Comment by JavinYang** [comment]
@SaschaWillems 
Thank you very much, I have gained a lot in these demos.
