### ISSUE TITLE
Validation errors during mipmapping layout setup

### ISSUE THREAD

**Issue by sasmaster** [SaschaWillems/Vulkan#631]
Hi.
I have been learning from your texturemipmapgen.cpp example how to generate mipmaps.
I did my first attempt on this one from https://vulkan-tutorial.com.
Then decided to check this sample which looks more compact.With  validation layers on,when

```
vks::tools::setImageLayout(
				blitCmd,
				texture.image,
				VK_IMAGE_LAYOUT_UNDEFINED,
				VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
				mipSubRange,
				VK_PIPELINE_STAGE_TRANSFER_BIT,
				VK_PIPELINE_STAGE_HOST_BIT);
```

Is set inside mipmap gen loop before the call to `vkCmdBlitImage` the validation output spits the following error:

Severity: Error,Type:Validation,12:04:12 ERROR  \..\vulkaninfrastructure.cpp Function:debugCallback Line:90 Message:Message:vkCmdPipelineBarrier()

> : pImageMemBarriers[0].dstAccessMask (0x1000) is not supported by dstStageMask (0x4000).

 The Vulkan spec states: Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)

Where dstAccessMask =VK_ACCESS_TRANSFER_WRITE_BIT,dstStageMask=VK_PIPELINE_STAGE_HOST_BIT.

The  demo still ends up running with mipmapped image ok. But it would be nice to get pointed out to the reason why this setup causes Vulkan to complain. Mostly for the learning purposed.

Thanks.

**Comment by sasmaster** [comment]
I added this :

```
       if (dstStageMask== VK_PIPELINE_STAGE_HOST_BIT)
	{
		imageMemoryBarrier.dstAccessMask = 0;
	}

	if (srcStageMask == VK_PIPELINE_STAGE_HOST_BIT)
	{
		imageMemoryBarrier.srcAccessMask = 0;
	}
```

Now the validation errors are gone. Could you explain to a noob like me why srcAccessMask and dstAccessMask in this case must be not set?

**Comment by SaschaWillems** [comment]
I haven't had time to update that sample yet to get validation clean.

As the validation message tells you: The access masks I've been using are simply not compatible with the selected pipeline stage. That's something that the validation layers did not check when I wrote that sample.

You can find a table on what access flag is supported for what pipeline stage at https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkAccessFlagBits.html

I'm a bit short on time as of currently, but I'll try to fix this as soon as possible.

**Comment by SaschaWillems** [comment]
I have pushed an update that fixes the validation messages. This change uses a more explicit function for specifying barriers, so in addition to fixing the barriers this also selects proper stages (instead of ```VK_PIPELINE_STAGE_ALL_COMMANDS_BIT``` as ```setImageLayout```) did.
