### ISSUE TITLE
PbrTexture crashing after updating to libktx replacing with gli

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#640]
pbrtexture: /home/wjl/github/Vulkan/base/VulkanTexture.hpp:114: void vks::Texture2D::loadFromFile(std::__cxx11::string, VkFormat, vks::VulkanDevice*, VkQueue, VkImageUsageFlags, VkImageLayout, bool): Assertion `result == KTX_SUCCESS' failed.
Aborted (core dumped)

GDB results:
1 __GI_raise                   raise.c           51   0x7ffff53cae97 
2 __GI_abort                   abort.c           79   0x7ffff53cc801 
3 __assert_fail_base           assert.c          92   0x7ffff53bc39a 
4 __GI___assert_fail           assert.c          101  0x7ffff53bc412 
5 vks::Texture2D::loadFromFile VulkanTexture.hpp 114  0x5555555aac7a 
6 VulkanExample::loadAssets    main.cpp          212  0x5555555b05ab 
7 VulkanExample::prepare       main.cpp          1423 0x5555555baec8 
8 main                         main.cpp          1462 0x5555555a7d73 

Break point:
textures.aoMap.loadFromFile(ASSET_PATH "models/cerberus/ao.ktx", VK_FORMAT_R8_UNORM, vulkanDevice, queue);

**Comment by SaschaWillems** [comment]
Please re-download the asset pack. It seems that something was wrong/broken with some of the model's textures. I re-saved them with the PowerVR Texture tools and after that it worked again.
