### ISSUE TITLE
Is it allowed to use this full commercially in an engine?

### ISSUE THREAD

**Issue by Noel2003** [SaschaWillems/Vulkan#642]
I know this is MIT License, but is it really allowed to use all the source code with shaders and example base framework in a commercial engine?
Whats about the 3D-Models?

Cheers
Noël

**Comment by SaschaWillems** [comment]
MIT to my knowledge is okay to use for a commercial product. But I'm not a copyright lawyer, so if unsure you should get professional advise.

Assets come with their own licenses, so you have to check on a per-asset base.
