### ISSUE TITLE
What is going on here with pipelineDepthStencilStateCreateInfo?

### ISSUE THREAD

**Issue by jmatzen** [SaschaWillems/Vulkan#648]
https://github.com/SaschaWillems/Vulkan/blob/e18d42824930dc2d2a23a68914ed5b52cfafe27b/base/VulkanInitializers.hpp#L454

Specifically why is back (presumably default initialized) copied to front?  Shouldn't they be the same values?

**Comment by SaschaWillems** [comment]
That's a left-over and doesn't make any sense. I'll remove this.
