### ISSUE TITLE
Wrong pipeline stage in example vkCmdPipelineBarrier (?)

### ISSUE THREAD

**Issue by k-j0** [SaschaWillems/Vulkan#649]
Hi!

The [Compute Particles example](https://github.com/SaschaWillems/Vulkan/blob/master/examples/computeparticles/computeparticles.cpp) uses vkCmdPipelineBarrier on lines 197 and 223 with the pipeline stage VK_PIPELINE_STAGE_VERTEX_SHADER_BIT respectively as srcStageMask and as dstStageMask. VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT is used by both barriers as respectively the srcAccessMask and dstAccessMask. However, the [Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#synchronization-access-types-supported) indicates that VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT can only be used with a corresponding pipeline stage of VK_PIPELINE_STAGE_VERTEX_INPUT_BIT (as opposed to VK_PIPELINE_STAGE_VERTEX_SHADER_BIT). This is also picked up by the core validation layers. If this is indeed a typo in the code, is it meant to read VK_PIPELINE_STAGE_VERTEX_INPUT_BIT as the pipeline stage for both barriers?

Cheers!

**Comment by SaschaWillems** [comment]
Yes, those barriers aren't okay. I'm currently reworking synchronization for all the compute demos.
