### ISSUE TITLE
how to render the real-time stream of Yuv420

### ISSUE THREAD

**Issue by huyu0415** [SaschaWillems/Vulkan#654]
There is a question, in wulkan 1.0.0 how to render the real-time stream of Yuv420, just like the Yuv data decoded by Decoder, how to render it in real time.

**Comment by SaschaWillems** [comment]
Can you elaborate? Are you looking for help on how to decode and render video streams? If so, you may be better off asking questions at dedicated Forums like over at Khronos or Reddit.

**Comment by SaschaWillems** [comment]
Closing this, as this is not an issue related to my code.
