### ISSUE TITLE
Subpasses: app resume on Android causes MMU page fault

### ISSUE THREAD

**Issue by Yours3lf** [SaschaWillems/Vulkan#656]
Hi,

we found that while the subpasses example works fine normally, if the user presses the Home button on Android, and then resume the app, it will show black screen.

The issues is caused by:
After the app moves from background to foreground, it will create the new VkDevice and record draw command on the new VkCommandbuffer created from the new VkDevice. However, the app doesn't re-create and allocate all of the resources for the new VkDevice. The app binds the old index buffer allocated from the old VkDevice on the new VkCommandBuffer. 

This causes an MMU page fault.

**Comment by SaschaWillems** [comment]
Thanks for detailed rundown of the cause. I'll take a look at this as soon as possible.
