### ISSUE TITLE
Unused/Wrong stuff in shadowmapping example

### ISSUE THREAD

**Issue by ScrappyCocco** [SaschaWillems/Vulkan#657]
This format here:
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/examples/shadowmapping/shadowmapping.cpp#L39
Is only referenced here:
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/examples/shadowmapping/shadowmapping.cpp#L243
But then `fbColorFormat ` is not used, and `DEPTH_FORMAT` is always used instead, is this correct?

**Comment by ScrappyCocco** [comment]
Also, there are commented lines in shadowmapping shaders that, if not used, should be removed to avoid confusion:
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/data/shaders/shadowmapping/offscreen.frag#L4
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/data/shaders/shadowmapping/offscreen.frag#L8
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/data/shaders/shadowmapping/scene.frag#L63

**Comment by ScrappyCocco** [comment]
The `uniformBuffers.debug` is created with size `sizeof(uboVSscene)`
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/examples/shadowmapping/shadowmapping.cpp#L659
But is only used with `sizeof(uboVSquad):`
https://github.com/SaschaWillems/Vulkan/blob/8acc59a2e1df3584b661da117cb8a639a200f7ed/examples/shadowmapping/shadowmapping.cpp#L701
So can probably be allocated with size `sizeof(uboVSquad)` if i'm not wrong

**Comment by SaschaWillems** [comment]
Thx for raising this issue. I'll take a look at these.

**Comment by ScrappyCocco** [comment]
@SaschaWillems thank you for fixing the code, another small question: Why keeping `offscreen.frag`?
Looks like it's never used
