### ISSUE TITLE
something broken in subpasses demo, on window resize

### ISSUE THREAD

**Issue by danilw** [SaschaWillems/Vulkan#659]
Windows 10

Nvidia and AMD drivers latest

Screenshots

1. after launch **not broken**
![1](https://user-images.githubusercontent.com/24825887/73425435-ae561100-4342-11ea-8e84-5507dd07fb01.png)

2. **broken**, Nvidia black screen, AMD display some *trash-pixels* with image
that hapened after resize few times small/big (even just little resize)
![2](https://user-images.githubusercontent.com/24825887/73425436-ae561100-4342-11ea-9b8e-66ee5e49a8db.png)

Edit: same in other OS, tested in Linux, crash to error:
```
Fatal : VkResult is "ERROR_DEVICE_LOST" in Vulkan/base/vulkanexamplebase.cpp at line 665
subpasses: Vulkan/base/vulkanexamplebase.cpp:665: void VulkanExampleBase::submitFrame(): Assertion `res == VK_SUCCESS' failed.
```

**Comment by eloj** [comment]
Sounds like #414

**Comment by SaschaWillems** [comment]
Yes, I'm aware of this. That sample has a few problems that I need to tackle. Haven't had time for that yet.

**Comment by SaschaWillems** [comment]
Please check again. I have updated the sample to properly handle resizes.

**Comment by danilw** [comment]
it work now, on both Nvidia and AMD
