### ISSUE TITLE
Official Khronos Vulkan Sample Repository

### ISSUE THREAD

**Issue by SaschaWillems** [SaschaWillems/Vulkan#662]
Khronos has recently released an official Vulkan Samples Repository at https://github.com/KhronosGroup/Vulkan-Samples where I'm also contributing.

While I'll still be working on this repository, I'll mainly add new samples to the Khronos Repository.

So if you want to request new examples, please open up an issue at the [Khronos Repository](https://github.com/KhronosGroup/Vulkan-Samples/issues).

**Comment by eero-t** [comment]
While it's nice to have an official place for them, I'm a bit disappointed that they don't have screenshots of what the sample output should look like, and that the screenshots have been removed from this repository doc.

(They were very useful in determining whether given driver version was rendering the sample correctly / filing bugs against that driver, as user of the sample may not have HW with a fully functioning driver, or one that had regressed.)

**Comment by SaschaWillems** [comment]
I hav added current screenshots for all the samples in the repo in the screenshots folder. Having them up-to-date makes a lot of sense, esp. for IHVs that test their implementations.

**Comment by eero-t** [comment]
Great!  It would be nice if they would be linked from README too though.
