### ISSUE TITLE
Included assimp headers are out-of-sync with later assimp versions causing stack corruption in some cases

### ISSUE THREAD

**Issue by gary-sweet** [SaschaWillems/Vulkan#663]
It looks like the assimp headers that you have in your external/assimp/assimp folder are pretty old (from the v3.2 of assimp). Using a newer version of assimp (it's now on v5.0.1) results in a mismatch between your version of the headers and assimp's. That causes stack corruption when using parts of the assimp API. That causes problems for me (in embedded Linux) in 'scenerendering' and 'skeletalanimation'.

I've changed our build to pull the v3.2 tagged version of assimp rather than the latest and those problems go away. The minimal change here would be to document that exactly v3.2 was required, I think you currently state that at least v3.2 is needed.

**Comment by huangxiaoxi** [comment]
hi, Gary
How to pull the v3.2 tagged version of assimp?

**Comment by SaschaWillems** [comment]
I have removed ASSIMP and replaced it with a custom glTF loader based on the header-only tinyglTF, so closing this.
