### ISSUE TITLE
Queue Family Ownership Transfer in the compute shader example

### ISSUE THREAD

**Issue by ansicode** [SaschaWillems/Vulkan#667]
in examples/computeshader/computeshader.cpp line 142:

> // Sharing mode exclusive means that ownership of the image does not need to be explicitly transferred between the compute and graphics queue
		imageCreateInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

but the [vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-queue-transfers) says:

> Resources created with a VkSharingMode of VK_SHARING_MODE_EXCLUSIVE must have their ownership explicitly transferred from one queue family to another in order to access their content in a well-defined manner on a queue in a different queue family.

and,

> An application must ensure that these operations occur in the correct order by defining an execution dependency between them, e.g. using a semaphore.

so i don't  understand why this example runs well without any validation layer error.
Should we add a semaphore between the compute queue and graphics queue, and two VkCmdPipelineBarriers to transfer the ownership?

**Comment by SaschaWillems** [comment]
Yes, I'm aware of this. There are multiple issues regarding compute synchronization. Work on this is documented at the Khronos samples repo, see [#3](https://github.com/KhronosGroup/Vulkan-Samples/issues/3).
