### ISSUE TITLE
examples/skeletalanimation/skeletalanimation.cpp line 570:

### ISSUE THREAD

**Issue by Judgecut** [SaschaWillems/Vulkan#669]
```
vertex.pos = glm::make_vec3(&skinnedMesh->scene->mMeshes[m]->mVertices[v].x);
vertex.normal = glm::make_vec3(&skinnedMesh->scene->mMeshes[m]->mNormals[v].x);
vertex.uv = glm::make_vec2(&skinnedMesh->scene->mMeshes[m]->mTextureCoords[0][v].x);
vertex.color = (skinnedMesh->scene->mMeshes[m]->HasVertexColors(0)) ? glm::make_vec3(&skinnedMesh->scene->mMeshes[m]->mColors[0][v].r) : glm::vec3(1.0f);
```

The function loadmesh()，vertex.pos.x vertex.pos.y vertex.pos.z all is equal to the mVertices[v].x，mesh data is error？

**Comment by SaschaWillems** [comment]
Can you please elaborate? It's not clear from your description if this is a bug, a question or a suggestion.

**Comment by Judgecut** [comment]
skinnedMesh->scene->mMeshes[m]->mVertices 0x0000016646349eb0 {x=-137.281006 y=364.010986 z=1633.54004 }

`vertex.pos = glm::make_vec3(&skinnedMesh->scene->mMeshes[m]->mVertices[v].x);`

but use glm::make_vec3 after, vertex.pos value is {x=-137.281006 r=-137.281006 s=-137.281006 ...},
I think is a bug?

**Comment by Judgecut** [comment]
I think I find real problem, the skeletalanimationmesh.vert UBO line 12:
```
layout (binding = 0) uniform UBO 
{
	mat4 projection;
	mat4 view;
	mat4 model;
	mat4 bones[MAX_BONES];	
	vec4 lightPos;
	vec4 viewPos;
} ubo;
```

but in skeletalanimation.cpp line 368:
```
struct {
	glm::mat4 projection;
	glm::mat4 model;
	glm::mat4 view;
	glm::mat4 bones[MAX_BONES];
	glm::vec4 lightPos = glm::vec4(0.0f, -250.0f, 250.0f, 1.0);
	glm::vec4 viewPos;
} uboVS;
```

order of view and model is different，so can not show mesh in example well, is a bug...

**Comment by SaschaWillems** [comment]
Yes, that's obviously wrong. I'll take a look at it.

**Comment by Judgecut** [comment]
the sample is ok now, thanks.

the sample can not rendering skinned mesh(only render a floor) before I fixed uboVS.model matrix.
In the function updateUniformBuffers() line 942:
```
uboVS.view = viewMatrix * glm::translate(glm::mat4(1.0f), glm::vec3(cameraPos.x, -cameraPos.z, cameraPos.y) * 100.0f);
uboVS.view = glm::rotate(uboVS.view, glm::radians(rotation.x), glm::vec3(1.0f, 0.0f, 0.0f));
uboVS.view = glm::rotate(uboVS.view, glm::radians(rotation.z), glm::vec3(0.0f, 1.0f, 0.0f));
uboVS.view = glm::rotate(uboVS.view, glm::radians(-rotation.y), glm::vec3(0.0f, 0.0f, 1.0f));
uboVS.viewPos = glm::vec4(0.0f, 0.0f, -zoom, 0.0f);
uboFloor.projection = uboVS.projection;
```
uboVS.model is invalid. there are not assigned a useful value but vertexshader used it.

**Comment by SaschaWillems** [comment]
I have reworked parts of that sample. All matrices should now be properly initialized.
