### ISSUE TITLE
MultiView Smal glitch on intel hd

### ISSUE THREAD

**Issue by jack-javana** [SaschaWillems/Vulkan#672]
i have small glitches in Multi View Demo
![Screenshot from 2020-02-21 01-45-03](https://user-images.githubusercontent.com/56049751/74981695-2a2c1080-544c-11ea-837f-8deaa3f961b7.png)

info:
OS fedora linux 31 
Kernel 5.4.18
Mesa 19.2.8
intel hd 630 (Kaby Lake)
I see this glitch under xorg and under wayland

**Comment by jack-javana** [comment]
And if i resize window i get this
![Screenshot from 2020-02-21 01-55-48](https://user-images.githubusercontent.com/56049751/74982344-614ef180-544d-11ea-89db-1b4f302ab615.png)

**Comment by SaschaWillems** [comment]
Are you getting any validation layer issues? I have tested this sample on many different implementations, including Intel on Linux and never saw something like this.

**Comment by jack-javana** [comment]
No

**Comment by jack-javana** [comment]
there are no glitches in other demo's

**Comment by jack-javana** [comment]
ok i found error 
https://pastebin.com/aBcPMaBS

**Comment by SaschaWillems** [comment]
I'm not getting any validation layer messages. Do you get them after resizing the window? I can also imagine that this happens if your screen's height is smaller than the initial height of the sample. Can you run the sample with -w 640 -h 480 to rule this out?

**Comment by jack-javana** [comment]
Ok 
how do i get access to the computer i try

**Comment by jack-javana** [comment]
I tested 
With -w 640 -h 480  i don't get glitch's
