### ISSUE TITLE
Read information under mouse

### ISSUE THREAD

**Issue by Rominitch** [SaschaWillems/Vulkan#676]
Dear Devs,

I created a quick demo to read specific layout of my framebuffer based on mouse position.
It's write gl_InstanceIndex inside layout and inject which is under mouse to show high-lighting.
This demo is based on deferred demo.

Currently, demo does all I want but performances are not very perfect and validation layout give some error.
Do you know a mean to improve them ?
- install barrier to have better sync ?
- use optimal VK_IMAGE_LAYOUT_XXX
- avoid to dump all image's data and setup better viewport/scissor (I think GPU->CPU bandwidth is not an issue).

See my Vulkan fork (this commit 399d3051d05cb92cf155291312e5fe289a2d0471).

Thanks

PS: Sorry, I code it quickly and my knowledge about Vulkan are not very good.
Don't hesitate to integrate this demo if you think it's important to community.

**Comment by SaschaWillems** [comment]
I don't plan on adding such a demo to my repo. If you're having performance problem, try to narrow down the area you read from (e.g. to just 1 pixel) and maybe do async readbacks.
