### ISSUE TITLE
physicalDeviceFeatures2 used out of scope on pNext

### ISSUE THREAD

**Issue by ewerness-nv** [SaschaWillems/Vulkan#678]
`			// If a pNext(Chain) has been passed, we need to add it to the device creation info
			if (pNextChain) {
				VkPhysicalDeviceFeatures2 physicalDeviceFeatures2{};
...
				deviceCreateInfo.pNext = &physicalDeviceFeatures2;
			}
`

Then deviceCreateInfo is used outside that scope. Moving the definition of physicalDeviceFeatures2 outside the if (pNextChain) fixes the issue.

**Comment by SaschaWillems** [comment]
Thanks for noticing. Will fix this.
