### ISSUE TITLE
Shadowmapping: App uses a renderpass which is incompatible with the specified framebuffer

### ISSUE THREAD

**Issue by kbiElude** [SaschaWillems/Vulkan#68]
VulkanExampleBase::prepareOffscreenFramebuffer() sets up a color image view, which uses R8G8B8A8_UNORM format, and a depth image view of **D16_UNORM** format. These are then used to form a framebuffer, which is used for shadow map rendering process.

To render SMs, the framework re-uses a renderpass created earlier, which is initialized as per sshots below:

![image](https://cloud.githubusercontent.com/assets/9154207/13646460/dc0c50ec-e62f-11e5-9826-0f091d8cb9ce.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13646472/ed72fd72-e62f-11e5-8a5d-0cc3be0cdb15.png)

While B8G8R8A8_UNORM is just a swizzled version of R8G8B8A8_UNORM, the real problem here is **D32F_S8** is incompatible with **D16_UNORM**, so the renderpass must not be used with the off-screen framebuffer.

**Comment by SaschaWillems** [comment]
Thanks for spotting this :+1: Seems that the current public SDK's validation layers don't catch this and the GPUs I've tested on neither. Will fix this
