### ISSUE TITLE
Double delete

### ISSUE THREAD

**Issue by ScrappyCocco** [SaschaWillems/Vulkan#684]
Duble delete of the same object in computeparticles.cpp

https://github.com/SaschaWillems/Vulkan/blob/67f1c2904c05181542022b83101720dda4f48607/examples/computeparticles/computeparticles.cpp#L112

https://github.com/SaschaWillems/Vulkan/blob/67f1c2904c05181542022b83101720dda4f48607/examples/computeparticles/computeparticles.cpp#L113

**Comment by ScrappyCocco** [comment]
Same as issue #682

**Comment by SaschaWillems** [comment]
Fixed, see #682.
