### ISSUE TITLE
[deferred] Vertex input inconsistent across examples

### ISSUE THREAD

**Issue by Spirrwell** [SaschaWillems/Vulkan#685]
Hello there!

I was trying to learn from the deferred example and I got very confused because it binds the quad vertex buffer and index buffer here: https://github.com/SaschaWillems/Vulkan/blob/master/examples/deferred/deferred.cpp#L592

But the deferred.vert shader here doesn't take any vertex input: https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/deferred/deferred.vert

This seems wrong even though it still somehow works.

The deferredshadows example shader DOES take in vertex input.
The deferredmultisampling shader does NOT, but it just uses vkCmdDraw here: https://github.com/SaschaWillems/Vulkan/blob/master/examples/deferredmultisampling/deferredmultisampling.cpp#L559

It seems like the deferred project could just use vkCmdDraw like deferredmultisampling.

I don't know enough about shaders, but if it could be done, it would probably make sense for deferredshadows to be made consistent with deferredmultisampling as well.

**Comment by SaschaWillems** [comment]
> This seems wrong even though it still somehow works.

No, that's perfectly valid. The shader generates the position and uvs from the vertex index to render a full-screen quad. This does not require any buffers to be bound. The fact that some samples still use buffers for drawing such a quad is because I haven't had the time to update them. 

You can read up on how this works over here: https://www.saschawillems.de/blog/2016/08/13/vulkan-tutorial-on-rendering-a-fullscreen-quad-without-buffers/

**Comment by Spirrwell** [comment]
I understand the drawing a single triangle as a fullscreen quad (that visual helps a lot)

It's the use of the buffers that I find really confusing. The draw is being executed with vkCmdDrawIndexed, An index count of 6 is being passed in, but shouldn't this be 3? Wouldn't 6 be two triangles?

**Comment by SaschaWillems** [comment]
That call actually draws two triangles (6 indices) for a full-screen quad. That's older code, and is not as efficient as the newer code that just does a vkCmdDraw to render a full-screen triangle.

**Comment by SaschaWillems** [comment]
I have recently reworked this, and it's now consistent across the deferred samples.
