### ISSUE TITLE
scenerendering run failed due to lack of file

### ISSUE THREAD

**Issue by huangxiaoxi** [SaschaWillems/Vulkan#686]
/Vulkan_Sascha/bin# ./scenerendering
Material "n_zid_001"
  Diffuse: "n.ktx"
Could not load texture from ../data/models/sibenik/n_etc2_unorm.ktx

The file may be part of the additional asset pack.

Run "download_assets.py" in the repository root to download the latest version.

**Comment by SaschaWillems** [comment]
Please elaborate? Are you running from the proper directory?

**Comment by huangxiaoxi** [comment]
Yes, I cloned the repo to my ubuntu machine and changed to master branch, rebuild pass with arm-gcc 9.2.
Then I copied the whole folder to target board and renamed saschawillems-vulkan-imx to Vulkan_Sascha.
I checked the data folder but not found n_etc2_unorm.ktx under sibenik, and also there is no this file in vulkan_asset_pack (download by download_assets.py)

**Comment by SaschaWillems** [comment]
There is no such material and thus no file named "n_zid_001" in the model. Some materials start off with "kamen_zid_", so I guess there is something wrong with your build/compiler setup so that wrong file names get passed.

**Comment by gary-sweet** [comment]
I suspect this is related to https://github.com/SaschaWillems/Vulkan/issues/663

Truncated file names were one of the problems I was seeing.

**Comment by dmarian** [comment]
I'm seeing the same error here. Only with scenerendering and skeletalanimation and I solved it by using an assimp version I compiled myself.

**Comment by SaschaWillems** [comment]
I would have updated ASSIMP, if it wasn't for Android. Building ASSIMP on Android is not trivial, that's why I initially included a prebuilt version. Getting ASSIMP to build as part of the build chain on Android is even harder, and I haven't found a good solution for this problem yet.

**Comment by SaschaWillems** [comment]
I have removed ASSIMP and replaced it with a custom glTF loader based on the header-only tinyglTF, so closing this.
