### ISSUE TITLE
Shadowmapping: App performs the COLOR_ATTACHMENT_OPTIMAL->PRESENT_SRC_KHR layout transition w/o waiting for formerly submitted commands to end

### ISSUE THREAD

**Issue by kbiElude** [SaschaWillems/Vulkan#69]
In Shadowmapping::draw(), we have:

![image](https://cloud.githubusercontent.com/assets/9154207/13647410/5339978e-e634-11e5-9948-a1d69fee99ce.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13647414/5f6399e2-e634-11e5-9903-36826b82ad5d.png)

In other words, after these two cmd buffers are done with, we instruct the driver to signal a specific semaphore. So far so good.

Then, submitPrePresentBarrier() does the following:

![image](https://cloud.githubusercontent.com/assets/9154207/13647435/7eeff2c4-e634-11e5-8273-5305b4eb951d.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13647448/89e5afd4-e634-11e5-903b-6ad614bb61c8.png)

This is pretty bad. The two command buffers may be in-flight on the universal queue (which I'm making an educated guess your app is using :) ), while the app attempts to submit another, third command buffer, which may start moving the swapchain image to a presentable layout while these commands are still executing.

What I'd recommend doing to fix this situation is to configure the pWaitSemaphores & waitSemaphoreCount fields of VulkanExampleBase::submitPrePresentBarrier()::submitInfo, so that this command buffer starts executing no earlier than the two command buffers already in flight finish executing.

**Comment by SaschaWillems** [comment]
Thx for the detailed explanation. This will affect other examples as well. I'm gonna add the required semaphores.

**Comment by SaschaWillems** [comment]
The sample no longer uses two command buffers, but rather two render passes in a single command buffer with implicit synchronization in between.
