### ISSUE TITLE
Incorrect number of "in" variables in base.vert  (geometryshader - Normal Debugging example)

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#692]
geometryshader's base vert has 2 in locations but the pipeline's vertex input state provides 3. 
While solid rendering pipeline's mesh.vert uses 3, the reuse of vertices.inputState in the normal debugging pipeline is the cause of this.
The situation can be remedied by:
i. adjust vertices.inputState for 2 variables
or 
ii. introduce "layout (location = 2) in vec3 dummy;" to base.vert shader

**Comment by SaschaWillems** [comment]
I don't think this is an issue. Validation layers don't complain about this.

**Comment by kyamant** [comment]
FYI. I am using VK_LAYER_LUNARG_standard_validation, VK_LAYER_LUNARG_monitor,  VK_LAYER_GOOGLE_threading, VK_LAYER_LUNARG_core_validation, VK_LAYER_LUNARG_parameter_validation, VK_LAYER_LUNARG_object_tracker  layers and two of them (not sure which ones) are reporting:
"Vertex attribute at location 2 not consumed by vertex shader"

**Comment by SaschaWillems** [comment]
What version of the layers are you using? Recent SDK or built from source?

**Comment by kyamant** [comment]
I am using Vulkan 1.1.114.0. For my educational purposes only, I am using my framework using the core pieces from the examples.

**Comment by SaschaWillems** [comment]
Okay, I'm using a much newer SDK. Afair they moved this from a warning to a different (lesser) level as this wasn't really something that should have been a warning from the beginning.

**Comment by kyamant** [comment]
That's fine. As I mentioned, this is for my education and I have benefited greatly and wanted to contribute what I could.
