### ISSUE TITLE
computecuallandlod demo crashes on Android Samsung Galaxy S10

### ISSUE THREAD

**Issue by davidlunarg** [SaschaWillems/Vulkan#693]
The computecullandlod demo on Android crashes due to an assert failure. Here are the are the relevant lines from adb logcat: 

[logcat.log](https://github.com/SaschaWillems/Vulkan/files/4482182/logcat.log)

It's possible there might be a configuration problem on my device, although other demos seem to work OK (but I haven't tried all of them).

Here is information about my Android device:

Samsung Galaxy S10
Model number SM-G973F
Android version 10
Kernel version 4.14.113-17369399
Build number QP1A.190711.020.G973FXXS3BSL4

**Comment by SaschaWillems** [comment]
Thanks for the report. The synchronization for that example needs some work, so I expected that's what causes the crash. Will investigate.

**Comment by SaschaWillems** [comment]
Sorry for the very late reply, but I only recently got some time to fix a possible problem with this example where data may not get properly initialized. Can you check again and let me know if this works now?
