### ISSUE TITLE
[Android]Inputattachment demo crash on Adreno 640 GPU

### ISSUE THREAD

**Issue by congyue1977** [SaschaWillems/Vulkan#696]
The inputattachment demo crash on Adreno 640 GPU, and the crash occurred on line 463:

> VK_CHECK_RESULT(vkAllocateDescriptorSets(device, &allocInfo, &descriptorSets.attachmentRead[i]));

**Comment by infapi00** [comment]
FWIW, it is also crashing on with Intel(R) UHD Graphics 630 GPU, using the mesa driver. For completeness, when enabling the validation layers:

> VUID-VkDescriptorSetAllocateInfo-descriptorSetCount-00306(ERROR / SPEC): msgNum: 0 - Unable to allocate 1 descriptorSets from VkDescriptorPool 0x590000000059[]. This pool only has 0 descriptorSets remaining. The Vulkan spec states: descriptorSetCount must not be greater than the number of sets that are currently available for allocation in descriptorPool (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorSetCount-00306)
>     Objects: 1
>         [0] 0x590000000059, type: 22, name: NULL
> INTEL-MESA: error: ../src/intel/vulkan/anv_descriptor_set.c:871: VK_ERROR_OUT_OF_POOL_MEMORY
>

**Comment by infapi00** [comment]
FWIW pull request #697 also fixes the crash with the Intel GPU
