### ISSUE TITLE
The setup freeze from one of your c++ script !

### ISSUE THREAD

**Issue by Azaretdodo** [SaschaWillems/Vulkan#699]
Hello,

I am running one of your c++ script from base folder but the system freeze,

![image](https://user-images.githubusercontent.com/30596513/80459526-c6820000-8932-11ea-9c6b-b7f9a0ec1e71.png)

The system shoulden't freeze IT is a strong and heavy system,

a fx 6300 with sixteen gigabyte of ram arm by 2133 mhz of bandwith the gpu is a vulkan 56 who can run vulkan api,

Thank you in advance to explain to myself why the setup freeze and how to go more far finaly,

Regards.

azaretdodo.

**Comment by SaschaWillems** [comment]
Can you elaborate? I'm not doing any scripting in C++. And is this related to running the samples or to building them?

**Comment by Azaretdodo** [comment]
It is a hpp extension script or a h extension script

**Comment by Azaretdodo** [comment]
I run yours script with 'cpp' program

**Comment by Azaretdodo** [comment]
need I stop the process ?

**Comment by SaschaWillems** [comment]
Sorry, I can't follow you. Can you describe the problem in proper english?

**Comment by Azaretdodo** [comment]
Sorry for the problem I have come back to yours scripts after the problem now it is repaired,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________
