### ISSUE TITLE
Shadowmapping: App does not synchronize the "offscreen" pass with the "draw" pass

### ISSUE THREAD

**Issue by kbiElude** [SaschaWillems/Vulkan#70]
(this issue is somewhat related to #69)

The application draws a frame in two steps

1. A shadow map is rendered, using a command buffer recorded in buildOffscreenCommandBuffer()
2. The scene is rendered to current frame's swapchain image, using one of the command buffers created in buildCommandBuffers():

The command buffers are submitted to the same command queue using a single vkQueueSubmit() call in draw():

![image](https://cloud.githubusercontent.com/assets/9154207/13647077/bcf041ca-e632-11e5-9d87-acaefe541b2e.png)

As per spec, this means the scheduled command buffers may start executing at any time, including a situation where they both launch at the same time. This indicates we need to ensure proper synchronization is in place to prevent RAW hazards (that is: shadow map is sampled **before** the first command buffer finishes writing to it).

Sadly, the application does not seem to use any events to serialize execution of the two command buffers. Furthermore, I'm worried this problem affects more than just this application.

**Comment by SaschaWillems** [comment]
> Sadly, the application does not seem to use any events to serialize execution of the two command buffers. Furthermore, I'm worried this problem affects more than just this application.

Yes, this is true for all examples that use multiple command buffers in one queue and mostly affects those that do offscreen rendering.

I'll try to address this as soon as possible. Thanks for hinting me at this.

**Comment by SaschaWillems** [comment]
Sorry for the late reply, but I finally got around tackling this issue. 

I changed the code like this : 

![image](https://cloud.githubusercontent.com/assets/10283127/15269675/1141f018-1a07-11e6-9e6c-730dfbda2c4c.png)

There is now an additional semaphore for the offscreen rendering and the offscreen command buffer is submitted separately. 

The command buffer that does the final rendering using the offscreen texture (shadow map) will then wait for that semaphore.

Though it's hard to tell if this works as it has worked before without that semaphore on all devices I checked I think this should do the job?

If so I'll add this to all examples that submit multiple command buffers that rely on each other.

**Comment by SaschaWillems** [comment]
I'm also evaluating the use of events for synchronization. They are more light-weight and easier to put into the existing structure of the examples.

**Comment by DominikWitczakAMD** [comment]
Hey Sacha. Yeah, semaphores are fine, thanks for fixing this :-)

Events would also fit in here, but they put the additional restriction where all command buffers you submit must be targeted at exactly the same command queue. Depending on your engine's architecture, this may or may not be a good fit for all use cases.

**Comment by SaschaWillems** [comment]
All examples that do some sort of offscreen rendering now use a separate semaphore to synchronize between the offscreen and final rendering command buffers.
