### ISSUE TITLE
Where are shaders/mesh/mesh.vert.spv and shaders/mesh/mesh.frag.spv?

### ISSUE THREAD

**Issue by kumakoko** [SaschaWillems/Vulkan#703]
Hi All:
 I have built example **multisampling** successfully and tried to run it.But it could not find **shaders/mesh/mesh.vert.spv** and **shaders/mesh/mesh.frag.spv**. They aren't  in git path and **vulkan_asset_pack.zip.** either. Where are they? Did Sascha forget to upload them？

**Comment by SaschaWillems** [comment]
No, it's possible that I moved them for a recent change and forgot to fix the other samples that used them. Will have to check.
