### ISSUE TITLE
missing makefile

### ISSUE THREAD

**Issue by Azaretdodo** [SaschaWillems/Vulkan#706]
Hello,

When I want build I have assimp message,

I have assimp message but It doesn't missing in your github,

When I want 'make' from build folder of your Vulkan GitHub I am happening missing makefile, 

Thank you in advance to bring to myself a makefile for make and make install command line Vulkan Github,

Regards.

Azaretdodo.

**Comment by Azaretdodo** [comment]
for assimp I am in fixing the error !

this was a cmakecache error file,

Now I am in build and install assimp !

**Comment by Azaretdodo** [comment]
after fully build and install assimp I am keep the assimp message

**Comment by SaschaWillems** [comment]
Closing this as it's unclear what the actual issue is.

**Comment by Azaretdodo** [comment]
Closing this maybe because you don't know what is created a makefile and if it is real I don't know what you have work good on this github...

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________
