### ISSUE TITLE
I am grow your cmakeslist in external subdirectory

### ISSUE THREAD

**Issue by Azaretdodo** [SaschaWillems/Vulkan#707]
Hello,

I have Added in cmakeslist from external subdirectory thoses :

![CMakesListsAssimpAdding](https://user-images.githubusercontent.com/30596513/81406663-46ca1180-913a-11ea-9c1c-1f75e0ad448f.jpg)

![assimp2](https://user-images.githubusercontent.com/30596513/81406679-4fbae300-913a-11ea-9b8e-8108280bd1f4.jpg)

![assimp3](https://user-images.githubusercontent.com/30596513/81406684-547f9700-913a-11ea-88c7-66b115a8b30d.jpg)

all yours subdirectory in external I have growt Its there are a lots of Its empty !

![WhatAreUnderExternalFolder](https://user-images.githubusercontent.com/30596513/81406890-b5a76a80-913a-11ea-8782-4b0a95c3c5da.jpg)

I am in set up the CMakesList file for build all subdirectory by cmake and make command line :) 

I hope I will meet the success !

Regards.

Azaretdodo.

**Comment by SaschaWillems** [comment]
Your englisch is very hard to understand.

What's the actual issue?

Building has been working fine for thousands of users, and it's not clear what you're actually talking about.

**Comment by Azaretdodo** [comment]
there are a lot of folder not add in your cmakelist file !

**Comment by Azaretdodo** [comment]
I have remove all h extension files on the cmakelist for put Inside hpp extension files and cpp extension files !

**Comment by SaschaWillems** [comment]
The folders/files you added are not required. Did you read the build instructions?

**Comment by Azaretdodo** [comment]
Why they are in external folder?

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by SaschaWillems** [comment]
Becaus that's how I decided to include assimp. But the CMake files already properly include all paths to make ASSIMP work, so you don't need to change anything unless your setup is somehow wrong.

**Comment by Azaretdodo** [comment]
The file I have edited doesn't include assimp before I have edited

The vulkan github want yes

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by SaschaWillems** [comment]
Sorry, your englisch is very bad. I still don't know what's the actual problem and why you opened up an issue for something that's properly working.

**Comment by Azaretdodo** [comment]
That work you call it?

This is low work how they were built before

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by SaschaWillems** [comment]
Sorry, but your english is very hard to understand. You are the first person that has troubles building this, and without a proper description in a language I can understand I won't be able to help.
