### ISSUE TITLE
I have bring glm.hpp in glm directory on your base folder but It keep missing I don't know why !

### ISSUE THREAD

**Issue by Azaretdodo** [SaschaWillems/Vulkan#709]
Hello,

I trie to compile your base directory and happening glm.hpp in glm folder missing :

![GLMMissingTooGLM-HPPMissing](https://user-images.githubusercontent.com/30596513/81468026-20a97d80-91dd-11ea-9ea4-82ce100e2729.jpg)

I have take the glm GitHub from this GitHub link : 

https://github.com/g-truc/glm

I have copy past the glm subdirectory where there is the glm.hpp file for It is at the good level directory !

I am Don't know why I am happening glm directory and glm.hpp missing…

This is the Inside of the glm.hpp : 

https://github.com/g-truc/glm/blob/master/glm/glm.hpp

Thank you in advance to repair the problem,

Regards.

Azraretdodo.

**Comment by Azaretdodo** [comment]
Now I am happening less error after build glm folder :

![NowLessError](https://user-images.githubusercontent.com/30596513/81468170-30759180-91de-11ea-91ad-7f1882c88689.jpg)

Thank you in advance to repair the problem for build your base subdirectory,

Regards.


Azaretdodo.

**Comment by SaschaWillems** [comment]
You don't need to copy libraries like glm into the external directory. They are included as submodules, so after you check out the repo you need to init the submodules as noted [here](https://github.com/SaschaWillems/Vulkan#-cloning).

**Comment by Azaretdodo** [comment]
thank you for your answer,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
befor do yours advice I copy my Editing I don't want to loose my work,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
Hello,


I show what they are Under external submodules !

![WhatTheyDoAndWhatYouMiss](https://user-images.githubusercontent.com/30596513/81469365-cad8d380-91e4-11ea-8218-dcf68cb1bc6a.jpg)

Why your command line adviced miss a lot of submodules ?

Thank you in advance to bring more if you do how to do,

Regards.


Azaretdodo.
