### ISSUE TITLE
descriptorsets.cpp: Unnecessary code

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#711]
In function `render()`
`if (cubes[0].rotation.x > 360.0f)`
    `cubes[0].rotation.x -= 360.0f;`
is not needed as trigonometric functions handle the periodicity inherently
`if (cubes[1].rotation.x > 360.0f)`
				`cubes[1].rotation.x -= 360.0f;`
is also not needed because the rotation is around Y-axis and the trigonometric functions handle the periodicity  inherently.

**Comment by gary-sweet** [comment]
Although the trig functions will handle values > 360, if you let it run long enough that those values become very large you will start to see numerical inaccuracies appear. The code here is necessary to prevent that.

**Comment by kyamant** [comment]
In the second half of that code
`cubes[1].rotation.y += 2.0f * frameTimer;
			if (cubes[1].rotation.x > 360.0f)
				cubes[1].rotation.x -= 360.0f;`
Rotation is around Y axis, but X axis is handled

**Comment by SaschaWillems** [comment]
This may not be the most optimal way of doing this, but I' fine with the current code. So closing this.
