### ISSUE TITLE
In dynamic uniform buffer, should sizeof be alignof?

### ISSUE THREAD

**Issue by Yelnats321** [SaschaWillems/Vulkan#712]
Hi,

Reading the dynamic uniform buffer tutorial, when we calculate the dynamic alignment requirement, shouldn't we be taking the `alignof(glm::mat4)` instead of the `sizeof(glm::mat4)`? Since we need our accesses to align, we really only care about the stricter of those two alignments right? Was the code written in this way to make it easier to access the dynamic buffers later, since you still need to offset by the size of the matrices and not the alignment of it?

**Comment by SaschaWillems** [comment]
`alignof` would be the more correct way, but I don't think it should make any difference for basic types.
