### ISSUE TITLE
[Question] Why dlopen PFN libvulkan.so to load vulkan library on Android?

### ISSUE THREAD

**Issue by engineer1109** [SaschaWillems/Vulkan#714]
I know to add 
```
add_definitions(-DVK_NO_PROTOTYPES=1)
```
to dlopen libvulkan.so on Android.
However, why not load vulkan directly? Why not compile the vulkan code linking with libvulkan.so, like linux?

I add this:
Cancel the VK_NO_PROTOTYPES
```
add_definitions(-DVK_USE_PLATFORM_ANDROID_KHR)
add_definitions(-DVKAPI_ATTR=)
add_definitions(-DVKAPI_CALL=)
add_definitions(-DVKAPI_PTR=)
```
And compile the code and target link with -lvulkan on Android. It can also work.

**Comment by SaschaWillems** [comment]
But does this work on all Android devices? I remember doing the explicit Android loading stuff as esp. the earlier devices did not come with Vulkan libraries.

**Comment by engineer1109** [comment]
@SaschaWillems If the earlier devices dont come with the vulkan libraries, how to dlopen the libvulkan.so. The dlopen is searching the libpath /system/lib64/libvulkan.so

**Comment by SaschaWillems** [comment]
Yeah, it may no longer be necessary to load the lib and the function pointers manually. I may rework this when I get the time to do that.
