### ISSUE TITLE
can't link to imGui

### ISSUE THREAD

**Issue by xfj81525** [SaschaWillems/Vulkan#716]
hi all, I compile this project with Xcode and can't link to imGui , anyone have the same problem  or is there any way to solve this

**Comment by SaschaWillems** [comment]
The iOS / MacOS ports were provided by Brenwill, the makers of MoltenVK. It may be better to ask that over at their repository (https://github.com/KhronosGroup/MoltenVK) as I don't develop on Apple devices and can't help.
