### ISSUE TITLE
How about frustum culling ?

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#72]
Thanks for you examples !
If i want draw trees but with frustum culling, the instance bad solution.
How do right ?
I create separate cmdbuffer and draw(not use instance) two planks, but if i draw i get two twinkles planks:
https://www.youtube.com/watch?v=LPPj_-KBSoc
And Radeon HD7950 vkCmdPushConstants crush.

**Comment by SaschaWillems** [comment]
> If i want draw trees but with frustum culling, the instance bad solution.
The instancing demo is not meant to showcase frustum culling. Frustum culling is API-agnostic and not related to e.g. Vulkan. So if you want to do frustum culling, just use the same techniques as for OpenGL or Direct3D.

> And Radeon HD7950 vkCmdPushConstants crush.

Whats does maxPushConstantsSize report for your GPU? Maybe it's lower than the push constant space required by the example. If not this may be a driver bug. On my R9 390 this works fine.

**Comment by Ronniko** [comment]
maxPushConstantsSize = 0xFFFFFFFF
It is possible to compile release version pushconstants example ?

About frustum culling. I mean how it will look with Vulkan API features code frustum culling.
I think we need separate cmdbuffer and put to shader 3d coords then vkQueueSubmit, then again for next model put to shader 3d coords then vkQueueSubmit. And to do so many objects 
If i am right.

**Comment by Ronniko** [comment]
Describe pushconstants only in pipeline layout ?
VkPushConstantRange pushConstantRange;
pipelineLayoutCreateInfo.pushConstantRangeCount = 1;
pipelineLayoutCreateInfo.pPushConstantRanges = &pushConstantRange;
vkCreatePipelineLayout(device, &pipelineLayoutCreateInfo, nullptr, &pipelineLayout);

Nowhere else ?

**Comment by SaschaWillems** [comment]
> It is possible to compile release version pushconstants example ?

Release builds are available [here](http://vulkan.gpuinfo.org/examples.php), though they're not always up-to-date.

> About frustum culling. I mean how it will look with Vulkan API features code frustum culling.
I think we need separate cmdbuffer and put to shader 3d coords then vkQueueSubmit, then again for next model put to shader 3d coords then vkQueueSubmit. And to do so many objects 
If i am right.

No, you won't need multiple vkQueueSubmits. You can e.g. have a separate command buffer for each of your visibility sets (or meshes) and only submit them via the command buffer list if it's visible.

Matrices etc. can be updated in different ways. E.g. have separate descriptor sets with separate uniform buffer blocks for each mesh or just use push constants if you can fit everything in there.

> Describe pushconstants only in pipeline layout ?

Yes, push constant definition os part of the pipeline layout and is updated via vkCmdPushConstants. Other than that you also need to add a push constant block to the shaders

**Comment by Ronniko** [comment]
Your example(PushConstants) 64 bits work on my Radeon HD7950 !
Do you have 32 bits this example ?
I programming 32 bit Vulkan API.
Thanks for your help !
