### ISSUE TITLE
load mesh indexBase is count of lastest index count  , maybe laset vertex count ?

### ISSUE THREAD

**Issue by OPA827** [SaschaWillems/Vulkan#721]
// is correct ?
uint32_t indexBase = static_cast<uint32_t>(indexBuffer.size());
			for (uint32_t f = 0; f < scene->mMeshes[m]->mNumFaces; f++)
			{
				for (uint32_t i = 0; i < 3; i++)
				{
					indexBuffer.push_back(scene->mMeshes[m]->mFaces[f].mIndices[i] + indexBase);
				}
			}

**Comment by SaschaWillems** [comment]
Can you please elaborate?

**Comment by OPA827** [comment]
----- 原始邮件 -----
发件人：Sascha Willems <notifications@github.com>
收件人：SaschaWillems/Vulkan <Vulkan@noreply.github.com>
抄送人：OPA827 <mengxin@pixelgame.net>,  Author <author@noreply.github.com>
主题：Re: [SaschaWillems/Vulkan] load mesh indexBase is count of lastest index count  , maybe laset vertex count ? (#721)
日期：2020年05月27日 03点57分


Can you please elaborate?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

		// Generate vertex buffer from ASSIMP scene data		float scale = 1.0f;		std::vector<Vertex> vertexBuffer;		// ADD BY OPA827:		// Base vertex offset of submesh		std::vector<uint32_t> base_array;		// Iterate through all meshes in the file and extract the vertex components		for (uint32_t m = 0; m < scene->mNumMeshes; m++)		{			// ADD BY OPA827 :			// if triangle shared vertex. assert failed.			// if not shared vertex , why not vkCmdDraw ?			assert(scene->mMeshes[m]->mNumFaces * 3 == scene->mMeshes[m]->mNumVertices);
			base_array.push_back(static_cast<uint32_t>(vertexBuffer.size()));			for (uint32_t v = 0; v < scene->mMeshes[m]->mNumVertices; v++)			{				Vertex vertex;				// fill vertex data code ...				vertexBuffer.push_back(vertex);			}		}		size_t vertexBufferSize = vertexBuffer.size() * sizeof(Vertex);
		// Generate index buffer from ASSIMP scene data		std::vector<uint32_t> indexBuffer;		for (uint32_t m = 0; m < scene->mNumMeshes; m++)		{			uint32_t indexBase = static_cast<uint32_t>(indexBuffer.size());			uint32_t vertexBase = base_array[m];			// ADD BY OPA827			// indexBase always equal vertexBase in any case ?			assert(indexBase== vertexBase);			for (uint32_t f = 0; f < scene->mMeshes[m]->mNumFaces; f++)			{				// We assume that all faces are triangulated				for (uint32_t i = 0; i < 3; i++)				{					indexBuffer.push_back(scene->mMeshes[m]->mFaces[f].mIndices[i] + indexBase);				}			}		}		size_t indexBufferSize = indexBuffer.size() * sizeof(uint32_t);		model.indices.count = static_cast<uint32_t>(indexBuffer.size());

**Comment by SaschaWillems** [comment]
I have reworked the scene rendering sample to use glTF, so closing this for now.
