### ISSUE TITLE
Missing ktx/lib/texture.c

### ISSUE THREAD

**Issue by maxest** [SaschaWillems/Vulkan#722]
When trying to build samples for Android I get:
```
Cannot find source file:

      ../../../external/ktx/lib/texture.c
```
Indeed, the folder ktx is empty.

**Comment by SaschaWillems** [comment]
Please init the submodules as noted in the readme.

**Comment by maxest** [comment]
I did that. I got no errors (once call to update prompted a Git for Windows installation) and yet the folders were empty.
This happened when I manually downloaded the repo (not via Git).

Now I downloaded the repo with Git and ran submodules commands and indeed all is working just fine.

**Comment by SaschaWillems** [comment]
Sadly github source downloads don't include submodules.

**Comment by maxest** [comment]
Yeah, but I thought that's what calling:
git submodule init
git submodule update
would do for me

**Comment by maxest** [comment]
Anyway, thank you a lot for very quick response that worked :)
