### ISSUE TITLE
On-Screen-Display FrameRate/FrameTime/DrawCalls

### ISSUE THREAD

**Issue by MacGamerFR** [SaschaWillems/Vulkan#73]
It's an enhancement idea: displaying monitoring like FrameRate/FrameTime/DrawCalls (and so on) on the viewport after key pressed.

**Comment by SaschaWillems** [comment]
That's something I actually wanted to implement early on in the development process, but haven't gotten around yet.

I'm not sure on wether I'll implement this, but this could be added using one of the overlay layers like in the LunarG samples.

Though you can already display e,g. framerate for the samples using RenderDoc.

**Comment by SaschaWillems** [comment]
All examples now display the frame rate in the window title along with the GPU name. I'll also push an  update later this day that also displays frame time as a better way of measuring performance. The android examples will output fps to the monitor.
