### ISSUE TITLE
[Request] An example showing how to render simple debug lines

### ISSUE THREAD

**Issue by ScrappyCocco** [SaschaWillems/Vulkan#736]
It would be really helpful to have a small example to show how to draw simple debug lines/shapes, there is a lack of examples in vulkan about that. I mean also "standalone" lines, more easily than the debugmaker example.

You can also consider showing how to implement libraries such as [glampert/debug-draw](https://github.com/glampert/debug-draw) to show how to implement that debug draw.
(or any other debug library if there's one simpler than that one)

**Comment by SaschaWillems** [comment]
I don't have plans for such a sample. In the end rendering lines is the same as rendering any mesh: Upload vertices to a buffer and render it.
