### ISSUE TITLE
Cmake generated VS project as static library, but the examples require DLL linking.

### ISSUE THREAD

**Issue by ltqsoft** [SaschaWillems/Vulkan#738]
I think that adding the preprocessor KHRONOS_STATIC should solve this problem. But I currently have no idea how to edit Cmake projects (except generating VS project with default settings), thus I could not fix it myself.

**Comment by SaschaWillems** [comment]
Can you elaborate? What DLL and platform are you referring to? The only one I can imagine is the assimp one for windows, which will soon be replaced as I'm moving to gltf for models.

**Comment by ltqsoft** [comment]
Oops!
Yes, I use MSVC142 community and compile to win64 executables, the problem comes from ktx. I saw this after seeing that my pull request failed to build on your CI.
I haven't check all the other dependencies yet, just some examples I'm currently interested in.

**Comment by SaschaWillems** [comment]
Are you sure it's caused by a dll? There is no dll used for/by ktx.

**Comment by ltqsoft** [comment]
Maybe I was wrong. VC said there are some unresolved symbols with __imp__ prefix, I though the example resolved the ktx DLlAPI as __declspec(dllimport).
Also, I tried to tell that ktx is static but the linker still fails. Maybe those functions are still not implemented, 'cause I could not find them.

**Comment by SaschaWillems** [comment]
What's the actual error message? The repo should work out of the box.

**Comment by ltqsoft** [comment]
I decided to make new clone of the repo, and this time it works perfectly. Maybe I did something wrong while cloning. Thank you for spending time with me.
