### ISSUE TITLE
Linux build: conflict between headers and libraries.

### ISSUE THREAD

**Issue by ltqsoft** [SaschaWillems/Vulkan#742]
It looks like my Code::Blocks IDE have mixed your Assimp headers or libraries with my preinstalled version on my Linux PC. Should it get fixed if I clear the value or remove the ASSIMP_DIR entry?
Also I feel that it would be nice if adding a CMake entry named USE_SYSTEM_ASSIMP for linux build.
Linux distro: Manjaro KDE 20 64bit
Toolchain: GNU Make

**Comment by kimkulling** [comment]
I will add an issue report for thT situagion in assimp as well.

流陳光 <notifications@github.com> schrieb am Do., 2. Juli 2020, 08:30:

**Comment by kimkulling** [comment]
Ops that situation!

kim kulling <kim.kulling@googlemail.com> schrieb am Do., 2. Juli 2020,
08:37:

**Comment by SaschaWillems** [comment]
I have removed ASSIMP and replaced it with a custom glTF loader based on the header-only tinyglTF, so closing this.
