### ISSUE TITLE
Unused std::vector<VkFence> waitFences in VulkanExampleBase class

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#743]
`VulkanExampleBase` declares `std::vector<VkFence> waitFences`,  `createSynchronizationPrimitives()`  resizes the vector and creates fences and  `~VulkanExampleBase()` destroys them,  yet the examples that need fences use their own `waitFences`.

**Comment by SaschaWillems** [comment]
Yes, that's a left-over from trying to rework synchronization. As that's something I want to try in the future, I'll keep the fences in the base class.
