### ISSUE TITLE
Linux build error: use of undeclared identifier 'ZeroMemory'

### ISSUE THREAD

**Issue by fonkle** [SaschaWillems/Vulkan#745]
While building this on _Kubuntu 20.04_ with _cmake_ and _USE_WAYLAND_WSI=ON_ this error is raised:

```
/Vulkan/examples/texturesparseresidency/texturesparseresidency.cpp: In member function ‘void VulkanExample::uploadContent(VirtualTexturePage, VkImage)’:
/Vulkan/examples/texturesparseresidency/texturesparseresidency.cpp:816:3: error: ‘ZeroMemory’ was not declared in this scope
  816 |   ZeroMemory(&rndVal, sizeof(uint32_t));
      |   ^~~~~~~~~~
```

I could not find where it is supposed to be declared; internet only points to a Windows macro, which it should not be used in Kubuntu imo. Any hints where to find 'ZeroMemory' will be greatly appreciated. Thx!

**Comment by SaschaWillems** [comment]
Sorry, that was a mistake. I have replaced that function, it should now work again.

**Comment by fonkle** [comment]
Indeed it builds fine now :). Thank you very much!
