### ISSUE TITLE
Missing complitation instructions

### ISSUE THREAD

**Issue by thaiwash** [SaschaWillems/Vulkan#751]
Hello, I'm an experienced programmer, but C++ is not my strongest language.. I downloaded vulkan and ran cmake . in the root, everything seems to be fine so far. I have some .o files that were generated, but after that, am i suposed to run make? that didnt work, how do i get the binaries?

**Comment by SaschaWillems** [comment]
Build instructions can be found here: https://github.com/SaschaWillems/Vulkan/blob/master/BUILD.md

**Comment by thaiwash** [comment]
It only says use Cmake to buikd, so i run cmake . but it didnt build binaries.. I'm guessing it doesn't run on raspberry anyway, if it needs an nvidia graphics card, but i do have a jetson nano that would work quite as well for my standalone vr headset project.

**Comment by SaschaWillems** [comment]
If you're building via CLI then yes, you need to run make after cmake. I haven't tested this on a raspberry, so I'm not sure if it's working there.

**Comment by thaiwash** [comment]
pi@raspberrypi:~/project/gitted/cpp/Vulkan $ make
[ 10%] Built target base
[ 11%] Linking CXX executable ../bin/vulkanscene
../libs/vulkan/libvulkan.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/vulkanscene.dir/build.make:90: bin/vulkanscene] Virhe 1
make[1]: *** [CMakeFiles/Makefile2:286: examples/CMakeFiles/vulkanscene.dir/all] Virhe 2
make: *** [Makefile:84: all] Virhe 2

**Comment by SaschaWillems** [comment]
You need a Vulkan library that fits your platform. The one included is for 64-bit.

**Comment by thaiwash** [comment]
Hmm, looks like raspberry support is a bit lacking https://www.raspberrypi.org/blog/vulkan-raspberry-pi-first-triangle/

**Comment by SaschaWillems** [comment]
There are different efforts for the Rapsberry Pi 3 and 4, and at least some of my samples seem to run on model 4: https://www.raspberrypi.org/blog/vulkan-update-now-with-added-source-code/

**Comment by SaschaWillems** [comment]
I'm closing this for now, as the Raspberry Pi is not yet officially supported.
