### ISSUE TITLE
Terrain tessellation edge artifact.

### ISSUE THREAD

**Issue by Arzana** [SaschaWillems/Vulkan#758]
At the edge of the terrain I can see a artifact that seems to come from auto of range sampler access. 
The texture coordinates of the mesh don't seem to go outside of the [0, 1] range however.
It seems clear to me that the height texture is clamping to the edge here.

Is this a known issue with tessellation, or is this caused by something else?
I've been looking at this for quite a while and cannot seem to figure out what is causing this.
Thank you for your time.

![image](https://user-images.githubusercontent.com/7056426/91763533-02292100-ebd6-11ea-9dca-ad19e7ba000b.png)
![image](https://user-images.githubusercontent.com/7056426/91763558-0c4b1f80-ebd6-11ea-8f6b-a4edabd2e237.png)

**Comment by SaschaWillems** [comment]
Can you add the position and camera orientation at which those screenshots have been taken?  I haven't been able to reproduce this.

**Comment by Arzana** [comment]
I have logged the position and rotation in the UI. I'm running on a GeForce GTX 1080. Thank you for looking into this.
![image](https://user-images.githubusercontent.com/7056426/93047384-adb58500-f65c-11ea-9414-a513521aec29.png)
