### ISSUE TITLE
Question about multisampling 

### ISSUE THREAD

**Issue by lemon-PiC** [SaschaWillems/Vulkan#763]
1. Whether the multisampling is supported while using two subpasses？
2. If I calculate not only geometry information(normal position) but also shading information(color) in the first subpass，will the multisampling be supported with multisampleState.rasterizationSamples = sampleCount？How can I enable the multisampling in this situation.

**Comment by SaschaWillems** [comment]
As this is a more general question and not directly related to my samples. it's better suited for open forums like the ones from Khronos, Reddit or Stackoverflow.
