### ISSUE TITLE
Could not create Vulkan device:ERROR_EXTENSION_NOT_PRESENT

### ISSUE THREAD

**Issue by disini** [SaschaWillems/Vulkan#765]
Hi Sascha:
Thanks so much for your awesome job of this project! It's a great tutorial to learn vulkan!
I've already compiled all the projects in this repository, with Cmake 3.17 and VS2019 on windows 10 1909, and the windows kit is version 19041. Most of the compiled binaries(74 in total) run perfectly, but the three demo of raytracing(raytracingbasic, raytracingreflections, and raytracingshadows) have some problems. When I ran them either by double click or by debug in VS2019, an error window poped up which said: "Could not create Vulkan device:ERROR_EXTENSION_NOT_PRESENT".

I have googled that error but get nothing useful.
My graphics card is Nvidia RTX 2080ti, and driver version is 452.06.

What may cause this problem? and how should I do to make it work normally?
Looking forward to your reply!
Much appreciate!
![QQ截图20200917160007](https://user-images.githubusercontent.com/5233769/93437757-ed9b9700-f8fe-11ea-818c-d006fcbd2362.png)

**Comment by SaschaWillems** [comment]
The `VK_KHR_ray_tracing` extension is still a work-in-progress and considered beta. To use it on Nvidia you need to use the Vulkan beta developer driver from https://developer.nvidia.com/vulkan-driver.

**Comment by disini** [comment]
> The `VK_KHR_ray_tracing` extension is still a work-in-progress and considered beta. To use it on Nvidia you need to use the Vulkan beta developer driver from https://developer.nvidia.com/vulkan-driver.

OK I will try that link!
Thanks a lot Mr. Willems!
So kind of you!

**Comment by disini** [comment]
![image](https://user-images.githubusercontent.com/5233769/93571574-3c146880-f9c7-11ea-8d6d-d13a5f773849.png)
Nor it works perfectly!Thanks！

**Comment by cppsquare** [comment]
Oh, I had the same problem, good to know! Thanks.
