### ISSUE TITLE
vkconfig: Sync error on Subpasses example

### ISSUE THREAD

**Issue by gamagan** [SaschaWillems/Vulkan#769]
Using the vkconfig tool, I get the following validation errors on example 'subpasses':

```
SYNC-HAZARD-NONE(ERROR / SPEC): msgNum: 105717438 - Validation Error: [ SYNC-HAZARD-NONE ] Object 0: handle = 0x1abb7d37890, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x64d1ebe | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE vs. layout transition in subpass 0 for attachment 4 aspect depth during load with loadOp VK_ATTACHMENT_LOAD_OP_CLEAR.
    Objects: 1
        [0] 0x1abb7d37890, type: 18, name: NULL
```

**Comment by SaschaWillems** [comment]
Thanks for reporting this. I'm already aware of it. It's reported by the new synchronization validation layer, and there are several samples that now report some possible synchronization problems that I'll look into.

**Comment by kyamant** [comment]
Could you please point out which of the following is the new synchronization validation layer?
```
Vulkan Development Status:
- SDK path: d:\VulkanSDK\1.2.148.1
- Loader version: 1.2.141
- Custom Layers Paths: None
- Available Layers:
    - VK_LAYER_NV_optimus
    - VK_LAYER_RENDERDOC_Capture
    - VK_LAYER_NV_nsight
    - VK_LAYER_NV_nomad_release_public_2020_5_0
    - VK_LAYER_NV_GPU_Trace_release_public_2020_5_0
    - VK_LAYER_LUNARG_override
    - VK_LAYER_LUNARG_api_dump
    - VK_LAYER_LUNARG_device_simulation
    - VK_LAYER_LUNARG_gfxreconstruct
    - VK_LAYER_KHRONOS_validation
    - VK_LAYER_LUNARG_screenshot
- Physical Devices:
    - GeForce GTX 1050 Ti (Discrete GPU) with Vulkan 1.2.142
```

**Comment by SaschaWillems** [comment]
`VK_LAYER_KHRONOS_validation` with synchronization preset enabled in the Vulkan Configurator.

**Comment by kyamant** [comment]
Thanks. I noticed the same error with offscreen rendering, should I open a ticket for that?

**Comment by SaschaWillems** [comment]
No, not necessary. I'm aware of the issues reported by the new synchronization layers and will take a look at them.

**Comment by kyamant** [comment]
FYI: Even the `vkcube` is giving the same message.

**Comment by SaschaWillems** [comment]
It looks like they fixed that in the latest SDK. I'm currently looking into fixing this for my samples.

**Comment by kyamant** [comment]
> It looks like they fixed that in the latest SDK. I'm currently looking into fixing this for my samples. Though fixing something on a Vulkan SDK feature that is still in Alpha may be a bit too early.

Seems like this is still going on in **1.2.162.1**
