### ISSUE TITLE
Nvidia demos crash on AMD videocards.

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#77]
I try NVIDIA demos but get crash.
My videocard Radeon HD7950.

Nvidia demo Thread Rendering (aka FISH!) not found in my computer Vulkan API !!!

Sascha Willems do you worked with Mantle API ?
Mantle API more pleasant programming, but only for AMD GNC videocards.
And compile HLSL shaders to IL asm shaders.
It was good days

**Comment by SaschaWillems** [comment]
>  I try NVIDIA demos but get crash.
My videocard Radeon HD7950.

They propably use some vendor specific extensions (e.g. for loading GLSL) and stuff like GL/Vulkan Interop which is not present on other vendors.

> Sascha Willems do you worked with Mantle API ?

No, I haven't used Mantle

> Mantle API more pleasant programming, but only for AMD GNC videocards.

Mantle only had to support one GPU architecture, Vulkan needs to support multiple vendors and architectures.
