### ISSUE TITLE
Offscreen rendering in YUV format

### ISSUE THREAD

**Issue by ida03001** [SaschaWillems/Vulkan#775]
Hi, is there any sample code for off screen rendering in YUV format?
For example, the input format of image is VK_FORMAT_G8_B8R8_2PLANE_420_UNORM then rendering it on output which is VK_FORMAT_G8_B8R8_2PLANE_420_UNORM.

**Comment by SaschaWillems** [comment]
No, there's no such code and I don't plan to create such a sample.
