### ISSUE TITLE
issue with Xcode project

### ISSUE THREAD

**Issue by thewoz** [SaschaWillems/Vulkan#777]
I'm not more able to compile thought the Xcode project.
Some one can update the project?
thanks in advance.

**Comment by SaschaWillems** [comment]
What's the actual error? I don't have own a Mac device, but knowing the exact problem would help.

**Comment by 0xNotNeo** [comment]
For me it's: 
`error: Build input file cannot be found: '/Users/jad/Documents/Programming/GameDev/Vulkan/xcode/macOS/Prefix.pch' (in target 'examples-macos' from project 'examples')`

**Comment by thewoz** [comment]
same of 0xNotNeo
moreover there are a lot of file that Xcode is not able to find.
stb_rect_pack.h
stb_textedit.h
stb_truetype.h
VulkanBuffer.hpp
and so on

**Comment by SaschaWillems** [comment]
The Xcode port was handled by the people at MoltenVK. I don't own a Mac myself, so I can't test or fix this. If possible, a PR would be appreciated.
