### ISSUE TITLE
Building system for linux is bound with x64 and fails for arm

### ISSUE THREAD

**Issue by kingofthebongo2008** [SaschaWillems/Vulkan#778]
I have started the examples on jetson nano 2gb.

However the build system lib is bound to the x64 version so i had to change the links manually, jetson is arm.

May be something can be done to remove this binding.

![jetson-nano-2gb](https://user-images.githubusercontent.com/1145201/99902366-0b51f780-2cc6-11eb-89db-1ff34e9796f2.png)

**Comment by SaschaWillems** [comment]
I don't have access to such a platform, so if you want this added a PR would be welcome.

**Comment by kingofthebongo2008** [comment]
ok. i will try to do something

**Comment by engineer1109** [comment]
Nvidia Tegra ARM embed Computer.
OS: Ubuntu Arm
Arch: armv8 ?

**Comment by kingofthebongo2008** [comment]
This one, the 2GB model
https://developer.nvidia.com/embedded/jetson-nano-developer-kit

**Comment by mrcmunir** [comment]
you needed install libvulkan-dev so they linker with the libvulkan native in you system 
````
Or IF (NOT Vulkan_FOUND)
        if(CMAKE_SYSTEM_PROCESSOR)
	  if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^aarch64")
		find_library(Vulkan_LIBRARY NAMES vulkan-1 vulkan PATHS ${CMAKE_SOURCE_DIR}/libs/aarch64/vulkan)
         elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^amd64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "^x86_64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "^AMD64") 
                find_library(Vulkan_LIBRARY NAMES vulkan-1 vulkan PATHS ${CMAKE_SOURCE_DIR}/libs/amd64/vulkan)
                ```
      .............
      
something like that, to control each architecture in case libvulkan is not installed in the operating system with the libvulkan * .so.       
  
  Except Raytracing lack support on tegra all samples will work fine.
