### ISSUE TITLE
Why in example Occlusion queries not using one uniformData buffer for all objects ?

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#78]
In example we see 3 uniformData buffers.
1-uniformData.teapot.descriptor
2-uniformData.sphere.descriptor
3-uniformData.vsScene.descriptor

Why not using one big uniformData buffer and get matrices witch offsets ?
I mean uniformData.descriptor.offset = +192 and next mesh +192

**Comment by SaschaWillems** [comment]
Yes, that would be possible. I just preferred to use three separate uniform blocks in my examples. But if you want you can use offsets.

**Comment by Ronniko** [comment]
I want to see it in your example :)
