### ISSUE TITLE
Build failed VS2019 Win64

### ISSUE THREAD

**Issue by HerveRV** [SaschaWillems/Vulkan#784]
Here is my procedure for getting and compiling exemples, from the all beginning

1) git clone --recursive https://github.com/SaschaWillems/Vulkan.git
ok, no errors

2) i launch cmake 3.19.1 (the last), use default values (visual studio 2019, x64)
i put the 2 path needed
i configure pass : no error
then i generate and open project, no error

3) it open automaticaly vs2019, (i unload all exemples except the first to maintain readability here, so, i keep only 'bloom' demo, but errors are all the same for all exemples projects)
i launch the compilation, and errors appears
i have no idea why, i try many things without succes

(i use all software in they last version available, like vulkan in version 1.2.154)

i can notice than the project "base" compile, and generate "base.lib"
same errors occured for 32 bit generation, release, or whatever i tried

Thanks for everyone trying help me :)

--------------------------------------------------------------

there is the compiler log :

Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: base, Configuration: Debug x64 ------
2>Building Custom Rule U:/[VulkanSDK]/SaschaWillems/Vulkan/base/CMakeLists.txt
2>texture.c
2>U:\[VulkanSDK]\SaschaWillems\Vulkan\external\ktx\lib\texture.c(31,1): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
2>U:\[VulkanSDK]\SaschaWillems\Vulkan\external\ktx\lib\texture.c : message : see previous definition of '_CRT_SECURE_NO_WARNINGS'
2>hashlist.c
2>checkheader.c
2>swap.c
2>memstream.c
2>filestream.c
2>Generating Code...
2>base.vcxproj -> U:\[VulkanSDK]\SaschaWillems\Vulkan\BuildRV\base\Debug\base.lib
2>Done building project "base.vcxproj".
3>------ Build started: Project: bloom, Configuration: Debug x64 ------
3>Building Custom Rule U:/[VulkanSDK]/SaschaWillems/Vulkan/examples/CMakeLists.txt
3>bloom.cpp
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(497,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(516,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(524,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(532,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(540,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(553,1): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\examples\bloom\bloom.cpp(564,1): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data
3>bloom.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl getAssetPath(void)" (?getAssetPath@@YA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: void __cdecl VulkanExample::loadAssets(void)" (?loadAssets@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl vks::tools::errorString(enum VkResult)" (?errorString@tools@vks@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4VkResult@@@Z) referenced in function "public: virtual void __cdecl VulkanExample::buildCommandBuffers(void)" (?buildCommandBuffers@VulkanExample@@UEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl vks::tools::getSupportedDepthFormat(struct VkPhysicalDevice_T *,enum VkFormat *)" (?getSupportedDepthFormat@tools@vks@@YAIPEAUVkPhysicalDevice_T@@PEAW4VkFormat@@@Z) referenced in function "public: void __cdecl VulkanExample::prepareOffscreen(void)" (?prepareOffscreen@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: enum VkResult __cdecl vks::Buffer::map(unsigned __int64,unsigned __int64)" (?map@Buffer@vks@@QEAA?AW4VkResult@@_K0@Z) referenced in function "public: void __cdecl VulkanExample::prepareUniformBuffers(void)" (?prepareUniformBuffers@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl vks::Buffer::destroy(void)" (?destroy@Buffer@vks@@QEAAXXZ) referenced in function "public: virtual __cdecl VulkanExample::~VulkanExample(void)" (??1VulkanExample@@UEAA@XZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: unsigned int __cdecl vks::VulkanDevice::getMemoryType(unsigned int,unsigned int,unsigned int *)const " (?getMemoryType@VulkanDevice@vks@@QEBAIIIPEAI@Z) referenced in function "public: void __cdecl VulkanExample::prepareOffscreenFramebuffer(struct VulkanExample::FrameBuffer *,enum VkFormat,enum VkFormat)" (?prepareOffscreenFramebuffer@VulkanExample@@QEAAXPEAUFrameBuffer@1@W4VkFormat@@1@Z)
3>bloom.obj : error LNK2019: unresolved external symbol "public: enum VkResult __cdecl vks::VulkanDevice::createBuffer(unsigned int,unsigned int,struct vks::Buffer *,unsigned __int64,void *)" (?createBuffer@VulkanDevice@vks@@QEAA?AW4VkResult@@IIPEAUBuffer@2@_KPEAX@Z) referenced in function "public: void __cdecl VulkanExample::prepareUniformBuffers(void)" (?prepareUniformBuffers@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: bool __cdecl vks::UIOverlay::header(char const *)" (?header@UIOverlay@vks@@QEAA_NPEBD@Z) referenced in function "public: virtual void __cdecl VulkanExample::OnUpdateUIOverlay(class vks::UIOverlay *)" (?OnUpdateUIOverlay@VulkanExample@@UEAAXPEAVUIOverlay@vks@@@Z)
3>bloom.obj : error LNK2019: unresolved external symbol "public: bool __cdecl vks::UIOverlay::checkBox(char const *,bool *)" (?checkBox@UIOverlay@vks@@QEAA_NPEBDPEA_N@Z) referenced in function "public: virtual void __cdecl VulkanExample::OnUpdateUIOverlay(class vks::UIOverlay *)" (?OnUpdateUIOverlay@VulkanExample@@UEAAXPEAVUIOverlay@vks@@@Z)
3>bloom.obj : error LNK2019: unresolved external symbol "public: bool __cdecl vks::UIOverlay::inputFloat(char const *,float *,float,unsigned int)" (?inputFloat@UIOverlay@vks@@QEAA_NPEBDPEAMMI@Z) referenced in function "public: virtual void __cdecl VulkanExample::OnUpdateUIOverlay(class vks::UIOverlay *)" (?OnUpdateUIOverlay@VulkanExample@@UEAAXPEAVUIOverlay@vks@@@Z)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl vks::Texture::destroy(void)" (?destroy@Texture@vks@@QEAAXXZ) referenced in function "public: virtual __cdecl VulkanExample::~VulkanExample(void)" (??1VulkanExample@@UEAA@XZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl vks::TextureCubeMap::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,enum VkFormat,struct vks::VulkanDevice *,struct VkQueue_T *,unsigned int,enum VkImageLayout)" (?loadFromFile@TextureCubeMap@vks@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4VkFormat@@PEAUVulkanDevice@2@PEAUVkQueue_T@@IW4VkImageLayout@@@Z) referenced in function "public: void __cdecl VulkanExample::loadAssets(void)" (?loadAssets@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "protected: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl VulkanExampleBase::getShadersPath(void)const " (?getShadersPath@VulkanExampleBase@@IEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: void __cdecl VulkanExample::preparePipelines(void)" (?preparePipelines@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: __cdecl VulkanExampleBase::VulkanExampleBase(bool)" (??0VulkanExampleBase@@QEAA@_N@Z) referenced in function "public: __cdecl VulkanExample::VulkanExample(void)" (??0VulkanExample@@QEAA@XZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl VulkanExampleBase::~VulkanExampleBase(void)" (??1VulkanExampleBase@@UEAA@XZ) referenced in function "int `public: __cdecl VulkanExample::VulkanExample(void)'::`1'::dtor$0" (?dtor$0@?0???0VulkanExample@@QEAA@XZ@4HA)
3>bloom.obj : error LNK2019: unresolved external symbol "public: bool __cdecl VulkanExampleBase::initVulkan(void)" (?initVulkan@VulkanExampleBase@@QEAA_NXZ) referenced in function WinMain
3>bloom.obj : error LNK2019: unresolved external symbol "public: struct HWND__ * __cdecl VulkanExampleBase::setupWindow(struct HINSTANCE__ *,__int64 (__cdecl*)(struct HWND__ *,unsigned int,unsigned __int64,__int64))" (?setupWindow@VulkanExampleBase@@QEAAPEAUHWND__@@PEAUHINSTANCE__@@P6A_JPEAU2@I_K_J@Z@Z) referenced in function WinMain
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl VulkanExampleBase::handleMessages(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?handleMessages@VulkanExampleBase@@QEAAXPEAUHWND__@@I_K_J@Z) referenced in function "__int64 __cdecl WndProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?WndProc@@YA_JPEAUHWND__@@I_K_J@Z)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual enum VkResult __cdecl VulkanExampleBase::createInstance(bool)" (?createInstance@VulkanExampleBase@@UEAA?AW4VkResult@@_N@Z)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::viewChanged(void)" (?viewChanged@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::keyPressed(unsigned int)" (?keyPressed@VulkanExampleBase@@UEAAXI@Z)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::mouseMoved(double,double,bool &)" (?mouseMoved@VulkanExampleBase@@UEAAXNNAEA_N@Z)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::windowResized(void)" (?windowResized@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::setupDepthStencil(void)" (?setupDepthStencil@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::setupFrameBuffer(void)" (?setupFrameBuffer@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::setupRenderPass(void)" (?setupRenderPass@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::getEnabledFeatures(void)" (?getEnabledFeatures@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::prepare(void)" (?prepare@VulkanExampleBase@@UEAAXXZ) referenced in function "public: virtual void __cdecl VulkanExample::prepare(void)" (?prepare@VulkanExample@@UEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: struct VkPipelineShaderStageCreateInfo __cdecl VulkanExampleBase::loadShader(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,enum VkShaderStageFlagBits)" (?loadShader@VulkanExampleBase@@QEAA?AUVkPipelineShaderStageCreateInfo@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4VkShaderStageFlagBits@@@Z) referenced in function "public: void __cdecl VulkanExample::preparePipelines(void)" (?preparePipelines@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl VulkanExampleBase::renderLoop(void)" (?renderLoop@VulkanExampleBase@@QEAAXXZ) referenced in function WinMain
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl VulkanExampleBase::drawUI(struct VkCommandBuffer_T * const)" (?drawUI@VulkanExampleBase@@QEAAXQEAUVkCommandBuffer_T@@@Z) referenced in function "public: virtual void __cdecl VulkanExample::buildCommandBuffers(void)" (?buildCommandBuffers@VulkanExample@@UEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl VulkanExampleBase::prepareFrame(void)" (?prepareFrame@VulkanExampleBase@@QEAAXXZ) referenced in function "public: void __cdecl VulkanExample::draw(void)" (?draw@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl VulkanExampleBase::submitFrame(void)" (?submitFrame@VulkanExampleBase@@QEAAXXZ) referenced in function "public: void __cdecl VulkanExample::draw(void)" (?draw@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl VulkanExampleBase::renderFrame(void)" (?renderFrame@VulkanExampleBase@@UEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: static struct VkPipelineVertexInputStateCreateInfo * __cdecl vkglTF::Vertex::getPipelineVertexInputState(class std::vector<enum vkglTF::VertexComponent,class std::allocator<enum vkglTF::VertexComponent> >)" (?getPipelineVertexInputState@Vertex@vkglTF@@SAPEAUVkPipelineVertexInputStateCreateInfo@@V?$vector@W4VertexComponent@vkglTF@@V?$allocator@W4VertexComponent@vkglTF@@@std@@@std@@@Z) referenced in function "public: void __cdecl VulkanExample::preparePipelines(void)" (?preparePipelines@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: __cdecl vkglTF::Model::~Model(void)" (??1Model@vkglTF@@QEAA@XZ) referenced in function "int `public: __cdecl VulkanExample::<unnamed-type-models>::<unnamed-type-models>(void)'::`1'::dtor$0" (?dtor$0@?0???0<unnamed-type-models>@VulkanExample@@QEAA@XZ@4HA)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl vkglTF::Model::loadFromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct vks::VulkanDevice *,struct VkQueue_T *,unsigned int,float)" (?loadFromFile@Model@vkglTF@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAUVulkanDevice@vks@@PEAUVkQueue_T@@IM@Z) referenced in function "public: void __cdecl VulkanExample::loadAssets(void)" (?loadAssets@VulkanExample@@QEAAXXZ)
3>bloom.obj : error LNK2019: unresolved external symbol "public: void __cdecl vkglTF::Model::draw(struct VkCommandBuffer_T *,unsigned int,struct VkPipelineLayout_T *,unsigned int)" (?draw@Model@vkglTF@@QEAAXPEAUVkCommandBuffer_T@@IPEAUVkPipelineLayout_T@@I@Z) referenced in function "public: virtual void __cdecl VulkanExample::buildCommandBuffers(void)" (?buildCommandBuffers@VulkanExample@@UEAAXXZ)
3>bloom.obj : error LNK2001: unresolved external symbol "public: static class std::vector<char const *,class std::allocator<char const *> > VulkanExampleBase::args" (?args@VulkanExampleBase@@2V?$vector@PEBDV?$allocator@PEBD@std@@@std@@A)
3>U:\[VulkanSDK]\SaschaWillems\Vulkan\BuildRV\bin\Debug\bloom.exe : fatal error LNK1120: 39 unresolved externals
3>Done building project "bloom.vcxproj" -- FAILED.
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

**Comment by SaschaWillems** [comment]
That's odd. I'm using VS2019 too, and both appveyor and Travis CI is building the projects just fine. Compiling seems to work for you just fine, but the linker doesn't seem to find the libraries.

Can you try with a path that does not contain square brackets (U:[VulkanSDK]). This looks odd and may cause some troubles for VS?

**Comment by HerveRV** [comment]
i have retry from "C:\SaschaWillems\Vulkan\" ... and ... it works !!
i work on U:\ and with brackets over years now without problems, and for many projects, it's strange

try with "U:\AAAAAA\Vulkan\" and it worked too ...
ok, thank you for your help and your good idea !
