### ISSUE TITLE
Bugs in computeheadless and renderheadless.

### ISSUE THREAD

**Issue by YuanTianNXP** [SaschaWillems/Vulkan#792]
examples/computeheadless/computeheadless.cpp | 4 ++--
 examples/renderheadless/renderheadless.cpp   | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/examples/computeheadless/computeheadless.cpp b/examples/computeheadless/computeheadless.cpp
index 49566394..002f74a4 100644
--- a/examples/computeheadless/computeheadless.cpp
+++ b/examples/computeheadless/computeheadless.cpp
@@ -154,6 +154,7 @@ public:
 		vkEnumerateInstanceLayerProperties(&instanceLayerCount, nullptr);
 		std::vector<VkLayerProperties> instanceLayers(instanceLayerCount);
 		vkEnumerateInstanceLayerProperties(&instanceLayerCount, instanceLayers.data());
+		const char *validationExt = VK_EXT_DEBUG_REPORT_EXTENSION_NAME;
 
 		bool layersAvailable = true;
 		for (auto layerName : validationLayers) {
@@ -172,7 +173,6 @@ public:
 
 		if (layersAvailable) {
 			instanceCreateInfo.ppEnabledLayerNames = validationLayers;
-			const char *validationExt = VK_EXT_DEBUG_REPORT_EXTENSION_NAME;
 			instanceCreateInfo.enabledLayerCount = layerCount;
 			instanceCreateInfo.enabledExtensionCount = 1;
 			instanceCreateInfo.ppEnabledExtensionNames = &validationExt;
@@ -562,4 +562,4 @@ int main() {
 	delete(vulkanExample);
 	return 0;
 }
-#endif
\ No newline at end of file
+#endif
diff --git a/examples/renderheadless/renderheadless.cpp b/examples/renderheadless/renderheadless.cpp
index a0126cf3..295346c0 100644
--- a/examples/renderheadless/renderheadless.cpp
+++ b/examples/renderheadless/renderheadless.cpp
@@ -184,6 +184,7 @@ public:
 		vkEnumerateInstanceLayerProperties(&instanceLayerCount, nullptr);
 		std::vector<VkLayerProperties> instanceLayers(instanceLayerCount);
 		vkEnumerateInstanceLayerProperties(&instanceLayerCount, instanceLayers.data());
+		const char *validationExt = VK_EXT_DEBUG_REPORT_EXTENSION_NAME;
 
 		bool layersAvailable = true;
 		for (auto layerName : validationLayers) {
@@ -202,7 +203,6 @@ public:
 
 		if (layersAvailable) {
 			instanceCreateInfo.ppEnabledLayerNames = validationLayers;
-			const char *validationExt = VK_EXT_DEBUG_REPORT_EXTENSION_NAME;
 			instanceCreateInfo.enabledLayerCount = layerCount;
 			instanceCreateInfo.enabledExtensionCount = 1;
 			instanceCreateInfo.ppEnabledExtensionNames = &validationExt;
@@ -894,4 +894,4 @@ int main() {
 	delete(vulkanExample);
 	return 0;
 }
-#endif
\ No newline at end of file
+#endif
-- 
2.17.1

**Comment by SaschaWillems** [comment]
Can you elaborate? This issue does not contain an explanation, so I don't have a clue what to do with it.

**Comment by YuanTianNXP** [comment]
The local variable "validationExt" is only valid in "if (layersAvailable) { }" area. The following code "VK_CHECK_RESULT(vkCreateInstance(&instanceCreateInfo, nullptr, &instance));" would pass an invalid pointer. I found the issue because the vulkan loader returned with VK_STRING_ERROR_NULL_PTR. 
vulkan loader git : https://github.com/KhronosGroup/Vulkan-Loader

**Comment by SaschaWillems** [comment]
Should be fixed with merged PR #802.
