### ISSUE TITLE
Found bug on Radeon HD7950 in FullScreen.

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#80]
If i create my windows on full desktop resolution with flag WS_POPUP+WS_VISIBLE, vulkan api not clear color and depth. Screen black color.
Fix in renderPassBeginInfo.renderArea.extent.height = WinY+1;
In my case WinY = 1050;
And all will be well :)

**Comment by SaschaWillems** [comment]
Can you elaborate on this (os and driver versions)? I'm testing with a R9 390 and fullscreen mode works fine. So this may be a driver bug.

**Comment by Ronniko** [comment]
I try Vulkan in 32 bit 
AMD driver Beta for Vulkan™ Version 16.15.1009 Beta 5 feb 2/26/2016

**Comment by Ronniko** [comment]
I try Vulkan API 32 bit vkCreateInstance and vkCreateDevice with "VK_LAYER_LUNARG_standard_validation", but get error create Instance and Device !

I do for this tutorial http://gpuopen.com/using-the-vulkan-validation-layers/

**Comment by SaschaWillems** [comment]
> I try Vulkan API 32 bit vkCreateInstance and vkCreateDevice with "VK_LAYER_LUNARG_standard_validation", but get error create Instance and Device !

Do you have the SDK installed and VK_SDK_PATH pointing to the right directory? If yes, what's the error message returned by vkCreateInstance?

**Comment by Ronniko** [comment]
vkCreateInstance get error VK_ERROR_INITIALIZATION_FAILED

**Comment by Ronniko** [comment]
instanceCreateInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
deviceCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO

**Comment by SaschaWillems** [comment]
VK_ERROR_LAYER_NOT_PRESENT means that the Vulkan loader was not able to locate the validation layer. Are the paths correct?

**Comment by Ronniko** [comment]
How check Vulkan API LAYER support ?
I mean Vulkan API command.

**Comment by SaschaWillems** [comment]
You can use [vkEnumerateInstanceLayerProperties ](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkEnumerateInstanceLayerProperties.html) to retrieve the list of globally available layers.

**Comment by Ronniko** [comment]
int pin = 8;
VkLayerProperties pon;
I try vkEnumerateInstanceLayerProperties(&pin,&pon) and get this:
VK_LAYER_RENDERDOC_Capture
Then empty. Only one layer.

**Comment by Ronniko** [comment]
With "VK_LAYER_RENDERDOC_Capture"
vkCreateInstance and vkCreateDevice create ok !

**Comment by Ronniko** [comment]
![vulkaninfo](https://cloud.githubusercontent.com/assets/11887473/13747500/91de155e-ea09-11e5-881a-2bc92a66c1aa.jpg)

**Comment by Ronniko** [comment]
I'm doomed :(

**Comment by SaschaWillems** [comment]
vulkaninfo has troubles reading from your registry. If you have the SDK installed, check if the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Khronos\Vulkan" exists (if you're on Win64, Win32 may differ).

**Comment by Ronniko** [comment]
![vu1](https://cloud.githubusercontent.com/assets/11887473/13751055/5f165b9e-ea19-11e5-8c23-8e6603626d70.jpg)
![vu2](https://cloud.githubusercontent.com/assets/11887473/13751056/5f16f518-ea19-11e5-972b-c9bf439840c0.jpg)
![vu3](https://cloud.githubusercontent.com/assets/11887473/13751057/5f1a6874-ea19-11e5-9a0f-b88665eb99b3.jpg)

**Comment by Ronniko** [comment]
![u](https://cloud.githubusercontent.com/assets/11887473/13751169/ef318730-ea19-11e5-924d-04a1fffa24f9.jpg)

**Comment by Ronniko** [comment]
![ff](https://cloud.githubusercontent.com/assets/11887473/13751518/a7770be8-ea1b-11e5-896a-b4af0b220d65.jpg)

**Comment by Ronniko** [comment]
I understood !
Finely i apply layer ! And my program see "VK_LAYER_LUNARG_mem_tracker" !
![dd](https://cloud.githubusercontent.com/assets/11887473/13752868/b3779e52-ea21-11e5-98ab-bf1d87fbffa0.jpg)

**Comment by Ronniko** [comment]
I apply three but my program see only "VK_LAYER_LUNARG_mem_tracker"
![cc](https://cloud.githubusercontent.com/assets/11887473/13753050/754d0e18-ea22-11e5-83dc-d2bbe26b8697.jpg)

**Comment by Ronniko** [comment]
https://www.youtube.com/watch?v=OCgDlrbX3KE&feature=youtu.be

**Comment by Ronniko** [comment]
Finally ! 
![hh](https://cloud.githubusercontent.com/assets/11887473/13768021/57dca9f0-ea82-11e5-98e1-972bdaeaf4b0.jpg)

**Comment by Ronniko** [comment]
Finally !
![gg](https://cloud.githubusercontent.com/assets/11887473/13768901/0a80b3a4-ea8c-11e5-8aa1-3a1fcb35ee82.jpg)

**Comment by SaschaWillems** [comment]
Can you still reproduce the full screen bug that you initially reported in this issue? If yes, can you plese check what dimensions the [surface capabilities ](https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkanswapchain.hpp#L245) of the swapchain reports?

**Comment by Ronniko** [comment]
currentExtent.width = 1680 and currentExtent.height = 1050
minImageExtent.width = 1 and minImageExtent.height = 1
maxImageExtent.width = 1680 and maxImageExtent.height = 1050
