### ISSUE TITLE
Raytracingreflections sample is launching in black color and closing

### ISSUE THREAD

**Issue by pandurangkatkar** [SaschaWillems/Vulkan#803]
Raytracingreflections sample is launching in black color and closing on Nvidia RTX 2080 and AMD Radeon RX 6800 Graphics
[NVIDIA System Information 01-19-2021 13-09-04.txt](https://github.com/SaschaWillems/Vulkan/files/5835691/NVIDIA.System.Information.01-19-2021.13-09-04.txt)

**Comment by SaschaWillems** [comment]
Can you please enable the validation layers and post the output here?

**Comment by pandurangkatkar** [comment]
[vk_apidump.txt](https://github.com/SaschaWillems/Vulkan/files/5849333/vk_apidump.txt)

**Comment by SaschaWillems** [comment]
That trace does not contain any errors. Do you get any validation layer errors? Did you download the assets?

**Comment by pandurangkatkar** [comment]
Yes I have download the assets

**Comment by SaschaWillems** [comment]
And what about validation layers? It's near impossible to help on such an issue without a proper error description.

**Comment by mdinkov** [comment]
I believe I've found the root cause. A proposed fix can be found here:
https://github.com/SaschaWillems/Vulkan/pull/811

**Comment by mdinkov** [comment]
Only one error is reported by the validation layers (copied below) on AMD Radeon RX 6800. This points out a different issue, where the test might not be checking VkPhysicalDeviceRayTracingPipelinePropertiesKHR::maxRayRecursionDepth.

VUID-VkRayTracingPipelineCreateInfoKHR-maxPipelineRayRecursionDepth-03589(ERROR / SPEC): msgNum: 1555164755 - Validation Error: [ VUID-VkRayTracingPipelineCreateInfoKHR-maxPipelineRayRecursionDepth-03589 ] Object 0: handle = 0x2b6676dc660, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x5cb1ee53 | vkCreateRayTracingPipelinesKHR: **maxPipelineRayRecursionDepth (4 ) must be less than or equal to VkPhysicalDeviceRayTracingPipelinePropertiesKHR::maxRayRecursionDepth 1** The Vulkan spec states: maxPipelineRayRecursionDepth must be less than or equal to VkPhysicalDeviceRayTracingPipelinePropertiesKHR::maxRayRecursionDepth (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkRayTracingPipelineCreateInfoKHR-maxPipelineRayRecursionDepth-03589)
    Objects: 1
       [0]  0x2b6676dc660, type: 3, name: NULL

**Comment by SaschaWillems** [comment]
I have merged the PR by @mdinkov, please test again.

I'll also take a look at the validation layer messages.

**Comment by pandurangkatkar** [comment]
not observed with latest

**Comment by mdinkov** [comment]
Thank you, @SaschaWillems.

I agree that a value above one might not be required for the raytracingreflections test, as all of the traceRay invocations seem to be made inside the raygen shader.

We're also observing a similar validation error with the raytracingshadows test. In this case, a recursive traceRay call is made inside the closest hit shader. Are there plans to address this?
