### ISSUE TITLE
Headless rendering of a 2d image

### ISSUE THREAD

**Issue by michael1309** [SaschaWillems/Vulkan#805]
Hello Sascha,

thank you very much for your great examples. This makes it much easier to get started with Vulkan.

For handling 2D images, I would find it great if there was an example where you can render an image over a headless path by piping an input 2d image (e.g. 800 x 600 pixel) and end up with a modified image of size 800 x 600 (e.g. low pass filtered). One idea of mine is to combine the example https://github.com/SaschaWillems/Vulkan/tree/master/examples/renderheadless with the example https://vulkan-tutorial.com/code/25_texture_mapping.cpp by putting an image as texture on a quad and running the processing on it. 

I know that theoretically you could also take a computing shader for this. But I find it interesting to possibly augment the image with 3D objects later.

Maybe there is such a 2D image processing example already and I missed it. Every hint is welcome.

**Comment by SaschaWillems** [comment]
This [compute shader](https://github.com/SaschaWillems/Vulkan/tree/master/examples/computeshader) does some basic image processing, and could be used as a base for such a sample. Making this headless shouldn't be hard, and reading the image back similar to how the other compute headless sample reads back the buffer is also not that hard to add. I don't plan to do such a sample myself, but I hope this helps as a starting point.

**Comment by michael1309** [comment]
Hello Sascha,

Thank you very much for your prompt reply. I will explicitly take a closer look at this example.
