### ISSUE TITLE
CUDA Interoperability Sample

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#806]
CUDA has been available for over a decade now and is rich with features, libraries with a wide installed base.
Some examples of how to use Vulkan with CUDA may be of interest to the community.
At least a basic CUDA + Vulkan(Graphics) and CUDA + Vulkan(Graphics + Compute) example to show the mechanics  that can pass validation would be of great use.
Submitted respectfully for consideration.

**Comment by SaschaWillems** [comment]
I don't have any plans for such a sample. NVIDIA does seem to have a sample the demonstrates CUDA + Vulkan interop: https://github.com/NVIDIA/cuda-samples/blob/master/Samples/simpleVulkan/README.md
