### ISSUE TITLE
cmake ninja build fails on windows 10

### ISSUE THREAD

**Issue by buzmeg** [SaschaWillems/Vulkan#819]
Hi, folks, I tried to build this on Windows 10 with cmake/ninja and most of it built.  However, it failed right at the end.

Log attached below.

Thanks.

```
>cmake -G Ninja CMakeLists.txt
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at CMakeLists.txt:2 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is Clang 11.0.0 with GNU-like command-line
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using module to find Vulkan
-- Found Vulkan: C:/VulkanSDK/1.2.170.0/Lib/vulkan-1.lib
-- C:/VulkanSDK/1.2.170.0/Lib/vulkan-1.lib
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/bloom
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computecloth
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computecullandlod
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computeheadless
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computenbody
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computeparticles
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computeraytracing
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/computeshader
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/conditionalrender
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/conservativeraster
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/debugmarker
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/deferred
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/deferredmultisampling
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/deferredshadows
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/descriptorindexing
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/descriptorsets
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/displacement
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/distancefieldfonts
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/dynamicuniformbuffer
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/gears
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/geometryshader
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/gltfloading
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/gltfscenerendering
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/gltfskinning
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/hdr
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/imgui
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/indirectdraw
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/inlineuniformblocks
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/inputattachments
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/instancing
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/multisampling
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/multithreading
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/multiview
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/negativeviewportheight
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/occlusionquery
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/offscreen
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/oit
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/parallaxmapping
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/particlefire
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pbrbasic
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pbribl
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pbrtexture
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pipelines
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pipelinestatistics
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pushconstants
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/pushdescriptors
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/radialblur
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/rayquery
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/raytracingbasic
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/raytracingcallable
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/raytracingreflections
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/raytracingshadows
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/renderheadless
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/screenshot
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/shadowmapping
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/shadowmappingomni
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/shadowmappingcascade
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/specializationconstants
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/sphericalenvmapping
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/ssao
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/stencilbuffer
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/subpasses
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/terraintessellation
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/tessellation
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/textoverlay
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texture
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texture3d
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texturearray
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texturecubemap
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texturecubemaparray
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texturemipmapgen
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/texturesparseresidency
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/triangle
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/variablerateshading
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/viewportarray
-- Generating project file for example in C:/Users/foo/Desktop/vulkan_projects/Vulkan/examples/vulkanscene
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/foo/Desktop/vulkan_projects/Vulkan

C:\Users\foo\Desktop\vulkan_projects\Vulkan>ninja
[5/179] Building C object base/CMakeFiles/base.dir/__/external/ktx/lib/texture.c.obj
external/ktx/lib/texture.c:31:9: warning: '_CRT_SECURE_NO_WARNINGS' macro redefined [-Wmacro-redefined]
#define _CRT_SECURE_NO_WARNINGS
        ^
<command line>:2:9: note: previous definition is here
#define _CRT_SECURE_NO_WARNINGS 1
        ^
1 warning generated.
[32/179] Building CXX object examples/CMakeFiles/oit.dir/oit/oit.cpp.obj
examples/oit/oit.cpp:501:7: warning: 'buildCommandBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void buildCommandBuffers()
             ^
base\vulkanexamplebase.h:373:15: note: overridden virtual function is here
        virtual void buildCommandBuffers();
                     ^
1 warning generated.
[157/179] Building CXX object examples/CMakeFiles/textoverlay.dir/textoverlay/textoverlay.cpp.obj
examples/textoverlay/textoverlay.cpp:509:11: warning: enumeration value 'alignLeft' not handled in switch [-Wswitch]
                switch (align)
                        ^
1 warning generated.
[162/179] Linking CXX executable bin\texture3d.exe
FAILED: bin/texture3d.exe
cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -DVK_USE_PLATFORM_WIN32_KHR -DNOMINMAX -D_USE_MATH_DEFINES -Wno-switch-enum -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:windows examples/CMakeFiles/texture3d.dir/texture3d/texture3d.cpp.obj -o bin\texture3d.exe -Xlinker /implib:examples\texture3d.lib -Xlinker /pdb:bin\texture3d.pdb -Xlinker /version:0.0   base/base.lib  C:/VulkanSDK/1.2.170.0/Lib/vulkan-1.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames && cd ."
lld-link: error: undefined symbol: __kmpc_fork_call
>>> referenced by C:\Users\foo\Desktop\vulkan_projects\Vulkan\examples\texture3d\texture3d.cpp:310
>>>               examples/CMakeFiles/texture3d.dir/texture3d/texture3d.cpp.obj:(public: void __cdecl VulkanExample::updateNoiseTexture(void))

lld-link: error: undefined symbol: __kmpc_for_static_init_4u
>>> referenced by C:\Users\foo\Desktop\vulkan_projects\Vulkan\examples\texture3d\texture3d.cpp:311
>>>               examples/CMakeFiles/texture3d.dir/texture3d/texture3d.cpp.obj:(.omp_outlined._debug__)

lld-link: error: undefined symbol: __kmpc_for_static_fini
>>> referenced by C:\Users\foo\Desktop\vulkan_projects\Vulkan\examples\texture3d\texture3d.cpp:310
>>>               examples/CMakeFiles/texture3d.dir/texture3d/texture3d.cpp.obj:(.omp_outlined._debug__)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[173/179] Building CXX object examples/CMakeFiles/vulkanscene.dir/vulkanscene/vulkanscene.cpp.obj
ninja: build stopped: subcommand failed.
```

**Comment by SaschaWillems** [comment]
Sorry, I have never used ninja to build my samples so I can't help with this. The build errors also point to functions outside of my samples, so I don't know why this fails.

**Comment by buzmeg** [comment]
Then please list the "blessed" (aka: anything that somebody actually used in the last couple months to build) build combinations in the BUILD.md file.

I really don't want to go through the grief to install "Visual Studio 14 2015 Win64" only to find that nobody has used that in several years and it's broken too.

Thanks.

**Comment by SaschaWillems** [comment]
clang should work fine. It seems to fail at the texture3D sample which uses OpenMP. So maybe you need to link against OpenGP with clang? I did successful compiles with clang and gcc on Windows, but that has been some time ago.

**Comment by buzmeg** [comment]
I'll try this at some point, but it's going to take me a little while to get back to it as I moved forward a while ago.

**Comment by buzmeg** [comment]
I can confirm that the cmake/ninja combination does work with Ubuntu.  

I don't think it has to do with OpenMP though--quoting the log:

```
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
```

This is not something I'm willing to spend time running down, so feel free to do whatever you want with the issue.

Feel free to close the issue or leave it open so someone else has a warning that this doesn't work on Windows.

Thanks.

**Comment by GetzGames** [comment]
I also use cmake-ninja-clang on windows and i get the following errors:
`[main] Building folder: Vulkan triangle
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/emile/Desktop/Vulkan/build --config Debug --target triangle -j 10 --
[build] [1/1 100% :: 0.715] Linking CXX executable bin\triangle.exe
[build] FAILED: bin/triangle.exe 
[build] cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -DVK_USE_PLATFORM_WIN32_KHR -DNOMINMAX -D_USE_MATH_DEFINES -Wno-switch-enum -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:windows examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj -o bin\triangle.exe -Xlinker /implib:examples\triangle.lib -Xlinker /pdb:bin\triangle.pdb -Xlinker /version:0.0   base/base.lib  C:/VulkanSDK/1.2.176.0/Lib/vulkan-1.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames && cd ."
[build] lld-link: error: undefined symbol: public: void __cdecl VulkanExampleBase::handleMessages(struct HWND__*, unsigned int, unsigned __int64, __int64)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1107
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(__int64 __cdecl WndProc(struct HWND__*, unsigned int, unsigned __int64, __int64))
[build] 
[build] lld-link: error: undefined symbol: public: static class std::vector<char const *, class std::allocator<char const *>> VulkanExampleBase::args
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1113
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(WinMain)
[build] 
[build] lld-link: error: undefined symbol: public: bool __cdecl VulkanExampleBase::initVulkan(void)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1115
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(WinMain)
[build] 
[build] lld-link: error: undefined symbol: public: struct HWND__* __cdecl VulkanExampleBase::setupWindow(struct HINSTANCE__*, __int64 (__cdecl *)(struct HWND__*, unsigned int, unsigned __int64, __int64))
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1116
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(WinMain)
[build] 
[build] lld-link: error: undefined symbol: public: void __cdecl VulkanExampleBase::renderLoop(void)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1118
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(WinMain)
[build] 
[build] lld-link: error: undefined symbol: public: __cdecl VulkanExampleBase::VulkanExampleBase(bool)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:115
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: __cdecl VulkanExample::VulkanExample(void))
[build] 
[build] lld-link: error: undefined symbol: public: virtual __cdecl VulkanExampleBase::~VulkanExampleBase(void)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:123
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(int `public: __cdecl VulkanExample::VulkanExample(void)'::`1'::dtor$7)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:150
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: virtual __cdecl VulkanExample::~VulkanExample(void))
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:150
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(int `public: virtual __cdecl VulkanExample::~VulkanExample(void)'::`1'::dtor$19)
[build] 
[build] lld-link: error: undefined symbol: class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> __cdecl vks::tools::errorString(enum VkResult)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:285
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: virtual void __cdecl VulkanExample::buildCommandBuffers(void))
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:329
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: virtual void __cdecl VulkanExample::buildCommandBuffers(void))
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:642
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: virtual void __cdecl VulkanExample::setupDepthStencil(void))
[build] >>> referenced 51 more times
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::prepare(void)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:1071
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: virtual void __cdecl VulkanExample::prepare(void))
[build] 
[build] lld-link: error: undefined symbol: public: enum VkResult __cdecl VulkanSwapChain::acquireNextImage(struct VkSemaphore_T *, unsigned int *)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:336
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: void __cdecl VulkanExample::draw(void))
[build] 
[build] lld-link: error: undefined symbol: public: enum VkResult __cdecl VulkanSwapChain::queuePresent(struct VkQueue_T *, unsigned int, struct VkSemaphore_T *)
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:361
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: void __cdecl VulkanExample::draw(void))
[build] 
[build] lld-link: error: undefined symbol: protected: class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> __cdecl VulkanExampleBase::getShadersPath(void) const
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:973
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: void __cdecl VulkanExample::preparePipelines(void))
[build] >>> referenced by C:\Users\emile\Desktop\Vulkan\examples\triangle\triangle.cpp:983
[build] >>>               examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(public: void __cdecl VulkanExample::preparePipelines(void))
[build] 
[build] lld-link: error: undefined symbol: public: virtual enum VkResult __cdecl VulkanExampleBase::createInstance(bool)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::keyPressed(unsigned int)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::mouseMoved(double, double, bool &)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::windowResized(void)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::getEnabledFeatures(void)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::renderFrame(void)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] 
[build] lld-link: error: undefined symbol: public: virtual void __cdecl VulkanExampleBase::OnUpdateUIOverlay(class vks::UIOverlay *)
[build] >>> referenced by examples/CMakeFiles/triangle.dir/triangle/triangle.cpp.obj:(const VulkanExample::`vftable')
[build] clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1`

**Comment by buzmeg** [comment]
Only Windows 10 with Visual Studio 2019 is used by Sacha Willems.  See #972.

All other configurations can be assumed to be questionable.

Closing.
