### ISSUE TITLE
need help with which glm version to use for ubuntu 16.04

### ISSUE THREAD

**Issue by jmairey** [SaschaWillems/Vulkan#821]
cmake runs just fine on my ubuntu 16.04 machine. so does vulkan-info. the machine has a 2016 era nvidia gpu in it.

I cloned the project I apt installed glm-dev (don't know what version tho).

When I try to compile triangle, I get a syntax error that appears to indicate I don't have the right version of glm.

what version of glm do I need to be able to compile triangle? I am an old graphics guy, but not a modern c++ whiz. 

need help or advice from somebody on how to get triangle to compile and how to navigate glm versions with this repo. jmairey at hotmail dot com

jairey@machine:~/SaschaWillemsVulkan/Vulkan$ make triangle
[  0%] Building CXX object base/CMakeFiles/base.dir/VulkanAndroid.cpp.o
[  7%] Building CXX object base/CMakeFiles/base.dir/VulkanBuffer.cpp.o
[  7%] Building CXX object base/CMakeFiles/base.dir/VulkanDebug.cpp.o
[ 15%] Building CXX object base/CMakeFiles/base.dir/VulkanDevice.cpp.o
[ 15%] Building CXX object base/CMakeFiles/base.dir/VulkanRaytracingSample.cpp.o
[ 23%] Building CXX object base/CMakeFiles/base.dir/VulkanSwapChain.cpp.o
[ 23%] Building CXX object base/CMakeFiles/base.dir/VulkanTexture.cpp.o
[ 30%] Building CXX object base/CMakeFiles/base.dir/VulkanTools.cpp.o
[ 38%] Building CXX object base/CMakeFiles/base.dir/VulkanUIOverlay.cpp.o
[ 38%] Building CXX object base/CMakeFiles/base.dir/VulkanglTFModel.cpp.o
/home/jairey/SaschaWillemsVulkan/Vulkan/base/VulkanglTFModel.cpp: In member function ‘void vkglTF::Model::loadNode(vkglTF::Node*, const tinygltf::Node&, uint32_t, const tinygltf::Model&, std::vector<unsigned int>&, std::vector<vkglTF::Vertex>&, float)’:
/home/jairey/SaschaWillemsVulkan/Vulkan/base/VulkanglTFModel.cpp:768:21: error: no match for ‘operator=’ (operand types are ‘glm::quat {aka glm::tquat<float, (glm::precision)0u>}’ and ‘glm::tmat4x4<float, (glm::precision)0u>’)
   newNode->rotation = glm::mat4(q);
                     ^
In file included from /usr/include/glm/gtc/type_ptr.hpp:66:0,
                 from /home/jairey/SaschaWillemsVulkan/Vulkan/base/VulkanglTFModel.h:26,
                 from /home/jairey/SaschaWillemsVulkan/Vulkan/base/VulkanglTFModel.cpp:14:
/usr/include/glm/gtc/quaternion.hpp:136:31: note: candidate: glm::tquat<T, P>& glm::tquat<T, P>::operator=(const glm::tquat<T, P>&) [with T = float; glm::precision P = (glm::precision)0u]
   GLM_FUNC_DECL tquat<T, P> & operator=(tquat<T, P> const & m) GLM_DEFAULT;
                               ^
/usr/include/glm/gtc/quaternion.hpp:136:31: note:   no known conversion for argument 1 from ‘glm::tmat4x4<float, (glm::precision)0u>’ to ‘const glm::tquat<float, (glm::precision)0u>&’
/usr/include/glm/gtc/quaternion.hpp:139:31: note: candidate: template<class U> glm::tquat<T, P>& glm::tquat<T, P>::operator=(const glm::tquat<U, P>&) [with U = U; T = float; glm::precision P = (glm::precision)0u]
   GLM_FUNC_DECL tquat<T, P> & operator=(tquat<U, P> const & m);
                               ^

**Comment by SaschaWillems** [comment]
You don't need to manually install glm at all. This repo is setup so that you can compile and run it out of the box.

glm is included as a submodule, so you just need to clone with submodules (see https://github.com/SaschaWillems/Vulkan#cloning), run cmake and then you're ready to go with the exact glm version that this repo requires.

**Comment by jmairey** [comment]
Thanks Sascha. that worked. my excuse is that only smart people read silly things like manuals. sigh.

1407  mv Vulkan/ Vulkan.orig
 1408  git clone --recursive https://github.com/SaschaWillems/Vulkan.git
 1409  cd Vulkan
 1410  cmake .
 1411  make triangle
 1412  ls bin/triangle 
 1413  bin/triangle  <I saw a triangle>
 1414  history
