### ISSUE TITLE
Issue in gltf-loading and scene rendering

### ISSUE THREAD

**Issue by MohammadFakhreddin** [SaschaWillems/Vulkan#822]
Dear Mr. Willems, 
Thank you for your great examples. today while I was reading your examples I found an issue about rendering gltf nodes that have transformation matrices. I attached 2 images to help you realize the issue.
This is the model running on your sample code
![image](https://user-images.githubusercontent.com/13017021/114286616-a715b180-9a75-11eb-9011-40ef93006bb7.png)
This is what the model actually has to be
![image](https://user-images.githubusercontent.com/13017021/114286627-bc8adb80-9a75-11eb-83ac-2c13922db69a.png)
As you can see the wings do not have the correct position.

**Comment by MohammadFakhreddin** [comment]
Unfortunately I couldn't attach the model directly, This is the address that you can download the gunship mode
https://sketchfab.com/3d-models/warhammer-40k-space-marine-stormtalon-gunship-f3fb70e7628048b99b635d4e4cd13e7b

**Comment by SaschaWillems** [comment]
As noted in the header, the glTF sample is not a complete glTF implementation. If you're looking for a more complete implementation please take a look at https://github.com/SaschaWillems/Vulkan-glTF-PBR.

**Comment by MohammadFakhreddin** [comment]
Thanks for your response
