### ISSUE TITLE
Bugs in using custom descriptor set layout of vkglTF

### ISSUE THREAD

**Issue by FlyAndNotDown** [SaschaWillems/Vulkan#824]
Hello, there are some bugs when I using custom descriptor layout of vkglTF:

* Some arguments (like `renderFlags`, `pipelineLayout`) of `vkglTF::Model::draw()` will not transfer to `vkglTF::Model::drawNode()`, so when I using `RenderFlags::BindImages` to render scene, variable `pipelineLayout` is `VK_NULL_HANDLE` in `vkglTF::Model::drawNode()`
* Sometime, `baseColorTexture` of material is nullptr, if this situation happened, `material.descriptorSet` will be nullptr, so `vkCmdBindDescriptorSets` in `vkglTF::Model::drawNode` will failed

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. esp. the latter is a limitation I'm aware of, and the vkglTF class provided is not actually meant to load arbitrary models. I'll take a look at it though.

**Comment by SaschaWillems** [comment]
Point 1 is fixed. Arguments are now passed down to the child nodes.

Point 2 is out of scope, as it would require to e.g. bind some dummy texture.

If you're looking for a more complete glTF implementation in Vulkan, please check https://github.com/SaschaWillems/Vulkan-glTF-PBR.
