### ISSUE TITLE
Benchmarking under Wayland

### ISSUE THREAD

**Issue by Flakebi** [SaschaWillems/Vulkan#833]
Hi, thanks for these nice examples.

Benchmarking under wayland (with `-DUSE_WAYLAND_WSI=ON`) hangs for me after a few frames without showing a window. I fixed it with the following patch (influenced by https://github.com/michaelforney/st/pull/8#issuecomment-403615287):
```diff
diff --git a/base/vulkanexamplebase.cpp b/base/vulkanexamplebase.cpp
index 507666ee..4ff26ced 100644
--- a/base/vulkanexamplebase.cpp
+++ b/base/vulkanexamplebase.cpp
@@ -2205,6 +2205,10 @@ struct xdg_surface *VulkanExampleBase::setupWindow()
    std::string windowTitle = getWindowTitle();
    xdg_toplevel_set_title(xdg_toplevel, windowTitle.c_str());
    wl_surface_commit(surface);
+   wl_display_flush(display);
+   while (!configured)
+       wl_display_dispatch(display);
+
    return xdg_surface;
 }
```

I think this more of a hack than a proper fix as the same code is also in `VulkanExampleBase::renderLoop`, but that is not called when benchmarking

**Comment by SaschaWillems** [comment]
Should be fixed with #1042
