### ISSUE TITLE
Suggestion: RadeonRays ray tracing examples

### ISSUE THREAD

**Issue by procedural** [SaschaWillems/Vulkan#834]
Yesterday, Radeon Rays 4.1 [was open sourced](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/releases/tag/4.1) under MIT again, given that it's an official AMD library that works on non-RX 6000 and non-RTX cards as well, it would be cool to see your examples using it. :)

**Comment by SaschaWillems** [comment]
I don't plan on adding such a sample, esp. as this would pull in a large external dependency.

**Comment by procedural** [comment]
Bummer!
