### ISSUE TITLE
"Instancing" example: Incorrect device count in vulkanappbase

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#835]
Only when running the `instancing` example, `vkEnumeratePhysicalDevices()` in `bool VulkanExampleBase::initVulkan()` returns incorrect gpu count of 1 in a 2 gpu system: Intel HD 630(driver 27.20.100.9466) and GTX 1050Ti(driver 465.89)

Running windows 10.0.18363  Pro workstation, Vulkan SDK 1.2.162.1. 

 I have tried over a dozen other examples and they return the correct count of 2.

**Comment by SaschaWillems** [comment]
That's very odd. I sadly don't have a system with multiple GPUs, so I can't reproduce this.

**Comment by SaschaWillems** [comment]
Any update on this?

**Comment by kyamant** [comment]
Unfortunately no. I have moved to a single gpu desktop and no longer updating the Vulkan, Nvidia drivers etc on the laptop where I observed this
