### ISSUE TITLE
multiview hit validation error UNASSIGNED-CoreValidation-DrawState-InvalidRenderArea during window resize

### ISSUE THREAD

**Issue by souravpNV** [SaschaWillems/Vulkan#840]
[UNASSIGNED-CoreValidation-DrawState-InvalidRenderArea]cannot execute a render pass with renderArea not within the bound of the framebuffer

The fix would be to set multiviewPass.frameBuffer to appropriate size in prepareMultiview during resize too.

**Comment by SaschaWillems** [comment]
This ha recently been fixed, the multiviewPass' framebuffer is now properly resized too.
