### ISSUE TITLE
stuttering when using VK_PRESENT_MODE_FIFO_KHR

### ISSUE THREAD

**Issue by xatian** [SaschaWillems/Vulkan#844]
I forced your examples to use VK_PRESENT_MODE_FIFO_KHR by basically changing this line of code:
https://github.com/SaschaWillems/Vulkan/blob/434546625f6612ad2de6d8c6d2f0ff39505e8610/base/VulkanSwapChain.cpp#L267
Then when running e.g. the gears example I experience stuttering.
(like every now and then it seems as if a frame is dropped and the gears jump slightly)
The system is running debian testing / GTX 1080 (460.73.01).

Is this to be expected?
Are your examples not designed to be run with vsync enabled and therefore the stuttering is fine?
If that is not the case (so if vsync should work) --> do you have an explanation for this?
I tested some games via steam that have a native linux version and using vulkan and they don't seem to have this problem --> even when running them in window mode and of course vsync enabled there is no stuttering noticable.

Thank you!

**Comment by SaschaWillems** [comment]
No, that's not expected behavior. I test my samples on different implementations and platforms using different present modes with and without v-sync and I don't have any stutter.

Did you run one of the stuttering sample through a GPU profiler to see what's causing the stuttering?

**Comment by xatian** [comment]
Interesting.
No I did not --> I used nvidia Nsight in the past but it only shows vulkan buffer contents and command-buffer calls. For most stuff (including timings) it says that I need a turing-class GPU which is (I believe) the next GPU-generation than what I have currently :-)
Is there a profiler that you would suggest?

**Comment by HugoPeters1024** [comment]
Maybe a bug in the video driver, has the issue been magically resolved months later?

**Comment by xatian** [comment]
Yes it has resolved. All that has changed is the video driver version which is now 470.57.02
Though I never found the reason why retail games did not suffer from frame drops as well.
Thank you!

**Comment by DaveGravel** [comment]
I get a problem with the vsync mode me too.
I have the last nvidia driver.
Exemple if I build the bloom demo with vsync active, I get some strange squared pixels when I rotate the view.
It look to happen in pretty much all demos when vsync is active.
Exemple if you enable the vsync and you open a demo just to zoom in and out and rotate the view from up and down with a fast move.
In the bottom right corner you can see a sort a rectangular glitch and in the bottom you can see some squared pixel and triangular shape.
The visual glitch look like some parts of the screen is cutted.
