### ISSUE TITLE
Android arm64 target

### ISSUE THREAD

**Issue by SupinePandora43** [SaschaWillems/Vulkan#848]
Or armeabi-v7a is enough?

**Comment by SaschaWillems** [comment]
What's the actual question? Can you add some details?

**Comment by SupinePandora43** [comment]
It is worth compiling also for `arm-x64` target architecture in android examples?

**Comment by SaschaWillems** [comment]
Not sure. Is that Windows on ARM? If so, I'm not sure if that supports Vulkan at all.

**Comment by SupinePandora43** [comment]
> Not sure. Is that Windows on ARM? If so, I'm not sure if that supports Vulkan at all.

> Android

**Comment by SaschaWillems** [comment]
If you're lacking a target architecture, feel free to do add it. There's nothing in the repo that shouldn't work with arm-x64.
