### ISSUE TITLE
c++98 version and mingw32 version and source?

### ISSUE THREAD

**Issue by sdragonx** [SaschaWillems/Vulkan#853]
c++98 version and mingw32 version and source?

**Comment by SaschaWillems** [comment]
Can you elaborate? What's the actual question here?

**Comment by sdragonx** [comment]
vulkan SDK only provides vs development library. Is there C + + 98 or mingw32?
Or source code.

**Comment by SaschaWillems** [comment]
This is just a samples repository and not connected to LunarG's Vulkan SDK. You need to ask that question to LunarG.
