### ISSUE TITLE
libs/libvulkan.so.1.1.73 is only for x86 linux, need ARM linux

### ISSUE THREAD

**Issue by zhangfuwen** [SaschaWillems/Vulkan#857]
Hi, I am running ARM linux and I am trying to compile this code on my platform. the provided lib is only for x86. Is there any workaround I can make to make this code work under ARM linux?

**Comment by mrcmunir** [comment]
@zhangfuwen the workarround install libvulkan-dev in you system so the linker not linker by libs/libvulkan.so repo .

**Comment by SaschaWillems** [comment]
I only provide some Vulkan libraries for common platforms so people can run this out of the box.

Installing the SDK or package for your platform is actually the preferred way, as it's the only way to get the latest libraries.
