### ISSUE TITLE
clang-format file doesn't match with the files in the github

### ISSUE THREAD

**Issue by pdc3** [SaschaWillems/Vulkan#858]
when I run clang-format on most of the example files, it create a quite different file. What are the rules use for the format in this repository ?

**Comment by SaschaWillems** [comment]
The clang format file has been added only recently, so all the existing samples don't make use of it yet. If you want to add a new sample a via a PR, using clang format is suggested. If you want to submit a fix for an existing sample, use the code style of that sample instead.

**Comment by pdc3** [comment]
Thanks for the update. I'm using VS and Eclipse. I didn't find a way to enable or disable the clang format per project. I will leave it off per default. 
FYI in the clang format file there are some key's VS 2017 and clang-format-6.0 (default Ubuntu 18.04) don't understand. In both cases the latest version (from https://llvm.org/ ) needs to be added to overwrite the default versions.

**Comment by SaschaWillems** [comment]
I have removed the clang file for now.
