### ISSUE TITLE
Big buffer in Vulkan shader.

### ISSUE THREAD

**Issue by Ronniko** [SaschaWillems/Vulkan#86]
In GLSL (OpenGL) layout (std430, binding=0) buffer

But for Vulkan shader how create big buffer(100 megabytes data).

I mean analog layout (std430, binding=0) buffer in Vulkan shader.

**Comment by SaschaWillems** [comment]
What exactly do you want to do? If you need to access lots of data in a shader use shader storage buffer objects like in the compute shader particle system. Create them host visible and use staging to move them to gpu (this is currently missing form my example, but I'm working on that).

**Comment by eloj** [comment]
@Ronniko Could you please find a different "forum" for general questions? Something like the [Khronos](https://forums.khronos.org/forumdisplay.php/114-Vulkan-High-Efficiency-GPU-Graphics-and-Compute) forum for Vulkan would be much better suited for these things. Thank you.

**Comment by SaschaWillems** [comment]
I'm with eloj on this. The github issue tracker is not the right place to ask questions, so either use the Vulkan forums at Khronos or ask your questions at StackOverflow.
