### ISSUE TITLE
Build error for android

### ISSUE THREAD

**Issue by dubeyabhijeet** [SaschaWillems/Vulkan#869]
D:/Vulkan-master/Vulkan-master/android/examples/base/../../../base/vulkanexamplebase.h:52:10: fatal error: 'glm/glm.hpp' file not found

  #include <glm/glm.hpp>

           ^~~~~~~~~~~~~

Please help

**Comment by SaschaWillems** [comment]
You probably did not clone the submodules. See the build instructions on how to do that.
