### ISSUE TITLE
inlineuniformblocks example

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#875]
In inlineuniformblocks.cpp's `void setupDescriptorSetLayout()` function,  `vks::initializers::descriptorSetLayoutBinding(VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(Object::Material)` 
causes validation error in 
`VK_CHECK_RESULT(vkCreateDescriptorSetLayout(device, &descriptorLayoutCI, nullptr, &descriptorSetLayouts.object));`

`ERROR: [-1434200713][VUID-VkDescriptorSetLayoutBinding-descriptorType-04604] : Validation Error: [ VUID-VkDescriptorSetLayoutBinding-descriptorType-04604 ] Object 0: handle = 0x1eb95238288, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xaa83d577 | vkCreateDescriptorSetLayout(): pBindings[0] is creating VkDescriptorSetLayout with descriptor type VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT but the inlineUniformBlock feature is not enabled The Vulkan spec states: If the inlineUniformBlock feature is not enabled, descriptorType must not be VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT (https://vulkan.lunarg.com/doc/view/1.2.182.0/windows/1.2-extensions/vkspec.html#VUID-VkDescriptorSetLayoutBinding-descriptorType-04604)`

One solution, not necessarily optimal, is to modify `VulkanDevice::createLogicalDevice()` in VulkanDevice.cpp and add a
 `PhysicalDeviceInlineUniformBlockFeaturesEXT` structure, with `inlineUniformBlock = VK_TRUE`, to `deviceCreateInfo.pNext` before the call to `vkCreateDevice()`.

**Comment by SaschaWillems** [comment]
Thanks for reporting this. I have created an issue to collect all validation layer errors to make it easier to keep track of them: #876. I'm currently doing a large rework of the samples (see #871), so some of these have already been fixed in a different branch.

**Comment by SaschaWillems** [comment]
> One solution, not necessarily optimal, is to modify VulkanDevice::createLogicalDevice() in VulkanDevice.cpp and add a
PhysicalDeviceInlineUniformBlockFeaturesEXT structure, with inlineUniformBlock = VK_TRUE, to deviceCreateInfo.pNext before the call to vkCreateDevice().

The samples already have functionality to enable such features.
