### ISSUE TITLE
Qestion about installing vulkan

### ISSUE THREAD

**Issue by WilliamWangPeng** [SaschaWillems/Vulkan#879]
Hi dear author,  
    It's a great honor to open the issue here, I have got the following problems when installing vulkan, the examples in bin folder can not be tested, do you know why? 

![image](https://user-images.githubusercontent.com/51076736/133737978-8520ba03-d724-4ad6-94c9-d72fb1066cd5.png)

![image](https://user-images.githubusercontent.com/51076736/133738013-76c2cb96-f6a3-4b4c-a204-53acec65678e.png)

thank you
best regards
William

**Comment by HugoPeters1024** [comment]
I don't think it's a problem with the vulkan installation per se. It seems like GLFW and your windowing manager have some beef.

**Comment by SaschaWillems** [comment]
Please try running the samples with Validation enabled, and check output for any errors.
