### ISSUE TITLE
window10 Android Studio build failing

### ISSUE THREAD

**Issue by 1479482558** [SaschaWillems/Vulkan#883]
Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true
-----------------------------------------------------------------------------------------
local.properties file:
```
sdk.dir=C\:\\Users\\czm\\AppData\\Local\\Android\\Sdk

ndk.dir=C\:\\Users\\czm\\AppData\\Local\\Android\\Sdk\\ndk\\23.0.7599858
```

Sync Project with Gradle file
ERROR:

```
A problem occurred configuring project ":bloom".

> java.lang.NullPointerException (**no error message**)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project :bloom.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:72)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$600(LifecycleProjectEvaluator.java:53)
       ... more
Caused by: java.lang.NullPointerException
	at com.android.build.gradle.internal.ndk.NdkHandler.getPlatformVersion(NdkHandler.java:121)
	at com.android.build.gradle.internal.ndk.NdkHandler.supports64Bits(NdkHandler.java:221)
	at com.android.build.gradle.internal.ndk.NdkHandler.getSupportedAbis(NdkHandler.java:269)
	... more
```

On Windows execute
```
gradlew.bat assembleDebug
```

ERROR:

```
> Configure project :bloom
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\czm\AppData\Local\Android\Sdk\23.0.7599858.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
```

**_How to set the NDK path ???_**

**Comment by SaschaWillems** [comment]
The whole Android native build ecosystem is pretty broken. Just create an empty platforms directory in your NDK directory and the error message should go away.

**Comment by 1479482558** [comment]
```
ndk\\23.0.7599858
```
build failing
```
ndk\\21.4.7075529
```
build pass

Change version to create project . But Make Project...
```
C:\Users\czm\AndroidStudioProjects\Vulkan\base\VulkanDebug.h:23:10:
fatal error: 'glm/glm.hpp' file not found
```
¬_¬
other 
Google Play requires that apps target API level 29 or higher.
All examples are targetSdkVersion 26

**Comment by SaschaWillems** [comment]
So does it work now? If yes, you could close the issue.

> Google Play requires that apps target API level 29 or higher.
All examples are targetSdkVersion 26

I know. But I'm not distributing my samples on the store.
