### ISSUE TITLE
Suggestion for new examples

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#897]
I would like to suggest the following be considered for future examples:
**1.** Transform Feedback (and queries)
**2.** Video Encode/Decode
**3.** Vulkan  Display

**Comment by SaschaWillems** [comment]
> Vulkan Display

Can you elaborate on this? Are you referring to Direct Display?

**Comment by kyamant** [comment]
Yes I meant Direct Display, sorry for the confusion.

**Comment by SaschaWillems** [comment]
The framework already supports Direct Display. There is no explicit sample though.

**Comment by kyamant** [comment]
**4.** Raytracing with procedurally generated object(s)

**Comment by kyamant** [comment]
**5.** MicroMaps

**Comment by kyamant** [comment]
**6.** Optical Flow

**Comment by tphan-gpfw** [comment]
I would like to have some pointers to integrate [vk_video_decoder](https://github.com/nvpro-samples/vk_video_samples/tree/main/vk_video_decoder) to display a frame from a video inside a VulkanExample please

**Comment by SaschaWillems** [comment]
> 4. Raytracing with procedurally generated object(s)

I added a sample for that now, see https://github.com/SaschaWillems/Vulkan/tree/master/examples/raytracingintersection

**Comment by SaschaWillems** [comment]
> I would like to have some pointers to integrate [vk_video_decoder](https://github.com/nvpro-samples/vk_video_samples/tree/main/vk_video_decoder) to display a frame from a video inside a VulkanExample please
> 
> Update: I managed to integrate `vk_video_decoder` with `VulkanExample`. The trick is to use `VulkanDeviceContext` of `vk_video_decoder` to initialize VkInstance, VkPhysicalDevice and VkDevice of VulkanExample class.

I don't have any plans for Vulkan video samples for this repository as of now. Nvidia has you covered though, see https://github.com/nvpro-samples/vk_video_samples

**Comment by SaschaWillems** [comment]
Closing this for now. I added samples/stuff that makes sense for this repo.
