### ISSUE TITLE
Problems with learming Vulkan

### ISSUE THREAD

**Issue by acterhd** [SaschaWillems/Vulkan#9]
Hello. Can you present SFML (or SDL) version, with single file (main.cpp) realization? 
And please, sort descriptions declaration sequentionally. 

Allowed: functions, GLM, GLI, SFML or SDL,  single file (main) . 
Need hello triangle sample.

**Comment by Marqin** [comment]
College homework?

**Comment by acterhd** [comment]
I just plan to write more complex example - smallpt.

**Comment by Marqin** [comment]
After I finish my exams ( so, next week ) I'll work on and post some Vulkan examples that use only GLFW ( and assimp for 3d objects ), but I've still not decided if it will be pure C11 or C++14 with classes and GLM.

**Comment by vinjn** [comment]
assimp is too huge, for static objects, I would recommend https://github.com/syoyo/tinyobjloader

**Comment by acterhd** [comment]
I have no problems with assimp. I have problems with understand vulkan. I
compare with directx 12, and can't understand what is "pool"?! In DirectX
we can get cbv offset, and use part. In Vulkan I can't understand system. I
think directx 12 idea slightly simpler.

**Comment by acterhd** [comment]
And... I look to vulkan from dx12 point, because 6 month I learned only
dx12 code. So I can understand only with accurate comparsion with directx
12.

**Comment by SaschaWillems** [comment]
@acterhd : If you need a single file example, please take a look at the cube.c and tri.c examples from the LunarGSDK.

**Comment by SaschaWillems** [comment]
@acterhd : Also take a look at this great article by Baldur Karlsson : [Vulkan in 30 minuts](https://renderdoc.org/vulkan-in-30-minutes.html)

Perfect starting point if you want to learn Vulkan from the ground up

**Comment by acterhd** [comment]
I want C++ wrapper for Vulkan API...

**Comment by SaschaWillems** [comment]
@acterhd : Please take a look at this : https://developer.nvidia.com/open-source-vulkan-c-api
