### ISSUE TITLE
Bad `width` test

### ISSUE THREAD

**Issue by 1ace** [SaschaWillems/Vulkan#90]
In base/vulkanswapchain.hpp +261
```
if (surfCaps.currentExtent.width == -1)
```
`struct VkExtent2D` is composed of `uint32_t`, so `width` can never be `-1`.

I haven't looked at the code that would set it to that value, but it should probably be written some other way. Maybe add a bool to the struct?
It's also possible the test wasn't meant to be for `-1` but `0`?

**Comment by SaschaWillems** [comment]
Thx, this is indeed wrong. In one of the early Vulkan SDKs width and height of an extent were signed integers. I'll take a look at this.

**Comment by 1ace** [comment]
That's the problem with early access: your whole codebase has to follow a moving target ^^

**Comment by SaschaWillems** [comment]
Just digging through some old issues :wink: 

The comparison is actually correct, but was lacking a proper explanation, so I added a comment and an explicit cast to (uint32_t)-1 which equals the special value of 0xFFFFFFFF as described in the spec:

> currentExtent is the current width and height of the surface, or the special value (0xFFFFFFFF,0xFFFFFFFF)
indicating that the surface size will be determined by the extent of a swapchain targeting the surface.
