### ISSUE TITLE
download_assets.py sometimes fails

### ISSUE THREAD

**Issue by jwinarske** [SaschaWillems/Vulkan#903]
I'm seeing download_assets.py fail periodically in CI job.

Is it possible to move to a git submodule for assets, or at least a versioned asset download file?

**Comment by SaschaWillems** [comment]
Are you getting a specific error code? The assets are hosted on my own web space, which should be very reliable.

Moving the assets to a git submodule is something I've been wanting to do for a long time, but haven't found time to do so yet. I may tackle that once I'm done with reworking the synchronization part of the samples. But that probably won't happen this year.

**Comment by jwinarske** [comment]
I wiped the log.  It was something about mismatched size, and failed.  I will switch to using curl in CI with a 5x retry.

Sure.  If you have a git lfs repo of the assets i would be happy to submit a PR.

**Comment by SaschaWillems** [comment]
I made the assets repository public, see https://github.com/SaschaWillems/Vulkan-Assets

It's not (yet) included as a submodule, but maybe you can clone this from your CI job instead of trying to download the assets via python.

**Comment by jwinarske** [comment]
I pulled this in and haven't seen any further CI errors.

Thank you!
