### ISSUE TITLE
Why, when creating a logical device, the index of the computational queue family is recorded if it is not required.

### ISSUE THREAD

**Issue by mrjbom** [SaschaWillems/Vulkan#904]
The code of the [createLogicalDevice()](https://github.com/SaschaWillems/Vulkan/blob/41a52bda4c811fb451be949c9f2a29dd8e2848bc/base/VulkanDevice.cpp#L172) function contains the code:
```
if (requestedQueueTypes & VK_QUEUE_COMPUTE_BIT)
{
	queueFamilyIndices.compute = getQueueFamilyIndex(VK_QUEUE_COMPUTE_BIT);
	if (queueFamilyIndices.compute != queueFamilyIndices.graphics)
	{
		// If compute family index differs, we need an additional queue create info for the compute queue
		VkDeviceQueueCreateInfo queueInfo{};
		queueInfo.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
		queueInfo.queueFamilyIndex = queueFamilyIndices.compute;
		queueInfo.queueCount = 1;
		queueInfo.pQueuePriorities = &defaultQueuePriority;
		queueCreateInfos.push_back(queueInfo);
	}
}
else
{
	// Else we use the same queue
	queueFamilyIndices.compute = queueFamilyIndices.graphics;
}
```
Why if there is no **VK_QUEUE_COMPUTE_BIT** flag in the request, then _queueFamilyIndices.compute_ writes _queueFamilyIndices.graphics_? Shouldn't we do anything? And why _.graphics_? I didn't find any guarantees in the 
Vulkan specification that _.graphics_ will support _.compute_

**Comment by SaschaWillems** [comment]
> Why if there is no VK_QUEUE_COMPUTE_BIT flag in the request, then queueFamilyIndices.compute writes queueFamilyIndices.graphics? Shouldn't we do anything?

If compute and graphics queues are same, I set both to the same queue family index so code can compare them and skip special parts that are required of graphics and compute queue families differ.

> I didn't find any guarantees in the
Vulkan specification that .graphics will support .compute

Yes, there is no such guarantee. If your code relies on proper queue family type selection for compute loaders, you need to properly check that.
