### ISSUE TITLE
Order Independent Transparency-Performance Concerns

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#905]
Using a GTX 1050Ti, I'm experiencing ~65 fps, whereas in the [nvpro-samples](https://github.com/nvpro-samples/vk_order_independent_transparency), I'm seeing 600+ fps (using the linked-list algorithm) and that shader is not too different from yours. To make matters worse, their scene looks much more complicated and they use bubble sort which is worse than the insertion sort you use.
Could this be the result of:
1. buffer choice `uimageBuffer` vs `buffer` or 
2. scene creation(vertex and index buffers are created once and left alone until user changes some parameter) vs going through the gltf tree of the models (cube and spehere) all the time. This seems to be the likely case, is there a way to compose a scene from multiple gltf models and obtain the resulting buffers.

**Comment by SaschaWillems** [comment]
That sample was a contribution, so I sadly can't say to much about it and why it's so slow.

But I'm pretty sure it's not the gltf drawing part. The models are very simple and the command buffers are baked.

I'll try to profile a bit, but can't promise anything.

**Comment by SaschaWillems** [comment]
As suspected, the device local SSBOs result in the low performance. Updating the sample to use device local for all SSBOs, performance goes from ~60fps to 1300fps on my 2060:

![image](https://user-images.githubusercontent.com/10283127/143762832-c65b8814-75ce-4917-998b-f9f891c54ab9.png)

I still need to fix and clean up a few things before updating this though. Will let you know once I pushed the fixes.

**Comment by SaschaWillems** [comment]
I pushed the changes. Performance should now be a lot better. Sync is not yet optimal (and partially missing), so once sync is redone it should be even faster.

**Comment by kyamant** [comment]
Thank you for working on this, especially on your weekend.
One small addition; the staging buffer should be created with `VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT `usage flags, not just `VK_BUFFER_USAGE_STORAGE_BUFFER_BIT`.
Again, many thanks

**Comment by SaschaWillems** [comment]
> One small addition; the staging buffer should be created with VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT usage flags, not just VK_BUFFER_USAGE_STORAGE_BUFFER_BIT.

I'm already doing that:

```cpp
VK_CHECK_RESULT(vulkanDevice->createBuffer(
	VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
	VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
	&stagingBuffer,
	sizeof(geometrySBO)));
VK_CHECK_RESULT(stagingBuffer.map());
```

The buffer is only used as a copy source, so the transfer flag is sufficient.

**Comment by kyamant** [comment]
You are correct, I was looking at the old code.
