### ISSUE TITLE
Deferred Example Inconsistency

### ISSUE THREAD

**Issue by kklouzal** [SaschaWillems/Vulkan#912]
The jumping off point for your deferred examples *is* deferred.cpp and after mastering this example it is appropriate to move onto a deferred example showcasing shadows aka deferredshadows.cpp

There is an inconsistency which creates a bit of a roadblock for learning. deferred.cpp showcases point lights (specifically multiple point lights) and deferredshadows.cpp showcases spotlights (specifically a maximum of 3 spotlights). This is a major inconsistency and I think it should be addressed to better facilitate the learning process.

Two issues, going from point lights to spot lights perhaps could be addressed by creating a DeferredShadowMappingOmni.cpp example and secondly is the hard limit to 3 spot lights where as the initial demo shows you how to use any number of point lights.

It shouldn't be too difficult to master the already available shadowmappingomni.cpp example and apply what you've learned into a deferred rendering pipeline, the issue here again is DeferredShadowMappingOmni.cpp only teaches you how to use a single light source.

So I guess to sum it up I would like to see a deferred example showcasing cube maps..

**Comment by SaschaWillems** [comment]
That's a valid point, but when I wrote the samples such a learning progression wasn't on my mind. Adding omni directional shadow mapping adds a whole new level of complexity. As you noticed, it could make sense to do a separate sample for that. I'm mostly working on the official Khronos samples now, so I can't tell if I'll ever get around doing so.

**Comment by kklouzal** [comment]
Thank you for the acknowledgement, I put shadows off for so long but it's knocking at my door again. Would you suppose implementing, say, the [Deferred Shadows Example](https://github.com/SaschaWillems/Vulkan/blob/master/examples/deferredshadows/deferredshadows.cpp), and then later adding omnidirectional shadows into this would be feasible? or are the difference between the Deferred Shadows Example and omnidirectional shadows too great?
It has been almost a year now since my original post here, has the thought of Omnidirectional Deferred Shadows example come closer to fruition?

**Comment by SaschaWillems** [comment]
Sorry, I don't plan on adding a new sample combining deferred rendering and omnidirectional shadows. The building blocks are there, so combining the deferred spotlight shadows samples with omnidirectional shadows shouldn't be too hard to do yourself.
