### ISSUE TITLE
computecloth: compute commandBuffer(s)

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#918]
The code allocates and actually records to two commandBuffers for the compute pipeline, but actually only one of them ever gets used since _readSet_, the controlling variable of this ping-pong approach, does not get updated in steady-state:
from _draw()_:
`computeSubmitInfo.pCommandBuffers = &compute.commandBuffers[readSet];`

The only place _readSet_ gets updated is _buildComputeCommandBuffer()_  and that's for alternating between descriptorSets (input buffer becomes output buffer in the next iteration, etc)

**Comment by SaschaWillems** [comment]
I'll rework this with the sync rework, so closing for now.
