### ISSUE TITLE
displacement example: ineffective call

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#926]
In the `buildCommandBuffers()` function of `displacement.cpp`, the call 
 `plane.bindBuffers(drawCmdBuffers[i]);`
does not have any effect.

**Comment by SaschaWillems** [comment]
Sorry for the very late reply. I just checked and that call indeed does have an effect. The function binds the vertex and index buffers of that model, and the draw functions will check if buffers are bound and then won't rebind.

**Comment by kyamant** [comment]
Thanks for the clarification
