### ISSUE TITLE
best practices layer

### ISSUE THREAD

**Issue by jjYBdx4IL** [SaschaWillems/Vulkan#927]
The following code addition would enable best practices warnings. I'd be curious whether you can solve some of those warnings or in how far you consider them relevant.

vulkanexamplebase.cpp:
```
		if (validationLayerPresent) {
			instanceCreateInfo.ppEnabledLayerNames = &validationLayerName;
			instanceCreateInfo.enabledLayerCount = 1;

			// enable best practices validation
			VkValidationFeatureEnableEXT enables[] = { VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT };
			VkValidationFeaturesEXT features = {};
			features.sType = VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT;
			features.enabledValidationFeatureCount = 1;
			features.pEnabledValidationFeatures = enables;
			instanceCreateInfo.pNext = &features;
		} else {
			std::cerr << "Validation layer VK_LAYER_KHRONOS_validation not present, validation is disabled";
		}
```

**Comment by jjYBdx4IL** [comment]
"those warnings" disappeared for me for no apparent reason. No windows update, no software installed/removed, just booted the PC today.

**Comment by SaschaWillems** [comment]
I don't enable such layers in my code, but rather use the Vulkan Configurator from the SDK to enable layers as the best practices one when I'm cleaning up my code. Right now I'm completely reworking synchronization and once that's done I'll take a look at the best practices messages.
