### ISSUE TITLE
"Updated hdr example to new sync" is not destroying descriptor set layouts

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#929]
`hdr.cpp` under` proper_sync_dynamic_cb` is not destroying descriptor set layouts

**Comment by SaschaWillems** [comment]
That sample is still work-in-progress, see https://github.com/SaschaWillems/Vulkan/commit/5a8b2f4fc8d839e23083dfeef55b80909ca8e690.
