### ISSUE TITLE
Vertex resource deallocation

### ISSUE THREAD

**Issue by timprepscius** [SaschaWillems/Vulkan#942]
Hey there,

I have a question about resource deallocation.  I'm wondering whether you have any advice on the topic.
Basically, I:

1.  Create a vertex buffer A
2. Perform the drawIndexed into a command buffer 
3. Initiate the draw.
4. Delete vertex buffer A before the draw has finished <-- (crash), and create new vertex buffer A

(Note: step 4 isn't happening every frame, just once in a while)

This is obviously a problem.

I'm wondering if there is an established best practice for this with Vulkan.

I'm assuming that I will need to:

1. When a new vertex buffer A is about to be created, save the old vertex buffer
2. When a draw/fence has completed, delete any saved old vertex buffers (or any other memory)

Am I thinking about this the right way?
Is there a way to say to Vulkan, "delete this when it's not needed anymore."

Thank you very much for your examples, btw, they have helped immensely.  You are a master!

If this question is too off-topic, I apologize.

**Comment by SaschaWillems** [comment]
As you noted, using a fence to wait until you can safely delete/recreate a buffer is the way to go. The usual way of doing something like that is using a ring buffer: While buffer A is still used in the draw, you already start updating buffer B and switch to that in the next frame, and for the frame after that you do the same the other way round.

**Comment by timprepscius** [comment]
Great.  Thanks for this response. 

Again, thank you for the tutorials, much appreciated!
