### ISSUE TITLE
Examples launch only a black window

### ISSUE THREAD

**Issue by lgmventura** [SaschaWillems/Vulkan#943]
After compiling it successfully, whatever example I run, it only launches the terminal with the warning `MESA-INTEL: warning: Haswell Vulkan support is incomplete` and another titled window completely black. The processor usage stays very low.

I can run games that use Vulkan on my system, though.

System:
- Nvidia GeForce GTX 760M (Acer Aspire V3)
- Ubuntu 20.04
- Driver nvidia-driver-470 (proprietary).

**Comment by SaschaWillems** [comment]
Do you get any validation layer messages?

What I find kinda odd is that you get a warning for an Intel GPU even though you're on NVIDIA. It's possible that some layer interferes with device selection, so try to manually set the device using the `gpuselection` argument.

**Comment by lgmventura** [comment]
Great, it works this way! In my case, I had to put `-g 1` since Nvidia is listed as 1 (Intel is listed as 0). But strangely I still get the same warning even selecting Nvidia. Maybe only because Intel is there.

**Comment by SaschaWillems** [comment]
You can safely ignore that warning. I guess it's triggered because the loader iterates over all registered ICDs.
