### ISSUE TITLE
experimental support Image in ImGui

### ISSUE THREAD

**Issue by geotyper** [SaschaWillems/Vulkan#944]
experimental support Image in ImGui.
Try myself add this code to your code, but have problems with fonts, they also became as image or image display as font.
Can you planning to add support of Image View?
```
// Register a texture
// FIXME: This is experimental in the sense that we are unsure how to best design/tackle this problem, please post to https://github.com/ocornut/imgui/pull/914 if you have suggestions.
VkDescriptorSet ImGui_ImplVulkan_AddTexture(VkSampler sampler, VkImageView image_view, VkImageLayout image_layout)
{
    ImGui_ImplVulkan_Data* bd = ImGui_ImplVulkan_GetBackendData();
    ImGui_ImplVulkan_InitInfo* v = &bd->VulkanInitInfo;

    // Create Descriptor Set:
    VkDescriptorSet descriptor_set;
    {
        VkDescriptorSetAllocateInfo alloc_info = {};
        alloc_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        alloc_info.descriptorPool = v->DescriptorPool;
        alloc_info.descriptorSetCount = 1;
        alloc_info.pSetLayouts = &bd->DescriptorSetLayout;
        VkResult err = vkAllocateDescriptorSets(v->Device, &alloc_info, &descriptor_set);
        check_vk_result(err);
    }

    // Update the Descriptor Set:
    {
        VkDescriptorImageInfo desc_image[1] = {};
        desc_image[0].sampler = sampler;
        desc_image[0].imageView = image_view;
        desc_image[0].imageLayout = image_layout;
        VkWriteDescriptorSet write_desc[1] = {};
        write_desc[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write_desc[0].dstSet = descriptor_set;
        write_desc[0].descriptorCount = 1;
        write_desc[0].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        write_desc[0].pImageInfo = desc_image;
        vkUpdateDescriptorSets(v->Device, 1, write_desc, 0, NULL);
    }
    return descriptor_set;
}
```

**Comment by SaschaWillems** [comment]
Can you elaborate? It's hard to find out what you're asking from your description.

**Comment by geotyper** [comment]
![Screenshot at 2022-05-02 17-43-44](https://user-images.githubusercontent.com/30755433/166254291-444a92d3-155b-423e-853e-56cc257b00eb.png)

For example in my OpenGL project use several Imgui Image to display textures as separate windows.
Some time it more effective, than create quard with texture.
In this article explain subject:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
all platforms but without vulkan, in new release of Imgui include experimental support of ImGui::Image.
So question is it possible to implement this in your code base.
Sorry for my English.

**Comment by SaschaWillems** [comment]
I see. So this is about display a Vulkan image inside ImGui. I don't have plans for doing such a sample currently.
