### ISSUE TITLE
shadowmapping example: cull mode

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#946]
To improve realism and to avoid peter panning, the offscreen pass should use  `VK_CULL_MODE_FRONT_BIT`.
Without that, one of the walls of the box does not cast proper shadows in the _teapot and pillars_ scene

**Comment by SaschaWillems** [comment]
I have disabled culling for the shadow pass. Front mode would cause other problems and holes in shadow meshes.
