### ISSUE TITLE
Issue of launching Bloom with Mesa 22.0

### ISSUE THREAD

**Issue by zhouleonlei** [SaschaWillems/Vulkan#947]
Hello
    I have met an issue when launching the vk-sample of "bloom" after I updated mesa 22.0 like below:
../src/vulkan/runtime/vk_image.c:248:vk_image_expand_aspect_mask: Assertion `aspect_mask && !(aspect_mask & ~image->aspects)' failed.

### 1. /vk_image.c:248 codes:
VkImageAspectFlags
vk_image_expand_aspect_mask(const struct vk_image *image,
                            VkImageAspectFlags aspect_mask)
{
   if (aspect_mask == VK_IMAGE_ASPECT_COLOR_BIT) {
      assert(image->aspects & VK_IMAGE_ASPECT_ANY_COLOR_MASK_MESA);
      return image->aspects;
   } else {
      **assert(aspect_mask && !(aspect_mask & ~image->aspects));**
      return aspect_mask;
   }
}

The reason is that "image aspects" is different from "subresourceRange.aspectMask" of imageView.
"image aspects" == VK_IMAGE_ASPECT_DEPTH_BIT
"subresourceRange.aspectMask" == VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT

### 2. "image aspects" is decided by image format which is gained from vks::tools::getSupportedDepthFormat
		VkBool32 getSupportedDepthFormat(VkPhysicalDevice physicalDevice, VkFormat *depthFormat)
		{
			// Since all depth formats may be optional, we need to find a suitable depth format to use
			// Start with the highest precision packed format
			std::vector<VkFormat> depthFormats = {
				VK_FORMAT_D32_SFLOAT_S8_UINT,
				VK_FORMAT_D32_SFLOAT,
				VK_FORMAT_D24_UNORM_S8_UINT,
				VK_FORMAT_D16_UNORM_S8_UINT,
				VK_FORMAT_D16_UNORM
			};

			for (auto& format : depthFormats)
			{
				VkFormatProperties formatProps;
				vkGetPhysicalDeviceFormatProperties(physicalDevice, format, &formatProps);
				// Format must support depth stencil attachment for optimal tiling
				if (formatProps.optimalTilingFeatures & VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT)
				{
					*depthFormat = format;
					return true;
				}
			}

			return false;
		}

VK_FORMAT_D32_SFLOAT has been chosen first.  
**image.aspects = vk_format_aspects(VK_FORMAT_D32_SFLOAT)** 
   case VK_FORMAT_D16_UNORM_S8_UINT:
   case VK_FORMAT_D24_UNORM_S8_UINT:
   case VK_FORMAT_D32_SFLOAT_S8_UINT:
      return VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT;

   case VK_FORMAT_D16_UNORM:
   case VK_FORMAT_X8_D24_UNORM_PACK32:
   case VK_FORMAT_D32_SFLOAT:
      return VK_IMAGE_ASPECT_DEPTH_BIT;

### 3. I think VK_FORMAT_D24_UNORM_S8_UINT should be chosen because:
VK_FORMAT_D24_UNORM_S8_UINT specifies a two-component, 32-bit packed format that has 8 unsigned integer bits in the stencil component, and 24 unsigned normalized bits in the depth component.

I am not sure whether Mesa 22.0 follow the wrong vkspec or not.
Please help to give your suggestion

Thanks

**Comment by luck-bear** [comment]
您好，邮件已收到，谢谢。会尽快给回复。

**Comment by SaschaWillems** [comment]
Mesa 22 isn't doing anything wrong in here. The sample is at fault (and possibly other samples too). I have pushed a fix that only adds the stencil aspect flag if the selected format actually has a stencil part. 

Can you fetch the latest code from master and check if that fixes it? If so, I'll also apply that fix to other samples.

**Comment by zhouleonlei** [comment]
> 



> Mesa 22 isn't doing anything wrong in here. The sample is at fault (and possibly other samples too). I have pushed a fix that only adds the stencil aspect flag if the selected format actually has a stencil part.
> 
> Can you fetch the latest code from master and check if that fixes it? If so, I'll also apply that fix to other samples.

I have tested with your latest codes. It works.
Thanks~
