### ISSUE TITLE
Vulkan 1.3.216.0 introduces runtime problems on the Mac

### ISSUE THREAD

**Issue by rainergericke** [SaschaWillems/Vulkan#954]
Building the examples on the Mac (M1 Max, MacOS 12.4) leads to a runtime error (VK_ERROR_INCOMPATIBLE_DRIVER). This does not happen, if Vulkan 1.3.211 or earlier is used.

This problem is mentioned in the actual Vulkan Docs. Adding the proposed values in vulkanexamplebase.cpp does not fix the problem.

std::vector<const char*> extNames;
extNames.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
extNames.push_back(VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME);

VKInstanceCreateInfo inst_info = {};

ins_info.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
inst_info.enabledExtensionCount = static_cast<uint32_t>(extNames.size());
inst_info.ppEnabledExtensionNames = extNames.data();

Do you have an idea how to solve it?

Best

**Comment by SaschaWillems** [comment]
As you noticed, this is caused by the changes in the most recent SDK.

I sadly don't have a Mac to test on, so I probably can't help with this issue. 

Maybe someone at the MoltenVK repo can help with this: https://github.com/KhronosGroup/MoltenVK/issues

**Comment by rainergericke** [comment]
Thanks, I will try it.

**Comment by Radagan** [comment]
I have the same issue but on 2019 Intel macbook. Glad to try and help as well. Here is the reference doc:
https://www.lunarg.com/wp-content/uploads/2022/04/Portability-Enumeration-Extension-APR2022.pdf

**Comment by Radagan** [comment]
@rainergericke I did for my project at work--had to do that first. The official Vulkan samples look like they have the same issue. The same configuration changes should do it, but I had to only set them for mac or I had issues on Windows. Would a PR addressing these config changes be welcome?

**Comment by SaschaWillems** [comment]
@Radagan: Yes, A PR would be very much appreciated. I don't own a Mac device, so I can't provide that fix by myself.

**Comment by Radagan** [comment]
@SaschaWillems, No worries. I made the changes and sent you a PR. Let me know if you would like any adjustments to the code. You should have edit rights as well on the PR.

In VulkanDevice.cpp, I was unable to figure out what the proper define was for this string, so left it as is:
```
deviceExtensions.push_back("VK_KHR_portability_subset");
```

**Comment by rainergericke** [comment]
I just implemented the proposed changes by hand from @Radagan 's commit. Everything runs fine again. Thanks a lot!

**Comment by Radagan** [comment]
@rainergericke Thank you for testing on an M1. It's good to know that everything runs fine there!

**Comment by rainergericke** [comment]
I implemented these changes also in project::chrono, where I am working on a 3d viewer for physical systems based on Vulkan Scene Graph. It also worked here. Project::chrono uses a continuous integration system with 7 standardized build tests with different OSes and Vulkan versions. There we found an issue: our proposed changes break the build on Macs with earlier Vulkan versions than 1.3.216. That's easy to solve yet:
Instead:
	#if defined(VK_USE_PLATFORM_MACOS_MVK)
		instanceCreateInfo.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
	#endif
we should write:
	#if defined(VK_USE_PLATFORM_MACOS_MVK) && (VK_HEADER_VERSION >= 216)
		instanceCreateInfo.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
	#endif
Same at all places, were #if defined(VK_USE_PLATFORM_MACOS_MVK) occurs.

Btw: deviceExtensions.push_back("VK_KHR_portability_subset");
can be made 'canonical' with:
deviceExtensions.push_back(VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME);

VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME is defined in 'vulkan_beta.h', it must be conditionally included before use.

Sorry for the inconvenience, but sometimes wisdom increases with the time.

**Comment by Radagan** [comment]
@rainergericke Thank you! I have been very focused on latest Vulkan in an early stage project, so didn't even think of regression testing it. I'll create a new PR with your updates!

**Comment by Radagan** [comment]
@rainergericke I made the changes, but for me VK_HEADER_VERSION is not being defined properly so the changes are not being applied. 

The issue is that the project includes the vulkan headers in external/vulkan and their version is 210.

@SaschaWillems, Is there a reason you are including the headers rather than getting them from the installed Vulkan SDK?

**Comment by SaschaWillems** [comment]
Main reason is submodule size. The Vulkan headers repo is already at 100%. I'll updated the headers to .216 asap, so build on Mac OSX work again.

**Comment by SaschaWillems** [comment]
I have updated to the latest headers. Please check again, and if the problem still persists drop me a line and I'll check.

**Comment by Radagan** [comment]
@SaschaWillems Thank you. I updated my fork and submitted a PR for review.

**Comment by rainergericke** [comment]
I just tested the examples with Vulkan 1.3.216 and Vulkan 1.3.211. It's all good again. Good to have it back.
