### ISSUE TITLE
proper_sync_dynamic_cb build fails

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#958]
The culprit is line # 198 in VulkanDevice.cpp
`queueFamilyIndices.graphics = VK_NULL_HANDLE;`

**Comment by SaschaWillems** [comment]
Yeah, it's a work in progress branch. Please don't clone and try it yet. It's also missing a lot of changes that I haven't committed yet.

**Comment by SaschaWillems** [comment]
I have pushed a fix for this. But as noticed above, please note that this branch is still heavy work-in-progress and doesn't include all changes to e.g. the base code to properly work.
