### ISSUE TITLE
Trying to load other gltf model with 'gltfloading' but crashes with segfault.

### ISSUE THREAD

**Issue by Fredrum** [SaschaWillems/Vulkan#961]
Hello!  Thank you so much for all these amazing examples! :)
I'm trying to do a bit of Vulkan on a Raspberry Pi4b and just looking into, well apart from Everything, how to load 3d models.
I'm using your 'gltfloading' example but just changed the model read to,

```
//loadglTFFile(getAssetPath() + "models/FlightHelmet/glTF/FlightHelmet.gltf");
loadglTFFile(getAssetPath() + "models/cube.gltf");
```

And getting a crash to segfault.
I'm going to try and pinpoint this issue as it would be great to have this example being able to more than just the FlightHelmet asset file.

Please let me know if you know what this is due to?

**UPDATE**:  A gdb+run+bt gives:
```
Thread 1 "gltfloading" received signal SIGSEGV, Segmentation fault.
0x00000055556aa3fc in VulkanglTFModel::drawNode(VkCommandBuffer_T*, VkPipelineLayout_T*, VulkanglTFModel::Node) ()
(gdb) bt
#0  0x00000055556aa3fc in VulkanglTFModel::drawNode(VkCommandBuffer_T*, VkPipelineLayout_T*, VulkanglTFModel::Node) ()
#1  0x00000055556aa5e0 in VulkanglTFModel::draw(VkCommandBuffer_T*, VkPipelineLayout_T*) ()
#2  0x00000055556aae8c in VulkanExample::buildCommandBuffers() ()
#3  0x00000055556ad7e4 in VulkanExample::prepare() ()
#4  0x000000555569d21c in main ()
```

Cheers!

**Comment by SaschaWillems** [comment]
Please check out my https://github.com/SaschaWillems/Vulkan-glTF-PBR repo. This is a more complete Vulkan glTF loader that should be able to handle most samples.

As for this sample crashing. It's very specific to the used model, so I can imagine that it crashes if using e.g. a model without PBR textures.

Just run it through a debugger and check where it crashes. Callstack and locals may help me locate the problem.

**Comment by Fredrum** [comment]
Wow that was quick ! :D  
Yes Ok thank yo uso much I will do that right now!!

Cheers!
