### ISSUE TITLE
gltfloading example - nodes may not be working as expected

### ISSUE THREAD

**Issue by arkiruthis** [SaschaWillems/Vulkan#964]
Firstly, thank you for these wonderful examples that helped me move my work from OpenGL to Vulkan, they were invaluable.

I recently implemented GLTF loading and found something curious in this example. The idea is sound, that a Node has children, and a node can point to a parent, so in the draw call we traverse down and multiply matrices of parents.

However, the Node parent is never set in the code anywhere (it would probably be set on the node's parent variable [here ](https://github.com/SaschaWillems/Vulkan/blob/0dc33496df5c2e3a5b3c2ae150802dc660ddfd83/examples/gltfloading/gltfloading.cpp#L317)), so this means in the Draw call, we never do this. It only appears correct, because the immediate submeshes of the flight helmet only have one level of matrix. More complicated GLTF probably would have submeshes appear near the origin.

The fix, however isn't as simple as just adding that parent assignment just mentioned. This is because the std::vector will shuffle the pointers around and when it comes to the Draw call, the Node's parent pointers will probably be pointing to random memory.

My own solution in my project is to make the Node parent member a std::weak_ptr and the children (and main model node list) std::vector<std::shared_ptr>. 

```
    struct Node
    {
        std::weak_ptr<Node> parent;
        std::vector<std::shared_ptr<Node>> children;
        Mesh mesh;
        glm::mat4 matrix;
    };
```

I also change the signature of the loadNode function to take a std::shared_ptr as well.
```
void loadNode(const tinygltf::Node& inputNode, const tinygltf::Model& input, std::shared_ptr<VulkanglTFModel::Node> parent, std::vector<uint32_t>& indexBuffer, std::vector<VulkanglTFModel::Vertex>& vertexBuffer)
```

**Comment by Radagan** [comment]
@arkiruthis I too am working on supporting loading glTF models/scenes in my code. Have you seen Sascha's other repo? 

https://github.com/SaschaWillems/Vulkan-glTF-PBR

It is a more complete example. I'm having difficulty making the descriptor sets that are built during loading to be compatible with my existing set 0, but the code is the most complete example for working with glTF files in Vulkan I've seen anywhere.

**Comment by SaschaWillems** [comment]
I have slightly updated the glTF samples. Parent/child relations are now properly stored and used for node transition in matrix computations. In fact the flight helmet actually has such a relation which is now properly applied. This makes the code more correct, which imo is important for people trying to learn glTF and Vulkan from my samples.

But as already mentioned, the goal of this sample is not a fully-fledged glTF loader. That would be too much for the scope of a basic sample. 

For a more complete glTF loader take a look at https://github.com/SaschaWillems/Vulkan-glTF-PBR.
