### ISSUE TITLE
dynamic rendering example is missing required extension

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#969]
`vkCmdBeginRenderingKHR()` and  `vkCmdEndRenderingKHR()` require `VK_KHR_depth_stencil_resolve` to be enabled.

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. Looks like this has recently been changed, and requires several extensions to be enabled due to an odd chaining of required things to be enabled now. I'll take a look at this.

**Comment by SaschaWillems** [comment]
This was fixed with https://github.com/SaschaWillems/Vulkan/pull/974
