### ISSUE TITLE
2D texture sampler clamp option

### ISSUE THREAD

**Issue by rytisss** [SaschaWillems/Vulkan#971]
Hi!
I have a problem with texture visualization. I am not a pro in Vulkan API, I am trying to visualize the texture (picture) and clamp the image to the border. However, as much as I try to change the parameters in the sampler, I still get the repetitive pattern:  
  
![image](https://user-images.githubusercontent.com/22094617/180305993-818e0c9e-41e7-4944-ae0f-7d53de415d9a.png)
The code for the sampler:  
  
```cpp
        VkSamplerCreateInfo samplerInfo{};
	samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
	samplerInfo.magFilter = VK_FILTER_LINEAR;
	samplerInfo.minFilter = VK_FILTER_LINEAR;
	samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;
	samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;
	samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;
	samplerInfo.anisotropyEnable = VK_FALSE;
	samplerInfo.maxAnisotropy = 1.0f;
	samplerInfo.borderColor = VK_BORDER_COLOR_INT_OPAQUE_BLACK;
	samplerInfo.unnormalizedCoordinates = VK_FALSE;
	samplerInfo.compareEnable = VK_FALSE;
	samplerInfo.compareOp = VK_COMPARE_OP_ALWAYS;
	samplerInfo.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
	samplerInfo.mipLodBias = 0.0f;
	samplerInfo.minLod = 0.0f;
	samplerInfo.maxLod = 0.0f;

	if (vkCreateSampler(m_info.Device, &samplerInfo, nullptr, &m_textureSampler) != VK_SUCCESS)
	{
		throw std::runtime_error("failed to create texture sampler!");
	}
```  
Even when `VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER` or `VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE` is set, the results are the same (see image above). Maybe anyone encountered something like this? Any help is appreciated!

**Comment by cforfang** [comment]
Are you changing the right code? The code snippet you quote appears to be from `base/VulkanTexture.cpp`, but the sampler used by the texture sample is in `examples/texture/texture.cpp` here: https://github.com/SaschaWillems/Vulkan/blob/0dc33496df5c2e3a5b3c2ae150802dc660ddfd83/examples/texture/texture.cpp#L398

**Comment by rytisss** [comment]
Yes indeed, I have written a structured function in my application. I am just not sure what am I doing wrong with a sampler definition since it is not clamping texture (although it is defined `VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER`). In general, it gives the same result as using `VK_SAMPLER_ADDRESS_MODE_REPEAT`. I am not sure which part might cause this kind of sampler behavior.

**Comment by SaschaWillems** [comment]
Use [RenderDoc](https://renderdoc.org/) to verify the sampler settings to rule out that you're using the wrong sampler.

P.S. : I'm closing this, as it's not an issue related to my repo. If you want to discuss further, feel free to move to the discussion section of this repo.
