### ISSUE TITLE
Officially "blessed" build environment and instructions are missing from build instructions

### ISSUE THREAD

**Issue by buzmeg** [SaschaWillems/Vulkan#972]
The BUILD.md file has extremely skeletal information on how to build the demos.

As requested in #819, it would be good to know what combinations of OS, compiler, and build tools have *actually* been used and tested.

For example, it was mentioned that ninja was never used, but clang was apparently used.  Clang normally would imply Linux; however, if we're talking Windows, it would be nice to know how clang was installed in order to match with what has been used.

Most people would be happy to match with the developers, but, to do that, we need to actually know what the developers are using.

Thanks.

**Comment by SaschaWillems** [comment]
There is no official build environment. I'm working on this repo in my spare time, mainly on Windows 10 with VS 2019. So that's my "official" environment.

**Comment by buzmeg** [comment]
Thanks.  That's really useful to know as I've been having build issues caused by 2019/2022 build tool confusions.

I'll set up a VM that is Win 10 and VS 2019.  Please do put it into the BUILD.md when you shift to something newer.

Thanks.
