### ISSUE TITLE
CMake Successful, no Executables Found (Examples)

### ISSUE THREAD

**Issue by coryharrington** [SaschaWillems/Vulkan#973]
`$ rm CMakeCache.txt && cmake .
-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.32.31332.0
-- The CXX compiler identification is MSVC 19.32.31332.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using module to find Vulkan
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Using bundled Vulkan library version
-- C:/Users/krisp/github/Vulkan/libs/vulkan/vulkan-1.lib
C:/Users/krisp/github/Vulkan/bin/
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/bloom
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computecloth
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computecullandlod
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computeheadless
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computenbody
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computeparticles
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computeraytracing
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/computeshader
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/conditionalrender
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/conservativeraster
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/debugmarker
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/deferred
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/deferredmultisampling
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/deferredshadows
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/descriptorindexing
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/descriptorsets
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/displacement
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/distancefieldfonts
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/dynamicrendering
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/dynamicuniformbuffer
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/gears
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/geometryshader
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/gltfloading
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/gltfscenerendering
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/gltfskinning
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/graphicspipelinelibrary
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/hdr
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/imgui
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/indirectdraw
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/inlineuniformblocks
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/inputattachments
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/instancing
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/multisampling
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/multithreading
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/multiview
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/negativeviewportheight
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/occlusionquery
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/offscreen
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/oit
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/parallaxmapping
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/particlefire
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pbrbasic
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pbribl
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pbrtexture
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pipelines
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pipelinestatistics
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pushconstants
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/pushdescriptors
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/radialblur
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/rayquery
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/raytracingbasic
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/raytracingcallable
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/raytracingreflections
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/raytracingshadows
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/renderheadless
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/screenshot
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/shadowmapping
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/shadowmappingomni
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/shadowmappingcascade
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/specializationconstants
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/sphericalenvmapping
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/ssao
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/stencilbuffer
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/subpasses
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/terraintessellation
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/tessellation
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/textoverlay
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texture
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texture3d
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texturearray
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texturecubemap
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texturecubemaparray
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texturemipmapgen
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/texturesparseresidency
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/triangle
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/variablerateshading
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/vertexattributes
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/viewportarray
-- Generating project file for example in C:/Users/krisp/github/Vulkan/examples/vulkanscene
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/krisp/github/Vulkan`

The above output seems to run but then no executables are to be found and the bin dir is empty.
ex.

`$ find -regex '.*triangle.*'
./android/examples/triangle
./android/examples/triangle/build.gradle
./android/examples/triangle/CMakeLists.txt
./android/examples/triangle/src
./android/examples/triangle/src/main
./android/examples/triangle/src/main/AndroidManifest.xml
./android/examples/triangle/src/main/java
./android/examples/triangle/src/main/java/de
./android/examples/triangle/src/main/java/de/saschawillems
./android/examples/triangle/src/main/java/de/saschawillems/vulkanSample
./android/examples/triangle/src/main/java/de/saschawillems/vulkanSample/VulkanActivity.java
./data/shaders/glsl/conservativeraster/triangle.frag
./data/shaders/glsl/conservativeraster/triangle.frag.spv
./data/shaders/glsl/conservativeraster/triangle.vert
./data/shaders/glsl/conservativeraster/triangle.vert.spv
./data/shaders/glsl/conservativeraster/triangleoverlay.frag
./data/shaders/glsl/conservativeraster/triangleoverlay.frag.spv
./data/shaders/glsl/renderheadless/triangle.frag
./data/shaders/glsl/renderheadless/triangle.frag.spv
./data/shaders/glsl/renderheadless/triangle.vert
./data/shaders/glsl/renderheadless/triangle.vert.spv
./data/shaders/glsl/tessellation/pntriangles.tesc
./data/shaders/glsl/tessellation/pntriangles.tesc.spv
./data/shaders/glsl/tessellation/pntriangles.tese
./data/shaders/glsl/tessellation/pntriangles.tese.spv
./data/shaders/glsl/triangle
./data/shaders/glsl/triangle/triangle.frag
./data/shaders/glsl/triangle/triangle.frag.spv
./data/shaders/glsl/triangle/triangle.vert
./data/shaders/glsl/triangle/triangle.vert.spv
./data/shaders/hlsl/conservativeraster/triangle.frag
./data/shaders/hlsl/conservativeraster/triangle.frag.spv
./data/shaders/hlsl/conservativeraster/triangle.vert
./data/shaders/hlsl/conservativeraster/triangle.vert.spv
./data/shaders/hlsl/conservativeraster/triangleoverlay.frag
./data/shaders/hlsl/conservativeraster/triangleoverlay.frag.spv
./data/shaders/hlsl/renderheadless/triangle.frag
./data/shaders/hlsl/renderheadless/triangle.frag.spv
./data/shaders/hlsl/renderheadless/triangle.vert
./data/shaders/hlsl/renderheadless/triangle.vert.spv
./data/shaders/hlsl/tessellation/pntriangles.tesc
./data/shaders/hlsl/tessellation/pntriangles.tesc.spv
./data/shaders/hlsl/tessellation/pntriangles.tese
./data/shaders/hlsl/tessellation/pntriangles.tese.spv
./data/shaders/hlsl/triangle
./data/shaders/hlsl/triangle/triangle.frag
./data/shaders/hlsl/triangle/triangle.frag.spv
./data/shaders/hlsl/triangle/triangle.vert
./data/shaders/hlsl/triangle/triangle.vert.spv
./examples/triangle
./examples/triangle/triangle.cpp
./examples/triangle.vcxproj
./examples/triangle.vcxproj.filters
./screenshots/triangle.jpg`

**Comment by coryharrington** [comment]
The above output seems to run but then no executables are to be found and the bin dir is empty.

**Comment by SaschaWillems** [comment]
I'm still on VS2019, so I probably can't help. But can you check out the comments in https://github.com/SaschaWillems/Vulkan/issues/952 and see if that works for you?

**Comment by coryharrington** [comment]
Thanks so much for getting back! I'll keep updated I may try this from another shell, using mingw64 with msvc, the executable for that is cl and I may not be compiling correctly or something.

`set(CMAKE_C_COMPILER` "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x86/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx86/x86/cl.exe")
`

I totally forgot to mention I did this to the root CMakeLists.txt

**Comment by coryharrington** [comment]
Same result with or without the -G and -A x64. Maybe I should just use clang I am more familiar with it. Gotta find where its installed and I'll get back asap

**Comment by coryharrington** [comment]
No luck even using clang, clang somehow is pointing to MSVC or MSVC is being detected and the cl.exe is still being used. So I don't think its used clang

**Comment by coryharrington** [comment]
Closing this Issue as the issue was not building after configuring. Been a while since I used cmake.

cmake --build . 

is what compiles... 👯‍♂️
