### ISSUE TITLE
multisampling example - resize operation leaves orphaned objects

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#982]
On a resize operation `setupMultisampleTarget()` recreates images and imageViews and allocates memory without checking present state. 
For example, instead of 
`VK_CHECK_RESULT(vkCreateImage(device, &info, nullptr, &multisampleTarget.color.image));`

use 
```
if (VK_NULL_HANDLE != multisampleTarget.color.image)
		vkDestroyImage(device, multisampleTarget.color.image, nullptr);
VK_CHECK_RESULT(vkCreateImage(device, &info, nullptr, &multisampleTarget.color.image));
```

**Comment by SaschaWillems** [comment]
Images for that sample are destoryed in `setupFrameBuffer`, so the sample looks fine. I also don't get any validation layer errors after resizing.

**Comment by kyamant** [comment]
Thanks, I was looking at a very old version, it turned out.
