### ISSUE TITLE
dynamic rendering in macos

### ISSUE THREAD

**Issue by SakuragiHnmch** [SaschaWillems/Vulkan#983]
Hey, SaschaWillems,
When I run the dynamic rendering examples in macos,  I encountered some problems. The program did not run as expected, and thrown some error message:

Enabled device extension "VK_KHR_dynamic_rendering" is not present at device level
Could not create Vulkan device: 
ERROR_EXTENSION_NOT_PRESENT

I wondered if the dynamic rendering extension is supported in macos, and I failed to find any answer on the Internet.
Could this be the problem of the version of Monterey? My version is 12.3 and the latest version is 12.5.

**Comment by SaschaWillems** [comment]
I don't own any MacOS devices, so I can't really help here. All I know is that MoltenVK recently got support for VK_KHR_dynamic_rendering, but I have now clue on what OS version or hardware. Maybe ask about this over at https://github.com/KhronosGroup/MoltenVK.

**Comment by SakuragiHnmch** [comment]
> I don't own any MacOS devices, so I can't really help here. All I know is that MoltenVK recently got support for VK_KHR_dynamic_rendering, but I have now clue on what OS version or hardware. Maybe ask about this over at https://github.com/KhronosGroup/MoltenVK.

ok, thanks for your reply
