### ISSUE TITLE
texturesparseresidency requests shaderResourceMinLod, but not uses it

### ISSUE THREAD

**Issue by scygan** [SaschaWillems/Vulkan#984]
It looks like texturesparseresidency demo requests shaderResourceMinLod feature: 

https://github.com/SaschaWillems/Vulkan/blob/279c954/examples/texturesparseresidency/texturesparseresidency.cpp#L175

However, it does not seem to be used in shaders at this moment. 
Moreover, according to vulkan.gpuinfo,org, it is not uniformly supported accross most HW. 

Would it be possible to stop requesting this feature?   We have tested this demo on Intel/Windows and it seems it works correctly when shaderResourceMinLod   is not requested.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. An earlier version of this sample used `sparseTextureClampARB` in the fragment shader, which required shaderResourceMinLod. Since the shader isn't currently using that I'll remove this requirement.

**Comment by scygan** [comment]
Thanks!
