### ISSUE TITLE
raytracingcallable example- Mismatch in the use of vkCmdBuildAccelerationStructuresKHR()

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#986]
In `createBottomLevelAccelerationStructure()`
```
vkCmdBuildAccelerationStructuresKHR(
	commandBuffer,
	1,
	&accelerationBuildGeometryInfo,
	accelerationBuildStructureRangeInfos.data());
```
There is a single instance of `accelerationBuildGeometryInfo` and `accelerationBuildStructureRangeInfos` is a vector of size 3.
According to [Vulkan Specification](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkCmdBuildAccelerationStructuresKHR)
```
// Provided by VK_KHR_acceleration_structure
void vkCmdBuildAccelerationStructuresKHR(
    VkCommandBuffer                             commandBuffer,
    uint32_t                                    infoCount,
    const VkAccelerationStructureBuildGeometryInfoKHR* pInfos,
    const VkAccelerationStructureBuildRangeInfoKHR* const* ppBuildRangeInfos);
```

- infoCount is the number of acceleration structures to build. It specifies the number of the pInfos structures and ppBuildRangeInfos pointers that must be provided.

But in this example the counts do not match.

**Comment by SaschaWillems** [comment]
Just checked, and the sample is correct. The sample has three *VkAccelerationStructureBuildRangeInfoKHR*, but the infoCount does refer to *VkAccelerationStructureBuildGeometryInfoKHR* of which the sample only uses one.
