### ISSUE TITLE
rayquery example: scene fragment shader is missing required directive

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#988]
In the fragment shader the use of _gl_RayFlagsSkipAABBEXT_ 
`rayQueryInitializeEXT(rayQuery, topLevelAS, gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipAABBEXT, 0xFF, inWorldPos, 0.01, L, 1000.0);`
requires  _GL_EXT_ray_flags_primitive_culling_ extension.

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. The flag is actually not needed by that sample anyway.
