### ISSUE TITLE
Unexpected behavior in ray tracing

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#992]
I've modified ray tracing samples to port my cornel box from nvidia's optix platform.
The objects, including the side walls, are placed as if they are mirror images along the y axis (i.e. x coordinate -100 became 100 and 100 became -100).
Also, view and projection matrices are inverted (i.e. glm::inverse()), why is that?

**Comment by SaschaWillems** [comment]
Can you post screenshots? An is this for the hardware raytracing or compute shader raytracing samples?

**Comment by kyamant** [comment]
I've created a simple Cornell box  based on the Vulkan Hardware RayTracing example using the model from Optix7 SDK Sample (optixPathTracer) and objects are swapped "left <--> right". What could be the reason behind this?
**Optix 7**
![OptixRayTracing](https://user-images.githubusercontent.com/16941640/189482890-50826b72-8e89-4253-bd48-4aca038b0744.png)
**Vulkan Hardware RayTracing**
![VulkanHardwareRayTracing](https://user-images.githubusercontent.com/16941640/189482936-b2a77bb0-2daf-46cd-8254-d0c39f1f7873.png)

**Comment by SaschaWillems** [comment]
In what format is that model in glTF? Maybe Optix is using a different coordinate system than my samples.

If it's a glTF model, can you attach it to this issue.

**Comment by kyamant** [comment]
It is not gltf; just a bunch of triangles.
The project came with the installation of [Optix7](https://developer.nvidia.com/designworks/optix/download); did not come from a github repo. It is in optixPathTracer.cpp file.

**Comment by SaschaWillems** [comment]
I can only imagine that OptiX uses a different coordinate system than I do.

As for the inverted matrices (sorry, didn't initially notice): That's because the we need the origin and direction of the ray, which is easily done by using the inverse of the matrices.
